- .github/PULL_REQUEST_TEMPLATE.md
Change PR template to adjust both issue# and jira#
---
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:
`<Issue #>: Description of pull request`
`e.g. Issue 123: Description ...`
---
> Issue 212: change github PR template to adjust both issue# and jira#

- .htaccess
Add a .htaccess file to redirect /archives to the old releases.
> Issue 324: Add htaccess for handling redirections to old releases

- dev/bk-merge-pr.py
The merge script is broken due to a typo in 4c2e90d2536676f14df944c5d8b4288362aa48b9
> fix merge script

- bookkeeper-benchmark/pom.xml
- bookkeeper-dist/pom.xml
- bookkeeper-server/pom.xml
- bookkeeper-stats-providers/codahale-metrics-provider/pom.xml
- bookkeeper-stats-providers/pom.xml
- bookkeeper-stats-providers/prometheus-metrics-provider/pom.xml
- bookkeeper-stats-providers/twitter-finagle-provider/pom.xml
- bookkeeper-stats-providers/twitter-ostrich-provider/pom.xml
- bookkeeper-stats-providers/twitter-science-provider/pom.xml
- bookkeeper-stats/pom.xml
- buildtools/pom.xml
- compat-deps/bookkeeper-server-compat-4.0.0/pom.xml
- compat-deps/bookkeeper-server-compat-4.1.0/pom.xml
- compat-deps/bookkeeper-server-compat-4.2.0/pom.xml
- compat-deps/pom.xml
- pom.xml
Change version to 4.5.2-SNAPSHOT on branch-4.5
> Update brach-4.5 to version 4.5.2-SNAPSHOT

- site/bps/BP-21-new-api-close-inconsistencies.md
- site/community/bookkeeper_proposals.md
Proposal to clean up inconsistencies in Handle#close.
> BP-21:  New API close inconsistencies

- bookkeeper-benchmark/pom.xml
- bookkeeper-common/pom.xml
- bookkeeper-dist/all/pom.xml
- bookkeeper-dist/pom.xml
- bookkeeper-dist/server/pom.xml
- bookkeeper-http/http-server/pom.xml
- bookkeeper-http/pom.xml
- bookkeeper-http/twitter-http-server/pom.xml
- bookkeeper-http/vertx-http-server/pom.xml
- bookkeeper-server/pom.xml
- bookkeeper-stats-providers/codahale-metrics-provider/pom.xml
- bookkeeper-stats-providers/pom.xml
- bookkeeper-stats-providers/prometheus-metrics-provider/pom.xml
- bookkeeper-stats-providers/twitter-finagle-provider/pom.xml
- bookkeeper-stats-providers/twitter-ostrich-provider/pom.xml
- bookkeeper-stats-providers/twitter-science-provider/pom.xml
- bookkeeper-stats/pom.xml
- buildtools/pom.xml
- pom.xml
- shaded/bookkeeper-server-shaded/pom.xml
- shaded/bookkeeper-server-tests-shaded/pom.xml
- shaded/pom.xml
- tests/backward/pom.xml
- tests/bookkeeper-server-compat-4.0.0/pom.xml
- tests/bookkeeper-server-compat-4.1.0/pom.xml
- tests/bookkeeper-server-compat-4.2.0/pom.xml
- tests/bookkeeper-server-shaded-artifact-test/pom.xml
- tests/bookkeeper-server-shaded-test/pom.xml
- tests/bookkeeper-server-tests-shaded-test/pom.xml
- tests/pom.xml
Bump version to 4.6.2-SNAPSHOT on branch-4.6 branch
> Start 4.6.2-SNAPSHOT

- pom.xml
Changed pom, added "additionalOptions" for javadoc plugin in addition to "additionalparam".
Seems to do the trick. 
Master Issue: #1467 
> ---
>
>
>
> Otherwise:
> 
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass …
> Issue #1467: build failing with MavenReportException: Error while generating Javadoc.

- dev/bk-merge-pr.py
- dev/bk-merge-pr3.py
make sure the script works for python 3 as well.
since python2 and python3 have different syntax and library, make a copy of the merge script for python3.
> ---
>
> - [x] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` …
>  [dev] make merge script work with python 3

- docker/scripts/healthcheck.sh
Fixes https://github.com/apache/bookkeeper/issues/1687
https://github.com/apache/bookkeeper/issues/1687
Using eval instead of exec to run the health check script.
Master Issue: #1687 
> ---
>
> - [ ] [skip bookkeeper-server bookie tests]: skip testing …
> Issue 1687: Using eval instead of exec to handle quotes in healtcheck.sh

- stream/proto/src/main/proto/cluster.proto
- stream/proto/src/main/proto/kv_store.proto
- stream/proto/src/main/proto/stream.proto
*Motivation*
There are build warnings about `Import xyz.proto but not used`. for example:
```
cluster.proto: warning: Import common.proto but not used.
kv_store.proto: warning: Import kv.proto but not used.
```
*Changes*
Remove unused imports
> ---
>
> - …
> [table service] remove build warnings "Import xxx.proto but not used"

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
*Changes*
This is the second part of changing AutoRecovery to use metadata driver. It removes
the zookeeper reference from ReplicationWorker, because the zookeeper instance is not
used anyway
This change is based on #1693 
> ---
>
> - [ ] [skip …
>  autorecovery-use-metadata-driver (part 2) : remove ZooKeeper from ReplicationWorker

- buildtools/src/main/resources/bookkeeper/suppressions.xml
- stream/clients/python/bookkeeper/common/router/__init__.py
- stream/clients/python/bookkeeper/common/router/router.py
- stream/clients/python/setup.py
- stream/clients/python/tests/unit/bookkeeper/common/router/test_router.py
- stream/common/src/main/java/org/apache/bookkeeper/common/hash/Murmur3.java
- stream/common/src/main/java/org/apache/bookkeeper/common/router/AbstractHashRouter.java
- stream/common/src/test/java/org/apache/bookkeeper/common/router/HashRouterTest.java
*Motivation*
As part of implementing python client for #1690, we need a hash router to compute the hash routing value
for a given key.
*Changes*
- Murmur2 is not well supported in python 3. so standarized hash computation in using Murmur3.
- Change java hash router to use Murmur3
- Add python hash router
- Add unit tests to cover the hash value computation and make sure it is consistent across java and python
Master Issue: #1690 
> ---
> the precommit checks can take a long time, some trivial changes don't need to run all …
> [table service][python] add hash router for computing the hash routing value for a given key

- .gitignore
*Motivation*
when running bookkeeper servers using `bin/bookkeeper-daemon`, `pid` files
will be added in current directory.
*Changes*
Add `.pid` in `.gitignore`, so those pid files will be ignored.
> ---
>
> - [x] [skip bookkeeper-server bookie tests]: …
> [build] Ignore pid files

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
added try/finally around runnable.run()
To correctly track (metrics/log) runnable that throw unexpected exception.
added try/finally around runnable.run()
Master Issue: #1700 
> ---
>
> - [ ] [skip bookkeeper-server bookie tests]: skip testing …
> Issue #1700: fixed: TimedRunnable does not anticipate exception from wrapped runnable

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorElector.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorBookieTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorLedgerCheckerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicBookieCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
This is the 3rd change to remove zookeeper from Auditor. It also changes how
we construct metadata driver from AutoRecoveryMain. Since we are using bookkeeper client
and admin across auditor and replication. So change the AutoRecoveryMain to construct
the bookkeeper client from client configuration and pass bookkeeper client down to
replication worker and auditor.
> ---
> can check following list to skip the …
>  autorecovery-use-metadata-driver (part 3) : remove zookeeper from Auditor class

- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/sc/ZkStorageContainerManager.java
*Motivation*
the storage container manager probes containers to ensure containers are started and stopped to reflect to topology change.
however the logging can be very annoying if there is no topology changed.
*Changes*
Improve the logic to only log the message when topology is changed.
> ---
> you …
> [table service][logging] improve logging at zk storage container manager

- bin/bookkeeper
- conf/bk_server.conf
*motivation*
Currently `bin/bookkeeper` automatically choose modules based on the command.
However it would be much better to detect which module to use by checking the bookkeeper configuration settings.
*changes*
Improve `bin/bookkeeper` to better detect which module to use based on bookkeeper server configuration.
Additionally adding dlog related settings in the server configuration file.
> ---
> can check …
> [table service] improve the bookkeeper script to better detect whether table service is enabled or not

- pom.xml
Running tests on JDK11 requires a new version of Mockito, because in JDK11 they dropped Unsafe.defineClass.
Upgrade Mockito
Master Issue: #1710
> ---
> …
> Upgrade Mockito to 2.22.0 in order to support build on JDK11

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
*Motivation*
Currently when a request is failed, bookkeeper client logs the error message. However the log
message doesn't include error code. It makes debugging hard.
*Changes*
Improve the log message to include error code
> ---
>
> - [ ] [skip …
> [logging] PendingReadOp should log the error code when failing requests

- site/docs/4.8.0/overview/releaseNotes.md
- site/releases.md
- Fix a bunch of typos and indentation issues on 4.8.0 release page
- Fix releases.md
> ---
>
> - [x] [skip bookkeeper-server client …
> Fix release notes for 4.8.0

- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/DlogPerfCommandGroup.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/dlog/PerfReader.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/dlog/PerfReaderBase.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/dlog/PerfSegmentReader.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/dlog/PerfWriter.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/dlog/SegmentReadCommand.java
*Motivation*
Find what is the bottleneck/throughput limit of reading a single ledger.
*Changes*
Provide a `segread` perf command to split a stream into a list of segments and split segments into splits,
and test reading segment splits in parallel.
> ---
> …
> [tools][perf] Add a `segread` perf command to read distributedlog streams in segment splits

- stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/StorageClientImpl.java
- stream/common/src/main/java/org/apache/bookkeeper/common/util/AutoAsyncCloseable.java
Closing the storage client sometime takes long time. And closing the client typically happens at the last step. So we don't necessarily to be blocking at waiting it to complete.
Provide a timeout version of sync close. And timeout the closing operation if it doesn't complete within 1 second.
> ---
> …
> [table service] [client] Provide a timeout mechanism on closing the client

- tests/integration-tests-topologies/src/main/java/org/apache/bookkeeper/tests/containers/BookieContainer.java
- tests/integration-tests-topologies/src/main/java/org/apache/bookkeeper/tests/containers/ChaosContainer.java
- tests/integration-tests-utils/src/main/java/org/apache/bookkeeper/tests/integration/utils/DockerUtils.java
*Motivation*
For debugging purpose, it would be great to dump container logs before
stopping tests.
*Changes*
Copying container and bookkeeper logs before stopping the tests.
> ---
>
> - [ ] [skip bookkeeper-server bookie tests]: skip testing …
> [integration tests] Dump container logs before stopping tests

- stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/routing/RangeRouter.java
- stream/common/src/main/java/org/apache/bookkeeper/common/hash/Murmur3.java
- stream/common/src/main/java/org/apache/bookkeeper/common/router/BytesHashRouter.java
- stream/common/src/test/java/org/apache/bookkeeper/common/router/HashRouterTest.java
*Motivation*
Currently the hash router takes `ByteBuf`. At some cases,
we need to compute the hash of bytes array directly.
*Changes*
Add `BytesHashRouter` to compute hash value of bytes array directly,
avoiding wrapping bytes into `ByteBuf`
> ---
>
> - …
> [table service][common] add BytesHashRouter

- stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/channel/StorageServerChannel.java
- stream/clients/java/base/src/test/java/org/apache/bookkeeper/clients/impl/channel/TestStorageServerChannel.java
*Motivation*
When a storage server channel is intercepted, the underlying channel will not be `ManagedChannel`
any more. so closing storage server channel will never close the underlying managed channel.
*Changes*
StorageServerChannel#intercept should keep reference to the original storage server channel.
so when closing the intercepted channel, it can close the original channel.
> ---
> can check following list …
> [table service] Intercepted storage server channel should shutdown the underlying managed channel

- stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/channel/StorageServerChannel.java
- stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/internal/ProtocolInternalUtils.java
- stream/clients/java/base/src/test/java/org/apache/bookkeeper/clients/impl/channel/TestStorageServerChannel.java
- stream/proto/src/main/java/org/apache/bookkeeper/stream/protocol/ProtocolConstants.java
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/StorageServer.java
- stream/storage/api/src/main/java/org/apache/bookkeeper/stream/storage/api/sc/StorageContainerRegistry.java
- stream/storage/impl/pom.xml
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/StorageContainerStoreBuilder.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/StorageContainerStoreImpl.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/routing/RangeRoutingTable.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/routing/RangeRoutingTableImpl.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/routing/RoutingHeaderProxyInterceptor.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/routing/StorageContainerProxyChannelManager.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/routing/StorageContainerProxyChannelManagerImpl.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/routing/package-info.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/sc/StorageContainerRegistryImpl.java
- stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/TestStorageContainerStoreBuilder.java
- stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/TestStorageContainerStoreImpl.java
- stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/routing/RangeRoutingTableImplTest.java
- stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/routing/RoutingHeaderProxyInterceptorTest.java
- stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/routing/StorageContainerProxyChannelManagerImplTest.java
*Motivation*
In order to implement non-java clients and avoid the complexity in the client implementation.
We need to proxy a routing table in the server side for proxying table service requests.
*Changes*
Add routing table in the service side to proxy grpc requests to the right storage containers.
> ---
> can check following list to skip the tests that don't need to run for your pull request. Leave them …
> [table service][storage] add routing table for proxying table service requests

- pom.xml
- stream/common/pom.xml
- stream/distributedlog/core/pom.xml
- stream/proto/pom.xml
- stream/tests-common/pom.xml
Java Annotations API has been dropped from JRE since JDK11. We should add it explicitly at compile time.
As we are using only the '@Generated' annotation, which has "source" retention when can add the dependency as 'optional'.
We are not re-distributing the JAR in binary packages.
Add 'optional' dependency wherever it is needed (all GRPC artifacts for instance)
Master Issue: #1710
> ---
> can check following list …
> Add optional compile time only annotations-api dependency dropped in JDK11

- bookkeeper-server/pom.xml
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/LedgerManagerIteratorTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/sasl/GSSAPIBookKeeperTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/sasl/MiniKdc.java
- pom.xml
- move to Kerby (MiniKDC code copied from Apache ZooKeeper repository)
- adapt tests to run with new KDC
- force TCP on krb5.conf for tests (this is needed for Kerby, which opens only TCP by default config)
Master Issue: #1710 
> ---
>
> - [ ] [skip …
> Fix Kerberos tests on JDK11:

- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/StorageContainerStoreBuilder.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/metadata/MetaRangeStoreImpl.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/metadata/RootRangeStoreImpl.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/service/RangeStoreServiceFactoryImpl.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/service/RangeStoreServiceImpl.java
- stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/metadata/MetaRangeStoreImplTest.java
- stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/metadata/TestRootRangeStoreImpl.java
*Motivation*
Currently the creation of meta range for table is deferred until we first try to use it.
The propagation of stream properties is carried by the client.
*Changes*
Improve the creation logic to fetch stream properties from the root range.
> --- …
> [table service][storage] improve the logic on creating the meta range for a table

- .travis.yml
Start testing builds on JDK11, as it is the latest available version of Java 
Add Oracle JDK 11 to Travis configuration file
Master Issue: #1710
> ---
> …
> Add Oracle JDK11 to Travis CI build

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/net/ServiceURI.java
- conf/log4j.cli.properties
- stream/server/src/main/java/org/apache/bookkeeper/stream/cluster/StreamCluster.java
- tests/integration/cluster/src/test/java/org/apache/bookkeeper/tests/integration/stream/BkCtlTest.java
- tests/integration/standalone/src/test/java/org/apache/bookkeeper/tests/integration/standalone/StandaloneTest.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/Commands.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/NamespaceCommandGroup.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/TableAdminCommandGroup.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/TableCommandGroup.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/AbstractStreamCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/AdminCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/ClientCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/cluster/InitClusterCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/namespace/CreateNamespaceCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/namespace/DeleteNamespaceCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/namespace/GetNamespaceCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/table/CreateTableCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/table/DelCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/table/DeleteTableCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/table/GetCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/table/GetTableCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/table/PutCommand.java
*Motivation*
Add missing commands for table service related operations.
*Changes*
- Add missing commands such as get/delete
- Fill the default service uri if it is not provided
- Define the command ops in `Commands` util class
> ---
>
> - [x] [skip …
> [table service][cli] improve table service related cli commands

- bookkeeper-benchmark/pom.xml
- bookkeeper-common/src/test/java/org/apache/bookkeeper/test/TestStatsProvider.java
- metadata-drivers/etcd/pom.xml
- stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/config/StorageClientSettings.java
- stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/channel/StorageServerChannel.java
- stream/common/pom.xml
- stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/ClientStats.java
- stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/MonitoringClientCall.java
- stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/MonitoringClientCallListener.java
- stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/MonitoringClientInterceptor.java
- stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/MonitoringServerCall.java
- stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/MonitoringServerCallListener.java
- stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/MonitoringServerInterceptor.java
- stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/ServerStats.java
- stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/package-info.java
- stream/common/src/test/java/org/apache/bookkeeper/common/grpc/stats/ClientStatsTest.java
- stream/common/src/test/java/org/apache/bookkeeper/common/grpc/stats/GrpcStatsIntegrationTest.java
- stream/common/src/test/java/org/apache/bookkeeper/common/grpc/stats/ServerStatsTest.java
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/grpc/GrpcServer.java
*Motivation*
We need visibility on both client and server on table service.
*Changes*
- introduce grpc monitoring interceptors for both client and server
- enable monitoring interceptors on both client and server
> ---
>
> - [x] [skip bookkeeper-server …
> [table service][stats] enable stats for grpc calls on both client and server

- bookkeeper-server/pom.xml
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/Main.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/service/AutoRecoveryService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieInitializationTest.java
- lifecycle components for managing components in AutoRecovery
- expose metrics of AR in the same http admin endpoint
> Introduce lifecycle components for managing components in AutoRecovery

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/IOUtils.java
added close() variant that takes one Closeable.
100% of close() usage is with one Closeable.
light refactoring.
Master Issue: #1740 
> ---
>
> - [ ] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in bookkeeper-server …
> Issue #1740: IOUtils.close() only accepts Closeable as a vararg which results in unnecessary Object[] created if only one Closeable passed there

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForSingleEntryLog.java
*Motivation*
Fixes #1703.
The active entry log channel in EntryLogManagerForSingleEntryLog is closed twice during shutdown.
One is by EntryLogManagerForSingleEntryLog#close and the other one is EntryLogManagerForSingleEntryLog#forceClose().
*Changes*
This change is adding logic in BufferedChannel to make sure BufferedChannel can be closed multiple times.
> ---
> can check following list to skip the tests that …
> Issue 1703: IllegalReferenceCountException at closing EntryLogManagerForSingleEntryLog

- .test-infra/jenkins/job_bookkeeper_postcommit_master_python.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_integrationtests.groovy
- .test-infra/scripts/post-docker-tests.sh
- .test-infra/scripts/pre-docker-tests.sh
- pom.xml
- stream/clients/python/.gitignore
- stream/clients/python/bookkeeper/common/constants.py
- stream/clients/python/bookkeeper/common/util.py
- stream/clients/python/bookkeeper/kv/table.py
- stream/clients/python/nox.py
- stream/clients/python/scripts/docker_tests.sh
- stream/clients/python/scripts/test.sh
*Motivation*
We need have test coverage for python clients.
*Changes*
- add scripts to run python client tests for different python versions
- make sure the client can be built on both python2 and python3
- add a postcommit job to run python tests
> ---
> …
>  [table service][tests] add integration tests for python clients

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ReadLastConfirmedAndEntryOp.java
*Motivation*
I saw all CI jobs are failing when changes are cherry-picked for 4.7.3.
It turns about some cherry-picks broke the build before.
*Changes*
Fix the checkstyle issues on branch47
> ---
>
> - [ ] [skip bookkeeper-server bookie tests]: skip …
> [build] Fix checkstyle issues on branch47

- stream/api/src/main/java/org/apache/bookkeeper/api/StorageClient.java
- stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/SimpleClientBase.java
- stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/SimpleStorageClientImpl.java
- stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/StorageClientBuilder.java
- stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/StorageClientImpl.java
- stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/admin/SimpleStorageAdminClientImpl.java
- stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/admin/StorageAdminClient.java
- stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/admin/StorageAdminClientImpl.java
- stream/clients/java/all/src/test/java/org/apache/bookkeeper/clients/StorageClientImplTest.java
- stream/clients/java/all/src/test/java/org/apache/bookkeeper/clients/admin/TestStorageAdminClientImpl.java
*Motivation*
In some cases, we are using same storage client for opening tables under different namespaces.
It would be good that a client instance can do that.
*Changes*
- Add methods to `StorageClient` to open tables under different namespaces
- Add `asClient` to `StorageAdminClient` to convert admin client to storage client
> ---
> can check following list to skip the tests that don't need to run for your pull …
> [table service][client] storage client can open tables on a different namespace

- .travis.yml
- .travis_scripts/build.sh
- bin/bookkeeper
- pom.xml
- tools/pom.xml
*Motivation*
There are two issues in current master when building without stream
- build `bkperf` failed
- bin/bookkeeper is using the wrong module
*Changes*
- build `bkperf` module as part of `stream` profile
- fix the problem in `bin/bookkeeper` locating the right module
- add two tests in travis to test builds without `stream` profile
> ---
> can check following list to skip the tests that don't need to run …
> [build] Fix build & bash script error when not using `stream` profile

- dev/bk-merge-pr.py
- dev/bk-merge-pr3.py
*Motivation*
We are using github api to merge pull requests now.
So the authors section is not correct, remove that section and rely on github merge api.
*Changes*
remove authors section in the commit log.
> ---
>
> - [x] [skip bookkeeper-server bookie …
> [merge script] remove authors section

- site/docs/4.7.2/api/ledger-api.md
- site/docs/4.8.0/api/ledger-api.md
- site/docs/latest/api/ledger-api.md
Link should be to a section in same page
> [website] Fix broken link to ledger-api#example-application

- metadata-drivers/etcd/pom.xml
*Motivation*
apache/bookkeeper#1766 attempts to disable etcd tests in normal builds.
however it only added the `integrationTests` profile but didn't disable tests
in normal builds.
*Changes*
Disable etcd tests in normal builds
Master Issue: #1752 
> ---
> …
> [tests] Issue #1752: disable etcd tests in normal builds

- stream/clients/python/bookkeeper/common/service_uri.py
- stream/clients/python/bookkeeper/common/util.py
- stream/clients/python/tests/unit/bookkeeper/common/test_service_uri.py
- stream/clients/python/tests/unit/bookkeeper/common/test_util.py
*Motivation*
Similar as #1778, add default port to service hosts if port is missing.
*Changes*
add default port to service hosts if they miss ports
Related Issue: #1778
> ---
>
> - [x] [skip bookkeeper-server bookie tests]: skip testing …
>  [table service][python] add default port to service hosts

- bookkeeper-dist/src/assemble/bin-all.xml
- bookkeeper-dist/src/assemble/bin-server.xml
- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/deps/jline-2.11/LICENSE
- pom.xml
Upgraded jline and jackson to remove security vulnerabilities mentioned in #1767 
Remove security vulnerabilities mentioned in #1767 
Upgraded jline and jackson 3rd party dependencies
Master Issue: #1767 
> ---
>
> - [ ] [skip bookkeeper-server bookie …
> Issue 1767: security vulnerabilities in 3rd party dependencies

- site/bps/BP-34-cluster-metadata-checker.md
> Fix indentation in BP-34 doc

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ReadOnlyLedgerHandle.java
*Motivation*
when #1791 is cherry-picked into branch-4.8, it breaks the build.
*Changes*
Fix the compilation issue.
Related Issue: #1791 
> ---
> …
> [branch 4.8] Fix compilation issue introduced by issue #1791

- site/bps/BP-34-cluster-metadata-checker.md
- this condensed encoding format will take fewer bytes than initially
proposed bit vector.
> Introduce condensed encoding format for availabilityOfEntriesOfLedger

- bin/bookkeeper
- bin/common.sh
*Motivation*
`bin/bookkeeper standalone` is broken when a release package is built without including `stream` profile.
*Changes*
`standalone` is a service component including everything. so fail the command if it can't locate corresponding components.
Related Issues: #1822
> ---
> you are not sure, …
> [scripts] improve bookkeeper script to better handle standalone command

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadata.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadataBuilder.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerRecoveryTest.java
> Make LedgerMetadata fields for closing immutable

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadata.java
> Make custom metadata final

- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SortedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/TriggerGCService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
- site/docs/latest/admin/http.md
Add rest endpoint trigger_gc to trigger GC on Bookie
Some times user would like to trigger GC manually instead of waiting to the timeout or disk full. 
> ---
> …
> Add rest endpoint trigger_gc to trigger GC on Bookie

- dev/release/000-run-docker.sh
* Motivation
#1674 introduced a regression for running release scripts on mac.
the destination should be "/home/${USER}" rather than ${LOCAL_HOME}.
because the docker os is linux. Otherwise the gpg keys can not propagated
correctly from host machine to docker.
* Changes
Use `/home/${USER}` as the destination path
> ---
> can check following list to skip the tests that don't need to run for your pull request. …
> [release] fix docker mount volume issue

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/stats/BookieStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ForceLedgerProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/GetBookieInfoProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/LongPollReadEntryProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBaseV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadLacProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/RequestStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteLacProcessorV3.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ForceLedgerProcessorV3Test.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorV3Test.java
- bookkeeper-stats/src/main/java/org/apache/bookkeeper/stats/annotations/StatsDoc.java
*Motivation*
As part of [BP-36](https://github.com/apache/bookkeeper/issues/1785), this PR is to document the request stats
for bookkeeper server.
*Changes*
- add `parent` and `happensAfter` in @StatsDoc
- convert bookie request stats to use @StatsDoc for documenting metrics
Master Issue: #1785 
> ---
> can check following list to skip the tests that don't need to run for your pull request. Leave them unchecked …
> [stats] Add @StatsDoc annotation for bookie server request stats

- .test-infra/jenkins/common_job_properties.groovy
*Motivation*
Since we have more releases, the build time for website is increasing to beyond 30 min.
Increase it to 120 mins for now
> ---
>
> - [ ] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in bookkeeper-server …
> [CI] increase timeout of website build to 120 mins

- docker/Dockerfile
Change version from 4.8.0 in 4.8.1 on Dockerfile in branch-4.8
Distribute new Docker images for 4.8.1 release
> ---
>
> - [x] [skip …
> Update BookKeeper version in Docker file for 4.8.1 release

- site/_config.yml
Change website configuration so that the downloads make suggest 4.8.1 and 4.8.0
> ---
>
> - [x] [skip bookkeeper-server client tests]: …
> Mark 4.8.1 as latest release

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
review code and found extra code.
clean code
clean extra code
> ---
>
> - [x] [skip …
> [table service] remove extra code

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
*Motivation*
ParallelRead is actually used internally at ledger recovery. It is used at production.
*Changes*
Removed misleading comment.
> ---
>
> - [x] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in …
> remove misleading comment

- site/docs/4.7.3/overview/releaseNotes.md
> ---
>
> - [x] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [x] [skip bookkeeper-server replication …
> [release notes] Release Notes for 4.7.3

- docker/Dockerfile
*Motivation*
Update release version in the docker file
> ---
>
> - [x] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server …
> [release][docker] Update the docker file for release 4.7.3

- .test-infra/jenkins/job_bookkeeper_precommit_bookie_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_client_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_integrationtests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_java8.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_java9.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_remaining_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_replication_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_tls_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_validation.groovy
*Motivation*
Sometime people don't know how to retrigger a bookkeeper precommit job.
*Changes*
This PR is adding the trigger phrase to the job caption. so people will know
how to retrigger the jobs in the PR itself.
> ---
>
> - [ ] [skip bookkeeper-server …
> [CI] Update precommit job captions with trigger phrase

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForEntryLogPerLedger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
*Motivation*
As part of [BP-36](https://github.com/apache/bookkeeper/issues/1785),
this PR is to document the entrylogger stats.
*Changes*
- convert entrylogger stats to use @StatsDoc for documenting metrics
> ---
>
> - [ ] [skip …
> [stats][doc] Add @StatsDoc annotation for entrylogger stats

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieStateManager.java
*Motivation*
As part of [BP-36](https://github.com/apache/bookkeeper/issues/1785), this PR is to document bookie state manager stats.
*Changes*
- convert bookie state manager stats to use @StatsDoc for documenting metrics
> ---
>
> - [ …
> [stats][doc] Add @StatsDoc annotation for bookie state manager stats

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
*Motivation*
As part of [BP-36](https://github.com/apache/bookkeeper/issues/1785), this PR is to document interleaved ledger storage stats.
*Changes*
- convert interleaved ledger storage stats to use @StatsDoc for documenting metrics
> ---
> you are not sure, committers will help …
> [stats][doc] Add @StatsDoc annotation for interleaved ledger storage stats

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryMemTable.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryMemTableWithParallelFlusher.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/stats/EntryMemTableStats.java
*Motivation*
As part of [BP-36](https://github.com/apache/bookkeeper/issues/1785), this PR is to document the memtable stats.
*Changes*
- convert memtable stats to use @StatsDoc for documenting metrics
> ---
>
> - [ ] [skip …
> [stats][doc] Add @StatsDoc annotation for memtable stats

- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectionStatus.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SortedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/GCDetailsService.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/TriggerGCService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
- site/docs/latest/admin/http.md
Add get method for rest endpoint gc to get force triggered GC running status on Bookie.
true -- force triggered GC is running on Bookie. false -- not running.
This is base on PR #1838, and in the review comments @sijie is suggested to add get methods.
Add get method for rest endpoint gc and unit test.
> ---
> can check following list to skip the tests that don't need to run for your pull request. Leave them …
> Add get method for rest endpoint gc 

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndexStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndexStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
*Motivation*
As part of [BP-36](https://github.com/apache/bookkeeper/issues/1785), this PR is to document the db ledger storage stats.
*Changes*
- convert db ledger storage stats to use @StatsDoc for documenting metrics
> ---
>
> - [ ] …
> [stats][doc] Add @StatsDoc annotation for db ledger storage stats

- site/bps/BP-37-conf-documentation.md
- site/community/bookkeeper_proposals.md
*Motivation*
One common task in developing bookkeeper is to make sure all the configuration
settings are well documented, and the configuration file we ship in each release
is in-sync with the code itself.
However maintaining things in-sync is non-trivial. This proposal is exploring
a new way to manage configuration settings for better documentation.
Master Issue: #1867
> ---
> can check following list to skip …
> BP-37: Improve configuration management for better documentation

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/ScanAndCompareGarbageCollector.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/stats/GarbageCollectorStats.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/GcLedgersTest.java
*Motivation*
As part of [BP-36](https://github.com/apache/bookkeeper/issues/1785), this PR is to document gc stats.
*Changes*
- convert gc stats to use @StatsDoc for documenting metrics
> ---
>
> - [ ] [skip bookkeeper-server bookie …
> [stats][doc] Add @StatsDoc annotation for garbage collector stats

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexInMemPageMgr.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexPersistenceMgr.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/stats/IndexInMemPageMgrStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/stats/IndexPersistenceMgrStats.java
*Motivation*
As part of [BP-36](https://github.com/apache/bookkeeper/issues/1785), this PR is to document the ledger cache stats.
*Changes*
- convert ledger cache stats to use @StatsDoc for documenting metrics
> ---
>
> - [ ] [skip …
> [stats][doc] Add @StatsDoc annotation for ledger cache stats

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/conf/ConfigDef.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/conf/ConfigException.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/conf/ConfigKey.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/conf/ConfigKeyGroup.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/conf/Type.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/conf/Validator.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/conf/validators/ClassValidator.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/conf/validators/NullValidator.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/conf/validators/Range.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/conf/validators/RangeValidator.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/conf/validators/package-info.java
- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/conf/ConfigDefTest.java
- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/conf/ConfigKeyGroupTest.java
- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/conf/ConfigKeyTest.java
- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/conf/validators/ClassValidatorTest.java
- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/conf/validators/RangeValidatorTest.java
- bookkeeper-common/src/test/resources/test_conf_2.conf
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/SortedLedgerStorageCheckpointTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/conf/TestServerConfiguration.java
- pom.xml
One common task in developing bookkeeper is to make sure all the configuration
settings are well documented, and the configuration file we ship in each release
is in-sync with the code itself.
However maintaining things in-sync is non-trivial. This proposal is exploring
a new way to manage configuration settings for better documentation.
- Introduce `ConfigKey` for defining a configuration setting key in a configuration
- Introduce `ConfigKeyGroup` for grouping configuration settings together
- Introduce `ConfigDef` for generating the configuration definition for a given configuration
- Add a `save` method for saving a configuration definition into a configuration file
Master Issue: #1867 
> ---
> In order to uphold a high standard for quality for …
> Introduce a configuration framework for better organizing and documentating configuration settings

- bookkeeper-dist/pom.xml
- pom.xml
> replace default source-release-assembly by bookkeeper-dist

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RoundRobinDistributionSchedule.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/RoundRobinDistributionScheduleTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/BookieAutoRecoveryTest.java
Since count `nodesUninitialized` is always 0,
there is no wait if we haven't seen any OK responses and there are still nodes not heard from
Correct  nodesUninitialized count and add a related testcase
> ---
>
> - [ ] [skip bookkeeper-server bookie tests]: …
> Small fix wrong nodesUninitialized count when checkCovered

- stream/api/pom.xml
- stream/bk-grpc-name-resolver/pom.xml
- stream/clients/java/all/pom.xml
- stream/clients/java/base/pom.xml
- stream/clients/java/kv/pom.xml
- stream/clients/java/pom.xml
- stream/clients/pom.xml
- stream/common/pom.xml
- stream/pom.xml
- stream/proto/pom.xml
- stream/server/pom.xml
- stream/statelib/pom.xml
- stream/storage/api/pom.xml
- stream/storage/impl/pom.xml
- stream/storage/pom.xml
- stream/tests-common/pom.xml
- tests/integration/cluster/pom.xml
- tools/perf/pom.xml
- tools/stream/pom.xml
*Motivation*
when creating branch-4.9, maven release plugin doesn't bump the version for stream modules.
run `mvn versions:set` to manually fix the version for all modules
> ---
>
> - [ ] [skip bookkeeper-server bookie tests]: skip testing …
> [build] Fix master build after release 4.9.0

- stream/api/pom.xml
- stream/bk-grpc-name-resolver/pom.xml
- stream/clients/java/all/pom.xml
- stream/clients/java/base/pom.xml
- stream/clients/java/kv/pom.xml
- stream/clients/java/pom.xml
- stream/clients/pom.xml
- stream/clients/python/setup.py
- stream/common/pom.xml
- stream/pom.xml
- stream/proto/pom.xml
- stream/server/pom.xml
- stream/statelib/pom.xml
- stream/storage/api/pom.xml
- stream/storage/impl/pom.xml
- stream/storage/pom.xml
- stream/tests-common/pom.xml
- tests/integration/cluster/pom.xml
- tools/perf/pom.xml
- tools/stream/pom.xml
*Motivation*
Update the table service python client version to release version
Bump the version to 4.9.0
> ---
>
> - …
> [release] Release table service python client

- dev/release/004-stage-packages.sh
- stream/api/pom.xml
- stream/bk-grpc-name-resolver/pom.xml
- stream/clients/java/all/pom.xml
- stream/clients/java/base/pom.xml
- stream/clients/java/kv/pom.xml
- stream/clients/java/pom.xml
- stream/clients/pom.xml
- stream/common/pom.xml
- stream/pom.xml
- stream/proto/pom.xml
- stream/server/pom.xml
- stream/statelib/pom.xml
- stream/storage/api/pom.xml
- stream/storage/impl/pom.xml
- stream/storage/pom.xml
- stream/tests-common/pom.xml
- tests/integration/cluster/pom.xml
- tools/perf/pom.xml
- tools/stream/pom.xml
*Motivation*
starting from bookkeeper 4.9.0, a separate tool package `bkctl` is released.
add bkctl into release scripts
> ---
> …
> [release] add bkctl package to release scripts

- stream/clients/python/setup.py
Bump the development of python client to 4.10.0-SNAPSHOT
> ---
>
> - [x] [skip bookkeeper-server client tests]: skip …
> [table service] bump python client version to 4.10.0-SNAPSHOT

- .github/ISSUE_TEMPLATE/bp.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
*Motivation*
Following the Github community recommendations (https://github.com/apache/bookkeeper/community)
to break down current ISSUE_TEMPLATE to multiple single templates
- break down the `ISSUE_TEMPLATE.md` into multiple files in `ISSUE_TEMPLATE`
- fix the skip phrase in PULL_REQUEST_TEMPLATE
> ---
> can check following list to skip the tests that don't need to run for your pull request. …
> [dev] Break current ISSUE_TEMPLATE into multiple single templates

- site/community/releases.md
> ---
>
> - [x] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [x] [skip bookkeeper-server replication …
> [website] Update release schedule for 4.10.0

- site/community/release_guide.md
> ---
>
> - [x] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [x] [skip bookkeeper-server replication …
> [doc] Add python client release instructions to release guide

- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/AbstractDNSToSwitchMapping.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/ScriptBasedMapping.java
- filter empty string for networkTopologyScriptFileName.
> Filter empty string for networkTopologyScriptFileName

- docker/README.md
- site/_data/cli/bookkeeper-daemon.yaml
- site/_data/cli/bookkeeper.yaml
- site/_includes/shell.html
- site/docs/latest/admin/autorecovery.md
- site/docs/latest/admin/bookies.md
- site/docs/latest/api/ledger-api.md
- site/docs/latest/deployment/manual.md
- site/docs/latest/getting-started/run-locally.md
> [DOC] Fix command path in documents

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/Shell.java
- Log error (if any) in Shell.runCommand even in the case of successful execution
> Log error (if any) in Shell.runCommand

- stream/clients/python/setup.py
*Motivation*
The development cycle of branch-4.9 is 4.9.1
Update the python client version to `4.9.1-alpha-0`
Related Issue: #1954 
> ---
>
> - [x] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in …
> [python][branch-4.9] Bump python client version to 4.9.1-alpha-0

- bookkeeper-http/vertx-http-server/src/test/java/org/apache/bookkeeper/http/vertx/TestVertxHttpServer.java
As discussed at #1953, adding test to verify all http-method works for vertx-http-server.
> Add http method test for vertx-http server

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieStatus.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Cookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
We can use automatic resource management introduced in java 7, which makes code shorter.
> Use automatic resource management to close streams

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDirsMonitor.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieInitializationTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieStorageThresholdTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/IndexPersistenceMgrTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/TestLedgerDirsManager.java
> Use the same thread to monitor ledger and index directories

- stream/clients/python/setup.py
> ---
>
> - [x] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [x] [skip bookkeeper-server replication …
> Bump python client to 4.9.1

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndexTest.java
Fixes #2001
*Motivation*
When met a unexpect entry id, db indexes failed cleanup.
Catch the exception and ignore it.
Master Issue: #2001 
> ---
>
> - [ ] [skip …
> Fix when met unexpect entry id crashed

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerCache.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/FormatUtil.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadJournalCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadJournalCommandTest.java
- Use `bkctl` execute `readjournal` command
- Migrate from bookieshelll
> ---
>
> - [ ] [skip bookkeeper-server client tests]: skip …
> Migrate command `readjournal`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListLedgersCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListLedgersCommandTest.java
Using `bkctl` run command `listledgers`
#2004
> Migrate command `listledgers`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/MetaFormatCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookiesCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookies/MetaFormatCommandTest.java
> Migrate command `metadataformat`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/DeleteLedgerCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/LedgerCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/client/DeleteLedgerCommandTest.java
> Migrate command `deleteledger`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogMetadata.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLogMetadataCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLogMetadataCommandTest.java
> Migrate command `readlogmetadata`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/InitCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookiesCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookies/InitCommandTest.java
> Migrate command `initnewcluster`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/NukeExistingClusterCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookiesCommandGroup.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/LedgerCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookies/NukeExistingClusterCommandTest.java
> Migrate command `nukeexistingcluster`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLogCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLogCommandTest.java
> Migrate command `readlog`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/DecommissionCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookiesCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookies/DecommissionCommandTest.java
> Migrate command `decommission`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/InstanceIdCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookiesCommandGroup.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/LedgerCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookies/InstanceIdCommandTest.java
> Migrate command `Whatisinstanceid`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/LedgerMetaDataCommand.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/TestLedgerMetadataSerDe.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/LedgerCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/client/LedgerMetaDataCommandTest.java
Using `bkctl` run command `ledgermetadata`
#2018
> Migrate command `ledgermetadata`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/LastMarkCommand.java
`lastmark` shell command is to be used while debugging however currently it cannot be used since it returns incorrect value.
Updated `LedgerDirsManager` object initialization to use correct `ledgerDirs`.
Master Issue: #2075
> ---
>
> - [ ] [skip …
> ISSUE #2075: Bookieshell lastmark command isn't functional, always returning 0-0

- site/docs/4.9.2/overview/releaseNotes.md
Release notes for patch release
> Added release notes for release 4.9.2

- site/_data/config/bk_server.yaml
Fixes #2079
when the client-side attempt to send more than the default size bytes, it should set up the corresponding parameter `setNettyMaxFrameSizeBytes(int maxSize)`
Master Issue: #2079 
> ---
> you are not sure, …
> [site]modify nettyMaxFrameSizeBytes Description

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MetadataDrivers.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/discover/MockRegistrationClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockBookieClient.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/ReadAheadEntryReader.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/bk/LedgerAllocatorPool.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/namespace/NamespaceDriverManager.java
* Use the `addAll` method instead of iteration
> Use bulk operation instead of iteration

- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookies/ListBookiesCommandTest.java
Introduced and fixed the tests involving the ListBookiesCommand
> Issue #2124: Test 'ListBookiesCommand ' is failing

- pom.xml
Build fails on recent JDK11 versions and on JDK11, see #2133, this is because javadoc has problems with references to core Java API when source version is set to 8.
Upgrade Java doc plugin to latest 3.1.1 and disable auto linking to core Java classes with
`<detectJavaApiLink>false</detectJavaApiLink>
`
Closes #2133
> ---
> can check following list to skip the tests that don't need to run for your pull request. …
> Make build pass on JDK11, fix javadoc configuration

- .test-infra/jenkins/common_job_properties.groovy
- dev/docker/Dockerfile
- dev/docker/run.sh
- dev/release/Dockerfile
- ASF CI does not support Maven 3.5.0
- Maven 3.5.0 is a very old version
- update Jenkins DSL files to "Maven (latest)"
- update release procedure to Maven 3.6.1
- update docker based dev environment to use Maven 3.6.1 + jdk11 (it was 3.5.0 + legacy jdk9)
> ---
>
> - [ ] [skip …
> Upgrade to latest Maven version 3.6.1

- bookkeeper-server/src/main/java/org/apache/bookkeeper/sasl/SaslClientState.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/sasl/SaslConstants.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/sasl/GSSAPIBookKeeperTest.java
- site/docs/4.9.2/security/sasl.md
default SASL service name "bookkeeper" can be override by JVM property "bookkeeper.sasl.servicename"
Instead of use a constant value, it would read from JVM property first, if it doesn't exists, then use default value from constant variable SaslConstants.SASL_BOOKKEEPER_PROTOCOL
Master Issue: #2127
> ---
> can check following list to skip the tests that don't need to run for your pull request. Leave them …
> Issue #2127: Allow user override default SASL service name bookkeeper

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/AvailabilityOfEntriesOfLedger.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTest.java
- adding comprehensive testcases for newly added
scrutiny - replicasCheck.
> Replicascheck comprehensive testcases.

- tests/backward-compat/current-server-old-clients/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatOldClients.groovy
- tests/backward-compat/hostname-bookieid/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatUpgradeWithHostnameBookieId.groovy
- tests/backward-compat/upgrade/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatUpgrade.groovy
- tests/docker-images/all-released-versions-image/Dockerfile
- tests/docker-images/all-released-versions-image/scripts/install-tarball.sh
- tests/docker-images/all-versions-image/scripts/install-all-tarballs.sh
With backward compatibility tests we should cover the compatibility of current version against old versions, current we are only test current version against ancient releases.
This change supersedes #1648 from @sijie 
Change the list of versions to test clients and bookie upgrade
> ---
>
> - [ …
> Update bc tests to include versions up to 4.9.x

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandleAdv.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/api/WriteAdvHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/api/WriteHandle.java
Adding documentation for the issue [here](https://github.com/apache/bookkeeper/issues/2138) as discussed [here](https://github.com/apache/bookkeeper/issues/2138#issuecomment-522099668).
Master Issue: #2138
> Add documentation for ByteBuffer lifecycle when adding entries

- pom.xml
Update the reference to the common Apache Parent POM, version 19
Be up to date with ASF-wide configurations
Change the version
> ---
> …
> Upgrade Apache Parent Pom to 19

- dev/release/001-release-branch.sh
- dev/release/002-release-prepare.sh
- dev/release/003-release-perform.sh
With this commit we disable Twitter providers from default build
https://github.com/apache/bookkeeper/commit/b689d8313654de21759b2e2d47210b75434038c3
This leads to inconsistences during the release process
Add -Dtwitter to every release script
> ---
>
> - [x] [skip bookkeeper-server bookie …
> Add -Dtwitter to release scripts in order to build Twitter stats providers

- bin/common.sh
Make bin/bookkeeper standalone work again
Add -Dtwitter in order to activate "Twitter" profile and build Twitter stats providers.
> ---
>
> - [x] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in bookkeeper-server …
> Add -Dtwitter to fix auto-build

- site/_config.yml
4.10.0 has been released, 4.9.2 has been running in production for a while on several known projects. We can mark 4.9.2 as current 'stable' 
Update website config.
Fix DLog version.
> ---
>
> - [x] [skip bookkeeper-server bookie tests]: skip testing …
> Make 4.9.2 as stable

- site/_data/sidebar.yaml
- site/docs/latest/admin/decomission.md
Documentation on how to decommission a bookie safely.
Added `decommission.md`
> [documentation] Add doc for decommissioning bookie process

- .travis.yml
- .travis_scripts/build.sh
- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
fixes #2227
- Account Thrift and Http client in LICENSE files.
- Force using Maven 3.6.3 in MacOSx builds on Travis
- Test only with -Dstream profile
Those files are inside the binary packages but they are not taken into account in LICENSE file.
Travis started to report errors when Travis updated Maven version to 3.6.2 in Linux machines, MaxOSx machines are still with 3.3.9 and the build does not bundle all of the needed jars ! 
Master Issue: #2227 
> ---
> the precommit checks can take a long time, some trivial changes …
> Account Apache Thrift and Http Client files in LICENSE files - Fix build on Travis

- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/cluster/ZkClusterInitializer.java
Increase the 'segment store path' in the 'Initializing stream cluster' log
> Increase the 'segment store path' in the 'Initializing stream cluster' log

- site/docs/4.10.0/api/ledger-api.md
- site/docs/4.5.0/api/ledger-api.md
- site/docs/4.5.1/api/ledger-api.md
- site/docs/4.6.0/api/ledger-api.md
- site/docs/4.6.1/api/ledger-api.md
- site/docs/4.6.2/api/ledger-api.md
- site/docs/4.7.0/api/ledger-api.md
- site/docs/4.7.1/api/ledger-api.md
- site/docs/4.7.2/api/ledger-api.md
- site/docs/4.7.3/api/ledger-api.md
- site/docs/4.8.0/api/ledger-api.md
- site/docs/4.8.1/api/ledger-api.md
- site/docs/4.8.2/api/ledger-api.md
- site/docs/4.9.0/api/ledger-api.md
- site/docs/4.9.1/api/ledger-api.md
- site/docs/4.9.2/api/ledger-api.md
- site/docs/latest/api/ledger-api.md
This PR :
1. add missing comma and dot
2. fix some layout error
in ledger-api document
> [hotfix][docs] fix error in leger api document

- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/tls-tests.yml
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/EntryMemTableTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/FileInfoBackingCacheTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/GcOverreplicatedLedgerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerDirsManagerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/SkipListArenaTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/SyncThreadTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/TestEntryLog.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/TestInterleavedLedgerStorage.java
---
Master Issue: #2242
Migrate theJenkins CI to Github Action
> [CI] Migrate the Jenkins CI to Github Action

- site/bps/BP-38-bookie-endpoint-discovery.md
This is the BP page for BP-38 Publish Bookie Service Info on Metadata Service
Master Issue: #2215 
> ---
>
> - [ ] [skip bookkeeper-server client tests]: skip testing …
> BP-38 Publish Bookie Service Info on Metadata Service

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
This PR fix NullPointerException when exec readjournal command
See issue #2279
> #2279 fix NPE when exec readjournal command

- pom.xml
Update Arquillian to latest version
> Update Arquillian Cube to 1.18.2

- site/docs/4.10.0/development/protocol.md
- site/docs/4.10.0/getting-started/concepts.md
Fix minor mistakes in the sentences of the documentation
> ---
>
> - [ ] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in …
> Fix mistakes in documentation

- conf/bk_server.conf
- site/_data/config/bk_server.yaml
From 4.6.0 SSLContextFactory has been changed into TLSContextFactory. but some of the doc not updated.
Updated related doc.
> [Doc]:  SSLContextFactory -> TLSContextFactory

- tests/backward-compat/current-server-old-clients/pom.xml
- tests/backward-compat/hierarchical-ledger-manager/pom.xml
- tests/backward-compat/hostname-bookieid/pom.xml
- tests/backward-compat/old-cookie-new-cluster/pom.xml
- tests/backward-compat/pom.xml
- tests/backward-compat/recovery-no-password/pom.xml
- tests/backward-compat/upgrade-direct/pom.xml
- tests/backward-compat/upgrade/pom.xml
- tests/backward-compat/yahoo-custom-version/pom.xml
- tests/integration/cluster/pom.xml
- tests/integration/pom.xml
- tests/integration/smoke/pom.xml
- tests/integration/standalone/pom.xml
Fix wrong maven artifactId, there are three module use the same artifactId.
> Fix wrong module artifactId

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieStateManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryMemTable.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileInfo.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDescriptorImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ExplicitLacFlushPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerLayout.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/ScriptBasedMapping.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClientImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/DecommissionService.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/TLSContextFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLogMetadataCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSet.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperAdminTest.java
- circe-checksum/src/main/java/com/scurrilous/circe/Hashes.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/proto/ProtocolBenchmark.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/DigestTypeBenchmark.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/stats/StatsLoggerBenchmark.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/stats/codahale/TimerBenchmark.java
Fix compilation failure after merged https://github.com/apache/bookkeeper/pull/2338
Fix wrong package location.
> [BUG] Fix class not found compilation failure

- stream/distributedlog/common/pom.xml
- stream/distributedlog/core/pom.xml
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/metadata/ZKLogStreamMetadataStore.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/subscription/ZKSubscriptionStateStore.java
- stream/distributedlog/io/dlfs/pom.xml
- stream/distributedlog/io/pom.xml
- stream/distributedlog/pom.xml
- stream/distributedlog/protocol/pom.xml
- stream/pom.xml
- fix version
- add explicitly distributedlog to the modules of Stream project
- fix checkstyle on distributedlog, it wasn't executed
> Fix distributedlog Maven reactor module

- stream/clients/python/setup.py
Bump up python client version 4.12.0-alpha-0
> Bump Python client version: 4.12.0-alpha-0

- site/_sass/vendor/bulma/sass/layout/footer.sass
- site/css/style.sass
Improve the user experience of the site.
**Compare:**
https://lamber-ken.github.io/docs/4.10.0/getting-started/installation/
https://bookkeeper.apache.org/docs/4.10.0/getting-started/installation/
> [SITE] Improve the user experience of the site

- site/bps/BP-41-bookieid.md
- site/community/bookkeeper_proposals.md
This is the design document of "BP-41 Separate BookieId from Bookie Network Address"
Master Issue: #2396
> BP-41 Separate BookieId from Bookie Network Address

- site/docs/4.10.0/getting-started/concepts.md
- site/docs/4.11.0/getting-started/concepts.md
- site/docs/4.11.1/getting-started/concepts.md
- site/docs/4.5.0/getting-started/concepts.md
- site/docs/4.5.1/getting-started/concepts.md
- site/docs/4.6.0/getting-started/concepts.md
- site/docs/4.6.1/getting-started/concepts.md
- site/docs/4.6.2/getting-started/concepts.md
- site/docs/4.7.0/getting-started/concepts.md
- site/docs/4.7.1/getting-started/concepts.md
- site/docs/4.7.2/getting-started/concepts.md
- site/docs/4.7.3/getting-started/concepts.md
- site/docs/4.8.0/getting-started/concepts.md
- site/docs/4.8.1/getting-started/concepts.md
- site/docs/4.8.2/getting-started/concepts.md
- site/docs/4.9.0/getting-started/concepts.md
- site/docs/4.9.1/getting-started/concepts.md
- site/docs/4.9.2/getting-started/concepts.md
- site/docs/latest/getting-started/concepts.md
> Fix site 'responsbility' typo

- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/helpers/CommandHelpers.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookies/ListBookiesCommandTest.java
NP check for print BookieSocketAddress and a better format to fix issues #2376 and #2371
* NP check for print BookieSocketAddress on listbookies command
* A better format mentioned on #2376 
Master Issue: #2376 #2371
> NP check for print BookieSocketAddress and a better format

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
Under heavy load, the write cache can fill up faster than it can be
flushed. When this occurs, something needs to trigger the
flush. Previously we've triggered the flush and then gone into a loop
waiting to be able to add to the write cache. However, if the
currently active write cache fills while we are waiting for the
flushing write cache to be flushed, we can end up in a situation where
nothing is able to flush because all I/O threads are waiting for the
write cache to empty.
The solution is to move the flush into the loop so that if we fail to
add to the cache, we flush the write cache if it is needed.
> Trigger flush if write cache is full while waiting

- bookkeeper-server/pom.xml
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-stats/pom.xml
- pom.xml
- stream/distributedlog/pom.xml
Resolves #2285
We write "bookie server unavailable log" every 30 seconds per bookie client
> Spammy log when one bookie of ensemble is down #2285

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
Porting of #2285 PR on 4.11 branch
> Spammy log when one bookie of ensemble is down (4.11 porting) 

- site/_data/cli/shell.yaml
the web site rendering error in section reference/cli/ updateBookieInLedger Options
> ---
>
> ---
>
>
> - [ …
> fix website rendering 

- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/tls-tests.yml
Set log level to INFO.
@fpj noticed that sometimes Maven build fails but the action completes successfully
> Do not hide Maven log in github actions

- site2/docs/bookkeeper-proposals.md
- site2/docs/coding-guide.md
- site2/docs/contributing.md
- site2/docs/issue-report-guide.md
- site2/docs/mailing-lists.md
- site2/docs/papers-and-presentations.md
- site2/docs/release-guide.md
- site2/docs/release-management.md
- site2/docs/testing-guide.md
- site2/website/pages/en/community.js
This PR introduces changes to complete the community page of the new up-coming docusaurus based website.
The #2426 Pull Request introduced the changes for new docuasurus based website, However few of the pages like community and project were incomplete. This PR introduces the changes to complete the community page.
I have added the markdown files for the following web-pages - 
* bookkeeper-proposals
* coding-guide
* community-meetings
* contributing
* issue-report-guide
* mailing-lists
* papers-and-presentations
* release-guide
* release-management
* testing-guide
I have also updated the code in community.js to refactor the way tables for PMC and committers is getting generated, So that we get the best out of the react based framework.
I have build …
> [Issue 2443] Complete community page in the new docusaurus website

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestHandler.java
fix #2475 
add channel information if catch exception in BookieRequestHandler
> add channel information if catch exception in BookieRequestHandler

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileInfo.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexPersistenceMgr.java
1. Remove redundant synchronized
2. rename fi.getSizeSinceLastwrite -> fi.getSizeSinceLastWrite
3. fix typo
> Issue 2467: Remove redundant synchronized

- site2/docs/privacy.md
- site2/website/pages/en/project.js
Update our new website project Privacy policy page
we decide to use new website framework and skeleton to renew our website
Add Privacy policy 
Master Issue: #2442
> [Doc][Issue #2442] New website Project Page

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookieInfoReader.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestGetBookieInfoTimeout.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
getBookieInfo is stuck if no bookie is up
Fix the problem, add a test case.
Also the getBookieInfoTimeout configuration was not  used, we were using the read entry timeout.
> getBookieInfo is stuck if no bookie is up

- pom.xml
Upgraded libraries mentioned in #2509 #2510 #2511 #2512 #2513
> Upgrade libraries Common Compress and Hadoop (only tests) to fix vulnerabilities

- stream/server/src/main/java/org/apache/bookkeeper/stream/server/service/GrpcService.java
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/service/RegistrationStateService.java
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/service/StorageService.java
Check NP of  BookKeeper Stream Storage Server LifecycleComponents
Fix issue #2505 
Master Issue: #2505
> Check np for LifecycleComponent close

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
fix typo when logging format-bookie info
fix typo
rename one word when logging
> fix typo when logging

- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/dlog/DLCheckpointStore.java
DLCheckpointStore rethrows exceptions as FNFE but swallows the rootcause
Same as https://github.com/apache/bookkeeper/pull/2553 but for master branch
added .initCause for the new FNFE exception to preserver it
got the
ERROR org.apache.bookkeeper.statelib.impl.rocksdb.checkpoint.RocksCheckpointer - Failed to restore rocksdb ...
java.io.FileNotFoundException: ..../metadata
without any additional info for the rootcause (other than stack pointing to the DLCheckpointStore)
DLCheckpointStore appears to re-throw exceptions as FNFE without preserving the rootcause
added .initCause
Master Issue: #2552
> ---
> checks for pull requests. A pull …
> Fixed: DLCheckpointStore rethrows exceptions as FNFE but swallows the rootcause

- stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/store/MVCCAsyncStoreTestBase.java
fixed mock creation.
tests fail
fixed mock creation
Master Issue: #2572
> ---
>
> ---
>
>
>
> Otherwise:
> 
> - [ ] Make …
> fix: TableStoreImplTest failed because of NPE in AbstractStateStoreWithJournal initialization (test/mock issue)

- stream/statelib/pom.xml
- stream/storage/impl/pom.xml
- stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/store/MVCCStoreFactoryImplTest.java
Fixed (some of) the test failures.
Other tests need more work, some of them succeed on retry, some might fail but for different reasons.
To be continued.
the tests shall pass
Fixed: missing dependencies for some subprojects
Fixed: mock setup for some tests
Master Issue: #2577
> ---
>
> ---
>
>
> …
> Fix: Multiple tests failing in /stream subproject

- site/releases.md
Releasing 4.13, site update
Releasing 4.13
site update
> ---
>
> ---
>
>
>
> Otherwise:
> 
> - [ ] Make sure the PR title …
> Release 4.13 update

- settings.gradle
* Format settings.gradle correctly.
> Fix settings.gradle formatting

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForSingleEntryLog.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexInMemPageMgr.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultBookieAddressResolver.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/ZKRegistrationClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/EventLoopUtil.java
Fix java doc problem
1. Some log in slf4j, the pattern number and the member log not equal
2. Some javadoc grammar problem
> Fix logger member not correct、some javadoc  problem

- bookkeeper-dist/src/assemble/src.xml
gradle files weren't included into the source artifact of the release
site2/ was included.
Added gradle into the include pattern.
Added site2 into the exclude patterns.
> Include gradle files into the source artifact for releases, exclude site2/**

- site/_config.yml
- site/docs/4.14.0/api/distributedlog-api.md
- site/docs/4.14.0/api/ledger-api.md
- site/docs/4.14.0/deployment/dcos.md
- site/docs/4.14.0/overview/overview.md
- site/releases.md
> site update for release 4.14, this time actually updating the latest version in _config.yml

- conf/bk_server.conf
- site/_data/config/bk_server.yaml
---
Fixes #2699
*Motivation*
Add missing configuration `tlsCertificatePath` in the configuration file
and website description
> Add the `tlsCertificatePath` to the configuration file

- stream/clients/python/setup.py
Updated py client's version to 4.14
Preparing for the release
https://bookkeeper.apache.org/community/release_guide/#change-python-client-version
> Preparing for the release 4.14

- site/docs/4.14.2/overview/releaseNotes.md
---
*Motivation*
Release note update for 4.14.2
> Release note for 4.14.2

- stream/clients/python/setup.py
---
Release python client 4.14.2
> Release python client 4.14.2

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
Optimize code
1. Use try with resource to optimize close
2. remove isDebugEnabled
> Use try with resource to optimize code

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/MathUtils.java
> Fix wrong time unit in the comments of MathUtils

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
---
*Motivation*
Fix typo in DBLedgerStorage. `getLedgerSorage` -> `getLedgerStorage`
> Fix typo in method name

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DynamicWeightedRandomSelectionImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/Main.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorageTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerCacheTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/SortedLedgerStorageTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestReadLastEntry.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/AsyncLedgerOpsTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieFailureTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieReadWriteTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/AvailabilityOfEntriesOfLedgerTest.java
- bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/TestPrometheusFormatter.java
- stream/common/src/main/java/org/apache/bookkeeper/common/coder/VarIntCoder.java
- stream/common/src/test/java/org/apache/bookkeeper/common/router/HashRouterTest.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/tools/DistributedLogTool.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/tools/TestDistributedLogTool.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/CheckpointInfo.java
- stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/sc/DefaultStorageContainerControllerTest.java
No need convert int to integer in main.
> Remove unnecessary boxing unboxing

- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdBookieRegister.java
- stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/channel/StorageServerChannelManager.java
- stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/container/StorageContainerManager.java
- stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/internal/LocationClientImpl.java
- stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/internal/RootRangeClientImplWithRetries.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/MaxTxId.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestReader.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/journal/JournalWriter.java
Fix bookkeeper logger number not correct
> Fix bookkeeper logger number not correct

- site/project/who.md
Adding new committer
New committer
> Adding Prashant Kumar to committer list

- NOTICE
Updated Notice file year to 2022
> Updated Notice file year to 2022

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ForceLedgerOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadLacOp.java
1. check all Op requests and update log
2. correct logs help us locate problems
1. ForceLedgerOp: change log's level 
2. PendingReadLacOp: print coverageSet and  change log's level
> check all Op requests and update log

- build.gradle
- gradle.properties
Bump gradle plugin version, prepare for gradle7 update
> Bump gradle plugin version, prepare for gradle7 update

- site/docs/4.14.4/overview/releaseNotes.md
Added release notes for 4.14.4
> Added release notes for 4.14.4

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
> remove unused variable

- dependencies.gradle
CVE-2017-18640
Upgraded snakeyaml dependency
> Upgraded snakeyaml, CVE-2017-18640

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- tests/backward-compat/bc-non-fips/build.gradle
- tests/integration/cluster/build.gradle
- tests/integration/smoke/build.gradle
Bump gradle to 7.3.1, compat java 17.
> Bump gradle to 7.3.3, compat java 17

- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/RecoveryBookieService.java
update doc RecoveryBookieService: bookie_dest has been removed
> update doc RecoveryBookieService: bookie_dest has been removed

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForEntryLogPerLedger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogMetadata.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileInfoBackingCache.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/HandleFactoryImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/WriteCache.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSet.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSet.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSetTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSetTest.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManager.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdWatchClient.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/routing/RangeRoutingTableImpl.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/sc/ZkStorageContainerManager.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLogMetadataCommandTest.java
support shrink for ConcurrentLong map or set.
> support shrink for ConcurrentLong map or set

- .github/workflows/website-deploy.yaml
The deploy action does not work
* Added various setup
* Tested locally with https://github.com/nektos/act
> [website] Fix deploy action

- stream/clients/python/setup.py
Updated py client's version to 4.15
Motivation
Preparing for the release
https://bookkeeper.apache.org/community/release_guide/#change-python-client-version
> Preparing for the release 4.15

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMap.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSetTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMapTest.java
Add corresponding unit tests for the previous PR: https://github.com/apache/bookkeeper/pull/3072
> add unit tests for reduce unnecessary expansions 

- .asf.yaml
Create .asf.yaml for staging deployment as written in the [ASF guide](https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Primer)
* added the .asf.yaml
> [website] create .asf.yaml for staging

- .github/workflows/backward-compat-tests.yml
- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/owasp-dep-check.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/stream-tests.yml
- .github/workflows/tls-tests.yml
- .github/workflows/website-staging-deploy.yaml
- site3/website/scripts/publish-website.sh
Deploy staging for each modification, same as the current website.
* Run staging push after each change in site3 or deployment action
* excluded site3 from gh actions
* set to push to `asf-staging` site
> [website] deploy staging after every change

- .github/workflows/website-deploy.yaml
- site/Gemfile.lock
Current website deployment is broken (it works locally but not on GH)
https://github.com/apache/bookkeeper/actions/runs/1980176217
* Downgrade ruby
* Upgrade some packages
> [website] fix current site deployment

- site3/website/docs/api/distributedlog-api.md
- site3/website/docs/deployment/dcos.md
- site3/website/versioned_docs/version-4.10.0/api/distributedlog-api.md
- site3/website/versioned_docs/version-4.10.0/deployment/dcos.md
- site3/website/versioned_docs/version-4.11.1/api/distributedlog-api.md
- site3/website/versioned_docs/version-4.11.1/deployment/dcos.md
- site3/website/versioned_docs/version-4.12.1/api/distributedlog-api.md
- site3/website/versioned_docs/version-4.12.1/deployment/dcos.md
- site3/website/versioned_docs/version-4.13.0/api/distributedlog-api.md
- site3/website/versioned_docs/version-4.13.0/deployment/dcos.md
- site3/website/versioned_docs/version-4.14.4/api/distributedlog-api.md
- site3/website/versioned_docs/version-4.14.4/deployment/dcos.md
- site3/website/versioned_docs/version-4.5.1/api/distributedlog-api.md
- site3/website/versioned_docs/version-4.5.1/deployment/dcos.md
- site3/website/versioned_docs/version-4.6.2/api/distributedlog-api.md
- site3/website/versioned_docs/version-4.6.2/deployment/dcos.md
- site3/website/versioned_docs/version-4.7.3/api/distributedlog-api.md
- site3/website/versioned_docs/version-4.7.3/deployment/dcos.md
- site3/website/versioned_docs/version-4.8.2/api/distributedlog-api.md
- site3/website/versioned_docs/version-4.8.2/deployment/dcos.md
- site3/website/versioned_docs/version-4.9.2/api/distributedlog-api.md
- site3/website/versioned_docs/version-4.9.2/deployment/dcos.md
In the staging website image links are broken
* Fixed the links with the correct syntax (I checked every `img` reference)
> [website] Staging website: images are not visible

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/datainteg/CookieValidationTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/datainteg/DataIntegrityCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/datainteg/EntryCopierTest.java
use mockito.any instead of deprecated mockito.anyObject
> use mockito.any instead of deprecated mockito.anyObject

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/TopologyAwareEnsemblePlacementPolicy.java
When we update the bookie rack info, it will use all the bookie list to update rack topology. However If one bookie update failed and throw exception out, it will throw the exception out and the remains bookie info won't be updated into the rack topology, which will affect the ledger ensemble selection.
Catch the bookie topology update exception to ensure the remaining bookies' info can be updated into the rack topology.
> Catch onBookieRackChange exception

- site/project/who.md
- site3/website/src/pages/project/who.md
> [website] Update committers page

- .github/workflows/pr-validation.yml
- bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchReadThroughputLatency.java
- bookkeeper-http/servlet-http-server/src/main/java/org/apache/bookkeeper/http/servlet/BookieHttpServiceServlet.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MetadataDrivers.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DirectMemoryCRC32Digest.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/AutoRecoveryStatusService.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/ExpandStorageService.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ToggleCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/LedgerCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListActiveLedgersCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListLedgersCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLedgerCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/LedgerMetaDataCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/SimpleTestCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/helpers/DiscoveryCommand.java
- cpu-affinity/src/main/java/org/apache/bookkeeper/common/util/affinity/impl/NativeUtils.java
- pom.xml
- tests/integration-tests-utils/src/main/java/org/apache/bookkeeper/tests/integration/utils/DockerUtils.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/PerfClient.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/cluster/InitClusterCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/table/DelCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/table/GetCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/table/IncrementCommand.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/table/PutCommand.java
Cherry-pick of https://github.com/apache/bookkeeper/pull/3160 to the branch-4.14.
No real bugs spotted, just suppressions but it makes the CI pass
> [branch-4.14] Fix various spotbugs warnings

- bookkeeper-server/pom.xml
- pom.xml
- tests/scripts/pom.xml
Complement missing maven plugin version
> [build] Complement missing maven plugin version

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- dependencies.gradle
- pom.xml
This reverts commit 0e7f8f4245e6e5215677f9806983c25e8102006e.
See mailing list discussion: https://lists.apache.org/thread/dsdltmoy5ggqx4oj7hrt13hqok80d4jf
> [branch-4.14] Revert "Upgrade rocksdb to 6.29.4.1 (#3143)"

- .github/workflows/website-pr-validation.yml
- site3/README.md
Add CI checks to validate the website is built without errors.
* Run both for current and staging website
* Improved release doc for site3
> [website] add CI checks to validate the website

- bookkeeper-slogger/api/build.gradle
- bookkeeper-slogger/api/pom.xml
- bookkeeper-slogger/api/src/main/java/org/apache/bookkeeper/slogger/AbstractSlogger.java
- bookkeeper-slogger/api/src/main/java/org/apache/bookkeeper/slogger/ConsoleSlogger.java
- bookkeeper-slogger/api/src/main/java/org/apache/bookkeeper/slogger/NullSlogger.java
- bookkeeper-slogger/api/src/main/java/org/apache/bookkeeper/slogger/Sloggable.java
- bookkeeper-slogger/api/src/main/java/org/apache/bookkeeper/slogger/SloggableAccumulator.java
- bookkeeper-slogger/api/src/main/java/org/apache/bookkeeper/slogger/Slogger.java
- bookkeeper-slogger/api/src/main/java/org/apache/bookkeeper/slogger/package-info.java
- bookkeeper-slogger/api/src/test/java/org/apache/bookkeeper/slogger/ConcurrencyTest.java
- bookkeeper-slogger/api/src/test/java/org/apache/bookkeeper/slogger/ConsoleSloggerTest.java
- bookkeeper-slogger/api/src/test/java/org/apache/bookkeeper/slogger/MockSlogger.java
- bookkeeper-slogger/api/src/test/java/org/apache/bookkeeper/slogger/SloggerTest.java
- bookkeeper-slogger/pom.xml
- bookkeeper-slogger/slf4j/build.gradle
- bookkeeper-slogger/slf4j/pom.xml
- bookkeeper-slogger/slf4j/src/main/java/org/apache/bookkeeper/slogger/slf4j/Slf4jSlogger.java
- bookkeeper-slogger/slf4j/src/main/java/org/apache/bookkeeper/slogger/slf4j/package-info.java
- bookkeeper-slogger/slf4j/src/test/java/org/apache/bookkeeper/slogger/slf4j/Slf4jTest.java
- pom.xml
Add structured logger support for BookKeeper
> BP-47 (task2): Add structured logger support

- pom.xml
- src/owasp-dependency-check-suppressions.xml
- bump the dependency check version, I think it don't worth to open another pr.
- add cve suppression
> Fix master broken ci due to zookeeper CVE fp

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
Fix #3215 
Update the value when ledger or fragments replicated
> Fix numLedgersReplicated metric not update

- site3/website/docs/reference/cli.md
Fix #3221 
Fix some cli command doc issue, and keep sync with code.
> [Doc]Fix cli command doc issue

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
- add missing `lb.start();`
- delete commented out code
- add zookeeper 4lw for easily to run/debug in ide
> Fix "bookeepeer localbookie"

- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/util/TestThreadSelection.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/datainteg/DataIntegrityCookieValidation.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/AuthHandler.java
> [MINOR] fix logger number not correct

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InMemoryEntryLogMetadataMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- make field final
- delete unused variable
- remove stale `@VisiableForTesting` annotation, it has been already used for non-test code
> [minor] cleanup on InterleavedLedgerStorage

- README.md
fix the error link in README
[issue 2518](https://github.com/apache/bookkeeper/issues/2518)
just try to fix the error link.
> Issue 2518:fix error link

- .github/actions/copy-test-reports/action.yml
- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/owasp-dep-check.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/stream-tests.yml
- .github/workflows/tls-tests.yml
- dev/ci-tool
add github actions to upload test log when fail
You can find the test log in the github actions summary
> [ci] [github] upload test log when fail

- conf/bk_server.conf
Fix spelling mistake in bk_server.conf
Master Issue: #3261
> Fix typo in bk_server.conf

- site3/website/docs/overview/overview.md
Invalid hyperlink for Apache Pulsar#persistent-storage
Update hyperlink to [persistent-storage](https://pulsar.apache.org/docs/concepts-architecture-overview#persistent-storage)
Master Issue: #3270
> ISSUE#3270:Invalid hyperlink for Apache Pulsar#persistent-storage

- site3/website/src/pages/project/who.md
Update the organization to former Streamlio members to StreamNative
> Updated organization to Streamlio former members

- .github/workflows/website-pr-validation.yml
- site3/website/src/pages/community/release-guide.md
Some release guide points are deprecated or they're missing details
* Updated the website guide
* Fixed the python publish script path
* Added the step for the github release
> [doc] Improve release guide

- site3/website/docs/getting-started/installation.md
Getting started instructions for building the project were wrong since Gradle is not used anymore. I reverted to the old Maven one
> [fix][doc] Fixed build instruction to Maven since Gradle usage was reverted

- circe-checksum/pom.xml
- cpu-affinity/pom.xml
- cpu-affinity/src/main/affinity/cpp/affinity_jni.c
try to fix issue: #2270
Master Issue: #2270 
> ---
>
> ---
>
>
> - [ …
> [build] support circe-checksum and cpu-affinity build on Windows

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BKException.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- tests/scripts/pom.xml
> Fix javadoc and build warnings

- .github/workflows/macos-build.yml
add macos build check to avoid broken change on macos x86
> [ci] [build] add macos build check

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
add close journalChannel in testJunkEndedJournal
> Close journal channel in testJunkEndedJournal

- pom.xml
Bump apache version from 19 to 26
> Bump apache version from 19 to 26

- site3/website/docs/api/ledger-api.md
> Issue 3293 Fix missing link to paxos algorithm

- README.md
- site3/website/docs/overview/overview.md
Add Pravega (https://github.com/pravega/pravega) to the use-cases in Bookkeeper documentation.
Added Pravega as use case in README and Overview.md files.
Master Issue: #3327
Signed-off-by: Raúl Gracia <raul.gracia@emc.com>
> Add Pravega as a Bookkeeper use case.

- .github/workflows/compatibility-check-java17.yml
- tests/integration-tests-base-groovy/pom.xml
- tests/pom.xml
- add github ci check
- bump groovy compiler version to support jdk17
> allow build on jdk17

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
Reduce unnecessary checkpoints
> reduce unnecessary checkpoints

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageIndexDirTest.java
coding for basic function : directories to store index files 
1) DbLedgerStorage: add LedgerDirsManager init for index
2) SingleDirectoryDbLedgerStorage: add indexDirs check and default value
> Basic function: directories to store index files

- conf/bk_server.conf
change `Persiste` to `Persist`
> Fix a typo in bk_server.conf

- .gitignore
- pom.xml
- stream/.gitignore
- I think the Intellij should be changed to IntelliJ IDEA. For details, please refer to the official website https://www.jetbrains.com/idea/ and https://en.wikipedia.org/wiki/IntelliJ_IDEA.
- Modify Intellij to IntelliJ IDEA.
- Modify Intellij to IntelliJ IDEA.
> Fix the Intellij key nouns.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LocationsIndexRebuildOp.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/LocationsIndexRebuildTest.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/helpers/BookieCommandTestBase.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/helpers/CommandTestBase.java
stage 5 : 
1)  fix indexDirs for LocationsIndexRebuildOp
1.  bugfix indexDirs for LocationsIndexRebuildOp
2. add index's testcase for LocationsIndexRebuildOp
> stage 6: bugfix indexDirs for LocationsIndexRebuildOp

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbReadLedgerIndexEntriesTest.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/helpers/BookieCommandTestBase.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/helpers/CommandTestBase.java
stage 5 : 
1)  fix indexDirs for EntryLocationIndex's tool
1.  bugfix indexDirs for EntryLocationIndex's tool
2. add index's testcase for testReadLedgerIndexEntries
3. bugfix findexDirs for TestBase
> stage 5: bugfix indexDirs for readLedgerIndexEntries

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
Upgrading JNA
changed dependency version
Master Issue: #3394
> Upgrading JNA to 5.12.1

- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/Main.java
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/service/BookieService.java
stage 7 : 
1)  print indexDirs's info when start bookie
1.  just add log for indexDirs
> stage 7: print indexDirs's info when start bookie

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgersIndexCheckOp.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/LedgersIndexCheckOpTest.java
stage 8 : 
1)  fix indexDirs for LedgersIndexCheckOp
1.  bugfix indexDirs for LedgersIndexCheckOp
2. add index's testcase for LedgersIndexCheckOp
> stage 8: bugfix indexDirs for LedgersIndexCheckOp

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgersIndexRebuildOp.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/LedgersIndexRebuildOpTest.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/helpers/CommandTestBase.java
stage 9 : 
1)  fix indexDirs for LedgersIndexRebuildOp
1.  bugfix indexDirs for LedgersIndexRebuildOp
2. add index's testcase for LedgersIndexRebuildOp
> stage 9: bugfix indexDirs for LedgersIndexRebuildOp

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ListenerBasedPendingReadOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
Use linkedList to take place of ArrayList.
> Tuing PendingReadOp.java seq

- site3/website/src/pages/community/bookkeeper-proposals.md
> Fix typo in bookkeeper-proposals.md

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
Pre break loop when self create layoutZNode succeed.
> Pre break loop when self create layoutZNode succeed.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
The CI failed witch check style, fix it.
https://github.com/apache/bookkeeper/runs/7544140069?check_suite_focus=true
> Fix check style

- microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/DigestTypeBenchmark.java
---
*Motivation*
There are some unwanted changes committed by 3309
https://github.com/apache/bookkeeper/pull/3309
> Revert some unwanted changes in commit 3309

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
---
*Motivation*
When running the tls test, the remote address is a LocalAddress,
but we cast it to the `InetSocketAddress`. That cause the test
`testConnectToLocalTLSClusterTLSClient` failed.
> Fix the tls failed test

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/stats/JournalStats.java
Fix the wrong `cbThreadPoolQueueSize` doc name
> Fix wrong stats name

- .github/workflows/backward-compat-tests.yml
- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java17.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/macos-build.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/stream-tests.yml
- .github/workflows/tls-tests.yml
- .github/workflows/windows-build.yml
---
*Motivation*
We have enabled the requirement of the workflow before merging a
PR. We should skip checking the sites related changes because they
are non-code changes.
*Modification*
- Using apache/pulsar-test-infra/paths-filter@master to filter the files
> Skip runs the workflow when only have site related changes

- site3/website/src/pages/release-notes.md
- site3/website/versioned_docs/version-4.15.1/admin/autorecovery.md
- site3/website/versioned_docs/version-4.15.1/admin/bookies.md
- site3/website/versioned_docs/version-4.15.1/admin/decomission.md
- site3/website/versioned_docs/version-4.15.1/admin/geo-replication.md
- site3/website/versioned_docs/version-4.15.1/admin/http.md
- site3/website/versioned_docs/version-4.15.1/admin/metrics.md
- site3/website/versioned_docs/version-4.15.1/admin/perf.md
- site3/website/versioned_docs/version-4.15.1/admin/placement.md
- site3/website/versioned_docs/version-4.15.1/admin/upgrade.md
- site3/website/versioned_docs/version-4.15.1/api/distributedlog-api.md
- site3/website/versioned_docs/version-4.15.1/api/ledger-adv-api.md
- site3/website/versioned_docs/version-4.15.1/api/ledger-api.md
- site3/website/versioned_docs/version-4.15.1/api/overview.md
- site3/website/versioned_docs/version-4.15.1/deployment/kubernetes.md
- site3/website/versioned_docs/version-4.15.1/deployment/manual.md
- site3/website/versioned_docs/version-4.15.1/development/codebase.md
- site3/website/versioned_docs/version-4.15.1/development/protocol.md
- site3/website/versioned_docs/version-4.15.1/getting-started/concepts.md
- site3/website/versioned_docs/version-4.15.1/getting-started/installation.md
- site3/website/versioned_docs/version-4.15.1/getting-started/run-locally.md
- site3/website/versioned_docs/version-4.15.1/overview/overview.md
- site3/website/versioned_docs/version-4.15.1/reference/cli.md
- site3/website/versioned_docs/version-4.15.1/reference/config.md
- site3/website/versioned_docs/version-4.15.1/security/overview.md
- site3/website/versioned_docs/version-4.15.1/security/sasl.md
- site3/website/versioned_docs/version-4.15.1/security/tls.md
- site3/website/versioned_docs/version-4.15.1/security/zookeeper.md
- site3/website/versioned_sidebars/version-4.15.1-sidebars.json
---
*Motivation*
Generates the 4.15.1 docs and release note
> Add 4.15.1 release note

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
Print bookie address when writing entry failed
Printing bookie info will be help for solving online problem
Print bookie address when writing entry failed
> Optimize log for failed to write entry

- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/SlowBookieTest.java
- fix typo
- rename variable `state` to `writable`
- close the resource LedgerHandle
> [unit tests] optimize SlowBookieTest

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestDirectReader.java
- disable direct IO test on windows, it's not supported on windows
> disable direct IO test on windows

- site3/website/src/pages/release-notes.md
---
*Motivation*
Generates the 4.15.2 release note
> Add release 4.15.2 release note

- CONTRIBUTING.md
Setting guidelines for repository contributors
Master Issue: #3532
> <Issue #3532>Create CONTRIBUTING.md

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java
Inspired by #3151, support set replication throttle rate dynamic
support set replication throttle rate dynamic
> Replication throttle rate supports dynamic value

- site3/website/docs/api/ledger-api.md
> [docs] fix mistake in ledger api docs

- site3/website/docs/getting-started/concepts.md
> [website][fix]Repair `sequential nodes` address

- conf/bk_server.conf
> [configuration] fix typo in bk_server.conf

- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AutoRecoveryMainTest.java
Fix flaky tests:
https://github.com/apache/bookkeeper/actions/runs/3279561577/jobs/5399266347
Use `Awaitility.await()` wait until the election is done.
```
org.apache.bookkeeper.replication.AutoRecoveryMainTest.testAutoRecoverySessionLoss  Time elapsed: 1.65 s  <<< ERROR!
java.lang.NullPointerException
at org.apache.bookkeeper.replication.AutoRecoveryMainTest.testAutoRecoverySessionLoss(AutoRecoveryMainTest.java:119)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at …
```
> [test] Fix flaky test testAutoRecoverySessionLoss

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieNetworkAddressChangeTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestDelayEnsembleChange.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
> [Branch 4.14] Fix potential memory leak.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/Header.java
Fix typo issue when Header.assertFingerPrint throws IOException
Fix typo issue when Header.assertFingerPrint throws IOException
> ---
>
> ---
>
>
> - [ ] …
> Fix typo issue when Header.assertFingerPrint throws IOException

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageStats.java
> Fix readEntryStats typo

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java
> Using a separate thread pool to execute openWithMetadata

- site3/website/src/pages/release-notes.md
---
*Motivation*
Add 4.15.3 release note
> Add 4.15.3 relese note

- bin/bookkeeper-daemon.sh
bookkeeper-daemon script supports restart command
> bookkeeper-daemon script supports restart command

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieImplTest.java
testWriteLac recently became flaky-test: 
https://github.com/apache/bookkeeper/actions/runs/3424530676/jobs/5704307573#logs
1. Before the entry added the journal entry queue, entry.retain() will be executed.
2. So add a callback function to ensure that the entry is verified after the entry is executed done in the journal entry queue.
```java
public void logAddEntry(long ledgerId, long entryId, ByteBuf entry,
boolean ackBeforeSync, WriteCallback cb, Object ctx)
throws InterruptedException {
// Retain entry until it gets written to journal
entry.retain();
......
}
```
> fix Flaky-test: testWriteLac

- shaded/bookkeeper-server-shaded/pom.xml
> Include com.google.guava:failureaccess in shaded package

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageWriteCacheTest.java
> clean code: remove unused gcExecutor

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RegionAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
> Fix RegionAwareEnsemblePlacementPolicy update rack info problem.

- bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java
> [Branch-4.14] Fix cherry-pick #3677 issue

- conf/bk_server.conf
- site3/website/docs/reference/config.md
Add default value of `allowMultipleDirsUnderSameDiskPartition`
Signed-off-by: Paul Gier <paul.gier@datastax.com>
Just a minor doc fix
Updated the bk_server.conf and the website config doc
> [improve][doc] improve bk_server.conf docs

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
- site3/website/docs/reference/config.md
> BP-60:Change PCBC limitStatsLogging default value to true

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LocationsIndexRebuildOp.java
> [fix] Recycle LongPairWrapper after use

- site3/website/docs/admin/http.md
- site3/website/versioned_docs/version-4.10.0/admin/http.md
- site3/website/versioned_docs/version-4.11.1/admin/http.md
- site3/website/versioned_docs/version-4.12.1/admin/http.md
- site3/website/versioned_docs/version-4.13.0/admin/http.md
- site3/website/versioned_docs/version-4.14.6/admin/http.md
- site3/website/versioned_docs/version-4.15.3/admin/http.md
- site3/website/versioned_docs/version-4.8.2/admin/http.md
- site3/website/versioned_docs/version-4.9.2/admin/http.md
> fix admin rest api typo

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
As title, add blank between ledger and ledger number.
> Fix missing blank in log text

- site3/website/src/pages/release-notes.md
BookKeeper 4.14.7 will be released, this is the release note.
Generate BookKeeper 4.14.7 release note.
> Generate 4.14.7 release note

- pom.xml
> Upgrade lombok to 1.18.26

- metadata-drivers/etcd/src/test/java/org/apache/bookkeeper/metadata/etcd/helpers/KeySetReaderTest.java
- metadata-drivers/etcd/src/test/java/org/apache/bookkeeper/metadata/etcd/testing/EtcdContainer.java
- pom.xml
- tests/integration-tests-topologies/src/main/java/org/apache/bookkeeper/tests/containers/BookieContainer.java
- tests/integration-tests-topologies/src/main/java/org/apache/bookkeeper/tests/containers/ZKContainer.java
- tests/integration-tests-topologies/src/main/java/org/apache/bookkeeper/tests/containers/wait/HttpWaitStrategy.java
Update testcontainers to last version to support m1. Tested on my laptop.
> Update testcontainers to last version to support m1

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
> clean code: remove unused comment

- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/EmbeddedServer.java
Modify code to make metadataDriver initialization more robust.
> [Bugfix] make metadataDriver initialization more robust

- circe-checksum/pom.xml
- pom.xml
Remove unused jenkins profile, cleanup code
> Remove unused jenkins profile

- site3/website/src/pages/release-notes.md
Generate the 4.16.1 release note
> Generate 4.16.1 release note

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java
> [Fix] Recycle dropping read-write requests when various exceptions happened

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
Create `ReplicationEnableCb` when the if condition is true.
> Reduce unnecessary creation of ReplicationEnableCb objects

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultEntryLogger.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/DefaultEntryLogTest.java
Correct the parameters order of method `readEntry`
> Fix readEntry parameter order

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSet.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSet.java
Simillar improvement in Pulsar. refer to: https://github.com/apache/pulsar/pull/21110
~~Remove the optimistic read logic from forEach method in all util class.~~
Add doc for these util class.
```
ConcurrentLongHashMap
ConcurrentLongHashSet
ConcurrentLongLongHashMap
ConcurrentLongLongPairHashMap
ConcurrentOpenHashMap
ConcurrentOpenHashSet
```
> Add doc for customized util class

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/CreateCookieCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/DeleteCookieCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/GenerateCookieCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/GetCookieCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/UpdateCookieCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/helpers/BookieShellCommand.java
- tools/framework/src/main/java/org/apache/bookkeeper/tools/framework/CliCommand.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/CreateCookieCommandTest.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/UpdateCookieCommandTest.java
> BP-64: Improve the description of 47 commands for bin/bookkeeper

- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorBookieTest.java
Make AuditorBookieTest#waitForNewAuditor stronger.
> Make AuditorBookieTest#waitForNewAuditor stronger.

- site3/website/src/pages/community/coding-guide.md
Update StatsProvider URL
404 not found
Fix URL
> Fix the coding-guide page#StatsProvider URL

- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/TriggerGCService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/service/TriggerGCServiceTest.java
- buildtools/src/main/resources/bookkeeper/findbugsExclude.xml
Fix the CI spotbugs failure in the branch-4.15
> [Branch-4.15] Fix the CI spotbugs failure in the branch-4.15

- site3/website/docs/reference/config.md
Fix stats providers in configuration
> [fix][doc] Fix stats providers in configuration

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
---
###Motivation
Allow to override the getUnderreplicatedFragments to customize the behavior.
> Chagne the method getUnderreplicatedFragments to the package private

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/CleanupLedgerManager.java
Currently  the type of `CleanupLedgerManager#callbacks` is map, and the key and value are both the same `callbacks`. We just used it as a set. So this patch will change the `callbacks`  from map to set
Change `callbacks` in `CleanupLedgerManager` as a Set
> Change callbacks in CleanupLedgerManager as a Set

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/BookieProtoEncodingTest.java
This is the first PR for the batch read(#4051) feature. 
Protocol change: Support encoding and decoding for batchReadRequest and batchReadResponse
> [BP-62] Batch read protocol change: Support encoding and decoding for batchReadRequest and batchReadResponse

- bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchReadThroughputLatency.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
This is the sixth PR for the batch read(https://github.com/apache/bookkeeper/pull/4051) feature.
Add more test for Bookkeeper.
> [BP-62] Add more test for Bookkeeper.

- tests/integration-tests-utils/src/main/java/org/apache/bookkeeper/tests/integration/utils/DockerUtils.java
- tests/integration-tests-utils/src/main/java/org/apache/bookkeeper/tests/integration/utils/MavenClassLoader.java
Add filename check for unTar
> ---
>
> ---
>
>
>
> Otherwise:
> 
> - [ ] Make sure …
> Add filename check for unTar

- bookkeeper-http/servlet-http-server/src/main/java/org/apache/bookkeeper/http/servlet/BookieHttpServiceServlet.java
Fix error stack track may expose to external user
> ---
>
> ---
>
>
> - [ ] Attach the google doc link if the BP is …
> Fix error stack track may expose to external user

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BatchedReadOp.java
- site3/website/src/pages/bps/BP-62-new-API-for-batched-reads.md
In the coding stage, we implements API not same with the doc, we should correct the doc to match the code.
> [BP-62] Tune the BP-62 doc

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
The implementation of  is not consistent with the description.
fix doc.
Master Issue: https://github.com/apache/bookkeeper/issues/4253
> fix description of BookKeeperAdmin#watchWritableBookiesChanged

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
journalTime metric is unused anymore  since #3843 
Remove journalTime
> Remove unused journaltime

- src/owasp-dependency-check-suppressions.xml
Fix the OWASP check failed in branch-4.15
> ---
>
> ---
>
>
>
> Otherwise:
> 
> - [ ] …
> Fix owasp check failed

- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieClientTest.java
> [Branch-4.16] Fix check style

- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/Main.java
As the title
fix #4240
Master Issue: #4240
> Optimize bookie usage information while using command line option --help

- site3/website/src/pages/releases.md
See https://lists.apache.org/thread/kz8vc04qysjcc3prgbtr3n1s2f74c1ds
> doc: add the missing release news

- site3/website/docs/admin/upgrade.md
> doc: add the missing upgrade docs

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDescriptorImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDescriptorReadOnlyImpl.java
See #995 
Remove assert in LedgerDescriptor these are disabled at runtime and never works
> chore: remove assert statement in LedgerDescriptor

- .asf.yaml
Fix  #2229 
Enhanced the .asf.yaml file by including additional, more appropriate labels.
New labels added:
- apache
- distributed-log
- distributed-systems
- wal
> Added more relevant labels to .asf.yaml

- .github/actions/tune-runner-vm/action.yml
> [ci] Skip mount command error when tune runner vm

- site3/website/versioned_sidebars/version-4.17.0-sidebars.json
Fix #4362
add json file, show sidebar.
> [site][bugfix] BK website version 4.17.0, missing sidebar #4362

- docker/Dockerfile
> build: update latest docker image from 4.15.1 to 4.17.0

- .github/changes-filter.yaml
- .github/workflows/bk-ci.yml
- .github/workflows/codeql.yml
- .github/workflows/java21-daily-build.yml
- .github/workflows/windows-daily-build.yml
> build: fix owasp check broken

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieServer.java
Since #1400 is closed, remove this sleep code.
> remove stale sleep code in BookieServer

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
Main Issue: #4409
Upgrade RocksDB to version 7.10.2
Upgrade RocksDB to version 7.10.2
> Upgrade RocksDB to version 7.10.2

- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
Fixed string format for exception
> [fix] fix string format for exception in RocksdbKVStore

- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ClientSocketDisconnectTest.java
Fix #xyz
Main Issue: #xyz
BP: #xyz
> ---
>
> ---
> Be sure to do all the following to help us incorporate your contribution
>
>
> - [ ] Attach the …
> [Branch-4.17] Fix branch-4.17 CI
