apache/bookkeeper

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultSpeculativeRequestExecutionPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ReadLastConfirmedAndEntryOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/SpeculativeRequestExecutionPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/SpeculativeRequestExecutor.java
Fix a simple typo in class name. It should be `SpeculativeRequestExecutor` instead of `SpeculativeRequestExectuor`.
> ISSUE #239: typo in class name SpeculativeRequestExecutor

- .travis.yml
although we exclude `asf-site` branch in travis.yml, but the file only exists in master and other release branches. copy the `travis.yml` to `asf-site` branch.
https://travis-ci.org/apache/bookkeeper/builds/298028474
> add .travis.yml to skip build asf-site branch

- docker/scripts/entrypoint.sh
In issue #732, we changed Makefile for Docker:
BK_statsProviderClass=org.apache.bookkeeper.stats.NullStatsProvider
to avoid error:
java.lang.ClassNotFoundException: org.apache.bookkeeper.stats.PrometheusMetricsProvider
The reason is that 4.5.1 doesn't ship the providers, so we hard code it to the null providers.
It is more safe to change the default env in Dockerfile instead of Makefile. So that user use the default 4.5.1 Docker will not meet error.
> ---
> 
> - [x] Make sure the PR title is formatted like:
>     `<Issue # or BOOKKEEPER-#>: Description of pull request`
>     `e.g. Issue 123: Description ...`
>     `e.g. BOOKKEEPER-1234: Description …
> Issue 780:   change BK_statsProviderClass in to NullStatsProvider in Docker file

- bookkeeper-server/pom.xml
- pom.xml
- shaded/bookkeeper-server-shaded/pom.xml
- shaded/bookkeeper-server-tests-shaded/pom.xml
- shaded/pom.xml
- site/docs/latest/api/ledger-api.md
- tests/bookkeeper-server-shaded-artifact-test/pom.xml
- tests/bookkeeper-server-shaded-artifact-test/src/test/java/org/apache/bookkeeper/tests/shaded/BookKeeperServerShadedArtifactTest.java
- tests/bookkeeper-server-shaded-test/pom.xml
- tests/bookkeeper-server-shaded-test/src/test/java/org/apache/bookkeeper/tests/shaded/BookKeeperServerShadedJarTest.java
- tests/bookkeeper-server-tests-shaded-test/pom.xml
- tests/bookkeeper-server-tests-shaded-test/src/test/java/org/apache/bookkeeper/tests/shaded/BookKeeperServerTestsShadedJarTest.java
This is a cherry-pick for branch-4.6.
**Problem:**
`shadedArtifactAttached` was introduced in 4.6.0 to generate plain and shaded artifact for `bookkeeper-server`. Because for projects (e.g. distributedlog) that would use same protobuf and guava version as bookkeeper, they will use the plain artifact (to avoid shading protobuf/guava multiple times). However there are a few problems with that:
1) bookkeeper-common is not included in the shading include set.
2) `shadedArtifactAttached` only generate a shaded artifact (with relocated classes), but doesn't generate a dependency-reduced pom file. so you have to manually exclude relocated dependencies.
**Solutions:**
- for shaded artifact of `bookkeeper-server`, include all the bookkeeper submodules that …
> Issue 922: changes to shading bookkeeper-server jar for branch-4.6

- bookkeeper-server/pom.xml
Change "netty-common" to "netty-all" in order to simplify packaging of poms
> Issue-1004 Client of BookKeeper 4.6.1 imports dependencies to netty-common

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
There was a typo at cherry-picking #1240 when merging it.
> Fix a typo when cherry-picking #1240

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
This change is cherry-picking apache/bookkeeper@8b8c5515e041347e0fdd791534fa0a694c96c6ae to branch 4.6
Related Issue: #1218
> ---
>
>
>
> Otherwise:
> 
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn …
> Fix bytebuf leaking on `getLastAddConfirmed` at InterleaveLedgerStorage

- site/bps/BP-35-128-bits-support.md
- site/community/bookkeeper_proposals.md
BookKeeper coordinates with a metadata store to generate a cluster wide `ledgerId`.
Currently this is a signed `64 bit` number (effectively 63 bits). This method works
great because we have a centralized metadata store for coordinating the id generation.
However this method may not scale as the cluster size and number of ledgers grow.
[Universally unique identifier - Wikipedia](https://en.wikipedia.org/wiki/Globally_unique_identifier)
is a preferred way to generate decentralized globally unique IDs and it takes `128 bits`.
This method can scale well as it doesn't need a centralized coordination.
This BP proposes the changes for increasing ledger id from `63 bits` to `128 bits`.
Master Issue: #603
> ---
> In order to uphold a high standard for …
> BP-35: 128 bits support

- dev/bk-merge-pr.py
The development of bookkeeper has been moved from JIRA to Github.
So we can clean up the merge script to remove those instructions
assuming we are still on apache mirror and JIRA.
This change follows the changes that I have adjusted at apache/incubator-pulsar#2526
- remove related logic about JIRA from merge script
- change merge script to use github merge api
> ---
> can check following list to skip the tests …
>  [dev] clean up merge script

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/zk/ZKMetadataDriverBase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/TestLedgerManager.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/zk/ZKMetadataDriverBaseStaticTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
zk+null:// will cause the layout to be read from the store.  This patch
updates zk:// to do the same.  This matches past behavior with an
unspecified ledgerManagerFactoryClass.
Some tests needed to be updated with the new behavior.
(@bug W-5415120@)
(@rev cguttapalem@)
> ISSUE #1653: Clients with zk:// uri's should read layout from store

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/conf/AbstractConfigurationTest.java
The URI patch had a side effect of causing LocalBookKeeper to always
use a URI string of the form zk:// which defaults to HLM.  This
patch updates LocalBookKeeper to generate zk+<layout>:// based on
the legacy LEDGER_MANAGER_FACTORY_CLASS config when present.  +null
will be used otherwise and defaults to HLM.  Further, use the
(admittedly deprecated) zkLedgerRootPath config to determine the
ledger path (defaults to /ledger, so the behavior will be unchanged
if unspecified).
(@bug W-5415276@)
(@rev cguttapalem@)
> ISSUE 1662: LocalBookKeeper use layout manager and ledger path configs

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LedgerIdFormatter.java
- tests/integration/smoke/src/test/java/org/apache/bookkeeper/tests/integration/TestBookieShellCluster.java
Dumping will dump the serialized metadata to a file. Restoring will
parse the metadata from the file and write it to the metadata store.
Also changes the LedgerIdFormatter to default to long formatter (it
was UUID before, and we don't even currently support UUID ledger ids).
This fixes #1604
> Utility to dump/restore ledger metadata to/from file

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/MdcUtils.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedScheduler.java
- bookkeeper-proto/src/main/proto/BookkeeperProtocol.proto
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeper.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/OrderedGenericCallback.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MdcContextTest.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/proto/ProtocolBenchmark.java
- MDC context is passed to runnables, callables etc.
- protocol extended, context is sent to bookie servers, restored there and back on client with the response.
Hopefully did not miss some nuance on the server side, largely rely on changes in ordered executors to do all the magic.
- did microbenchmarking of the protocol changes (strings added to protobuf, MDC context preserved/restored). Looks ok.
- added unit tests.
(@bug W-5291641@) 
(@bug W-5291648@)
Troubleshooting of request-level failures/errors can be simplified if request id was passed through all the stages of the request, from threadpools on the client to bookies to the response back on the client. 
Log4j/Slf4j allows logging of MDC data so it makes sense to use this functionality for …
> Issue #850: Added request context across client and bookies.

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
The only blocking error is that the GRPC NOTICE had not been bubbled
up to our notice.
The links for common-lang 3.6 and jackson 1.9.11 were also wrong, and
while these aren't required in license files, bad links makes it
harder to check if a dependency has been correct noted in the LICENSE
and NOTICE.
> Fix license issues in master

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/EntryLogTest.java
- EntryLogger's instance shutdown method should be called
- Otherwise test would flap, since in tearDown method, FileUtils.deleteDirectory can fail because of EntryLogFile PreAllocation task.
> Shutdown appropriate EntryLogger instance.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- conf/bk_server.conf
- site/_data/config/bk_server.yaml
- As part of ISSUE #1527, new versions of 'journalFormatVersionToWrite'
and 'fileInfoFormatVersionToWrite' are introduced. Since 4.8 release version
is created, default values of these versions should be bumped.
> Bump journal and fileinfo version.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AutoRecoveryMainTest.java
We are introducing Etcd as the metadata storage. However AutoRecovery currently is still tied to zookeeper. In order to use Etcd as the metadata storage, we have to move AutoRecovery related classes to use metadata driver API.
This is the first change for changing AutoRecovery to use metadata driver. It changed AutoRecoveryMain to use metadata driver api and also removed the shutdown logic on session expired, which doesn't make any sense for current retryable zookeeper.
> ---
> the precommit checks can take a long time, some …
> autorecovery-use-metadata-driver (part 1) : move AutoRecoveryMain to use MetadataBookieDriver

- bin/bkperf
- conf/log4j.cli.properties
- pom.xml
- tools/perf/README.md
- tools/perf/pom.xml
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/BKPerf.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/DlogPerfCommandGroup.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/PerfCommandGroup.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/dlog/PerfReader.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/dlog/PerfWriter.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/dlog/ReadCommand.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/dlog/WriteCommand.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/dlog/package-info.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/package-info.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/utils/PaddingDecimalFormat.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/utils/package-info.java
- tools/pom.xml
when investigating performance on scanning entries in bookkeeper, it is hard to know what is the expectation of what kind of throughput that application can get. we need a perf tool to understand the baseline of performance that bookkeeper can provide.
this tool is following what pulsar perf tool is doing and using dlog library for evaluating the write and read throughput on bookkeeper using one (or a few) dlog streams.
> ---
> the precommit checks can take a long time, some trivial changes don't need to run all the …
> [tools] Add a perf tool for benchmarking bookkeeper

- stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/channel/StorageServerChannel.java
- stream/clients/java/kv/src/main/java/org/apache/bookkeeper/clients/impl/kv/interceptors/RoutingHeaderClientInterceptor.java
- stream/clients/java/kv/src/main/java/org/apache/bookkeeper/clients/impl/kv/interceptors/package-info.java
- stream/clients/java/kv/src/test/java/org/apache/bookkeeper/clients/impl/kv/interceptors/RoutingHeaderClientInterceptorTest.java
- stream/proto/src/main/java/org/apache/bookkeeper/stream/protocol/ProtocolConstants.java
*Motivation*
Currently java client deals with request routing and attach routing information before sending the request.
If we try to apply same mechanism for non-java language clients, it requires implementing this complex
routing logic for every non-java language client, which is not a desirable solution.
So we should move the request routing to the server side, which can simplify the implementation of non-java
language client.
*Changes*
Introduce a client interceptor which intercepts table service rpc calls and mutating the rpc request with
correct routing information. This interceptor can be used at server side for proxying grpc requests.
> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs …
> [table service] introduce a client interceptor to attach routing information for table service rpc calls

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedScheduler.java
- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/util/TestOrderedExecutorDecorators.java
Actually, decorate the runnables too, but apply the decoration in a
decorator on the thread so that if a runnable/callable is passed to
the thread, the decoration will be applied.
This allows users of OrderedExecutor/Scheduler to use
executor.chooseThread() for CompletableFuture async handlers and still
get things like the MDC context.
> Decorate OrderedExecutor threads rather than runnables

- pom.xml
- stream/clients/python/.gitignore
- stream/clients/python/README.md
- stream/clients/python/README.rst
- stream/clients/python/scripts/publish.sh
- stream/clients/python/scripts/publish_staging.sh
- stream/clients/python/setup.py
*Motivation*
make the python client available for usage
*Changes*
- update README and setup.py
- set the client version to `4.9.0-alpha-0`
- scripts to build python client and upload it to pypi
*Result*
https://pypi.org/project/apache-bookkeeper-client/4.9.0a0/
> ---
> you are not sure, committers …
>  [table service][client] provide scripts for uploading python clients to pypi

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryMemTable.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
Retaining a reference to that array assumes that the caller
won't reuse the array for something else -- an assumption
violated by Journal.scanJournal and probably other callers.
(@bug W-5499346@)
(@rev cguttapalem@)
> ISSUE #1737: EntryMemTable.newEntry: always make a copy

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- ReadEntryCallback in ReadLedgerEntriesCmd shouldn't release buffer,
which is not owned by the callback.
with the following change, Per channel bookie clients owns the buffer for read responses. So it is not correct for ReadEntryCallback in ReadLedgerEntriesCmd to release buffer
https://github.com/apache/bookkeeper/commit/8d048abce486c63d428041f77ee9a506756f4d1e#diff-e50ee2c1aec1539ea185a94605b0e550R1611
because of this issue I'm seeing following error with ReadLedgerEntriesCmd
```
/Workspace/SFStorage/bookkeeper/bookkeeper-server/bin$ ./bookkeeper shell -localbookie readledger -bookie ****  -ledgerid 00000000-0000-0000-0000-000000000003 -firstentryid 1 -lastentryid 3
JAVA_HOME not set, using java from PATH. (/usr/bin/java)
--------- …
```
> ReadEntryCallback in ReadLedgerEntriesCmd shouldn't release buffer.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MetadataClientDriver.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/zk/ZKMetadataClientDriver.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorElector.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/MetadataDriversTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AutoRecoveryMainTest.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdMetadataClientDriver.java
- add setConnectionExpiredListener method to MetadataClientDriver interface.
- add listener to shutdown AR in the case of metadata connection expiry
This commit - 4f0d2a195bd9be3788876b47813cee1440cf005c, has removed the shutdown logic in AutoRecoveryMain incase of ZK client session expiry, with the following reason "which doesn't make any sense for current retryable zookeeper". But if the ZK session has expired then it is not completely correct to let AutoRecoveryMain to continue to run in that state.
> Set ConnectionExpired Listener to MetadataClientDriver in AR

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieInitializationTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerStorageCheckpointTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/TestLongZkLedgerIdGenerator.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/TestZkLedgerIdGenerator.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestLedgerUnderreplicationManager.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ZooKeeperCluster.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ZooKeeperClusterUtil.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ZooKeeperUtil.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/TestZkUtils.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/zookeeper/TestZooKeeperClient.java
- adding multi-node ZKCluster util class
- adding new interface for ZKCluster util and having separate implementaions for
single node ZKCluster and multi-node ZKCluster
This helps in adding more test coverage to Zookeeper aspects.
> Adding multi-node ZKCluster test util class

- circe-checksum/src/main/assembly/assembly.xml
The current assembly configuration is including the jars of the modules dependency inside its own jar.
These jars are completely ignored, but they take up non trivial space.
With this change the size of `circe-checksum.jar` goes from 2.8 MB to 62 KB.
> Modules dependencies do not need to be included in checksum Jar

- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/BookieSocketAddress.java
`BookieSocketAddress` is resolving the bookie DNS name in its constructor and then using the already resolved `InetSocketAddress` instance.
If the IP of a bookie changes, the BK client will continue to use the old IP address.
Construct a new `InetSocketAddress` each time `getSocketAddress()` gets called (eg: each time we attempt to make a new connection) so that we're making sure to get the right IP.
I cannot think of a good way to add unit test for this at this point, suggestions are welcome. 
I think this should be included in a patch release as well 4.7.3 or 4.8.1
> Don't cache Bookie hostname DNS resolution forever

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadata.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerMetadataTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/UpdateLedgerCmdTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/UpdateLedgerOpTest.java
It doesn't make sense anymore, as local copies of the metadata are
never modified, only updated with the latest version from the metadata
store.
In effect, this logic has been broken out to the places where we try
to update the metadata store copy. Each time we try to update the
metadata store, we ensure that the update we are applying still makes
sense with regard to the copy of the metadata we are updating.
> Kill LedgerMetadata#isConflictWith

- bin/bookkeeper
*Motivation*
apache/bookkeeper#1749 fixes bash script issue but it introduced `set -e` which
will fail `bin/bookkeeper` if grepping configuration file failed.
*Changes*
`set -e` is useful to fail fast if anything fails in the bash script. This change
is to mask exit code of `grep` operation, since the bash script already handle
the grep result.
*Tests*
Manually verified the change works. And the existing TestCompatUpgradeYahooCustom.testUpgradeYahooCustom
integration tests would also verify if the change fixes the problem or not.
> ---
> checks for pull requests. A pull request can only be merged when it passes precommit checks. However …
> [tests] Fix integration test TestCompatUpgradeYahooCustom.testUpgradeYahooCustom

- pom.xml
- stream/clients/python/bookkeeper/admin/client.py
- stream/clients/python/bookkeeper/admin/namespace.py
- stream/clients/python/bookkeeper/admin/namespaces.py
- stream/clients/python/bookkeeper/common/constants.py
- stream/clients/python/bookkeeper/common/exceptions.py
- stream/clients/python/bookkeeper/kv/client.py
- stream/clients/python/bookkeeper/kv/table.py
- stream/clients/python/nox.py
- stream/clients/python/noxfile.py
- stream/clients/python/scripts/docker_build.sh
- stream/clients/python/scripts/docker_integration_tests.sh
- stream/clients/python/scripts/run_integration_tests.sh
- stream/clients/python/setup.py
- stream/clients/python/tests/integration/bookkeeper/__init__.py
- stream/clients/python/tests/integration/bookkeeper/admin/test_admin_client.py
- stream/clients/python/tests/integration/bookkeeper/kv/test_client.py
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/sc/StorageContainerImpl.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/service/RangeStoreServiceImpl.java
- tests/docker-images/current-version-image/Dockerfile
- tests/docker-images/current-version-image/pom.xml
- tests/docker-images/current-version-image/scripts/install-python-client.sh
*Motivation*
Python client is a thin table service client. So it relies on storage container
intercepting the requests to attach routing header. It attaches the routing header
if the requests are needed to route to remote containers; however for the local containers
it doesn't attach the right routing header.
*Changes*
Fix `StorageContainerImpl` to use proxy routing interceptor to intercept requests to attach routing header.
*Tests*
Add integration tests in python client & add test for python clients reading key/value pairs written by java clients.
> ---
> checks for pull requests. A pull request can only be merged when it passes …
>  [table service] Fix python client can't read keys written by java clients

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
For common "error" conditions the exception message is the only important bit while the stack traces are just adding clutter the logs files.
> Reduce stack traces in logs for common cases

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileInfo.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileInfoBackingCache.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexInMemPageMgr.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexPersistenceMgr.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerEntryPage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerCacheTest.java
IndexPersistencManager.flushLedgerHandle can race with delete by
obtaining a FileInfo just prior to delete and then proceeding to rewrite
the file info resurrecting it.  FileInfo provides a convenient point of
synchronization for avoinding this race.  FileInfo.moveLedgerIndexFile,
FileInfo.flushHeader, and FileInfo.delete() are synchronized already, so
this patch simply adds a deleted flag to the FileInfo object to indicate
that the FileInfo has become invalid.  checkOpen is called in every
method and will now throw FileInfoDeleted if delete has been called.
IndexPersistenceManager can catch it and deal with it appropriately in
flush (which generally means moving onto the next ledger).
This patch also eliminates ledgersToFlush and ledgersFlushing.  Their
purpose appears to be to allow …
> ISSUE #1757: prevent race between flush and delete from recreating index

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/net/ServiceURI.java
- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/net/ServiceURITest.java
*Motivation*
Currently we have to add `4181` in the service uri in order to make it work.
Ideally it would be great that the system can fill the default port if port is missing.
*Changes*
add default port when parsing `ServiceURI`
> ---
>
> - [ ] [skip …
> [table service] add default port to service hosts

- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/BookieSocketAddress.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/net/BookieSocketAddressTest.java
- in BookieSocketAddress if IPAddress is hostname then it is okay
to cache InetSocketAddress, since the canonicalhostname of the node
dont change.
> Cache InetSocketAddress if hostname is IPAddress

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
Profiling of our Bookkeeper Client code for read requests shows that client threads spend half of their time in dispatching requests to OrderedExecutors (just the dispatch itself, not the execution inside OSE): 54% of their CPU time is spent in OrderedExecutor.executeOrdered() (called by LedgerHandle.readEntriesInternalAsync()). The high time spend in request submission to OSE is largely caused by Linux scheduling cost, that is the cost of dispatching the OSE thread to CPU: 42% of total time (3/4th of executeOrdered() time), threads spend in Unsafe.unpark(), which is essentially Linux scheduling/dispatching of another thread.
This change executes read submissions (PendingReadOp) on read-only ledger handles directly inside the client thread instead of submitting them to Ordered Executors. …
> Issue #1791: Read Submission should bypass OSE Threads

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieException.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Cookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/ZKRegistrationManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/CookieCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/CreateCookieCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/DeleteCookieCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/GenerateCookieCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/GetCookieCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/UpdateCookieCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/package-info.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/helpers/BookieShellCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/helpers/ClientCommand.java
- tools/all/src/main/java/org/apache/bookkeeper/tools/cli/commands/CookieCommandGroup.java
- tools/all/src/main/resources/META-INF/services/org.apache.bookkeeper.tools.framework.CommandGroup
- tools/all/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/CreateCookieCommandTest.java
- tools/all/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/DeleteCookieCommandTest.java
- tools/all/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/GenerateCookieCommandTest.java
- tools/all/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/GetCookieCommandTest.java
- tools/all/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/UpdateCookieCommandTest.java
- tools/all/src/test/java/org/apache/bookkeeper/tools/cli/helpers/BookieShellCommandTest.java
- tools/all/src/test/java/org/apache/bookkeeper/tools/cli/helpers/CookieCommandTestBase.java
- tools/framework/src/main/java/org/apache/bookkeeper/tools/common/BKCommand.java
*Motivation*
In some use cases, you need cookie related tools to create/delete/update/get cookie when handling production issues.
Currently bookkeeper doesn't provide such commands.
*Changes*
Add cookie related commands
- create
- delete
- get
- update
- generate
> ---
> you are not sure, committers …
> [tools] add cookie related commands

- tools/all/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieCommandGroup.java
- tools/all/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookiesCommandGroup.java
- tools/all/src/main/java/org/apache/bookkeeper/tools/cli/commands/LedgerCommandGroup.java
- tools/framework/src/main/java/org/apache/bookkeeper/tools/common/BKCommandCategories.java
- tools/framework/src/main/java/org/apache/bookkeeper/tools/framework/CliCommand.java
- tools/framework/src/main/java/org/apache/bookkeeper/tools/framework/CliSpec.java
- tools/framework/src/main/java/org/apache/bookkeeper/tools/framework/Command.java
- tools/framework/src/main/java/org/apache/bookkeeper/tools/framework/CommandUtils.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/ClusterCommandGroup.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/NamespaceCommandGroup.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/TableAdminCommandGroup.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/TableCommandGroup.java
*Motivation*
Currently `bin/bktcl help` will output all command groups all together.
It is a bit hard to tell what command groups to use, especially some
commands are used for table service.
*Changes*
Introduce `category` in the cli spec to define which category that a
command group belongs to. So when it prints out the help message, it
can use that information to categorize the command groups together
to provide better user experience.
*Results*
```
$ bin/bkctl help
bkctl interacts and operates Apache BookKeeper clusters
Usage:  bkctl [flags] [command group] [commands]
Infrastructure commands :
bookie          Commands on operating a single bookie
bookies         Commands on operating a cluster of bookies
cluster         Commands on administrating …
```
> [tools] improve bkctl help message

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultEnsemblePlacementPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/GenericEnsemblePlacementPolicyTest.java
- bookieInfoMap is not initialized and newEnsemble will throws BKNotEnoughBookiesException if
diskWeightBasedPlacement is enabled
- add test coverage for DefaultEnsemblePlacementPolicy with diskWeightBasedPlacement enabled
> Fix bugs in DefaultEnsemblePlacementPolicy

- .travis_scripts/build.sh
- bin/common.sh
- bookkeeper-dist/bkctl/pom.xml
- bookkeeper-dist/pom.xml
- bookkeeper-dist/src/assemble/bkctl.xml
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
*Motivation*
Server distribution contains a lot of stuffs that doesn’t need to run bkctl and bookkeeper shell, such as stats providers, http servers and many other dependencies.
At many environments, you want to deliver a set of tools to your customers to interact with or operate bookkeeper clusters. They don’t care about server side stuffs and ask them to use a server package to run a tool makes things confused.
*changes*
Create a new ‘bkctl’ package that only contains bookkeeper shell and new cli.
> ---
> the precommit …
> [tools] package bookkeeper tools into a separated distribution

- site/bps/BP-36-stats-documentation-annotation.md
- site/community/bookkeeper_proposals.md
*Motivation*
A common ask from people using bookkeeper is how they can monitor bookies and bookkeeper clients, what kind of metrics that bookkeeper exposes
and what are the important metrics. Currently bookkeeper doesn't provide any metrics page for guiding people on monitoring bookkeeper services.
In order to help people on this, we need to provide a few documentation pages about metrics. However if we just write such pages, those pages
can quickly get out-of-dated when code is changed. The proposal here is to seek a programming way for generating metrics related pages.
> ---
> checks for pull requests. A pull …
> BP-36: Stats documentation annotation

- cpu-affinity/pom.xml
Port tricks from circe-checksum to cpu-affinity module in order to make the build pass on JDK11
> Fix cpu-affinity module build on jdk10+

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerBase.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForEntryLogPerLedger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForSingleEntryLog.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SortedLedgerStorage.java
*Motivation*
A strong behavior was observed when using sorted ledger storage with single entry log manager on production:
"the entry log files are rotated very frequently and small entry log files are produced".
The problem was introduced due to #1410.
At current entry logger, when a new entry log file is created, EntryLogger will notify its listeners
that a new entry log file is rotated via [`onRotateEntryLog`](https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerBase.java#L152).
Before the change in #1410, `SortedLedgerStorage` inherits from `InterleavedLedgerStorage`.
So when a new entry log file is rotated, `SortedLedgerStorage` is notified.
However after the change in …
> [bookie] Fix sorted ledger storage rotating entry log files too frequent

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadata.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadataBuilder.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MSLedgerManagerFactory.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MetadataUpdateLoopTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ParallelLedgerRecoveryTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/GcLedgersTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/MockLedgerManager.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManager.java
- metadata-drivers/etcd/src/test/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManagerTest.java
parseConfig is one of the main places that mutates member fields of
LedgerMetadata. This change removes these mutates to make it use
LedgerMetadataBuilder instead.
> LedgerMetadata#parseConfig uses Metadata Builder

- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicBookieCheckTest.java
The flake was occurring because the bookie checker was trying to
connect to a TCP endpoint that didn't respond (1.1.1.1) and was
waiting for the whole tcp connect timeout (10sec), while the test was
waiting 10 seconds for the success condition to occur. The success
condition often occurred just after the test fails.
The solution was to bring the connect timeout for the client down to
500ms, giving the auditor plenty of time to register the
underreplicated ledger.
I guess this used to pass in the past because maybe 1.1.1.1 was
actually rejecting packets instead of dropping them, and these changed
when cloudflare took over the address. I changed the endpoint to
192.0.2.0/24 range (TEST-NET) to avoid a similar scenario in the
future.
> Fix flake in AuditorPeriodicBookieCheckTest

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeper.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerCreateOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadata.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerMetadataTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockLedgerHandle.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ReadLastConfirmedAndEntryOpTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestLedgerFragmentReplication.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestWatchEnsembleChange.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/api/BookKeeperBuildersTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/LedgerManagerIteratorTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorLedgerCheckerTest.java
- metadata-drivers/etcd/src/test/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManagerTest.java
LedgerMetadata shouldn't generally be created outside the client,
except for testing. In the case where it is, the builder should be
used to construct it.
I've left the copy constructor for now, as I don't feel comfortable
removing it until all fields are final, which will occur soon.
> Remove LedgerMetadata constructors except one for builder

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadata.java
Make most fields in LedgerMetadata final. The ones which I have not
changed in this patch require a more involved change, so they'll come
in separate PRs.
> Make most LedgerMetadata fields final

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicy.java
With this change
https://github.com/apache/bookkeeper/commit/9ba4c4e0d8be770e03110a958fb8b75a65ae0f59
we introduced 'minNumRacksPerWriteQuorum' config option. To handle that, logic is added in
RackawareEnsemblePlacementPolicyImpl.newEnsembleInternal and RackQuorumCoverageSet. But in
retrospect, this is kind of duplicate logic and changes made in RackawareEnsemblePlacementPolicyImpl.newEnsembleInternal
is not really needed, because anyhow 'apply' of predicate (RRTopologyAwareCoverageEnsemble) is called, which calls
'apply' method on all the concerned RackQuorumCoverageSet.
> Remove duplication logic for 'minNumRacksPerWriteQuorum' handling in RackawareEnsemblePlacementPolicyImpl

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadata.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieWriteLedgerTest.java
The method is only used in the test, so it should live there.
> Move utility method from LedgerMetadata to test

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadata.java
Remove any methods in LedgerMetadata that modify the ensemble. With
this change the ensembles are 100% immutable.
> Remove LedgerMetadata methods modifying ensembles

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadata.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerRecoveryOp.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeperTestCase.java
A copy constructor makes no sense when it's not possible to mutate the object.
> Remove LedgerMetadata copy constructor

- site/_config.yml
- site/docs/4.8.1/overview/releaseNotes.md
- site/releases.md
Release notes for 4.8.1
The commit to review is d09296c589b8a188937833ca51a4b24ea337a901
> ---
>
> - [x] [skip bookkeeper-server client tests]: skip testing …
> Release notes for 4.8.1

- .test-infra/jenkins/job_bookkeeper_precommit_bookie_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_client_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_integrationtests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_java8.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_java9.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_remaining_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_replication_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_tls_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_validation.groovy
According to  the documentation of the GitHub Pull Request plugin:
- ${sha1} means a commit which is the result of merging the PR branch with the target branch
- ${ghprbActualCommit} is directly the PR branch
So currently we are not testing the PR branch against the target branch, but only the branch "as it is"
see:
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&ved=2ahUKEwje0PjpnuDeAhUF2SwKHXN4BgYQFjADegQIAxAB&url=https%3A%2F%2Fwiki.jenkins.io%2Fdisplay%2FJENKINS%2FGitHub%2Bpull%2Brequest%2Bbuilder%2Bplugin&usg=AOvVaw2XvPL5ynRYnqVEWqpe9cs1
Use ${sha1} instead of ${ghprbActualCommit} for Pre-commit Jobs
> ---
> checks …
> Use ${sha1} instead of ${ghprbActualCommit} for Pre-commit Jobs

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
This is a fix for a flake in
AuditorPeriodicCheckTest#testIndexCorruption. Auditor#checkAllLedgers()
runs a check on all ledgers, passing ProcessLostFragmentsCb as a
callback to LedgerChecker#checkLedger for each one.
LedgerChecker#checkLedger triggers the callback on completion,
regardless of whether there are fragments missing on not. Previously,
ProcessLostFragments was not checking if there were lost fragments
before publishing the ledger as suspected in zookeeper.
The flake triggered as there were always two ledgers that existed when
the check occurred, both would be reported as suspected, and it was
random which would be returned while polling for underreplicated
ledgers.
The fix is to check that something is actually underreplicated before
publishing.
> Only publish suspect ledgers if they have missing fragments

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
*Motivation*
DbLedgerStorage doesn't drive checkpoint itself. so currently DbLedgerStorage flush only
happens either when write-cache is full or entry log file rotated. The correctness is still
maintained. However the behavior is different from original yahoo behavior.
*Changes*
Revert the behavior back to original periodical flush
> ---
> can check following list to skip the tests that don't need to run for your …
> [ledger storage] DbLedgerStorage should do periodical flush

- bookkeeper-http/vertx-http-server/src/main/java/org/apache/bookkeeper/http/vertx/VertxHttpServer.java
- bookkeeper-http/vertx-http-server/src/test/java/org/apache/bookkeeper/http/vertx/TestVertxHttpServer.java
The previous implementation was searching for a open port by
repeatedly trying to startServer on ports starting at 8080. However,
after the first attempt fails, the Vertx instance in VertxHttpServer
is broken and the test hangs. 8080 is a very common port to have stuff
running on, so these hangs have happened to be repeatedly.
This fix is to allow the OS to choose the port, by specifying 0 as the
listening port and querying afterwards.
Issue: #1821
> Let OS choose port for vertx test

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerLayout.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerMetadataSerDe.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MSLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/GetLedgerMetaService.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/ListLedgerService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerMetadataTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/MockLedgerManager.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/TestLedgerLayout.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManager.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManagerFactory.java
- metadata-drivers/etcd/src/test/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManagerTest.java
The max ledger metadata format version is the maximum format version
that will be used to write ledger metadata. By setting it in the
ledger layout it becomes a cluster-wide configuration which is
initialized along with the cluster. Any cluster initialized with the
current code will end up with version 2. For this cluster serde will
only ever serialize with up to version 2 of the ledger metadata
format, so all clients that understand version 2 will continue to
work, even as the software version increases and new metadata formats
become available (such as the binary metadata format coming soon).
Currently there is no handling in LedgerMetadataSerDe, because we
don't have a new version, but when there is, it will use
```
Math.min(maxLedgerMetadataFormatVersion, …
```
> Add max ledger metadata format version to layout

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicy.java
Since beginning, selectFromNetworkLocation(excludeRacks, excludeBookies,..)
method kind of ignores predicate/ensemble passed to that method
https://github.com/apache/bookkeeper/blob/branch-4.7/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java#L694.
This was kind of ok, because so far effectively this method is called from only
one place - https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java#L612,
which passes TruePredicate.INSTANCE and EnsembleForReplacementWithNoConstraints.INSTANCE.
But it is not ideal to ignore those parameters in selectFromNetworkLocation(excludeRacks, excludeBookies,..),
from …
> Fix selectFromNetworkLocation in RackawareEnsemblePlacementPolicyImpl

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/HandleFailuresTest.java
If the first pending add op is completed, but does not have the
replaced bookie in its write set, callbacks are triggered straight
away.
Previously this would then hang forever, as the changingEnsemble would
be true. This patch sets changingEnsemble to false before calling
unsetSuccessAndSendWriteRequest so that if callbacks are triggered
straight away, they can actually complete. It also moves the call to
unsetSuccessAndSendWriteRequest outside of the metadataLock so that
the callbacks don't run inside the lock.
> changingEnsemble should be negated before calling unset success

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractHierarchicalLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/FlatLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/FlatLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/HierarchicalLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/HierarchicalLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LegacyHierarchicalLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LegacyHierarchicalLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LongHierarchicalLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LongHierarchicalLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MSLedgerManagerFactory.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ParallelLedgerRecoveryTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerTest.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManager.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManagerFactory.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdMetadataDriverBase.java
- metadata-drivers/etcd/src/test/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManagerTest.java
- tests/shaded/distributedlog-core-shaded-test/src/test/java/org/apache/bookkeeper/tests/shaded/DistributedLogCoreShadedJarTest.java
In dce4fd4 the max metadata format version was put in the
configuration which was then used to create ledger managers. This is
not safe though, as it there are multiple paths which through which
ledger manager factories are created and some may not see this
configuration modification. For example, on a new cluster where there
is no preexisting layout, the layout isn't written until after the
ledger manager factory has been created.
This patch changes LedgerManagerFactory#initialize to explicitly
require that the max ledger metadata format is specified in the call.
Master issue: #723
> Ledger manager factories initialized with max metadata version

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/AbstractLogCompactor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookKeeperServerStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannelBase.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedReadChannel.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogCompactor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexInMemPageMgr.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexPersistenceMgr.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedStorageRegenerateIndexOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerCache.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerCacheImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerEntryPage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/ScrubberStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SortedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/TransactionalEntryLogCompactor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/Main.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/service/ScrubberService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorageTest.java
The main goal of this patch is the ScrubberService LifecycleComponent
which runs in the background periodically verifying the internal
consistency of the LedgerStorage. To get that to work:
- LedgerStorage now has a localConsistencyCheck call with
implementations in Interleaved and Sorted.
- In service of that implementation, LedgerCache gains an interface for
iterating safely over the entries of a ledger with a way of handling
concurrently modified or deleted ledgers with corresponding
modifications to LedgerEntryPage for detecting deletion.
- EntryLogger has been refactored to permit checking the correctness
(and throwing a descriptive exception in case of a problem) of an entry
without actually reading it for use within localConsistencyCheck.
- The two mechanisms for iterating over a …
> ISSUE-1770: Add local checker for Sorted/InterleavedLedgerStorage

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClientImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
- site/_data/config/bk_server.yaml
- https://github.com/apache/bookkeeper/commit/2837f6257baf15dc9dd9eb4bcac34596b442be33
had inadvertently removed StatsLogger to BookKeeper client instance in ReplicationWorker process.
So restore StatsLogger in BookKeeper client object.
- Also introduce new config called - 'limitStatsLogging', which would be used to limit statslogging
as and when needed.
- currently this config is used to limit the stats from PCBC. Because if AR process is running in
each Bookie node, then for each AR there will be n number of PCBCs and totally it comes out to
n^2 PCBCs in the cluster. Which is unmanageable from stats collector perspective. So this config
value can be set to true in AR config.
> Bring back statslogger to BookKeeper client in ReplicationWorker process.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieWriteLedgerTest.java
For this race condition to happen:
1. ZK metadata version is different from Client write ledger
handle - Replication worker
2. Client made an ensemble change and replaced a bookie,
sent change proposal to zk
3. While this is pending, Client made another ensemble change
replaced the same index with the bookie that was prior to step#2
4. Ensemble change made in step#2 came back to client with
version conflict error.
5. Client need to resolve this conflict
The fix is to reconsile the local state, zk state, and do bookie
replaceemnt, send the updated metadata to zk.
Signed-off-by: Venkateswararao Jujjuri (JV) <vjujjuri@salesforce.com>
(@rev Sam Just@)
(Describe: what …
> Issue#1886 Handle double bookie failures

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerClose2Test.java
The previous behaviour was to complete successfully immediately if
close had already been called on the handle. This allowed for
potential consistency violations, as the caller could believe that the
ledger was closed, when in fact the close operation was still in
progress and could still potentially fail.
Issue: #1712
> Multiple calls to LedgerHandle#close should wait on actual close

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractHierarchicalLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/FlatLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/FlatLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/HierarchicalLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/HierarchicalLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerLayout.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerMetadataSerDe.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LegacyHierarchicalLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LegacyHierarchicalLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LongHierarchicalLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LongHierarchicalLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MSLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/GetLedgerMetaService.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/ListLedgerService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerMetadataTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ParallelLedgerRecoveryTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/MockLedgerManager.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/TestLedgerLayout.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManager.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManagerFactory.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdMetadataDriverBase.java
- metadata-drivers/etcd/src/test/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManagerTest.java
- tests/shaded/distributedlog-core-shaded-test/src/test/java/org/apache/bookkeeper/tests/shaded/DistributedLogCoreShadedJarTest.java
There is ongoing discussions about how to do this, so I'm reverting this
change for now to allow 4.9 release to proceed. The change modifies the
contents of the layout znode, so once they're in an official release they
cannot be removed without breaking BC.
The reverted changes are:
dd684b Ledger manager factories initialized with max metadata version
dce4fd Add max ledger metadata format version to layout
Master issue: #723
> Revert maxLedgerMetadataFormatVersion changes in layout

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookKeeperServerStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorageTest.java
This patch additionally:
- modifies InterleavedLedgerStorageTest.java to test with and without
entryLogPerLedger
- refactors the test a bit to ensure that the gc calls really do race
with the right part of the checker
- addresses a few other more cosmetic errors
(@bug W-5721713@)
> ISSUE #1892: ILS: reset retry in consistency check loop

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ClientInternalConf.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/EnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieStickyReadsTest.java
Currently the BK client is issuing the read requests in round-robin fashion across all the bookies in the write set.
One issue with this approach is that it's not taking full advantage of the read-ahead cache, either explicit (like in `DbLedgerStorage`) or implicit (by reading data through Linux page cache which will do some prefetching).
With `e=2`, `w=2`, when we read `e-0` from `bookie-1` and `e-1` from `bookie-2`, we fail to take advantage of the fact that `bookie-1` will have already `e-1` in memory.
Effectively with `e-2`, `w-2` the disk read IO will be doubled, compared to the amount of data served to BK clients. The larger the quorum, the bigger will be overhead (eg: `e=5`, `w=5` will lead to 5x reads from disk).
Added a BK client flag for "sticky reads". When reading from a …
> Allow to configure sticky reads

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerCreateOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/BookieSocketAddress.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/GetLedgerMetaService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
Once the binary ledger metadata serializing is available, the output
of GetMetaService would no longer be understandable. In preparation
for this, make GetMetaService use output JSON, rather than directly
calling #serialize.
Master issue: #723
>  HTTP GetMetaService returns JSON rather than calling #serialize

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LocalBookieEnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookieWatcherImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultEnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/EnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ITopologyAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RegionAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/GenericEnsemblePlacementPolicyTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicyUsingScript.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawarePolicyNotificationUpdates.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
Currently newEnsemble and replaceBookie in EnsemblePlacementPolicy
return a apache commons Pair<> with the second argument being a
boolean to denote whether the placement conforms strictly to the
policy. From calling code, the meaning of this second value is
unclear.
This patch replaces Pair<> with an PlacementResult object, in which
the strict conformity argument is clearly labels. This will also allow
extension in the future to return more metadata about particular
placements.
Also, we shouldn't put third party library classes in interfaces.
Issue:  #1914
> Add semantically meaningful return values to placement policy

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RegionAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- site/_data/config/bk_server.yaml
'ignoreLocalNodeInPlacementPolicy' specifies whether to ignore localnode
in the internal logic of placement policy. If it is not possible or useful
to use Bookkeeper client node's (or AutoReplicator) rack/region info. for
placement policy then it is better to ignore localnode instead of false
alarming with error/warn log lines and metrics.
It is not valid to expect rack mapping information to be available for Bookkeeper
client and ReplicationWorker nodes. So if rackmapping info. is not available
then it is better to ignore creation of BookieNode by resolving rack information
for the client localnode. Otherwise it would log unnecessary warn/error log lines
and rack resolution failure metrics.
> Ignore usage of localNode in PlacementPolicy.

- buildtools/src/main/resources/ide/eclipse/formatter.xml
`formatter.xml` is an invalid xml and eclipse fails to load it.
> fix invalid formatter xml

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexInMemPageMgr.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerCacheTest.java
IndexInMemPageMgr should translate FileInfoDeletedException into
NoLedgerException as expected by users like
InterleavedLedgerStorage.updateEntriesLocations and
EntryMemTable.flushSnapshot.
> BOOKKEEPER-1919: putEntryOffset translate FileInfoDeletedException

- site/community/contributing.md
- site/community/issue-report.md
- site/community/meeting.md
- site/community/releases.md
> Fix obsoleted proposals document link

- bookkeeper-http/vertx-http-server/src/main/java/org/apache/bookkeeper/http/vertx/VertxHttpServer.java
Right now, vertx-http-server is not serving any rest endpoint except get because vertx server doesn't add put/post/delete http-methods into routing rules.
Add put/post/delete http-methods into routing rules.
> [bookie-http-server] Fix: broken vertx rest endpoints

- site/_data/popovers.yaml
Adds a popover term for 'striped' to match 'striping'.
The first "link" text has no pop-over, but the second does. 
Just copies the pop-over for striping. It seems inelegant vs. allowing multiple pop-over terms to refer to the same HTML fragment rather than being 1-1, but also is a straightforward and unobtrusive change.
Master Issue: (no issue)
> ---
> can check following list to skip the tests that don't need to run for your pull request. Leave them …
> [DOC] popover for 'striped' as well as 'striping'

- bookkeeper-server/pom.xml
- bookkeeper-stats-providers/pom.xml
- microbenchmarks/pom.xml
- microbenchmarks/src/main/java/org/apache/bookkeeper/stats/StatsLoggerBenchmark.java
---
Fixes #1962
*Motivation*
There are some twitter dependencies can't download from repo
- remove some using in StatsLoggerBenchmark.java
- update some config in pom.xml
You can add -Dtwitter to choose add twitter dependencies.
Master Issue: #1962
> ---
> can check following …
> Fix unable download twitter dependencies

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicyUsingScript.java
- Use conf value in RackawareEnsemblePlacementPolicyImpl.initialize method,
instead of uninitialized enforceMinNumRacksPerWriteQuorum variable
> Use conf value in RackawareEnsemblePlacementPolicyImpl.initialize method

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/ReadAheadEntryReader.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestCancelledRead.java
There was a bug in the ReadAheadReader whereby, if it was in a paused
state and the last segment it had read had been closed, then when a
writer started writing new segments, the ReadAheadReader would issue a
double read. This would end up triggering an error when it got to the
end of the segment as the issued one of the issued reads would then be
cancelled when the segment was closed.
This fix adds an explicit state machine to the reader and moves all
state transitions to run on the ordered executor, so only one read can
ever be issued at a time.
> [DLOG] Avoid double read in readahead

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/AbstractDNSToSwitchMapping.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/ScriptBasedMapping.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicyUsingScript.java
- when setConf of AbstractDNSToSwitchMapping  is called it
should do sanity checking of the conf/env. and throw
RuntimeException if things are not valid.
- For RawScriptBasedMapping.validateConf, try executing
the script with no arguments for sanity check purpose.
Here it is expected that running script with no arguments
would do sanity check of the script and the env.
(there are 2 commits in this PR, but this PR is meant for the second commit and there is other PR for the first commit)
> Add validateConf to AbstractDNSToSwitchMapping

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/FormatCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/FormatCommandTest.java
Migrate command `bookieformat`.
#1974 
- Add command `bookieformat` to bkctl
- Replace command in shell
> Migrate command `bookieformat`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/InitCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/InitCommandTest.java
Migrate command `bookieinit` from shell to bkctl
Issue #1977 
- Replace command `bookieinit` in shell
> Issue #1977: Migrate command 'bookieinit'

- tests/integration/smoke/src/test/java/org/apache/bookkeeper/tests/integration/TestCLI.java
- tests/integration/smoke/src/test/java/org/apache/bookkeeper/tests/integration/TestSmoke.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieIdCommandGroup.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookieid/SearchReplaceBookieIdCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookieid/package-info.java
- tools/ledger/src/main/resources/commands
To use:
```
bin/bkctl bookieid searchreplace --from <from> --to <to>
```
To be used in cases where the DNS name of the bookie has to change, and you don't want all the data to have to be moved by autorecovery.
> Tool to search and replace bookie ids in ledger metadata

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/LedgerCommand.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorageTest.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/LedgerCommandTest.java
Migrate command `ledger` from shell to bkctl
#1980 
- Add new implement for `ledger`
> Issue #1980: Migrate command `ledger` from shell to bkctl

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ConvertToDBStorageCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/ConvertToDBStorageCommandTest.java
*Motivation*
- Use bkctl to run command `convert-to-db-storage`
- #1985 
- Add command in `bookieGroup`
> Issue #1985: Migrate command `convert-to-db-storage`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageBookieTest.java
Currently setting the `dbStorage_writeCacheMaxSizeMb=` with empty value is making the
DbLedgerStorage initialize to fail since the empty string is being parsed as long. 
Instead, we should just apply the default value as in the case where the config key is not there.
> In DbLedgerStorage use default values when config key is present but empty

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ConvertToInterleavedStorageCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/ConvertToInterleavedStorageCommandTest.java
- Migrate command `convert-to-interleaved-storage`
- #1987 
- Use `bkctl` to run command `convert-to-interleaved-storage`
- Add command in `bookiegroup`
> Issue #1987: Migrate command `convert-to-interleaved-storage`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListFilesOnDiscCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListFilesOnDiscCommandTest.java
- Replace command `listfilesondisk` 
- Use `bkctl` to run command `listfilesondisk`
- #1989 
- Add command in `bkctl`
> Migrate command `listfilesondisk`

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/logsegment/BKLogSegmentEntryReader.java
A interrupt exception can occur during the poll operation of the blocking and cause a NPE to be thrown
Check if entry is null before trying to release it
> fix potential NPE when releasing entry that is null

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
> Fix error message for unrecognized number-of-bookies

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BKException.java
There are two ```Code``` in ```org.apache.bookkeeper.client. BKException```:
The first is https://github.com/apache/bookkeeper/blob/f26a4cae0e9205ad391c6d4d79f2937871864c28/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BKException.java#L136
The second is https://github.com/apache/bookkeeper/blob/f26a4cae0e9205ad391c6d4d79f2937871864c28/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/api/BKException.java#L180
BKException's subclasses cannot auto choice which ```Code```.
> Fix IDE complain as there are multi choices for error code

- docker/Dockerfile
- docker/hooks/build
- site/community/release_guide.md
This hook will allow docker autobuild to build from the offical tag
and removes the need to update the dockerfile after the release has
been made.
It also adds a build arg, DISTRO_URL which can be used for testing
release candidates.
```
docker build --build-arg BK_VERSION=4.9.1
--build-arg DISTRO_URL=<rc-tarball-url> .
```
> Docker autobuild hook

- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/sc/StorageContainerRegistryImpl.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/store/MVCCStoreFactoryImpl.java
If not releasing resources of failed/closed asyncStore, new creating of the same store identifier will fail, mainly caused by RocksDBException, like #2020 shows.
add scStores to factory's instance variable at the `addstore` method of `MVCCStoreFactoryImpl` class;
release store when open fail;
Master Issue: #2020
> Issue 2020: close db properly to avoid open RocksDB failure at the second time

- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/PerfClient.java
change newCachedThreadPool() to newFixedThreadPool(int)
newFixedThreadPool(int) can be freely configured with the total number of threads, while cached thread pool may cause OutOfMemoryError when there are too many threads need to created.
> Issue 2023: change cached thread pool to fixed thread pool

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/LocalConsistencyCheckCommand.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieCommandGroup.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/LocalConsistencyCheckCommandTest.java
#2042 
Using bkctl run command localconsistencycheck
```
Validate Ledger Storage internal metadata
Usage:  bkctl bookie localconsistencycheck [flags]
Flags:
-h, --help
Display help information
```
> Migrate command `localconsistencycheck`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
Avoid useless verify if LedgerEntryRequest completed
Change-Id: Ifda2a6e218c49105a5627be69566ea2ce4a57699
Print misleading logs when the SpeculativeRequestExecutionPolicy is turned on：
2019-04-03 18:30:49,839 ERROR org.apache.bookkeeper.client.DigestManager: Entry-id mismatch in authenticated message, expected: -1 , actual: 602
2019-04-03 18:30:49,839 ERROR org.apache.bookkeeper.client.DigestManager: Entry-id mismatch in authenticated message, expected: -1 , actual: 606
2019-04-03 18:30:49,839 ERROR org.apache.bookkeeper.client.DigestManager: Entry-id mismatch in authenticated message, expected: -1 , actual: 610
2019-04-03 18:30:49,839 ERROR org.apache.bookkeeper.client.DigestManager: Entry-id mismatch in authenticated message, expected: -1 , …
> Avoid useless verify if LedgerEntryRequest completed

- bookkeeper-stats-providers/codahale-metrics-provider/src/main/java/org/apache/bookkeeper/stats/codahale/FastSnapshot.java
- bookkeeper-stats-providers/codahale-metrics-provider/src/test/java/org/apache/bookkeeper/stats/codahale/FastTimerTest.java
This bugfix for the FastCodahale timer implementation ensures that percentiles provided by a FastSnapshot are calculated correctly even if the total count of events (provided by FastTimer) is out of sync with the recorded events in the percentile buckets.
FastCodahale Timer implementation may miscalculate percentiles if snapshots of values are slightly out of sync, and if only few events have been recorded.
FastCodahale Timers use fine-grained locking and are meant to tolerate that (some) values change while being recorded or while snapshots are created. Currently, the total count of requests is not synchronized with the number of requests recorded in percentile buckets. If a snapshot is created while the total count of the timer has been incremented beyond the sum of values in the …
> Issue 2053: Bugfix for Percentile Calculation in FastCodahale Timer Implementation

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileInfo.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/TransientLedgerInfo.java
Previous behaviour was to return straight away. However, LAC can
change when the ledger is fenced and there is no guarantee that a
fenced ledger will turn into a closed ledger (fencing client may
crash), which would cause the client tailing with longpoll LAC to go
into a tight loop.
> Wait for LAC update even if ledger fenced

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileInfo.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexPersistenceMgr.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedStorageRegenerateIndexOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerCache.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerCacheImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDescriptor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDescriptorImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SortedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/TransientLedgerInfo.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/LongPollReadEntryProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessorV3.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/TestSyncThread.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/GcLedgersTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/LedgerManagerTestCase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/LongPollReadEntryProcessorV3Test.java
Otherwise the watch objects will accumulate and eventually cause an
OOM on the bookie, if LAC doesn't progress.
> Cancel LAC watch when longpoll LAC times out

- site/docs/4.8.2/overview/overview.md
The release notes link text was saying the latest version rather than
4.8.2.
> Fix typo in overview page for 4.8.2

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessor.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ReadEntryProcessorTest.java
Currently, the ```ReadEntryProcessor``` v2 does not support asynchronous fence request, which wait for 1000 milliseconds to wait it done if it's a fencing request. This pull request attempt to support asynchronous response if a thread pool is provided. 
Closes #283
> Support asynchronous fence request for V2 ReadEntryProcessor

- bookkeeper-proto/src/main/proto/DataFormats.proto
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadataBuilder.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadataImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/api/LedgerMetadata.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerMetadataSerDe.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/zookeeper/ZooKeeperClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/TestLedgerMetadataSerDe.java
- tests/backward-compat/current-server-old-clients/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatOldClients.groovy
- tests/backward-compat/yahoo-custom-version/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatUpgradeYahooCustom.groovy
The bookkeeper project ZooKeeperClient wrapper for the ZooKeeper client
will resend zk node creations and removals upon reconnect after a
ConnectionLoss event. In the event that the original succeeded, the
resent operation will erroneously return LedgerExistException or
NoSuchLedgerExistsException for creation and removal respectively.
For removal, this patch limits the operation by allowing it to always
succeed if the ledger does not exist in order to make it idempotent.
This is appears to be the simplest solution as exclusive removal isn't
important.
**Note, the above is an actual change to the bk client semantics**
For creation, exclusive creation is cleary important for correctness,
so this patch adds a creator token field to the LedgerMetdata …
> ISSUE-1967: make ledger creation and removal robust to zk connectionloss

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/api/namespace/Namespace.java
Other methods such as delete do, so openLog should declare it to be
consistent and to give users a hint that it can be caught.
> DLog Namespace#openLog should declare LogNotFoundException

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManager.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/TestLedgerMetadataSerDe.java
This change removes a byte[] copy in DigestManager digest calculation
(computeDigestAndPackageForSending)
that puts crc header and payload in a continuous buffer. Instead,
it uses protobuf ByteString.concat to concatenate header and payload
without copy when building protobuf message.
In add entry code path, I see lots of byte[] allocated to do digest calculation.  It's possible to not allocate byte[]. 
Don't allocate a ByteBuf to copy data. Keep header and data separate, but use ByteString.concat when construct protobuf message.
Master Issue: #2067 
> ---
> checks for pull requests. A pull request can only be merged when it passes …
> ISSUE-2067: reduce byte[] allocation in add entry

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/ScanAndCompareGarbageCollector.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BKException.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerChecker.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/UpdateLedgerOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/api/BKException.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/impl/OpenBuilderBase.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MSLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/BookieLedgerIndexer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeper.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeperTestCase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/api/BookKeeperApiTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/api/BookKeeperBuildersTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/GcLedgersTest.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/bk/TestLedgerAllocator.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/tools/TestDistributedLogTool.java
- tests/integration/smoke/src/test/java/org/apache/bookkeeper/tests/integration/TestBookieShellCluster.java
Client can get no extent error in the following two scenarios.
1. When client attempted to read/open an extent that
is not on ZK (metadata server)
2. When client attempted to read a Ledger which is on metadata
server, but somehow missing on bookies (Data server)
It is quite confusing to get the same error, NoSuchLedgerExists
for both these cases. This checkin introduced a new error at the
BookKeeper client level, NoSuchLedgerExistsOnMetadataServer if
it is not available on ZK.
For errors related to Ledger is not available on bookie,
I left NoSuchLedgerExists as-is(instead of changing it to
NoSuchLedgerExistsOnDataServer) to minimize code changes.
This change alone provides enough distinction between these
two types of errors.
Signed-off-by: Venkateswararao Jujjuri (JV) …
> Explicit error message if extent is not present on ZK

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerMetadataSerDe.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/TestLedgerMetadataSerDe.java
- fix test failures in TestLedgerMetadataSerDe
> ISSUE #1967: make ledger creation and removal robust to zk connectionloss

- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieIsReadyService.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieStateService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
- site/docs/latest/admin/http.md
Allow to check the state of the bookie through HTTP.
The main reason is to allow light-weight probes that can be run frequently to establish whether the bookie is running and meets a minimum readiness criteria. One example is to automatically wait until the bookie has completed the startup sequence.
Added new HTTP handler that exposes the values from the bookie `StateManager`.
> Added HTTP handler to expose bookie state

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultEnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/TopologyAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/WeightedRandomSelection.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/WeightedRandomSelectionImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestWeightedRandomSelection.java
- Moving components/methods which are common in nature with respect to
placementpolicy from RackawareEnsemblePlacementPolicyImpl to
TopologyAwareEnsemblePlacementPolicy, so that any new placementpolicy
implementation can extend TopologyAwareEnsemblePlacementPolicy and reuse
those common components/generic.
- This change has no functionality change, it is just reorganizing code.
> Move common placementpolicy components to TopologyAwareEnsemblePlacementPolicy.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/ScanAndCompareGarbageCollector.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/CleanupLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/FlatLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/HierarchicalLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LegacyHierarchicalLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LongHierarchicalLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MSLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ZkUtils.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ParallelLedgerRecoveryTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/MockLedgerManager.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManager.java
Right now, we have below 3 issues because of which gc thread gets blocked forever and it can't perform gc-task further. Below issues are mainly related to blocking call while doing zk-operation without timeout. 
bug-fixes:
1. right now, [GC - ScanAndCompareGarbageCollector](https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/ScanAndCompareGarbageCollector.java#L142) passes timeout in millisecond to [LedgerManager](https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LongHierarchicalLedgerManager.java#L166) but it 
takes it as second and again try to convert it in millis so, 30Kms timeout becomes [30M ms timeout](https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/ …
> [bk-gc] avoid blocking call in gc-thread

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ZkUtils.java
As discussed at [#4276](https://github.com/apache/pulsar/issues/4276), while deleting ledger, bk-client should check parent node is empty before issuing delete request for parent znode.
> [Bk-Client] Check empty ledger-parent node while deleting ledger

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieInitializationTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieWriteToJournalTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/TestUtils.java
Update `lastLogMark` in memory after replaying each journal
Check for writable ledger dirs with `minUsableSizeForEntryLogCreation` to flush the `lastMark` file for bookies in ReadOnlyMode
Log line changes
Master Issue: #2087
> Update and flush lastLogMark when replaying journal

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieInitializationTest.java
- in testIOVertexHTTPServerEndpointForARWithPrometheusProvider test
it is not correct to assume that Auditor would have been created and
started completely when we complete AutoRecoveryMain.start and see it
status as started. It would make sure AuditorElector.submitElectionTask
has submitted election task but not the completion of Auditor.start.
So instead of relying on Auditor metric (NUM_UNDER_REPLICATED_LEDGERS),
use ReplicationWorker metric - NUM_FULL_OR_PARTIAL_LEDGERS_REPLICATED.
> Fix flaky testIOVertexHTTPServerEndpointForARWithPrometheusProvider test

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
The [commit](https://github.com/apache/bookkeeper/commit/36be8362399341022c8de64f9319270726df2cb3) caused integration test failure `test101_RegenerateIndex`, with the exception
```
```java.io.IOException: Invalid argument
at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
at sun.nio.ch.IOUtil.read(IOUtil.java:197)
at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
at org.apache.bookkeeper.bookie.JournalChannel.read(JournalChannel.java:257)
at org.apache.bookkeeper.bookie.Journal.fullRead(Journal.java:1171)
at org.apache.bookkeeper.bookie.Journal.scanJournal(Journal.java:792)
at …
> Update lastLogMark to EOF when replaying journal

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperClientStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ClientInternalConf.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/EnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/impl/BookKeeperClientStatsImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicy.java
- conf/bk_server.conf
- site/_data/config/bk_server.yaml
Bookkeeper write logic makes sure that there are at least ackQuorumSize
number of successful writes before sending ack back to the client. In
many cases these may fall into the same fault domain. A mechanism to
force bookkeeper to make sure that there are acks from at least
minNumRacksPerWriteQuorum number of fault domains and a configuration
to enforce this.
Signed-off-by: Ankit Jain <jain.a@salesforce.com>
Master Issue: #2095
> Entries must be acknowledged by bookies in multiple fault domains before being acknowledged to client

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
It addresses #1927 where it provides a conf check at the beginning of startLocalBookiesInternal function.
- Add a conf check at the beginning of startLocalBookiesInternal function where non-default zkLedgersRootPath is not allowed.
cc @sijie
> Issue 1927: fix NoNodeException in LocalBookeeper

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/BookKeeperClient.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/logsegment/BKLogSegmentEntryStore.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/tools/DistributedLogTool.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestBKDistributedLogManager.java
*Motivation*
Issue #2066 introduced `NoSuchLedgerExistsOnMetadataServer`. But the distributedlog
library is not updated to reflect to this change.
Change to use `NoSuchLedgerExistsOnMetadataServer` in the right place.
> Update distributedlog library to use NoSuchLedgerExistsOnMetadataServer

- .test-infra/jenkins/job_bookkeeper_precommit_bookie_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_client_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_java11.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_java8.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_remaining_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_replication_tests.groovy
- .test-infra/jenkins/job_bookkeeper_precommit_tls_tests.groovy
- .test-infra/jenkins/job_bookkeeper_release_branch_47_integrationtests.groovy
- .test-infra/jenkins/job_bookkeeper_release_branch_48_integrationtests.groovy
- .test-infra/scripts/pre-docker-tests.sh
Changes to shell commands in few scripts
It was difficult to reproduce jenkins test failures locally and the cause might be due to differences in underlying file system. These commands will output more information to spot the exact differences.
Running `df` command with an additional `-T` parameter to output filesystem information
Added `docker info` command to print docker details before every test run
> Display filesystem and docker info for all jenkins runs

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieClientTest.java
bd2b16e880d172d4761461fdbf85c1bd19b24e36 had introduced
'limitStatsLogging' feature, which would be used to limit statslogging,
where it is needed. eg - we would like to suppress logs from PCBC
in Auditor/ReplicationWorker process.
In this commit I'm adding testcases for this feature.
> Testcase for limitStatsLogging.

- bookkeeper-stats-providers/twitter-science-provider/pom.xml
Fetch the maven dependencies through HTTPs
> Use https for Twitter maven repo

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/EnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
Master Issue: #1970
Related Issues: apache/pulsar#3715 apache/pulsar#4526
*Motivation*
Fixes #1970
By default bookie uses a random generator to generate a bookie index as the sticky
read bookie index. However the random generator will generate negative numbers. Hence
it will generate negative bookie indexes in write set and cause ArrayIndexOutOfBoundException
when bookkeeper attempts to read entries.
Make sure getStickyReadBookieIndex not return negative number.
*Verify this change*
This problem introduced by a random generator. It is very hard to write a unit test to reproduce this issue.
Existing StickyRead tests are good to cover this code change.
> ---
> In order to uphold a high standard for quality for code contributions, …
> Issue #1970: Ensure getStickyReadBookieIndex returns valid bookie index

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/LocalDLMEmulator.java
Added host IP binding to sandbox.
Allowing running the sandbox inside guest machines and be accessible by all system (including other guest machines). When binding 127.0.0.1 other guest machines will experience an error. By allowing to bind the correct IP the namespace will be available and correctly configured for other hosts.
Added a new argument to the _dlog_ tool allowing to define the host IP to bind ZooKeeper and DistributedLog namespace.
Master Issue: #1960
> ---
> the precommit checks can take a long time, some …
> Added zookeeper host configuration. Closes #1960

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookieWatcher.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookieWatcherImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/RegistrationClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/ZKRegistrationClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/ZKRegistrationManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/ListBookiesCommand.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieShellTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperAdminTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/discover/MockRegistrationClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/discover/TestZkRegistrationClient.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdRegistrationClient.java
In this PR I'm adding a `BokKeeperAdmin#getAllBookies` to retrive all the bookies (cookie) retriving them from the `RegistrationClient`
This is still a work in progress, I'm adding some tests in the next commit.
> Implement a method to get all the Bookies

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/ScanAndCompareGarbageCollector.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/GcLedgersTest.java
As described at: https://github.com/apache/pulsar/issues/4632
- Sometimes due to overreplication, bookie contains ledgers which are not owned by that bookie anymore and that bookie is not part of the ensemble-list of those ledgers. In this case, GC finds out those overreplicated ledgers and 
- deletes their index from dbStorage (rocksDB) and 
- tries to delete them from entrylog files.
However, bookie doesn't delete them from entry-log files due to change made in [#870](https://github.com/apache/bookkeeper/issues/870) where bookie avoids deleting ledger if znode of that ledger exists.
Because of that bookie ends up storing large number entrylog files with ledgers which are owned by different bookies. It also cause OOM when GC tries to deal with large number of entry log files.
Delete the …
> [bk-server] Clean up over-replicated ledgers owned by different bookies

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/GarbageCollectorThreadTest.java
As mentioned in #2103, if an exception occurs during compaction of a specific entry log, `GarbageCollectorThread` does not perform compaction of other entry logs until the bookie server is restarted. As a result, the number of entry logs continues to increase and eventually it will run out of disk space.
The cause of the compaction stop is that the `compacting` flag remains true if `compactor.compact(entryLogMeta)` throws some exception.
https://github.com/apache/bookkeeper/blob/b2e099bbc7b13f13825fe78ab009ca132cb3a9ba/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java#L504-L519
Therefore, fixed `GarbageCollectorThread` so that it set the compaction flag to false even if compaction of a specific entry log fails.
Master Issue: #2103
> Issue #2103: Avoid stop of entry log compaction

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/admin/DistributedLogAdmin.java
Included ZooKeeper Acl to the builder.
It is now possible to unbind DistributedLog namesapaces.
Master Issue: #1961
> ---
> - [ ] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [x] [skip bookkeeper-server replication tests]: skip testing `org.apache.bookkeeper.replication` in bookkeeper-server module.
> - [x] [skip bookkeeper-server tls tests]: skip testing `org.apache.bookkeeper.tls` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server remaining tests]: skip testing all other tests in bookkeeper-server module.
> - [ ] [skip integration tests]: skip docker …
> Issue #1961: Included ZooKeeper client AclId.

- .test-infra/scripts/pre-docker-tests.sh
Previously we were using a filter which matched on the network name of
the networks we create. However, docker seems to have removed this
functionality, so now we just prune all unused networks which are more
than 12h old (no CI job should be taking more than 12h).
> [CI] Prune networks older than 12h

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexPersistenceMgr.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/ScanAndCompareGarbageCollector.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/TransactionalEntryLogCompactor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingWriteLacOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/BookieSocketAddress.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestLedgerFragmentReplication.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
- stream/distributedlog/common/src/main/java/org/apache/distributedlog/common/config/ConfigurationSubscription.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/LocalDLMEmulator.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/bk/SimpleLedgerAllocator.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/metadata/BKDLConfig.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/net/DNSResolver.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestBKDistributedLogNamespace.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestLogSegmentCreation.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestReader.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestRollLogSegments.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/bk/TestLedgerAllocatorPool.java
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/service/BookieService.java
The following changes were made:
- remove unused placeholders in the log statements
- add missing placeholders to the log strings to show the complete information
- remove unnecessary initialization of object arrays in the log statements
> Fix log statements with incorrect placeholders

- README.md
Fixed broken URLs in README for Programmer Guide, Tutorial and Java API.
Updated the URLs.
Wanted to go through the tutorial when I came to the repo and found the links were broken in the README.
Master Issue: #2130
> Issue #2130 : Fix for broken URLs

- bin/common.sh
- detect new Java versions in bin/common.sh
- use different defaults on JDK8 vs JDK11+
Change distribution scripts in order to detect a JDK newer then JDK8 and set default JVM options accordingly.
Because I want that BookKeeper tools run out of the box with JDK11
1) detect a JDK newer then JDK8, but checking if exists $JAVA_HOME/bin/jshell (this is quite robust, better then parsing some Java version string)
2) use new defaults for JDK11, in particular do not enable experimental and deprecated options, use the new [Java Unified Logging](https://openjdk.java.net/jeps/158) log system for GC
Please note the output of "Java Unified Logging" is very different from the old pre-Java9 one and 
options are different, there is no simple port.
Master Issue: …
> Make default Bookie scripts work on JDK11+

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/annotation/InterfaceAudience.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/annotation/InterfaceStability.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/conf/validators/RangeValidator.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedScheduler.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/auth/BookKeeperPrincipal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileSystemUpgrade.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/api/LedgerMetadata.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MSLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/NetworkTopologyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/streaming/LedgerOutputStream.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/LedgerCommand.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/auth/TestAuth.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieDeferredSyncTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerCacheTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MetadataUpdateLoopTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/RoundRobinDistributionScheduleTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/BKDistributedLogManager.java
- stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/DLSN.java
* Simplify `if` statements where it is possible (mainly for `if` statements returning boolean values)
* Remove redundant semicolons
* Remove the `close` method where the resource is used withing the try-with-resources block
> Simplify if statements

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/FileModifiedTimeUpdater.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/TLSContextFactory.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
- conf/bk_server.conf
Right now, if certs are rotated then bookie doesn't pick up refresh cert and we have to restart the bookie. So, we need a way to auto refresh certs into bookie.
- add configuration `tlsCertFilesRefreshDurationSeconds` to auto refresh cert
- bookie checks last modified date of the cert after auto-refresh duration and refresh certs if requires
- Bookie can refresh certs without restart.
> [bookie] auto refresh tls cert at bookie-server

- bin/common.sh
- pom.xml
- tests/integration-tests-base-groovy/pom.xml
- tests/integration-tests-utils/pom.xml
- tests/pom.xml
Upgrade Lombok to 1.18.10
Upgrade Groovy and Groovy Compiler and Maven Compiler plugin
Fix an inverted if that prevented **bkctl** to work with JDK11+ and it made GC LOGGING opts not applied with JDK8 (in bkctl command), a regression introduced by #2132
> Make the project buildable with JDK12 and JDK13

- pom.xml
- tests/scripts/src/test/bash/bk_test_bin_common.sh
- Upgrade Mockito and PowerMock with a version that support JDK12+
- Fix bash script tests
> Fix tests and upgrade libs to make tests pass on JDK13

- stream/clients/python/setup.py
According to the release guide, before cutting a release we have to remove the 'alpha' qualifier from Python client version
> Change Python client version to 4.10.0

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
In the refactoring part of #1819, the `internalReadEntry()` behavior was changed into throwing an exception when reading an entry from a different ledger. 
This is causing a big performance issue when doing read-head from the ledger storage, because we keep reading from the current entry log until we find an entry from a different ledger.
> Avoid throwing exception when doing EntryLogger.internalReadEntry

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/component/AbstractLifecycleComponent.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/component/ComponentStarter.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/service/AutoRecoveryService.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/service/BookieService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieInitializationTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
When main thread of Bookie/BookieServer has exited with exception while starting Bookie,
Bookie process shouldn't be alive because of any non-daemon thread that has already
started.
> Call exceptionHandler if Bookie.start fails with exception.

- .test-infra/jenkins/common_job_properties.groovy
Update maven version to 3.6.2 for Jenkins build environments, since maven 3.6.0 is no longer available in the environment.
> Update maven version to 3.6.2 for Jenkins

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/BKDistributedLogManager.java
The pendingReaders set in BKDistributedLogManager exists so that if
the manager is closed which the lock is being acquired for a reader,
that reader will be closed (even though it hasn't been returned to the
client).
In the case that the reader is opened without a lock, there
is not async action being performed. Previously we were also adding
these readers to the pendingReaders, but they were never being removed
from the pendingReaders, causing a memory leak. This change avoids
adding no-locking readers to pendingReaders.
> [DLOG] LogReader shouldn't be added to pending if not locking

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperAdminTest.java
- in BookKeeperAdmin.areEntriesOfLedgerStoredInTheBookie method, segmentNum
is not correctly incremented while iterating over the segments of
the ledger. Fixing the logic of it.
- this issue caused decombookie bookieshell command to wait forever.
> Fix logic of areEntriesOfLedgerStoredInTheBookie

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieInitializationTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
During journal replay, we can encounter negative length value if there is journal corruption. Currently, due to this bug, we pass negative length to limit a buffer, which throws IllegalArgumentException.
Updated the Journal class to throw `IOException` with a clear message, instead of unclear `IllegalArgumentException`.
Master Issue: #2176
> Journal scan should throw IOException when it reads negative length

- site/docs/latest/deployment/manual.md
Following the [Manual deployment](https://bookkeeper.apache.org/docs/latest/deployment/manual/), startup bookie may have failure since there is no znode(e.g. /ledger) about bookie in zookeeper. 
Modify the site/docs/latest/deployment/manual.md, set up cluster metadata before startup of bookie.
> [doc] Improve the Manual deployment document.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragment.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestLedgerFragmentReplication.java
- firstStoredEntryId logic in LedgerFragment should return '-1'
only if no bookie contains any entry of that LedgerFragment.
This is a serious issue, in our cluster we observed for a particular ledger, which is marked under replicated, it is returning -1 for firstStoredEntryId and 10 for lastStoredEntryId. Because of that the ReplicationWorker, tries to replicate entryId ‘-1’ and as expected it keeps failing while reading it. So ledger remains under replicated for ever.
> Fix firstStoredEntryId logic in LedgerFragment

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BufferedChannelTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/EntryLogTest.java
Contention on `BufferedChannel` between the journal thread and the ForceWriteThread was introduced in #1228.
`unpersistentBytes` is only used if `unpersistedBytesBound > 0`, which is not true by default. We shouldn't be paying the penalty if not needed.
Also `position` doesn't need to be `AtomicLong` since it's only updated while the mutex is taken. Using a volatile will have the same effect with less overhead.
> Removed mutex contention on BufferedChannel

- site/community/coding_guide.md
The link to `OrderedSafeExecutor` does not work.
Correct the link to `OrderedExecutor`.
> [docs] Update coding_guide.md

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/CRC32CDigestManager.java
Signed-off-by: xiaolong.ran <ranxiaolong716@gmail.com>
When users are using Apache Pulsar, they will encounter the following error about `Sse42Crc32C`. But in fact it does not affect the correctness of Apache Pulsar use. But the error level log information will cause confusion for the user.
```
10:12:49.119 [pulsar-ordered-OrderedExecutor-0-0-EventThread] ERROR org.apache.bookkeeper.proto.checksum.CRC32CDigestManager - Sse42Crc32C is not supported, will use a slower CRC32C implementation.
```
Replace the log level of `not support Sse42Crc32C` from error to warn.
> Fix the log level of not support Sse42Crc32C

- site/docs/latest/admin/autorecovery.md
- site/docs/latest/admin/bookies.md
`bin/bookkeeper shell recover` only receives one parameter i.e. failed bookie. According to [recovery](https://bookkeeper.apache.org/docs/latest/admin/autorecovery/#manual-recovery) it is useless to specify ZooKeeper address and target bookie.
> [Docs] Modify “Using Autoecovery”,recover does not support the specified target bookie

- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadJournalCommand.java
An error occurred while executing `bin/bookkeeper shell readjournal`,
the journal file name is hexadecimal, but when readjournal is executed, the journal name is resolved in base 10
> Fixed  bin/bookkeeper shell readjournal

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/GarbageCollectorThreadTest.java
Unit test fails when build master branch
Config ServerConfiguration with setAllowLoopback(true) in the class GarbageCollectorThreadTest
Master Issue: #2224
> ISSUE-2224: Config ServerConfiguration with setAllowLoopback(true) for Unit Tests

- bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/TLSContextFactory.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
as described at: https://github.com/apache/pulsar/issues/6010
Bookkeeper-client caches the tls certificates when it first tries to create a cnx with a given bookie and after that it never reloads certs even when valid certs changes on the file-system or new bookie-connection is created. Because of that as soon as client certs expires and bk-client disconnects from bookie then bk-client is not able to reconnect to bookie until we restart the bk-client process. and we see below TLS exception at bk-client.
```
19:43:03.983 [bookkeeper-io-12-45] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Unexpected exception caught by bookie client channel handler
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
at …
```
> [bookie-server] add support of client auto cert refresh

- bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/ZKRegistrationManager.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/discover/TestZkRegistrationManager.java
Create ledgersRootPath recursively for `bin/bookkeeper shell metaformat`. The existence of any parent znodes is not an error condition
> Create ledgersRootPath recursively for 'bin/bookkeeper shell metaformat'

- site/docs/4.10.0/admin/http.md
- site/docs/4.6.0/admin/http.md
- site/docs/4.6.1/admin/http.md
- site/docs/4.6.2/admin/http.md
- site/docs/4.7.0/admin/http.md
- site/docs/4.7.1/admin/http.md
- site/docs/4.7.2/admin/http.md
- site/docs/4.7.3/admin/http.md
- site/docs/4.8.0/admin/http.md
- site/docs/4.8.1/admin/http.md
- site/docs/4.8.2/admin/http.md
- site/docs/4.9.0/admin/http.md
- site/docs/4.9.1/admin/http.md
- site/docs/4.9.2/admin/http.md
- site/docs/latest/admin/http.md
This PR is a hotfix for "BookKeeper Admin REST API" document, the compoent of HTTP endpoints should be 5, but it's 4 in the doc.
> [hotfix] fix the http endpoint component count error

- site/docs/4.10.0/development/protocol.md
- site/docs/4.5.0/development/protocol.md
- site/docs/4.5.1/development/protocol.md
- site/docs/4.6.0/development/protocol.md
- site/docs/4.6.1/development/protocol.md
- site/docs/4.6.2/development/protocol.md
- site/docs/4.7.0/development/protocol.md
- site/docs/4.7.1/development/protocol.md
- site/docs/4.7.2/development/protocol.md
- site/docs/4.7.3/development/protocol.md
- site/docs/4.8.0/development/protocol.md
- site/docs/4.8.1/development/protocol.md
- site/docs/4.8.2/development/protocol.md
- site/docs/4.9.0/development/protocol.md
- site/docs/4.9.1/development/protocol.md
- site/docs/4.9.2/development/protocol.md
- site/docs/latest/development/protocol.md
This PR removes redundant word  "because" in protocol documents.
> [hotfix][docs] remove redundant word in protocol documents

- site/community/releases.md
As discussed on the mailing list, I'm updating the BookKeeper website to reflect the new Time Based Release Plan.
You can find the staging website @ https://aluccaroni.github.io/bookkeeper-staging-site/community/releases/
Please note that I've removed the calendar since it was empty
> Website: Update Release Management for new Time Based Release Plan

- bin/bookkeeper
`bin/bookkeeper shell ` support `-conf configuration`, but it doesn't work. bk_server.conf is loaded by default, even if the configuration is specified
Modify `bin/bookkeeper` to specify the configuration file as an absolute path
> bin/bookkeeper shell supports the -conf

- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/cluster/ZkClusterInitializer.java
PR Validation build is failing with below exception:
```
[ERROR] src/main/java/org/apache/bookkeeper/stream/storage/impl/cluster/ZkClusterInitializer.java:[35] (imports) ImportOrder: Import org.apache.bookkeeper.stream.storage.StorageConstants.getSegmentsRootPath appears after other imports that it should precede
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (default-cli) on project stream-storage-service-impl: You have 1 Checkstyle violation. -> [Help 1]
```
> [code-style] fix build failure for check-style

- bin/bookkeeper
This reverts commit 163db4496d50cae198b80c9d88c14579f6d2e9f3.
Commit 163db4496d50cae198b80c9d88c14579f6d2e9f3 broke "bookkeeper shell" command and integration tests are no more able to work
> Revert "bin/bookkeeper shell supports the -conf"

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/TestEntryLog.java
TestEntyLog reuses the entryLogger variable across test methods execution, resulting in an unpredictable execution.
We can at least make the test work consistently across environments using JUnit built-in FixMethodOrder annotation
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
Fixes #2260
> Fix method order in order to make the execution of TestEntryLog predictable

- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/tls-tests.yml
"fatal: reference is not a tree" is a known issue in actions/checkout#23 and fixed in checkout@v2, update checkout used in GitHub actions.
The following three lines only "checkout pull request HEAD commit instead of merge commit" and made all commits available for the following actions. 
For Pulsar, there is a check for "doc only change" and compares the PR commit with the revision the PR is based, therefore git diff is used and needs the revision history visible. 
For BookKeeper, since git command is not using for the following steps now, these lines could be removed as well. 
```yml
with:
fetch-depth: 0
ref: ${{ github.event.pull_request.head.sha }}
```
> Move checkout action to v2

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/JournalChannel.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
> 2178: IOException Should Be Thrown When Journal Is Corrupted

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
when decommission a bookie, and the ledger size of the bookie is big enough, the thread timeout will get negative, and the decommission operation will give up by throw exceptions as follow
```
14:12:56.982 [main] INFO  org.apache.bookkeeper.client.BookKeeperAdmin - Count of Ledgers which need to be rereplicated: 272752
14:12:56.983 [main] ERROR org.apache.bookkeeper.bookie.BookieShell - Received exception in DecommissionBookieCmd 
java.lang.IllegalArgumentException: timeout value is negative
at java.lang.Thread.sleep(Native Method) ~[?:?]
at org.apache.bookkeeper.client.BookKeeperAdmin.waitForLedgersToBeReplicated(BookKeeperAdmin.java:1528) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
at org.apache.bookkeeper.client.BookKeeperAdmin.decommissionBookie(BookKeeperAdmin.java:1500 …
```
> fix bookie decommission sleep timeout value is negative bug

- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- pom.xml
Update Prometheus library to 0.8.1
We have an obsolete version
Update Prometheus library to latest version 0.8.1 and update NOTICE files
> Update Prometheus library to 0.8.1

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageStats.java
The journalStats.getJournalQueueSize increase once and decrease twice, so this stat metric will be negative.
It increases in `logAddEntry` function and decrease in `QueueEntry recall` methord and Journal main thread run methord.
so we should delete the decrease in journal main thread run methord.
```
queue.put(QueueEntry.create(
entry, ackBeforeSync,  ledgerId, entryId, cb, ctx, MathUtils.nowInNano(),
journalStats.getJournalAddEntryStats(),
journalStats.getJournalQueueSize()))
```
> fix some stats monitor metrics

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalPageCacheFlushTest.java
- conf/bk_server.conf
There was a weird behavior observed: when journalSyncData is disabled, it will trigger callbacks when the data is flushed to filesystem(PageCache) but still enqueue a fsync request to force write queue to fsync PageCache data to disk frequently. Though the fsync thread dequeue fsync request and execute fsync operation asynchronously, it still cause disk io util increase when fsync frequency high enough. when disk io util increase, especially reach 100%, it will block new journal file creation and lead to journal sync time increases to mutiple seconds.
when journalSyncData is disabled, we introduce `journalPageCacheFlushIntervalMSec` to control journal PageCache flush frequency to reduce disk io util, default value is 1000ms
> Add Journal PageCache flush interval control when journalSyncData is disabled

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookieWatcherImpl.java
Do not log 'New ensemble: {} is not adhering to Placement Policy. quarantinedBookies' in case of ensembleSize = 1
In tests cases and in simple demos it is very annoying to see that log line at "WARNING" level.
If we are requiring only 1 bookie it is not a big deal to WARN that the placement policy is not "adhering"
> Do not log WARNING about PlacementPolicy for tests and simple setups

- bookkeeper-dist/src/assemble/bin-all.xml
- bookkeeper-dist/src/assemble/bin-server.xml
- bookkeeper-dist/src/assemble/bkctl.xml
- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/deps/bouncycastle-1.60/LICENSE.html
- bookkeeper-server/pom.xml
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/TLSContextFactory.java
- pom.xml
As described at: https://github.com/apache/pulsar/issues/5047
Sometimes user  sees `Invalid TLS configuration` at bookie while loading PKCS8Key file and that can be fixed by using Bouncycastle provider.: https://stackoverflow.com/questions/6559272/algid-parse-error-not-a-sequence/18912362#18912362
```
2019-08-26 16:16:51,983 - ERROR - [BookKeeperClientWorker-OrderedExecutor-0-0:BookieClient@179] - Security Exception in creating new default PCBC pool: 
org.apache.bookkeeper.tls.SecurityException: Invalid TLS configuration
at org.apache.bookkeeper.tls.TLSContextFactory.init(TLSContextFactory.java:392)
at org.apache.bookkeeper.proto.PerChannelBookieClient.<init>(PerChannelBookieClient.java:266)
at org.apache.bookkeeper.proto.BookieClient.create(BookieClient.java:155)
at …
```
> [bookie-mtls] add BouncyCastleProvider for security-provider to avoid InvalidKeyException

- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/Constants.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/journal/AbstractStateStoreWithJournal.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/dlog/DLCheckpointStore.java
Added 'application' and 'component' metadata to StreamStorage ledgers.
application: bk-stream-storage-service
component: state-store / checkpoint-store
Master Issue: #2288 
> - [X] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in bookkeeper-server module.
> - [X] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [X] [skip bookkeeper-server replication tests]: skip testing `org.apache.bookkeeper.replication` in bookkeeper-server module.
> - [X] [skip bookkeeper-server tls tests]: skip testing `org.apache.bookkeeper.tls` in bookkeeper-server module.
> - [X] [skip bookkeeper-server remaining tests]: skip testing all other tests in bookkeeper-server …
>  #2288: add metadata to StreamStorage ledgers

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ReadLastConfirmedOp.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ParallelLedgerRecoveryTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieFailureTest.java
As discussed at https://github.com/apache/pulsar/issues/6505 
Bk-client was not able to recover ledger which has 2 write/ack quorum and one of the bookie went down and recovery was kept failing and bookkeeper client was not able to recover the ledger.
**BK-Client log**
```
20:44:43.721 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR org.apache.bookkeeper.client.ReadLastConfirmedOp - While readLastConfirmed ledger: 1234567 did not hear success responses from all quorums
20:44:43.721 [bookkeeper-io-12-27] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Could not connect to bookie: [id: 0xb8b97441, L:/1.1.1.1:1234]/1.1.1.2:3181, current s
tate CONNECTING : 
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: No route to host: /1.1.1.2:3181
at …
```
> [bookie-ledger-recovery] Fix bookie recovery stuck even with enough ack-quorum response

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/BookieProtoEncodingTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
*Motivation*
TLS is enabled using `startTLS` but the `startTLS`
is a v3 protobuf request. So if the client is
configured to use v2 protocol, the client is not
able to decode `startTLSResponse`.
This change is to improve the v2 protocol response handling for
handling `startTLS` response.
> ---
>
> ---
>
>
>     `<BP-#>: Description of …
> Unable to enable TLS if using v2 protocol

- pom.xml
- tests/docker-images/all-released-versions-image/pom.xml
- tests/integration-tests-base-groovy/pom.xml
Current version of Groovy compiler for integration tests do not support JDK14
Update Groovy Compiler
Update dockerfile-maven-plugin as well
> Allow build on JDK14 - upgrade Groovy compiler

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
As discussed at : https://github.com/apache/pulsar/issues/6042
We have config management tool which manages bookie-server configuration and sets empty value of `journalDirectories` if bookie-server is still wants to use single journal dir: `journalDirectory`. In this case, bookie-server doesn't consider `journalDirectory` value and keeps empty list of `journalDirectories` which stats bookie with invalid configuration.
Bookie-server should parse empty configuration `journalDirectories=` properly and avoid picking up empty value of `journalDirectories` and in that case, bookie-server should fallback to `journalDirectory` config.
> [bookie-server-config] Avoid considering empty journalDirectories

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
Fix batch read data in cache does not take effect
Master Issue: #2230 
Fixes: #2230
> Fix batch read data in cache does not take effect

- stream/clients/python/setup.py
- it looks like a newer version of grpcio has been published and we were using open version range
- by forcing a closed ended range of version we workaround the error in integration tests
> Force to use Python grpcio less then 1.26.0

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerFactory.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperAdminTest.java
After `metaformat`, ledgerId does not count from 0 because，the `metaformat` command does not delete `idgen` znode.
In the `AbstractZkLedgerManagerFactory` avoid skipping the igen and idgen-long nodes
Master Issue: #2274
> Issue 2274: The 'metaformat' command does not delete 'idgen' znode

- pom.xml
Current code forks a new JVM per module. (bookkeeper-server, bookkeeper-proto etc)
This means one fork per module for build and testing, no parallelism within the module where majority of the time goes.
We need parallelism within a module during the test execution so we can have the builds complete faster and have the artifacts shipped out quicker.
We use the maven surefire plugin but don't define the `forkCount` and hence set it to default of 1.
This means it executes each module with one thread.
This change sets `forkCount` to 5, enabling parallelism in testing and drastically reducing total turnaround time. (by about 2/3rds!)
*Total build+test time without this change*
```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total …
```
> Add forkCount option to parallelize build and tests

- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/AutoRecoveryStatusService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/service/AutoRecoveryStatusServiceTest.java
It would be convenient to support enable, disable, or check the status of autorecovery with REST API, just like what does in the toggle command.
Adds an API to enable, disable, and get the current status of autorecovery at `/api/v1/autorecovery/status`.
Master Issue: #2310 
> ---
>
> ---
>
>
>     `e.g. …
> Issue 2310: Adds the autorecovery status service.

- .github/workflows/bot.yml
---
*Motivation*
Currently, non-committers cannot rerun the failure tests, we need to
provide the ability to let non-committer to rerun the failed tests.
I wrote a Github Actions that can rerun the failed test by comments
`rerun failure tests` and add it to the bookkeeper ci process.
> Rerun the failed tests by comments

- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/tls-tests.yml
Sometimes GitHub actions checks are stuck in downloading SNAPSHOTs, there is not need for it
Add "-nsu" option to every Maven invokations and remove "-Dstream" that is now useless.
I am also adding "-B" that suppresses the "Progress" noise in logs
This fix relates to #2294
> Do not download SNAPSHOT during GitHub actions checks

- .github/workflows/bot.yml
The rerun checks CI can not use ref to get all failure test actions. So I change to use sha of the commits to get all failure test actions to rerun. https://github.com/zymap/bot/pull/3/files
> [CI] Using master action code for checking rerun commands

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-server/pom.xml
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/AuthHandler.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
- pom.xml
Right now, bookkeeper-client is not able to perform [hostname-verification](https://tersesystems.com/blog/2014/03/23/fixing-hostname-verification/) when it connects to broker over tls. Hostname-verification feature is already implemented in almost all [http-client](https://github.com/apache/httpcomponents-client/blob/master/httpclient5/src/main/java/org/apache/hc/client5/http/ssl/DefaultHostnameVerifier.java) but it's not supported by [netty](https://stackoverflow.com/questions/13315623/netty-ssl-hostname-verification-support) yet. therefore, client should be able to perform hostname-verification as per [RFC-2181](https://tools.ietf.org/html/rfc2818#section-3.1)
- added client configuration to enable hostname-verification (default disable)
- use …
> [bookie-mTLS] add support of hostname verification

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerRecoveryOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ReadLastConfirmedOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RoundRobinDistributionSchedule.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ParallelLedgerRecoveryTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ReadLastConfirmedOpTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/RoundRobinDistributionScheduleTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieFailureTest.java
- stream/distributedlog/core/src/main/java/org/apache/bookkeeper/client/LedgerReader.java
The original patch was contributed by @ivankelly in PR #2303, I have only fixed checkstyle and removed two tests that were wrong.
Quorum coverage checks if we have heard from enough nodes to know that
there is no entry that can have been written to enough nodes that we
haven't heard from to have formed an ack quorum.
The coverage algorithm was correct pre-5e399df.
5e399df(BOOKKEEPER-759: Delay Ensemble Change & Disable Ensemble
Change) broke this, but it still seems to have worked because they had
a broken else statement at the end. Why a change which is 100% about
the write-path changed something in the read-path is a mystery.
dcdd1e(Small fix wrong nodesUninitialized count when checkCovered)
went on to fix the broken fix, so the whole thing ended up broke.
The change also modifies …
> QuorumCoverage should only count unknown nodes

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieInitializationTest.java
Currently we allow bookies to come up even if they don't have a cookie in the metadata store.
The cookie is an identity of a registered bookie and a bookie should not be allowed to come up without it.
Update handling of bookie boot up. Add test.
This scenario is rarely expected but can happen in case of corruption or errant deletion of znodes for cookies
> Issue #2305: Bookies should not be allowed to come up without a cookie in metadata store.

- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieInfoService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
- site/docs/latest/admin/http.md
This adds an additional HTTP REST endpoint to expose the bookie's info (only storage numbers for now).
I was looking for an HTTP endpoint that returned the info of only the current bookie, but couldn't find one. The only similar API I've found was `/api/v1/bookie/list_bookie_info`, however it connects to all bookies and may take a long time to respond (plus its response format is difficult to parse).
I've added a new API at `/api/v1/bookie/info` that returns a response like:
```json
{
"freeSpace" : 0,
"totalSpace" : 0
}
```
> Add /api/v1/bookie/info REST API

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/TopologyAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/NetUtils.java
*Motivation*
```
06:00:53.731 [BookKeeperClientScheduler-OrderedScheduler-0-0] ERROR org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy - Unexpected exception while handling joining bookie pulsar-tls-bookie-0.pulsar-tls-bookie.pulsar.svc.cluster.local:3181
java.lang.NullPointerException: null
at org.apache.bookkeeper.net.NetUtils.resolveNetworkLocation(NetUtils.java:77) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
```
*TEST*
The `getAddress` is final method. It is hard to mock.
The method has been covered by other tests.
> ---
> checks for pull requests. A pull request can only be merged when it passes …
> Handle NPE when inet address is not able to resolve network address

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/MetadataUpdateLoop.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/UpdateLedgerOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/FlipBookieIdCommand.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/UpdateLedgerOpTest.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/FlipBookieIdCommandTest.java
Right now, `UpdateLedgerCmd` provides option `updatespersec` to throttle number of writes on zk. However, it throttles number of reads instead writes. Because of that it takes long time to complete this command as it slows down the read instead applying throttling while writing to zk.
- Apply throttling while updating zk.
- If writes are being throttled then we also want to avoid accumulating reads so, added `maxOutstandingReads` option to manage max concurrent reads.
**Note:** We also need this change for #2321 .. so, I will rebase #2321 once this PR is merged.
> [bookkeeper-tool] Fix update rate-limiting for update-ledger command

- site/bps/BP-34-cluster-metadata-checker.md
- site/docs/latest/getting-started/installation.md
We have adopted `lamada expression` and `stream api` in code base, it needs jdk1.8 at least.
e.g org.apache.bookkeeper.meta.zk.ZKMetadataClientDriver
```
@Override
public void setSessionStateListener(SessionStateListener sessionStateListener) {
zk.register((event) -> {
// Check for expired connection.
if (event.getType().equals(EventType.None) && event.getState().equals(KeeperState.Expired)) {
sessionStateListener.onSessionExpired();
}
});
}
```
Update `Java Development Kit 1.6` to `Java Development Kit 1.8`
> [BUG] Fix wrong jdk version on install doc page

- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieFailureTest.java
`BookieFailureTest#testLedgerOpenAfterBKCrashed` is a flaky test case, it cause some pr failed.
```
org.apache.bookkeeper.client.BKException$BKLedgerRecoveryException: Error while recovering ledger
at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
at org.apache.bookkeeper.client.SyncCallbackUtils$SyncOpenCallback.openComplete(SyncCallbackUtils.java:157)
at org.apache.bookkeeper.client.LedgerOpenOp.openComplete(LedgerOpenOp.java:232)
at org.apache.bookkeeper.client.LedgerOpenOp$1.safeOperationComplete(LedgerOpenOp.java:201)
at org.apache.bookkeeper.client.LedgerOpenOp$1.safeOperationComplete(LedgerOpenOp.java:193)
at org.apache.bookkeeper.util.OrderedGenericCallback.operationComplete(OrderedGenericCallback.java:62)
at …
```
> [BUG] Fix flaky testLedgerOpenAfterBKCrashed

- README.md
- bookkeeper-benchmark/conf/log4j.properties
1. Fix duplicate key in log4j.properties
2. `http` to `https` in `README`
> [CLEAN] remove duplicate property key in log4j.properties

- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/ListLedgerService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/service/ListLedgerServiceTest.java
The current list ledgers API output the metadata in a serialized binary format, which is not friendly to human operators and external tools, and is not consistent with the output of the [API that gets the metadata](https://bookkeeper.apache.org/docs/4.9.2/admin/http/#endpoint-apiv1ledgermetadataledger_idledger_id).
The PR adds a parameter called `decode_meta`, and output the ledger metadata in decoded format when the parameter presents and the value of it is 'true'.
Master Issue: https://github.com/apache/bookkeeper/issues/2311
> ---
>
> ---
> …
> Issue 2311: Adds support to decode metadata in the API that list ledgers

- conf/log4j.shell.properties
When use shell command, it output nothing caused by `ERROR` level.
**OLD** (output nothing)
```
bin/bookkeeper shell readlogmetadata 0
```
**FIX**
```
bin/bookkeeper shell readlogmetadata 0
06:58:01,364 INFO  Print entryLogMetadata of entrylog 0 (0.log)
06:58:01,467 INFO  Failed to get ledgers map index from: 0.log : No ledgers map index found on entryLogId0
06:58:01,471 INFO  --------- Lid=0, TotalSizeOfEntriesOfLedger=59  ---------
```
- Remove duplicate definition `VERBOSECONSOLE `
- Change `ERROR` to `INFO`
> [LOG] Change ERROR to INFO log level

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MetadataDrivers.java
static code blocks are always invoked when the class is initialized, when client connect to bookkeeper server, output repeat init log
```
2020-06-04 10:10:24,751 INFO  org.apache.bookkeeper.meta.MetadataDrivers                    - BookKeeper metadata driver manager initialized
2020-06-04 10:10:24,753 INFO  org.apache.bookkeeper.meta.MetadataDrivers                    - BookKeeper metadata driver manager initialized
2020-06-04 10:10:24,753 INFO  org.apache.bookkeeper.meta.MetadataDrivers                    - BookKeeper metadata driver manager initialized
```
Remove redundant initialization code.
> [BUG] Fix avoid invoke init drivers repeatedly

- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/InfoCommand.java
Fix redundant statistics, run 5 bookies `bin/bookkeeper localbookie 10`, then show bookieinfo
```
./bin/bookkeeper shell bookieinfo
```
**Wrong result**
```
Free disk space info:
10.101.52.18(10.101.52.18):5004:        Free: 34930151424(34.93GB)      Total: 255850758144(255.85GB)
10.101.52.18(10.101.52.18):5003:        Free: 34930151424(34.93GB)      Total: 255850758144(255.85GB)
10.101.52.18(10.101.52.18):5002:        Free: 34930151424(34.93GB)      Total: 255850758144(255.85GB)
10.101.52.18(10.101.52.18):5000:        Free: 34930151424(34.93GB)      Total: 255850758144(255.85GB)
10.101.52.18(10.101.52.18):5005:        Free: 34930151424(34.93GB)      Total: 255850758144(255.85GB)
Total free disk space in the cluster:   174650757120(174.65GB)
Total disk capacity in the cluster: …
```
> [BUG] Fix redundant statistics

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/HierarchicalLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
- in ZkLedgerUnderreplicationManager.releaseUnderreplicatedLedger remove ‘lock’
from ‘heldLocks’ only if lock znode deletion has succeeded.
- This is needed because, if RW.logBKExceptionAndReleaseLedger fails to delete
the lock znode, then it needs to be tried once more in the finally block of
'rereplicate(long ledgerIdToReplicate)’ before giving up and shutting down RW.
> Remove lock from URManager’s state only if lock znode deletion has succeeded

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/UpdateBookieInLedgerCommand.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/UpdateLedgerCmdTest.java
- site/_data/cli/shell.yaml
In a large bookie cluster environment, we frequently require a utility to change bookie-ip with a different bookie-ip in ledger's metadata in different scenarios such as:
1. Host Re-IP: requires updating ledger metadata and reuse the host without losing/copying data
2. Backup-restore usecase while doing cluster level data migration.
Therefore, we frequently need a tool to update bookie-ip with a new bookie-ip in existing ledgers' ensemble metadata.
Add CLI command to update bookie-id in ledger metadata.
> [bookie-shell] Add cmd to change bookie-address into ledger metadata

- stream/clients/python/setup.py
According to the release guide, before cutting a release we have to remove the 'alpha' qualifier from Python client version
> Change Python client version to 4.11.0

- stream/distributedlog/core/pom.xml
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/metadata/ZKLogStreamMetadataStore.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/subscription/ZKSubscriptionStateStore.java
- stream/pom.xml
- add explicitly distributedlog to the modules of Stream project
- fix checkstyle on distributedlog, it wasn't executed
>  Fix distributedlog Maven reactor module

- site/_config.yml
After generating website using [script](http://bookkeeper.apache.org/community/release_guide/#update-website), it seems somhow it has updated site with incorrect version. I still have to find out where was the issue while generating the website. But fixing it for now to correct the version on website.
> [bookkeeper-site] fix latest version of bookkeeper website

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
- in case of corrupted entry log file the bookie cannot perform GC
- handle the case of an unexpected negative entrysize
Stop scanning the file
Master Issue: #2264
> Issue 2264: Bookie cannot perform Garbage Collection in case of corrupted EntryLogger file

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
These code blocks will not be executed:
dbLedgerStorageStats.getReadAheadBatchCountStats().registerSuccessfulValue(count);
dbLedgerStorageStats.getReadAheadBatchSizeStats().registerSuccessfulValue(size);
fix fillReadAheadCache stat bug
Replace return with break to exit the while loop
> fix fillReadAheadCache stat bug

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/BKLogWriteHandler.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/zk/ZKTransaction.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestZooKeeperClient.java
Fix for #2385
Now we avoid to send out multiple operations request to ZooKeeper when there are not operations to execute
> Issue #2385: NullPointerException in Zookeeper multiple operations execution with 3.6.1

- bin/bkctl
Fix #2197
Create "logs" directory before run bkctl cli
> Issue #2197: bkctl binary distribution needs a 'logs' directory

- bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchThroughputLatency.java
- When` latency.size` is  is more than `20,000,000`(e.g, `25000000`),
`(size * percentile) / 100` will be a negative number due to Integer overflow and the latency will be wrong.
- For example: `size `= 25000000, `percentile `= 99, `sampleSize `= -18199672
> The latency of BenchThroughputLatency may be wrong due to Integer overflow when we do a large scale benchmark test 

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListActiveLedgersCommand.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/metadata/ZKLogStreamMetadataStore.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/subscription/ZKSubscriptionStateStore.java
For troubleshooting bookkeeper disk usage issues, having a tool to list the ledgers that are still alive in the entry log file is super useful.
* Add ListActiveLedgerCommand on BookieShell
Master Issue: #2358
> Active ledgers on entry log file

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
Signed-off-by: xiaolong.ran <rxl@apache.org>
As the https://github.com/apache/pulsar/issues/7931 said, CVE-2018-12540 has been raised on vertx 3.4.1 which is found in the pulsar dependencies. 
- Upgrade the vertx version from 3.4.1 to 3.5.3
- Update license files
> Upgrade the `vertx` version to 3.5.3

- bookkeeper-server/pom.xml
- bookkeeper-stats/pom.xml
- pom.xml
- stream/distributedlog/pom.xml
change the doclint configuration in pom.xml 
when you clone the project there is always warning in IntelliJ IDEA
change the doclint configuration in pom.xml  according to https://stackoverflow.com/questions/52547306/maven-javadoc-plugin-not-accepting-additionalparam-xdoclintnone-additionalpa
> fix maven-javadoc-plugin configuration.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- pom.xml
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
-Updated netty,netty-boringssl and rocksdb to latest version for aarch64 support
-Updated deprecated methods of rocksdb to remove compilation warning and resolve build failure of bookkeeper-server on amd64 and aarch64 platforms as Werror flag is enabled.
Build of the bookkeeper-server package was failing on amd64 and aarch64 platforms.
There are many methods that are marked deprecated in rocksdb, but in use by bookkeeper package.
So updated those methods in bookkeeper package according to current rocksdb implementation.
Also updated netty,netty-boringssl and rocksdb to latest version as they are having aarch64 support.
Master Issue: #2378
> Updated netty,netty-boringssl and rocksdb

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Cookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/ZKRegistrationClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/BookieSocketAddress.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/SimpleBookieServiceInfoProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/AdminCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/GenerateCookieCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/AdvertisedAddressTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieShellTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/UpdateCookieCmdTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperAdminTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestGetBookieInfoTimeout.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/UpdateLedgerCmdTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/UpdateLedgerOpTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
- conf/bk_server.conf
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/AdminCommandTest.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/GenerateCookieCommandTest.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/GetCookieCommandTest.java
This is the bookie side implementation of BP-41
- add new `bookieId` configuration option
- implement Bookie#getBookieId
- add test cases
- make all BookKeeperClusterTestCase to use a random UUID as bookieId in order to increase code coverage
- add useUUIDasBookieId flag to BookKeeperClusterTestCase for test cases that require using hostname:port
- add a default BookieServiceInfo provider in tests
- enable Auditor to use BookieId and not BookieSocketAddress.toBookieId()
- use BookieId for LocalTransport addresses
- in Cookie.java rename BookieHost to BookieId (only in Java code, no data format changes)
Master Issue: #2396
> BP-41 make bookieId configurable

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
Descriptions of the changes in this PR: 
- Fix potential NullPointerException when local book keeper stop on exit.
> Fix potential NullPointerException when local book keeper stop on exit

- NOTICE
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
Changes:
- update Copyright reference year to 2020 in main NOTICE file and in templates for the binary distributions
> Update Copyright year to 2020 in NOTICE files

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- site/_data/cli/shell.yaml
bookie format redundant clean ledgerDirs and indexDirs
> fix #2416 bookie format redundant clean ledgerDirs and indexDirs

- Jenkinsfile
- create a Jenkinsfile configuration
- the file is copied from Andor Molnar's work on Apache ZooKeeper project
This will run the tests on JDK8 and JDK11 for every active branch on the repository
> Create a Jenkinsfile to configure new ASF CI env

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeper.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ForceLedgerOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerLayout.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClientImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/DefaultPerChannelBookieClientPool.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClientPool.java
- site/docs/4.10.0/api/ledger-api.md
- site/docs/4.11.0/api/ledger-api.md
- site/docs/4.11.1/api/ledger-api.md
- site/docs/4.8.0/api/ledger-api.md
- site/docs/4.8.1/api/ledger-api.md
- site/docs/4.8.2/api/ledger-api.md
- site/docs/4.9.0/api/ledger-api.md
- site/docs/4.9.1/api/ledger-api.md
- site/docs/4.9.2/api/ledger-api.md
- site/docs/latest/api/ledger-api.md
Rename the method name:
```
PerChannelBookieClientPool#initialize
LedgerHandle#isWriteSetWritable
```
And some typos.
> Issue 2425: Typo for method name

- site/bps/BP-42-new-api-list-ledgers.md
The new Client API (org.apache.bookkeeper.client.api.BookKeeper) aims to replace obsolete BookKeeper API but some features are not implemented yet, like the functionalities provided by BookKeeperAdmin.
For example, it does not expose a method to list available ledgers, comparable to BookKeeperAdmin#listLedgers().
low.
- Ledgers listing
- Simpler access to LedgerMetadata
- Ledger id inside LedgerMetadata
Master Issue: #2422
> ---
>
> ---
>
> If …
> BP-42: new api list ledgers

- stream/clients/python/bookkeeper/common/router/router.py
- stream/clients/python/scripts/test.sh
- stream/clients/python/setup.py
Require a grpcio version that is minor of 1.28. This allow to install the 1.27.2 that has a pre-compiled wheel for python 3.8 on mac os.
Add tests for python 3.8
grpcio 1.25.0 does not allow the installation using python 3.8 on mac os x. This is due to the fact that the pre-compiled wheels have not been published before 1.26.0
Updated the setup.py to relax a bit the requirement for grpcio
Add python3.8 as tested version
Updated the setup.py to install the latest pymmh3 version. **Note**: master tests are broken, I've updated the library and removed the 'signed' parameter that does not exists not anymore.
cc @eolivelli 
> ---
> In order to uphold a high standard for quality for code contributions, Apache …
> ISSUE 2377 : Relax grpcio requirement for python client to support python3.8 on mac os

- docker/Dockerfile
- docker/README.md
- docker/docker-compose.yml
- docker/scripts/entrypoint.sh
- docker/scripts/healthcheck.sh
- tests/docker-images/current-version-image/Dockerfile
- Update "master" docker image to BK 4.11.0
- Update to OpenJDK11 the main Docker image and the Docker image used for integration tests
- We are not using "JRE" because it does not bundle jshell and our script detects the presence of JDK11+ from the presence of file "jshell"
Master Issue: #2387
> Update to OpenJDK11 in Docker image

- bin/common.sh
- Use 'lib/modules' in order to detect a modern JDK
- With this change we can detect both JDK and JRE
> Detect Java 11 JRE and not only JDK

- docker/hooks/build
Fixes #2445 by not overriding BK_VERSION variable in case of "latest" tag
> Issue 2445: Builds of Docker tag bookkeeper:latest are failing

- docker/Dockerfile
- docker/README.md
- docker/docker-compose.yml
- docker/hooks/build
- docker/scripts/entrypoint.sh
- docker/scripts/healthcheck.sh
- Fix Java 11 Path in Dockerfile
- Allow to overwrite JAVA_HOME in entrypoint.sh and healthcheck.sh
> Fix JAVA_HOME in Dockerimage and allow it to be overwritten

- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ListUnderReplicatedCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ToggleCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/FormatUtil.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/LastMarkCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListActiveLedgersCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListFilesOnDiscCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListLedgersCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadJournalCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLedgerCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLogCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLogMetadataCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/EndpointInfoCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/InfoCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/ListBookiesCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/RecoverCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/DeleteLedgerCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/LedgerMetaDataCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/SimpleTestCommand.java
In order to have an audit log of all user interactions, all print statements which come from such interactions need to be logged.
We have two user driven ways to mutate BookKeeper:
* BookieShell
* bkctl
Both internally use the same code from `tools/cli`
The logging in the code was inconsistent. At times we used `System.out.println` and at times we used `LOG.info`.
As a part of this work item we change these in the following way:
* For every `cli` class, confirm if a Logger object is present, if not create one.
* Convert all `System.out.println()` -> `LOG.info()`
* Convert all `System.err.println()` -> `LOG.error()`
BookieShell uses `log4j.shell.properties`
bkctl uses `log4j.cli.properties`
Both log4j property files have `CONSOLE appenders`, so the like previous `System.out.println()`, the …
> BP-40: Convert all System.*.print statements to LOG.* statements

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultBookieAddressResolver.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/ZKRegistrationClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/Main.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/helpers/CommandHelpers.java
BP-41 introduces the new bookieId concept, and tools have to be improvement in order to provide better user experience.
- Fix NPE while shutting down the ZKRegistration client no function impact)
- Clean up logs in general
- Print "bookieId" instead of Bookie Address in "bin/bkctl bookies list" command
- Print bookieId at Bookie startup (using standard scripts)
> BP-41 Cleanup tools logs

- pom.xml
protoc-gen-grpc-java is part of grpc libraries.
Usually it doesn't make sense to use a version other
than the current grpc version. Currently 2 different versions are used.
It seems that it has been forgotten to upgrade protoc-gen-grpc-java.version 
when grpc.version has been upgraded from 1.12.0 to 1.18.0
Make protoc-gen-grpc-java.version match grpc.version by referencing it with ${grpc.version}
> Make protoc-gen-grpc-java.version match grpc.version

- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/tls-tests.yml
Currently a single user can cause the Github Actions / Workflows based CI to get overloaded when commits are pushed to a PR branch frequently, one by one. To mitigate this issue, cancel any previous Github Actions runs that are not completed for a given workflow,  for a particular branch / PR. This can be achieved by using the https://github.com/marketplace/actions/cancel-workflow-action .
[There are multiple cancel actions available](https://github.community/t/github-actions-cancel-redundant-builds-not-solved/16025/22). This particular one was picked based on its popularity.
Append each workflow with the cancel workflow action step.
A similar change was made in Pulsar CI in PR https://github.com/apache/pulsar/pull/8393
> [Build] Use Cancel workflow action to cancel outdated PR build jobs

- bookkeeper-proto/src/main/proto/DbLedgerStorageDataFormats.proto
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDescriptor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDescriptorImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/TransientLedgerInfo.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ExplicitLacTest.java
DbLedgerStorage does not persist "ExplicitLAC" on RocksDB, so when you restart a Bookie the information is lost.
This work can be considered a follow up of @reddycharan  work at #1527
- persist ExplicitLAC on DBLedgerStorage
- save ExplicitLAC on RocksDB (it is an optional field, so this change is backward compatible)
- enable testExplicitLACIsPersisted test even for DBLedgerStorage
- on TransientLedgerInfo rewind the ByteBuf in order to be able to use it again while writing to RocksDB
- use computeIfAbsent in getOrAddLedgerInfo (code clean up, but code looked strange, probably subject to some possible race condition)
Master Issue: #1533
> Issue 1533: DbLedgerStorage does not persist ExplicitLAC: Information (Header) of TransientLedgerInfo is not persisted

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
In certain circumstances, all AR processes were running but not performing any replication. Thus ledgers remain under-replicated for periods more than the threshold defined by our monitoring system. The reason is that the latch here gets countdown only under certain condition.
Ensure that countdown latch is released for any ZK event. Also log the zk event.
Master Issue: #2302
> Autorecovery may hang indefinitely when zookeeper connection blips

- bookkeeper-server/src/main/java/org/apache/bookkeeper/zookeeper/ExponentialBackOffWithDeadlinePolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/zookeeper/TestRetryPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/zookeeper/TestZKClientBoundExpBackoffRP.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/zookeeper/TestZKClientExpBackoffWithDeadlineRP.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/zookeeper/TestZooKeeperClient.java
Current retry backoff policy is truly exponential, hence retries are spaced out at large intervals. There is maxBackOff time that limits it, but it doesn't have a concept of deadline. Hence, applications with shorter SLA's have issues dealing with ZK failures and recovering from it.
The new policy introduces an aggressive retry mechanism with the backoff constants as less exponential. The deadline ensures that we retry at least once at the deadline. The stack trace would indicate the operation at risk.
This doesn't update the product code, which is still in testing. I am splitting PR's for for sake of reviews.
> Introduce new retry policy for metadata operations

- bookkeeper-server/src/main/java/org/apache/bookkeeper/zookeeper/ZooKeeperClient.java
Currently, we wait for `sessionTimeoutMs` before initiating a new zk cnxn. Session expiry is recevied only
when zk quprum is in a healthy state and can acquire a quorum to expire a session.
All other connection loss retries happen at zk client library transparently.
There is not much benefit waiting at BK client level.
Updated the values for backoff and maxbackoff to 0 seconds.
> ZookeeperClient should retry instantly on zk session expiry

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
Protobuf serialization is the last step of the netty pipeline. Currently, we allocate a heap buffer while serializing
and pass it down to netty library. In `AbstractChannel#filterOutboundMessage()`, netty copies that data to a direct buffer if
it is currently in heap (otherwise skips it and uses it directly).
This change helps in reducing unncessary CPU cycles for buffer copies and also helps alleviate pressure off the GC, since there is
less churn of memory. In some stress tests, I see a reduction upto 33% in number of GC's with the same avg running duration in BK Client.
The workload does writes of different sizes, ranging from 1 KB to 512 KB.
Bookies aren't usually CPU bound. This change improves READ_ENTRY code paths by a small factor.
Used …
> Protobuf should be serialized to direct memory instead of heap memory

- tests/docker-images/current-version-image/Dockerfile
You can easily build locally a docker image regarding the "current" version, that is the code that you have currently on your git repository using these commands:
```
mvn clean install -DskipTests
mvn install -f tests/docker-images/current-version-image/pom.xml -DintegrationTests
```
```
docker run --network=host zookeeper:latest
```
```
docker run --network=host --env BK_zkServers=localhost:2181 --env BK_bookieId=bk1 --env BK_allowLoopback=true --env BK_bookiePort=3181 apachebookkeeper/bookkeeper-current
```
but in current master, after the first switch to JDK11 the Dockerfile of the "apachebookkeeper/bookkeeper-current" is broken and points to a broken path for the JAVA_HOME env entry.
Change the default JAVA_HOME to the good path
> Fix Default Java Home in apachebookkeeper/bookkeeper-current image

- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/tls-tests.yml
Fixes "Transfer failed for https://repo.maven.apache.org/...
.jar: Connection reset" type of failures in Github Flows environment such as
```
Error:  Failed to execute goal on project bookkeeper-common: Could not resolve dependencies for project org.apache.bookkeeper:bookkeeper-common:jar:4.12.0-SNAPSHOT: Could not transfer artifact org.jctools:jctools-core:jar:2.1.2 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/jctools/jctools-core/2.1.2/jctools-core-2.1.2.jar: Connection reset -> [Help 1]
```
Set `maven.wagon.httpconnectionManager.ttlSeconds` to 25 seconds.
Besides this, set `maven.wagon.http.retryHandler.count` to 3 retries.
https://issues.apache.org/jira/browse/WAGON-545
contains a recommendation "Azure users shall …
> Limit maven http connection pool TTL in Github flows

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultSpeculativeRequestExecutionPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ZooKeeperClusterUtil.java
- bookkeeper-stats-providers/codahale-metrics-provider/src/main/java/org/apache/bookkeeper/stats/codahale/CodahaleMetricsProvider.java
- pom.xml
- stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/utils/RpcUtils.java
- stream/common/src/main/java/org/apache/bookkeeper/common/util/ListenableFutures.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/BKLogSegmentWriter.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestRocksdbKVAsyncStore.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestRocksdbKVStore.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/mvcc/TestMVCCStoreImpl.java
- tools/framework/src/main/java/org/apache/bookkeeper/tools/framework/Cli.java
- Upgrade Guava to 30.0.jre (see https://github.com/google/guava/releases)
- adapt code, as Futures.addCallback(3-args) has been removed (see https://github.com/google/guava/commit/dfb00017144bf48c408bc4cfcebadc0a0498dc73)
> Upgrade Guava to 30.0-jre

- site/docs/4.10.0/admin/metrics.md
- site/docs/4.11.0/admin/metrics.md
- site/docs/4.11.1/admin/metrics.md
- site/docs/4.5.0/admin/metrics.md
- site/docs/4.5.1/admin/metrics.md
- site/docs/4.6.0/admin/metrics.md
- site/docs/4.6.1/admin/metrics.md
- site/docs/4.6.2/admin/metrics.md
- site/docs/4.7.0/admin/metrics.md
- site/docs/4.7.1/admin/metrics.md
- site/docs/4.7.2/admin/metrics.md
- site/docs/4.7.3/admin/metrics.md
- site/docs/4.8.0/admin/metrics.md
- site/docs/4.8.1/admin/metrics.md
- site/docs/4.8.2/admin/metrics.md
- site/docs/4.9.0/admin/metrics.md
- site/docs/4.9.1/admin/metrics.md
- site/docs/4.9.2/admin/metrics.md
- site/docs/latest/admin/metrics.md
Fixes #1979 
The link for `Metrics` is broken. However, the `Metrics` file is empty. Therefore, I temporarily removed the link in all versions. The same problem happened to `configuration parameters`.
I closed pr #2386 as it brought changes from the master instead of a new branch.
> ISSUE #1979 Metrics link missing

- site/docs/4.10.0/development/protocol.md
- site/docs/4.10.0/getting-started/concepts.md
- site/docs/4.11.0/development/protocol.md
- site/docs/4.11.0/getting-started/concepts.md
- site/docs/4.11.1/development/protocol.md
- site/docs/4.11.1/getting-started/concepts.md
- site/docs/4.9.0/development/protocol.md
- site/docs/4.9.0/getting-started/concepts.md
- site/docs/4.9.1/development/protocol.md
- site/docs/4.9.1/getting-started/concepts.md
- site/docs/4.9.2/development/protocol.md
- site/docs/4.9.2/getting-started/concepts.md
- site/docs/latest/development/protocol.md
- site/docs/latest/getting-started/concepts.md
fix #2408 
1. fix documentation concept part about default ledger manager.
2. fix documentation protocol part about  missing Qw value.
> ---
>
> ---
>
>
>     `<BP-#>: Description of bookkeeper …
> Issue 2408: [documentation] fix default ledger manager and Qw value in documentation

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieShellTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/ForceAuditorChecksCmdTest.java
Reset the last run time for auditor checks. Reboot auditor leader immediately to trigger the checks. This is mostly used for testing infra and get the sanity check of a cluster on demand.
Added a new shell command and tests
> Add Add ForceAuditChecksCmd to reset auditor checks last run time

- docker/Dockerfile
- site/_config.yml
- site/releases.md
the link in site/releases.md is not updated, this is to fix the issue.
update the version in [docker/Dockerfile](https://github.com/apache/bookkeeper/blob/master/docker/Dockerfile).
> [release 4.12.0] fix version 4.12 after release

- pom.xml
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/cluster/ZkClusterMetadataStore.java
Curator 5.x support ZooKeeper 3.6.x.
This change is needed to able the upgrade of Pulsar to ZooKeeper 3.6.2 
Upgrade Curator
> Upgrade to Curator 5.1

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerCreateOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeperTestCase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/api/BookKeeperBuildersTest.java
If you have a very small cluster, 3 bookies, you must use **2-2-2** as replication parameters in order to guarantee durability and tolerate the failure of at least one bookie.
With this situation you cannot leverage the striping feature of BookKeeper, when **ensembleSize > writeQuorumSize**.
With striping you can distribute your data among all of the bookies, and use better the available disk space.
You can also exploit the ability to write to/read from more disks (bookies) in parallel, achieving better overall performances.
With this change we introduce a new client option "opportunistic striping", that basically tells to the BK client to use as much bookies as configured in the ensembleSize parameter in the best case scenario, and to use less and less bookies, up to the configured …
> Opportunistic Striping

- conf/standalone.conf
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/StorageServer.java
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/StreamStorageLifecycleComponent.java
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/service/BookieService.java
When you run "bin/bookkeeper standalone" the server does not publish BP-38 endpoint info.
This way you cannot use bookieId (BP-41).
Fix BookieService in "standalone" package, that is very like to the BookieService in "bookkeeper-server".
The code cannot be reused, even if the name is similar the overall design of the class hierarchy is different.
> Publish BP-38 BookieEndpointInfo for BookKeeper Standalone mode

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerCreateOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeperTestCase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/api/BookKeeperBuildersTest.java
If you have a very small cluster, 3 bookies, you must use **2-2-2** as replication parameters in order to guarantee durability and tolerate the failure of at least one bookie.
With this situation you cannot leverage the striping feature of BookKeeper, when **ensembleSize > writeQuorumSize**.
With striping you can distribute your data among all of the bookies, and use better the available disk space.
You can also exploit the ability to write to/read from more disks (bookies) in parallel, achieving better overall performances.
With this change we introduce a new client option "opportunistic striping", that basically tells to the BK client to use as much bookies as configured in the ensembleSize parameter in the best case scenario, and to use less and less bookies, up to the configured …
> [Backport] Opportunistic Striping

- docker/README.md
Fix typo for `ledgers` directory
Typo in the documentation that can leads to issue (data not persistent across docker restarts)
Fix typo (added the `s` to `ledgers`)
Master Issue: #2437 
> ---
>
> ---
>
>
> - [ ] Attach the master issue link in the description …
> Issue 2437: Fix typo in ledgers data directory for Docker

- site2/docs/getting-started.md
- site2/website/pages/en/index.js
- site2/website/sidebars.json
This PR introduces changes for adding the sidebar to the new docusaurus based website.
The #2426 Pull Request introduced the changes for new docuasurus based website, However the new website still do not have sidebar similar to our current website. This PR introduces changes for adding the missing sidebar.
Added link to the getting-started README in the _sidebars.json_.
Master Issue: #2451 
I have build the changes locally and have verified that the sidebar is getting rendered properly. Here is the screenshot of the new sidebar -
> ISSUE #2451: Add sidebar to the documentation page

- bookkeeper-benchmark/pom.xml
- bookkeeper-dist/all/pom.xml
- bookkeeper-dist/server/pom.xml
- bookkeeper-server/pom.xml
- pom.xml
- stream/bk-grpc-name-resolver/pom.xml
- stream/distributedlog/core/pom.xml
- stream/distributedlog/io/dlfs/pom.xml
- tests/integration-tests-utils/pom.xml
- upgrade ZooKeeper dependency
- add explicit dependency on Snappy Java, needed by ZooKeeper Server
Please note that ZooKeeper server also needs Drop Wizard Metrics Core, but we are already bundling it
> Upgrade ZooKeeper to 3.6.2

- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/service/HttpService.java
- conf/standalone.conf
- stream/server/pom.xml
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/StorageServer.java
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/service/BookieService.java
- when you launch "bookkeeper standalone" service the system does not take into account the HTTP Server configuration
- the HTTP Server is important because it allows to use the HTTP API https://bookkeeper.apache.org/docs/latest/admin/http/
- the standalone service is very useful when you are working on client applications (like BKVM)
- consider HTTP server configuration in 'bin/bookkeeper standalone' command
- add default example configuration
- add VertxHttpServer to dependencies of Standalone Module
- the change is basically a copy and paste of this part of Main.java, but applied to the Main class of the Standalone Starter, which is a separate code: https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/server/Main.java#L327
After this …
> Start HTTP Server in Bookie Standlone Mode

- conf/bk_server.conf
- site/_data/config/bk_server.yaml
Fixes #2500 
The dbStorage_writeCacheMaxSizeMb configuration is not described clearly.
Refine the description in the broker.conf file.
> [docs] Update dbStorage_writeCacheMaxSizeMb configuration description

- site/docs/4.12.0/admin/autorecovery.md
I recently started using Apache Bookkeeper as part of my Apache Pulsar cluster. In learning some of the operational tasks related to managing the bookies and autorecovery, I noticed a few places where the documentation could be improved.
The changes are all to the `AutoRecovery.md` file for version 4.12.0. They might apply to earlier versions, but I'm not sure how documentation updates are handled. My first change is to explicitly mention the way to turn off the AutoRecovery daemon on the bookie nodes. This configuration was not obvious to me as a new user of the project, and I accidentally had recovery workers running on all nodes. (Regarding that, I mention in the PR that it is possible to run the process on bookie and autorecovery nodes. Perhaps …
> Add Some Clarifications to the AutoRecovery Documentation

- stream/server/pom.xml
With the upgrade to ZooKeeper 3.6.2 the two dependencies "snappy java" and "metrics-core" are to be explicitly added at runtime in order to make the ZooKeeper server work.
This fix is for "bin/bookkeeper standalone", that is not working anymore
Related commit that broke "standalone" mode:
https://github.com/apache/bookkeeper/commit/79cbf19a449a2dc96745fc563a489375b0846a09
How to verify this change:
- on current master "bin/bookkeeper standalone" does not work
- on this branch it works
> BookKeeper Standalone does not work after ZK upgrade - missing third party deps

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeper.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/TopologyAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ZoneawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/AbstractDNSToSwitchMapping.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/DNSToSwitchMapping.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/StaticDNSResolver.java
In order to allow Pulsar to leverage BookieId with custom Bookie-To-Rack Mapping (ZkBookieRackAffinityMapping) we need to inject the BookieAddressResolver into it.
There is not way to do it currently because it is created by the BookKeeper client, and we have to inject the same BookieAddressResolver used by the client itself.
*Changes*
- add new setBookieAddressResolver method (use 'default' methods in order to preserve backward compatibility
- call the new method in every point in which we instantiate a DNSToSwitchMapping and when we receive an instance at construction time
*Compatibility*
- this change is 100% compatible with previous versions
> Allow DNSToSwitchMapping to access BookieAddressResolver

- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/tls-tests.yml
Currently we are not running PR validation for Pull Requests against release branches (as branch-4.12).
Also we are not running tests on master branch and we do not have Jenkins anymore
- Enable PR validation for pull requests against all release branches
- Enable GitHub actions on "push"
> Activate GitHub Actions on all PRs and on push

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- pom.xml
- tools/framework/src/main/java/org/apache/bookkeeper/tools/framework/Cli.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/CreateCookieCommandTest.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/GenerateCookieCommandTest.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/UpdateCookieCommandTest.java
Certain bookkeeper shell commands when bookkeeper is bundled with pulsar because of conflicting jcommander versions
Updates jcommander to 1.78, same as pulsar.
Master Issue: #2522
> Issue 2522: Update jcommander from 1.48 to 1.78

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultBookieAddressResolver.java
The exception is managed with a fallback, printing the stacktrace would be misleading
- Changed log level from info to debug for the log line
- Removed the exception from the log line
Master Issue: #2531
> 2531: Fix noisy stacktrace at boot

- README.md
- docker/README.md
There are some broken and obsolete archive links in the README. Update them to point to latest Documentation site.
Update the README to point to latest info of the project.
Update the links in the main and Docker README files to point to right information.
Master Issue:N/A
> Fix the broken links and links to archive pages from README files

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/api/LedgerMetadata.java
Minor change to the documentation of the `LedgerMetadata` interface.
Looking to improve the javadoc.
The javadoc references an entry when it should (I believe) reference a ledger.
> Fix javadoc for LedgerMetadata's method getAllEnsembles

- bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java
- bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/TestPrometheusMetricsProvider.java
- conf/bk_server.conf
- site/_data/config/bk_server.yaml
make prometheus bind addr can cofigure
For security, make prometheus bind addr can config.
For compatibility, make default value is 0.0.0.0
make prometheus bind addr can cofigure
> Allow to configure Prometheus HTTP Server bind address

- conf/bk_server.conf
- site/_data/config/bk_server.yaml
Fix the default value in `bk_server.conf`, sync with the default value in code.
For `readAheadCacheBatchSize` in code default value.
``` Java
private static final int DEFAULT_READ_AHEAD_CACHE_BATCH_SIZE = 100;
readAheadCacheBatchSize = conf.getInt(READ_AHEAD_CACHE_BATCH_SIZE, DEFAULT_READ_AHEAD_CACHE_BATCH_SIZE);
```
So, it should be 100 in `bk_server.conf` default configuration.
For `dbStorage_readAheadCacheMaxSizeMb` in code default value.
```Java
public static final String READ_AHEAD_CACHE_MAX_SIZE_MB = "dbStorage_readAheadCacheMaxSizeMb";
private static final long DEFAULT_READ_CACHE_MAX_SIZE_MB = (long) (0.25 * PlatformDependent.maxDirectMemory())
/ MB;
long readCacheMaxSize = getLongVariableOrDefault(conf, READ_AHEAD_CACHE_MAX_SIZE_MB,
DEFAULT_READ_CACHE_MAX_SIZE_MB) * MB;
```
So, it …
> fix default value in bk_server.conf, sync with code default value

- site/docs/latest/admin/autorecovery.md
Copying documentation updates for auto recovery from the `4.12.0` directory to the `latest` directory based on @eolivelli's request in https://github.com/apache/bookkeeper/pull/2507.
> Sync 4.12.0 autorecovery doc to lastest

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultBookieAddressResolver.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/helpers/CommandHelpers.java
When a bookie is down you can see many error both on command line tools and during replicator work.
Also the CLI is not working at all
```
This is the error on "bookkeeper shell listbookies" when a bookie is downb
org.apache.bookkeeper.client.BKException$BKBookieHandleNotAvailableException: Bookie handle is not available
at org.apache.bookkeeper.discover.ZKRegistrationClient.getBookieServiceInfo(ZKRegistrationClient.java:248) ~[org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
at org.apache.bookkeeper.client.DefaultBookieAddressResolver.resolve(DefaultBookieAddressResolver.java:43) [org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
at org.apache.bookkeeper.tools.cli.helpers.CommandHelpers.getBookieSocketAddrStringRepresentation(CommandHelpers.java:45) …
```
> Fix BookKeeper shell "list bookies" in case of downbookie and reduce noisy log during re-replication in case of down bookie

- docker/Dockerfile
- tests/docker-images/current-version-image/Dockerfile
Fix Docker image build for Bookkeeper.
This PR just makes sure that the `pip` version used in the Dockerfile is compatible with Python 2.7. We may need to consider cherry-picking this PR to branches of Bookkeeper that are not end-of-life. 
Master Issue: #2557
Signed-off-by: Raúl Gracia <raul.gracia@emc.com>
> Issue 2557: Bookkeeper docker image build fails because of deprecated Python version for pip

- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
Fixed tests for /stream, RocksDB initialization.
Same as https://github.com/apache/bookkeeper/pull/2551 but for master branch
Tests were failing with " “java.lang.UnsatisfiedLinkError: 'long org.rocksdb.LRUCache.newLRUCache(long, int, boolean, double)'”".
Fixed following suggestion form https://github.com/facebook/rocksdb/issues/6789
Added
`    static {
RocksDB.loadLibrary();
}`
to extract the native library from the jar file etc.
Master Issue: #2550
> ---
>
> ---
> …
> Fixed failing tests for /stream.

- stream/server/src/main/java/org/apache/bookkeeper/stream/server/StorageServer.java
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/StreamStorageLifecycleComponent.java
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/conf/StorageServerConfiguration.java
Allow stream storage to use hostname instead of IP address
issue #2559
Allowed use of the host name for the endpoint.
Changes by @cdbartholomew
Master Issue: #2559
> ---
>
> ---
>
>
> - [ ] …
> Allow stream storage to use hostname instead of IP address

- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/dlog/DLOutputStream.java
Fix SST File corruption during checkpointing
Since the SST files are shared among checkpoints, this will not be resolved by future checkpoints. We will fail to restore all future checkpoints that depend on this file.
The record is sent asynchronously. We need to use a copy of the passed buffer
in the record. The ownership is retained by the caller and will be potentially
changed by the caller. In case of corruption the later blocks were
overwriting the previous blocks resulting in corruption
Master Issue: #2563 
> ---
>
> ---
> Be sure to do all of the following to help us …
> Issue 2563: Fix SST file corruption.

- site/README.md
- site/css/style.sass
Since there will be some time before we get site2 up and running, sending
this fix to allow links in doc content ot be clickable.
Currently, if user go to https://bookkeeper.apache.org/docs/latest/ the links
in the doc can not be click since the div overlay of navigator on left is
covering the content body.
The simple proposed fix is to set width of navigator container class to
certain width to not cover the body content.
To verify behavior and proposed fix difference:
1. Go to https://bookkeeper.apache.org/docs/latest/ and try to click the `WAL` link. You will not see the cursor change to hand icon to click the link
2. Now, visit the proposed fix at https://hsaputra.github.io/bookkeeper-staging-site/docs/latest/, then when  you hover on top of `WAL` link you should see the cursor change …
> Fix the current site to allow click links in doc

- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksCheckpointer.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksdbCheckpointTask.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksCheckpointerTest.java
Allowed fallback to previous checkpoint, assuming that corrupt checkpoint means that checkpointing did not complete and the journal is intact.
Reliability and resilience of teh table service.
Allowed fallback to previous checkpoint, assuming that corrupt checkpoint means that checkpointing did not complete and the journal is intact.
Master Issue: #2565
> ---
>
> ---
>
>
> - [ ] Make sure the PR title is …
> Handling checkpoint corruption in case of bookie crash

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/ReadAheadEntryReader.java
Limit logged data
Overly long log line at ReadAheadEntryReader
Found a log with single log line of over 5 mil characters long
"org.apache.distributedlog.ReadAheadEntryReader - Starting the readahead entry reader for ..." + the details of ~16000 segments.
Output details of up to 10 segments plus count of segments.
Master Issue: #2561
> ---
>
> ---
>
>
> …
> Limit log output to prevent in case of the large group of the log segments

- stream/server/src/main/java/org/apache/bookkeeper/stream/server/StorageServer.java
Update how hostname is retrieved when using hostname as identifier for stream storage to work consistenly between Java 8 and Java 11.
Between Java 8 and Java 11, the value returned by `InetAddress.getLocalHost().getHostName()` changed from being the fully qualified name to just the short hostname. When running in a Kubernetes environment, it is necessary for the endpoint to be identied by its fully qualified name so that clients can connect. 
This same change was made in Pulsar in https://github.com/apache/pulsar/pull/6235.
I have tested this change in Kubernetes environment using Java 11.
This is a simple change from `getHostName` to `getCanonicalHostName()`.
Master Issue: #2559
> Stream storage endpoint from hostname to return fully-qualified name in Java 11+

- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCStoreImpl.java
Save latest revision in rocksdb.
Currently while restoring the complete transaction log is replayed. 
As the transaction log builds up over time, it takes longer and longer to restore the storage containers on a new pod.
Instead we will save the revision in the rocksdb. We will use the revision retrieved after
restoring the last checkpoint to skip ahead in the journal logs and only replay the entries
that are not included in the checkpoint
Master Issue: #2567 
> ---
>
> ---
> Be sure to do all of the following to help us incorporate your …
> Issue 2567: Save last revision in rocksdb

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/BKAsyncLogWriter.java
- stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/exceptions/WriteException.java
Added first exception as a rootcause for the WriteException
simplify troubleshooting
Added first exception as a rootcause for the WriteException
Master Issue: #2574
> ---
>
> ---
>
>
> - [ ] …
> fix: BKAsyncLogWriter swallows rootcause of the WriteException

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Cookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerMetadataSerDe.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorElector.java
- pom.xml
Upgraded protobuf dependency
unit tests log "WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil" on Java11
This has been fixed in protobuf since version 3.7
Upgraded protobuf; 
updated code to remove use of deprecated methods
Master Issue: #2579
> ---
>
> ---
>
>
>     `e.g. BP-1: 64 …
> Upgrade protobuf to 3.14.0 (latest)

- bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/RegistrationClient.java
Basic javadoc update from what looks to be an accidental copy from another javadoc.
I opened https://github.com/apache/bookkeeper/issues/2588 to clarify what the meaning of "all" is. Either way, I'm sure we just need to update the javadoc as I did in this PR.
If https://github.com/apache/bookkeeper/issues/2588 reveals something interesting, it might be worth updating this javadoc to include that information.
> Fix javadoc for getAllBookies in RegistrationClient interface

- .github/workflows/stream-tests.yml
- bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/ZKRegistrationClient.java
- stream/bk-grpc-name-resolver/src/main/java/org/apache/bookkeeper/grpc/resolver/BKRegistrationNameResolver.java
- stream/common/pom.xml
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestDistributedLogBase.java
- stream/tests-common/pom.xml
GrpcChannelsTest and BKRegistrationNameResolverTest fail in /stream
fix tests
BKRegistrationNameResolverTest failed because the bookieAddressResolver tried to use clientDriver before clientDriver's initialization. Fixed initialization order.
GrpcChannelsTest failed because of the grpc.netty-shaded conflict with unshaded grpc.netty
Picked up @eolivelli 's changes to run stream tests on CI
Master Issue: #2594
> ---
>
> ---
>
> If this PR is a …
> Fix failing test in /stream

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- pom.xml
Upgraded Dropwizard Metrics to 3.2.5, that is the same version used by ZooKeeper 3.6.2
Upgraded Dropwizard Metrics to the same version used by ZooKeeper 3.6.2 (and Pulsar 2.8)
pom + license files
Master Issue: #2599
> ---
>
> ---
>
>
> - [ ] Attach the master …
> Upgrading dropwizard to 3.2.5

- dev/release/000-run-docker.sh
Fixed the script/docker run command to mount to `/home/$USER` instead of mac-style `/Users/$USER`. 
`dev/release/000-run-docker.sh` failed to mount source dir (got empty dir instead), printed permissions errors like
```
mkdir: cannot create directory '/root': Permission denied
Can not write to /root/.m2/copy_reference_file.log. Wrong volume permissions? Carrying on ...
```
see above
> ---
>
> ---
>
>
> …
> Release script does not work on MacOs Big Sur

- docker/Dockerfile
Building the docker image does not work anymore, see #2601 
Add python3 to the list of available packages
cd docker
docker build --build-arg BK_VERSION=4.12.1 -t testbk .
Fixes #2601
> Fix docker image build - add python3

- NOTICE
Very simple fix to update the year in the NOTICE file to 2021.
Fixes #2624
> Issue 2624: Update the NOTICE file to 2021 for copyright.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/NetworkTopologyImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/net/NetworkTopologyImplTest.java
NetworkTopologyImpl#getLeaves(String scope) was returning set with null value, when requested scope did not exist.
I've added null check in NetworkTopologyImpl#doGetLeaves(String scope), used by NetworkTopologyImpl#getLeaves method to not have null node returned as leaf node.
It would be nice to have this merged also with non master branch of bookeeper so maintenance releases could have that fix.
I've found my Apache Pulsar cluster polluted with log:
```
12:01:46.462 pulsar2-dev pulsar-broker {"logLevel":"ERROR","logThread":"pulsar-io-23-1","logger":"org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl","message":"found non-BookieNode: null as leaf of defaultrack: /default-rack","stack_trace":null}
```
After digging I've found that, …
> Fix NetworkTopologyImpl#getLeaves returning set with null value in case of non existing scope

- site/bps/BP-43-gradle-migration.md
- site/community/bookkeeper_proposals.md
This PR is to submit proposal for migrating existing maven based build and release pipeline to a gradle based one.
Adding a new BP BP-43 for gradle migration. 
Master Issue: https://github.com/apache/bookkeeper/issues/2640
> BP-43: Gradle migration

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageTest.java
---
Fixes #2596
*Motivation*
The isForceGCAllowWhenNoSpace does not work for the DBLedgerStorage.
Currently, the behavior of the isForceGCAllowWhenNoSpace is It is a
disk listener to decide whether to start the compaction task while
the disk of the Ledger almost full. 
- Add dir listener for the SingleDirectoryDbledgerStorage
> Allow DBLedgerStorage to force GC by disk listener

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionTest.java
- conf/bk_server.conf
---
Master Issue: #2596
*Motivation*
Sometimes user will disable the entry log compaction to reduce the
I/O load. But we should allow forcing compact the entry even if
the entry log compaction is disabled.
- Add a configuration to allow force compaction
> Allow force compact entry log when disabling entry log compaction

- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/journal/AbstractStateStoreWithJournal.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/CheckpointInfo.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksCheckpointer.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestRocksdbKVAsyncStoreWithCheckpoints.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestRocksdbKVStoreCheckpoint.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestStateStore.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksCheckpointerTest.java
If a checkpoint is corrupted, checkpoint restoration will fail. Currently we will keep
retrying to restore the same checkpoint. The system will never recover from this.
The only way out is to manually remove the checkpoint from the zookeeper
When a checkpoint is corrupted, we need to try and restore from previous checkpoint.
This  is done recursively till we hit a checkpoint that works. If none of the checkpoints
work, we will fallback to a `nullcheckpoint` which will initialize rocksdb from scratch
and replay all state from journal.
Instead of just dealing with the latest checkpoint, we now return a list of checkpoints
ordered by age. We then simply walk this list and stop as soon as a checkpoint is
successfully restored. We currently only keep a single checkpoint,  but with this change …
> Handle corrupted checkpoints

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerRecovery2Test.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockClientContext.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockBookieClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockBookies.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockLedgerData.java
Adding the fencing flag to recovery reads avoids a data loss scenario as described in [issue 2614](https://github.com/apache/bookkeeper/issues/2614)
Added the fencing flag to recovery reads. Refactored some mocking unit test code to introduce fencing and allow two writers to share the same bookie state. Added a new unit to verify the fix. You can recreate the initial problem by removing the fencing flag from recovery reads and running the new unit test.
Master Issue: #2614
> Add fencing to recovery reads to avoid data loss issue

- docker/Dockerfile
- tests/docker-images/current-version-image/Dockerfile
Integration tests are failing because the URL for get-pip.py has changed: 
```
[INFO] + wget -q https://bootstrap.pypa.io/2.7/get-pip.py
[INFO] 
[INFO] + python get-pip.py
[INFO] 
[INFO] 
[INFO] Hi there!
[INFO] 
[INFO] The URL you are using to fetch this script has changed, and this one will no
[INFO] longer work. Please use get-pip.py from the following URL instead:
[INFO] 
[INFO]     https://bootstrap.pypa.io/pip/2.7/get-pip.py
[INFO] 
[INFO] Sorry if this change causes any inconvenience for you!
[INFO] 
[INFO] We don't have a good mechanism to make more gradual changes here, and this
[INFO] renaming is a part of an effort to make it easier to us to update these
[INFO] scripts, when there's a pip release. It's also essential for improving how we
[INFO] handle the `get-pip.py` scripts, …
```
> Fixed get-pip URL in Dockerfile

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- conf/bk_server.conf
For dbLedgerStorage, it will initiate an RocksDB instance for each ledger directory. However, for each RocksDB instance, it will set defaultRocksDBBlockCacheSizeBytes to  10% of direct memory. If we configured multi ledger directories and default dbStorage_rocksDB_blockCacheSize, the direct memory will be exhausted and cause Out Of Memory Error(OOM)
1. Change default dbStorage_rocksDB_blockCacheSize to 10% / numberOfLedgers of direct memory.
> adjust default rocksDbBlockCache size to 10%/numberOfLedgers of direct memory

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
Fixes https://github.com/apache/bookkeeper/issues/2622.
This PR only affects metrics. Specifically, it improves the usage of `JournalQueueSize` and `JournalCbQueueSize` (including `bookie_journal_JOURNAL_QUEUE_SIZE` and `bookie_journal_JOURNAL_CB_QUEUE_SIZE`).
As mentioned in the issue, `bookie_journal_JOURNAL_CB_QUEUE_SIZE` grows unbounded. This PR looks to fix that, and in doing so, fixes `bookie_journal_JOURNAL_QUEUE_SIZE` as well.
The `bookie_journal_JOURNAL_CB_QUEUE_SIZE ` grows unbounded because it is never decremented. Ideally, it would measure the number of call backs outstanding for the Journal. I've updated the `Counter` object that is passed into the `QueueEntry` class so that the `Counter` is the one for the call back queue size. In …
> Issue 2622: Fix usage of JournalQueueSize and JournalCbQueueSize; JournalCbQueueSize should be bounded

- stream/proto/src/main/proto/kv_store.proto
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/StorageServer.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/api/StateStoreSpec.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/RocksUtils.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/CheckpointFile.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/CheckpointInfo.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksCheckpointer.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksdbCheckpointTask.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksdbRestoreTask.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestRocksdbKVAsyncStoreWithCheckpoints.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestStateStore.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksCheckpointerTest.java
- stream/storage/api/src/main/java/org/apache/bookkeeper/stream/storage/conf/StorageConfiguration.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/store/MVCCStoreFactoryImpl.java
- stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/store/MVCCStoreFactoryImplTest.java
Normally the SST file are immutable. A SST file from previous checkpoint can
be reused in subsequent checkpoints. This fact is used to avoid unnecessary
upload of SST files.
However there are scenarios in which just the name comparison doesn't work.
It is possible that the checkpoint process doesn't complete (due to
crash/restart). In such cases the stale SST files are left behind. When the
storage container is restarted, it will be correctly restored from previous
checkpoint. When we do a checkpoint on this new state, a new SST files
are created. Since we only compare the SST file names, we assume that files is
already available in the checkpoint store.
At best the size of the new files will mismatch, and restore will fail. But if
the size of the files match, restore will succeed and we …
> Add checksum validation for SST files

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessor.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ReadEntryProcessorTest.java
- conf/bk_server.conf
When bookie is doing reads, it may use a considerable amount of memory if there are many simultaneous readers and especially when the network becomes the bottleneck.
The problem is that the read thread is scheduling the async operation to write on the socket and then it moves on for the next read operation. If the TCP window is full, these write requests on the socket are just piling up in memory, resulting in a spike of direct memory usage, which may exceed the max configured in the JVM.
Instead, if the socket write operation is blocking, we should block the BK read thread in order to auto-throttle and limit the amount of memory. 
This change does not introduce any performance penalty on the read-path. The old behavior will still be available as a config option.
> Auto-throttle read operations

- pom.xml
- 1.18.18 includes fixes for IDE compatibility (IntelliJ, Eclipse, Netbeans).
This is relevant while developing Bookkeeper.
- see https://projectlombok.org/changelog for more details
Upgrade Lombok version from 1.18.10 to 1.18.18
> Upgrade Lombok version

- dependencies.gradle
- settings.gradle
- stream/api/build.gradle
- stream/common/build.gradle
- stream/server/build.gradle
- stream/storage/api/build.gradle
- tests/docker-images/statestore-image/Dockerfile
- tests/docker-images/statestore-image/bin/bkctl
- tests/docker-images/statestore-image/bin/bkperf
- tests/docker-images/statestore-image/bin/bookkeeper
- tests/docker-images/statestore-image/conf/log4j.cli.properties
- tests/docker-images/statestore-image/conf/log4j.properties
- tests/docker-images/statestore-image/conf/log4j.shell.properties
- tests/docker-images/statestore-image/image_builder.sh
- tests/integration/cluster/build.gradle
- tests/integration/smoke/build.gradle
- tests/integration/standalone/build.gradle
- tools/framework/build.gradle
- tools/ledger/build.gradle
- tools/ledger/src/main/resources/META-INF/services/org.apache.bookkeeper.tools.framework.CommandGroup
- tools/perf/build.gradle
- tools/stream/build.gradle
- tools/stream/src/main/resources/META-INF/services/org.apache.bookkeeper.tools.framework.CommandGroup
Migrate bookkeeper to gradle. 
- Build BKCTL and generate artifacts 
- Build docker image from the jar created from existing source and run integration tests.
- A Dockerfile which will build docker image from existing source.
- A Shell file which will generate all the artifacts for building Docker image
- All build.gradle files to build and run integration tests.
Master Issue: #2640 
./gradlew :tests:integration:cluster:test
` Task :tests:integration:cluster:buildImage
#1 [internal] load build definition from Dockerfile
#1 sha256:13c696b34811c50ef1582dd1c27e59e8cf726660222ada83feb0b294a4197b14
#1 transferring dockerfile: 37B 0.0s done
#1 DONE 0.0s
#2 [internal] load .dockerignore
#2 sha256:028ece09d81436333eece58b183b9dc0a52cbc28bf2d07cfad5f3080e03d38b7
#2 transferring context: 2B done
#2 …
> ISSUE-2640: BP-43: Run integration tests with current source code.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- site/_data/cli/shell.yaml
The arguments in the bookie shell documentation and help are incorrect.
In the past, the `recover` command required two arguments, `bookieSrc` and `bookieDest`, but now there is only one, `bookieSrc`.
https://github.com/apache/bookkeeper/commit/dad7e2ce0d1cf8f04c7e2f128900ea69792c948d#diff-981f006571d24dbcd1538399a5974163e7550e20bf7b49622b5a624d93fb40ceL305
In addition, we can specify multiple `bookieSrc`, but the delimiter is "," instead of ":".
https://github.com/apache/bookkeeper/blob/b1e602afc93cfd6299c43f99d26c9a6b7bcd27a7/bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/RecoverCommand.java#L125
> [Doc] Correct the argument of the recover command of bookie shell

- bin/bookkeeper
Bookkeeper script is failing to start. The variable is not being interpreted as a string. Instead we trying to run this as command and failing.
```
$ ./bin/bookkeeper localbookie 3
JAVA_HOME not set, using java from PATH. (/usr/bin/java)
./bin/bookkeeper: line 149: BOOKIE_EXTRA_OPTS: command not found
./bin/bookkeeper: line 149: -Dorg.bouncycastle.fips.approved_only=true: command not found
```
Add quotes around the variable definition.
> Fix a typo in bookkeeper script

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/GarbageCollectorThreadTest.java
The compaction status report is off by 1. 
When compaction is enabled, the 10% log is always empty. Setting the compaction threshold to .2 we were seeing the number of compacted entrylogs that were removed, match the sum of the 20% and 30% buckets. While the 10% bucket remained empty. Increasing the threshold to .3 we would see the sum of the first 4 buckets compacted (10%-40%). Also with the 10% bucket empty. 
Upon inspection of the code, the code is using the .ceil function to calculate the bucket index to be updated. This means that 10% bucket will never be used. However, there could be a rare 100% case in which the code runs into a index out of bounds exception when the entrylog is actually 100% used.  The index calculation should be using floor and not the ceil call using the next …
> Defect-Fix Compaction status report into correct buckets.

- build.gradle
Migrate bookkeeper build to gradle. The published artifacts need to be signed.
Add signing plugin to sign published artifacts. For details see
https://docs.gradle.org/current/userguide/signing_plugin.html
This was testing by publishing to local maven repository:
```
$ gradlew bookkeeper-server:publishMavenPublicationToMavenLocal
$ ls -ln ~/.m2/repository/org/apache/bookkeeper/bookkeeper-server/4.14.0-SNAPSHOT/
total 10568
-rw-r--r--  1 501  20  1596624 Mar 31 13:07 bookkeeper-server-4.14.0-SNAPSHOT-tests.jar
-rw-r--r--  1 501  20      650 Mar 31 13:07 bookkeeper-server-4.14.0-SNAPSHOT-tests.jar.asc
-rw-r--r--  1 501  20  2254279 Mar 31 13:07 bookkeeper-server-4.14.0-SNAPSHOT.jar
-rw-r--r--  1 501  20      650 Mar 31 13:07 bookkeeper-server-4.14.0-SNAPSHOT.jar.asc
-rw-r--r--  1 501  20 …
```
> ISSUE-2640: BP-43: gradle build: sign published packages

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/conf/TestServerConfiguration.java
- conf/bk_server.conf
This resolves issue 2638, by allowing a customer to set a limit on the duration of the major and minor compaction runs. This allows the customer to balance the needs for compaction against the need for normal garbage collection. Unbounded execution of compaction can starve the garbage collection process, and may lead to extended periods of high disk IO. By setting a upper bound on the execution duration for the garbage collection, we can ensure a balance is maintained between both GC and Compaction processes. 
Logging has been improved to allow a user to see the complete usage of the buckets, vs. those that were compacted, so that they can decide on any further tuning that may be required. 
Test cases have been added to ensure limits are enforced properly and that defaulting of the values …
> Issue 2638: Compaction Limits

- tests/integration/smoke/build.gradle
**Migrate bookkeeper to gradle.**
Current smoke tests in OSS do not run and do not do anything useful. 
They are quite old and need to move to testcontainer and away from Arquallian. 
That requires code change. Therefore punting running these tests with gradle too, 
until everything moved to gradle. 
Exclude Smoke tests from run.
> ISSUE-2640: BP-43: Exclude smoke tests for now can be enabled when we move to gradle.

- build.gradle
- buildtools/src/main/resources/bookkeeper/checkstyle.xml
- buildtools/src/main/resources/bookkeeper/suppressions.xml
- gradle.properties
**Migrate bookkeeper to gradle.**
Checkstyle is gradle as well as maven plugin which checks for code formatting spacing etc. 
**How to run** 
`./gradlew checkstyleMain  `
Integrate gradle build with checkstyle plugin
> ISSUE-2640: BP-43 Integrate checkstyle with gradle

- conf/bk_server.conf
`openLedgerRereplicationGracePeriod` default value doc doesn't consistent with the code
1. update default value doc for bk_server.conf
> fix openLedgerRereplicationGracePeriod default value doc

- build.gradle
**Migrate bookkeeper to gradle javadoc plugin.**
**How to run** 
`./gradlew javadoc`
- Integrate gradle build with javadoc plugin
**Few points to note**
- This integration is same/similar to the maven javadoc plugin integration.
> ISSUE-2640: BP-43 integrate gradle javadoc plugin

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerRecoveryOp.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerRecovery2Test.java
Ensures that only entries of the current ensemble are included in the ledger recovery process, thus avoiding a ledger recovery failure scenario where it tries to append an ensemble with a lower first entry id than the prior ensemble.
This PR includes a small change in the LedgerRecoveryOp that avoids a scenario where ledger recovery tries to create an invalid ensemble thereby failing. This could cause data unavailability for as long as trigger conditions last.
During ledger recovery, only entries of the current ensemble can be included in the read and write back phase. Prior ensembles, if any, are immutable. But it is possible, in a multi-ensemble ledger, for the current ensemble to return an LAC of -1. This then causes the recovery to read entries …
> Issue 2615: Fix for invalid ensemble issue during ledger recovery

- .github/actions/tune-runner-vm/action.yml
- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/stream-tests.yml
- .github/workflows/tls-tests.yml
Fixes reverse DNS lookup for current hostname. This is broken in GitHub Actions currently.
See https://github.com/apache/pulsar/issues/10232 and https://github.com/apache/pulsar/pull/10233 for more details.
Add the current IP address, long hostname and short hostname record to /etc/hosts file at the beginning of each GitHub Actions workflow.
> Add current ip address, long hostname and short hostname to /etc/hosts

- bookkeeper-server/build.gradle
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/EnableZkSecurityBasicTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ZooKeeperUtil.java
- build.gradle
- dependencies.gradle
Migrate bookkeeper build to gradle. Some test cases were failing while running test with gradle
* Fix dependencies to exclude some transitive dependencies.
* jassTmpDir was created under target folder. This fails while running tests using gradle. Instead we should use createTempDirectory to create temp folder
> ISSUE-2640: BP-43: Fix test cases that fail when running with gradle

- bookkeeper-stats-providers/codahale-metrics-provider/build.gradle
- build.gradle
- buildtools/src/main/resources/bookkeeper/findbugsExclude.xml
- gradle.properties
- settings.gradle
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCStoreImpl.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/metadata/stream/MetaRangeImpl.java
**Migrate bookkeeper to gradle spotbug plugin.**
spotbugs is gradle as well as maven plugin which checks for obvious bugs in source code.
**How to run** 
`./gradlew spotbugsMain `
- Integrate gradle build with spotbugs plugin
- Second commit is for fixing issues reported by spotbugs plugin 
Just to validate it's working. 
I introduced following bug.
```
public void test() {
+
+        String[] field = {"a", "b", "c", "s", "e"};
+
+        //concatenates strings using + in a loop
+        String ip = "127.0.0.1";
+        String s = "";
+        for (int i = 0; i < field.length; ++i) {
+            s = s + field[i];
+        }
+
+        System.out.println(ip);
+
+    }
```
spotbugs plugin reported following violation.
```
<BugInstance type="SBSC_USE_STRINGBUFFER_CONCATENATION" …
```
> ISSUE-2640: BP-43 Integrate spotbugs plugin with gradle

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
- pom.xml
After deleting many ledgers, seeking to the end of the RocksDB metadata can take a long time and trigger timeouts upstream. Address this by improving the seek logic as well as compacting out tombstones in situations where we've just deleted many entries.  This affects the entry location index and the ledger metadata index.
> Rocksdb tombstones

- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/stream-tests.yml
- .github/workflows/tls-tests.yml
In GitHub Actions, the default way to handle PR builds is to checkout GitHub provided merge_commit_sha . 
GitHub's merge_commit_sha is explained in [this documentation](https://docs.github.com/en/rest/reference/pulls#get-a-pull-request)
> Before merging a pull request, the merge_commit_sha attribute holds the SHA of the test merge commit.
Behind the scenes, GitHub automatically creates a "test merge commit" that merges the PR branch and the target branch (master). A pull request build won't be started at all if this test merge commit cannot be created without conflicts.
In current BK GitHub Actions workflows, the PR builds happen for the HEAD commit on the pull request branch, without a merge to the master branch. The downside of the approach used in the existing BK CI is that the PR …
> [Build] Run PR builds for merge commit

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufList.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/ByteBufListTest.java
Handling CompositeByteBuf in a way that avoids unnecessary data copy.
https://github.com/apache/pulsar/pull/10330
https://github.com/apache/pulsar/pull/10330#issuecomment-825619753
Handling CompositeByteBuf in a way that avoids unnecessary data copy.
> ---
>
> ---
>
>
>     `e.g. BP-1: 64 bits ledger is …
> Fixed unnecessary copy to heap, see https://github.com/apache/pulsar/pull/10330

- bookkeeper-dist/all/pom.xml
- bookkeeper-dist/server/pom.xml
- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
- stream/statelib/pom.xml
- stream/storage/impl/pom.xml
- jackson-mapper-asl is not required since Zookeeper 3.6.x+ no more depends on jackson-mapper-asl library (ZOOKEEPER-3051)
Remove jackson-mapper-asl dependency
> [Security] Remove jackson-mapper-asl dependency to resolve multiple CVEs

- site/docs/4.10.0/development/protocol.md
- site/docs/4.11.0/development/protocol.md
- site/docs/4.11.1/development/protocol.md
- site/docs/4.12.0/development/protocol.md
- site/docs/4.12.1/development/protocol.md
- site/docs/4.13.0/development/protocol.md
- site/docs/4.5.0/development/protocol.md
- site/docs/4.5.1/development/protocol.md
- site/docs/4.6.0/development/protocol.md
- site/docs/4.6.1/development/protocol.md
- site/docs/4.6.2/development/protocol.md
- site/docs/4.7.0/development/protocol.md
- site/docs/4.7.1/development/protocol.md
- site/docs/4.7.2/development/protocol.md
- site/docs/4.7.3/development/protocol.md
- site/docs/4.8.0/development/protocol.md
- site/docs/4.8.1/development/protocol.md
- site/docs/4.8.2/development/protocol.md
- site/docs/4.9.0/development/protocol.md
- site/docs/4.9.1/development/protocol.md
- site/docs/4.9.2/development/protocol.md
- site/docs/latest/development/protocol.md
the no striping occurs condition should Qw=E, not the Qw=Qa
update the condition to Qw=E
> [doc] fix the no striping occurs condition to Qw=E

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandleAdv.java
Fixes: #2660 
isWriteSetWritable() to use ledgerId for the client selection
Master Issue: #2660
> fix: Bookkeeper client throttling logic is based upon entryId instead of ledgerId

- dependencies.gradle
- pom.xml
- required for compilation on JDK 16
- see https://projectlombok.org/changelog
Upgrade Lombok version to `1.18.20` in `pom.xml` and `dependencies.gradle`.
> Upgrade Lombok to 1.18.20

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MdcContextTest.java
If we're trying to read an entry id that is bigger than the `lastAddConfirmed`, a read error is printed and looks like:
```
ReadException on ledgerId:1234 firstEntry:222 lastEntry:222
```
Adding the `lastAddConfirmed` would help to debug why the entries are out of the range.
> Read entry error should print lastAddConfirmed in the log

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RegionAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
When use `RegionAwareEnsemblePlacementPolicy` to select ensemble set, it always select the same region set for all ledger creation.
The reason is that it traverse the availableRegions set in the same order for ensemble selection and select bookies in the same region set, which lead the load not balance between regions.
```java
for (String region: availableRegions) {
regionsWiseAllocation.put(region, Pair.of(0, 0));
}
...
for (Map.Entry<String, Pair<Integer, Integer>> regionEntry: regionsWiseAllocation.entrySet()) {
// do selection
}
```
1. introduce `regionIndex` field to mark next select index for available region list, avoiding traverse from the same position for each ensemble selection.
I will add the test latter.
> fix always select the same region set bug for RegionAwareEnsemblePlacementPolicy

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
In case of corrupted entry log, this exception can show up during the compaction phase: 
```
18:53:37.224 [GarbageCollectorThread-7-1] ERROR org.apache.bookkeeper.bookie.GarbageCollectorThread - Failed to compact entry log 16 due to unexpected error
java.lang.IndexOutOfBoundsException: index: 8, length: 8 (expected: range(0, 0))
at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1425) ~[netty-buffer-4.1.51.Final.jar:4.1.51.Final]
at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1432) ~[netty-buffer-4.1.51.Final.jar:4.1.51.Final]
at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1419) ~[netty-buffer-4.1.51.Final.jar:4.1.51.Final]
at io.netty.buffer.UnpooledUnsafeDirectByteBuf.getLong(UnpooledUnsafeDirectByteBuf.java:144) …
```
> Exception in BK GC with corrupted data files

- tests/backward-compat/current-server-old-clients/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatOldClients.groovy
- tests/backward-compat/hostname-bookieid/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatUpgradeWithHostnameBookieId.groovy
- tests/backward-compat/upgrade/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatUpgrade.groovy
- tests/docker-images/all-released-versions-image/Dockerfile
4.14.0 release 
followed https://bookkeeper.apache.org/community/release_guide/#verify-docker-image and used https://github.com/apache/bookkeeper/pull/2171 as example
> Update bc tests to include versions up to 4.14.0

- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/api/StateStoreSpec.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestRocksdbKVStoreCheckpoint.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestStateStore.java
- stream/storage/api/src/main/java/org/apache/bookkeeper/stream/storage/conf/StorageConfiguration.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/store/MVCCStoreFactoryImpl.java
While restoring a storage container, we fetch the checkpoint from the
checkpoint store. Currently this checkpoint will never get cleaned up. Every
time we restore the storage container on pod, a new checkpoint will get added.
Over period of time the disk usage keeps going up and eventually we have to
manually delete these stale checkpoints.
With this change, we will cleanup the local storage for a storage container
whenever we close the KVStore. This will ensure that stale checkpoints are not
left behind. It is possible that POD may restart before the cleanup can be
done. To avoid these, we will also ensure that local storage for the storage
container is cleaned up before we restore the storage container.
> [statestore] Cleanup local storage for statestore storage container

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
'conif' seems to be a typo of `conf`.
Fixed the typo.
> Fix the typo in Auditor.java

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
I was trying to read the code to see how auto-recovery service works, just noticed the method `printUsage` was never called and the program doesn't print the usage even when '-h' is specified.
Print the usage of auto-recovery if '-h' is specified or additional unexpected arguments are provided when running the auto-recovery command.
> Print usage in autorecovery command if needed

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- metadata-drivers/etcd/pom.xml
- stream/common/pom.xml
- stream/tests-common/pom.xml
Fixes #2733
The okhttp dependency version 2.7.4 is old and vulnerable. This dependency isn't needed and it causes Bookkeeper to be flagged for security vulnerabilities.
- exclude grpc-okhttp dependency which pulls in okhttp 2.7.4 
- update license files
> [Security] Exclude grpc-okhttp dependency

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerCreateOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadataBuilder.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieWriteLedgerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeperTestCase.java
We need a way to use old bookie which doesn't support metadata-version-3 and upgrade bookkeeper-client with latest version. Right now, bk-4.12 writes ledger metadata with version-3 which will not be supported by bookie and replicator and replicator fails with below error
```
2021-05-07.00:43:53.115 [main-EventThread] ERROR
o.a.b.meta.AbstractZkLedgerManager   - Could not parse ledger metadata for ledger: 123456
java.io.IOException: Metadata version not compatible. Expected between 0 and 2, but got 3
at org.apache.bookkeeper.client.LedgerMetadata.parseConfig(LedgerMetadata.java:465)
at org.apache.bookkeeper.meta.AbstractZkLedgerManager$3.processResult(AbstractZkLedgerManager.java:414)
at org.apache.bookkeeper.zookeeper.ZooKeeperClient$19$1.processResult(ZooKeeperClient.java:994)
at …
```
> BookKeeper-Client config to write ledger metadata with configured version

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-http/vertx-http-server/src/main/java/org/apache/bookkeeper/http/vertx/VertxHttpServer.java
- pom.xml
Fixes #2511
See #2511
The current vertx version is 3.5.3 which has a vulnerability, CVE-2018-12541 .
- Upgrade [vertx version to 3.9.8](https://github.com/eclipse-vertx/vert.x/releases/tag/3.9.8)
- Fix issue with deprecated API usage
> [Security] Upgrade vertx to 3.9.8, addresses CVE-2018-12541

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- dependencies.gradle
- pom.xml
- stream/clients/java/base/build.gradle
Fixes #2732
- Freebuilder 1.14.9 contains an outdate jquery js file which causes the library to be flagged as vulnerable with the highest threat level in Sonatype IQ vulnerability scanner. This also flags Bookkeeper and Pulsar as vulnerable with the highest threat level although it is a false positive and not an actual threat.
- Freebuilder shouldn't be exposed as a transitive dependency
- it's an annotation processor which should be defined
- [optional in maven](https://github.com/inferred/FreeBuilder#maven)
- [compileOnly in gradle](https://github.com/inferred/FreeBuilder#gradle)
- upgrade [Freebuilder](https://github.com/inferred/FreeBuilder) from 1.14.9 to 2.7.0
- make dependency optional in maven pom.xml
- use `compileOnly` instead of `implementation` in gradle build
> [Build/Security] Upgrade Freebuilder version and fix the dependency

- bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/TLSContextFactory.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
- tests/backward-compat/bc-non-fips/pom.xml
- tests/backward-compat/bc-non-fips/src/test/java/org/apache/bookkeeper/tls/TestBCNonFips.java
- tests/backward-compat/pom.xml
More details are provided in [Pulsar # 10937](https://github.com/apache/pulsar/issues/10937).
In #2631, the default BouncyCastle was changed from non-fips into fips version. But the default version of BouncyCastle in Pulsar is the [non-fips](https://github.com/apache/pulsar/blob/v2.8.0/pulsar-client/pom.xml#L56) one(aimed to make it compatible with the old version of Pulsar). 
Bouncy Castle provides both FIPS and non-FIPS versions, but in a JVM, it can not include both of the 2 versions(non-Fips and Fips), and we have to exclude the current version before including the other. This makes the backward compatible a little hard, and that's why Pulsar has to involve an individual module for [Bouncy …
> Fix Bouncy Castle fips incompatible issue

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/NativeIO.java
I was running BK with jdk16 where --illegal-access property is set on "deny" and there was an illegal access done by `NativeIO#getFieldByReflection`; the application crashes due to java `assert` without logging which module/package you have to explicit open with --add-opens option
Plus: I'm not sure if it is correct to keep `assert` in this case, maybe throwing the IllegalAccessException is safer 
Log which field cannot be accessed before application crashes
> Log which java field cannot be accessed with --illegal-access=deny (NativeIO)

- bin/bkctl
- bin/bookkeeper
- bin/dlog
- stream/bin/streamstorage
- stream/bin/streamstorage-cli
Fix issue [#3726](https://github.com/apache/bookkeeper/issues/2726)
Add double quotation around `${JAVA}`  in `/bin/bookkeeper`.
> ISSUE #2726 Fix JAVA_HOME containing spaces

- site/_data/config/bk_server.yaml
It looks like an obvious typo that `tslProvider` should be `tlsProvider`, and the configuration item in the source code is also `tlsProvider`: https://github.com/apache/bookkeeper/blob/31e8d1b44ffafd867d0eb2774085e4b1141a7acb/bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java#L102
> [doc] Fix typo in bookkeeper config `tslProvider`

- stream/clients/python/setup.py
---
Master Issue: #2752
*Motivation*
As discussed at length in https://issues.apache.org/jira/browse/LEGAL-572
we found out that the chardet library used by requests library was a
mandatory dependency to requests and since it has LGPL licence, we
should not release any Apache Software with it.
> Remove the `request` in the stream python client dependency

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadLacProcessorV3.java
Two errors do not have an impact on functionality, so change log level from error to warn
change log level from error to warn in getReadLacResponse
do not need documentation.
> Change log level from error to warn in getReadLacResponse

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- dependencies.gradle
- pom.xml
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/acl/ZKAccessControl.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/metadata/BKDLConfig.java
Fixes #2512
See #2512 
The current libthrift version 0.12.0 has multiple vulnerabilities:
- CVE-2019-0205 , CVE-2019-0210 , CVE-2020-13949
- Upgrade libthrift version to 0.14.1 and fix compilation errors
- exclude new transitive dependencies org.apache.tomcat.embed:tomcat-embed-core and javax.annotation:javax.annotation-api
> [Security] Upgrade libthrift to 0.14.2 to address multiple CVEs

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- dependencies.gradle
- pom.xml
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/acl/ZKAccessControl.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/metadata/BKDLConfig.java
> [Security] Upgrade libthrift to 0.14.2 to address multiple CVEs (backport to branch-4.14)

- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/metadata/RootRangeStoreImpl.java
log the the tuple (namespace id, stream id, stream name) in RootStorageService getRange request.
Server request metrics are labeled with the stream id, extracted from the routing header.  The stream name
(aka "table name") is not available but more useful.  Rather than making a (cacheable) RPC request to fetch
the id -> name mapping in the metrics, logging the information allows one to find the name without requiring
admin access to the state store service.
> ---
>
> ---
>
> If this PR …
> state store: getStream: log stream info

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/conf/NoSystemPropertiesConfigurationTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/conf/SystemPropertiesConfigurationTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/TestPerChannelBookieClient.java
Added `TCP_USER_TIMEOUT` in Epoll channel config to limit the time a connection is left sending keepalives to a non-responding Bookie.
The original issue reported that in scenarios where Bookies may go down unexpectedly and change their IP (e.g., Kubernetes), the Bookkeeper client may be left for some time attempting to connect with the old IP of the restarted Bookie (see #2482 for details). To prevent this problem from happening (in Epoll channels), we introduce the following changes:
- Epoll channels are now configured with `TCP_USER_TIMEOUT`. This parameter rules over the underlying TCP keepalive configuration (see https://datatracker.ietf.org/doc/html/rfc5482), which may be defaulted to retry for too long depending on the environment (e.g., 10-15 minutes in our experience).
- To …
> Issue 2482: Added TCP_USER_TIMEOUT to Epoll channel config

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieFileChannel.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultFileChannel.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultFileChannelProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileChannelProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/JournalChannel.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalForceTest.java
- conf/bk_server.conf
Make the FileChannel in the JournalChannel can use different implement.
We found we can use [pmemstore](https://github.com/pmem/pcj)
as the JournalChannel read from. So abstract the FileChannel in the
JournnalChannel to make us can have a different implementation.
- Add interface for supporting implement different FileChannel
This PR doesn't introduce any new things in the code. So make sure it can pass the CI
> Abstract the FileChannel in the JournalChannel

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgersIndexCheckOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgersIndexRebuildOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LocationsIndexRebuildOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/CheckDBLedgersIndexCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/RebuildDBLedgerLocationsIndexCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/RebuildDBLedgersIndexCommand.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/LedgersIndexRebuildTest.java
- tools/ledger/src/main/java/org/apache/bookkeeper/tools/cli/commands/BookieCommandGroup.java
File corruption of the ledgers index (DbLedgerStorage) has happened in production and we currently have no good way of resolving it. There exists a locations index rebuild command, this issue describes a new command targeted at the ledgers index.
This command should only be run when either the bookie is offline, or when in readonly mode to avoid data loss. Container based environments may not be able to make the bookie go offline while also allowing the shell or bkctl to perform the operation.
The db ledgers index rebuild op does the following:
- scans all journal and entry log files to discover all ledger ids currently stored.
- builds a new index where each ledger is fenced and has an empty master key set.
- If all went well, replaces the original index with the new one
The bookie …
> ISSUE-2773: Add db ledgers index rebuild op

- .github/workflows/client-tests.yml
- bookkeeper-server/build.gradle
- gradle.properties
- settings.gradle
Sometimes ago gradle was introduced to Bookkeeper, 
and with that build and release capabilities were built in Bookkeeper with gradle. But we never migrated bookkeeper to gradle.
Taking a first step towards gradle migration; This PR migrate all client unit tests of bookkeepr-server module to gradle 
Replace maven test target with gradle
This is copy of the approved PR https://github.com/apache/bookkeeper/pull/2800
As github somehow is giving 404 with https://github.com/apache/bookkeeper/pull/2800 while merging it.
> ISSUE #2640: BP-43 Migrate bookkeeper client tests to gradle

- .github/workflows/bookie-tests.yml
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/EntryLogTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorageTest.java
Migrating bookkeeper-server bookie tests to gradle.
1. As per the naming convention name of test class/file Should be {FooFeature}Test as opposed to Test{FooFeature}
2. Migrating tests to gradle
> ISSUE #2640: BP-43 Migrate bookkeepr-server org.apache.bookkeeper.bookie.* tests to gradle

- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieIsReadyService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
API `/api/v1/bookie/is_ready` should set some response body, when code 200 returned.
Or, this will confuse people, they don't know if this api  return successfully.
> set response body for bookie  is_ready api

- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/TestPerChannelBookieClient.java
- Fixes #2787
- On some Linux systems the value 1234 is rounded to 1236, this patch simply uses 1236 as value in order to prevent failures
> Issue 2787: TestPerChannelBookieClient.testEpollChannelTcpUserTimeout fails

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
- conf/bk_server.conf
When we start BookKeeper auditor, it will start checking all ledgers task with given interval(default 7days) compared to last check timestamp,  and the check ledger operation will process all the activeLedgers shown in the follow code.
https://github.com/apache/bookkeeper/blob/c7236adc3cb659e65ae5ce53b7156569d7f50ebd/bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java#L571-L573
In the logic of process ledger, it will call `readLedgerMetadata` , which will call getData using zkClient and parse ZNode data in callback, which is time consuming.
https://github.com/apache/bookkeeper/blob/c7236adc3cb659e65ae5ce53b7156569d7f50ebd/bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java#L433-L474
When use use NettySocketChannel for …
> Add auditor get ledger throttle to avoid auto recovery zk session expire

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/GcOverreplicatedLedgerTest.java
Fixes https://github.com/apache/bookkeeper/issues/2854 issue
* Use correct lockpath at ZkLedgerUnderreplicationManager#acquireUnderreplicatedLedger
* Store Lock to heldLocks at ZkLedgerUnderreplicationManager#acquireUnderreplicatedLedger
- for safety, I introduce Optional to Lock#ledgerZNodeVersion
> Issue #2854: Use correct lockpath, store Lock to heldLocks at ZkLedgerUnderreplicationManager#acquireUnderreplicatedLedger

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/RecoverCommand.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieShellTest.java
When we use `bin/bookkeeper shell recover bookieId` command to recover specific bookie's ledgers, the recover process will exit when occurs recover ledger failed.
In our production bookkeeper cluster, we found some ledgers in Open state and has no entry.  When we call `bin/bookkeeper shell recover bookieId` command, it will traverse all the ledgers level by level. In the end, for each ledger, it will call the following code to process recover.
```Java
Processor<Long> ledgerProcessor = new Processor<Long>() {
@Override
public void process(Long ledgerId, AsyncCallback.VoidCallback iterCallback) {
recoverLedger(bookiesSrc, ledgerId, dryrun, skipOpenLedgers, skipUnrecoverableLedgers, iterCallback);
}
};
```
In the `recoverLedger` method, it will call `asyncOpenLedgerNoRecovery` to open ledger …
> Add skip unrecoverable ledger option for bookkeeper shell recover command

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieException.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessorV3.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorV3Test.java
When the write cache flush timeout occurs in SingleDirectoryDbLedgerStorage either because the disk is slow or if there are too many requests and the disk is busy, instead of returning EIO status to the client, ETOOMANYREQUESTS should be returned which is more appropriate for this situation.
- Whenever there is a resource constraint by the bookkeeper internal components OperationRejectedException is thrown. Now this exception send status=ETOOMANYREQUESTS
- Changed the Javadoc of OperationRejectedException to reflect the usage of OperationRejectedException appropriately
> Return too many requests error when the write cache flush timeout occurs

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/AdvertisedAddressTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieInitializationTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieShutdownTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieWriteToJournalTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CheckpointOnNewLedgersTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CookieTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/EntryLogTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerCacheTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerStorageTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/SingleBookieInitializationTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/TestBookieImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/UpgradeTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageWriteCacheTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperCloseTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperDiskSpaceWeightedLedgerPlacementTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieWriteLedgerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerCloseTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerRecoveryTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ParallelLedgerRecoveryTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestReadLastConfirmedAndEntry.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/BookieBackpressureTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/TestPerChannelBookieClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ConcurrentLedgerTest.java
To have DI on the bookie, it's better to have a single constructor
that takes all the injected implementations. With a single
constructor, there's only one place modify in production code when we
want to inject something, rather than having the bookie need to know
how to create a "default" version (which often breaks encapsulation).
If we need convenience constructors for tests, they should live in the
tests.
The principle changes are:
- remove the BookieImpl constructor which takes only a ServerConfiguration and chooses default values for the other ijectable dependencies.
- add a TestBookieImpl for use in tests which has a constructor that matches the one removed from BookieImpl.
This is one of many preliminary PRs with refactorings required for the "BP-46 Running without journal" work.
> There should only be a single BookieImpl constructor

- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AutoRecoveryMainTest.java
Sometimes the test AutoRecoveryMainTest fails this way on my test machine
```
[ERROR] org.apache.bookkeeper.replication.AutoRecoveryMainTest.testAutoRecoverySessionLoss  Time elapsed: 1.757 s  <<< FAILURE!
java.lang.AssertionError: autoRecoveryMain components should be running
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.apache.bookkeeper.replication.AutoRecoveryMainTest.startAutoRecoveryMain(AutoRecoveryMainTest.java:192)
at org.apache.bookkeeper.replication.AutoRecoveryMainTest.testAutoRecoverySessionLoss(AutoRecoveryMainTest.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at …
```
> Fix flaky AutoRecoveryMainTest

- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestRocksdbKVAsyncStoreWithCheckpoints.java
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/testing/executors/MockExecutorController.java
Fixed tests
Stream Storage tests are flaky; statelib test times out
MockExecutor managed to get into the situation when it submitted the task to the same thread it was running on.
Not sure why it didn't happen consistently, locally I can only repro this in the debugger and only when I step over some code.
> fix: Stream Storage tests are flaky; statelib test times out

- .github/workflows/pr-validation.yml
- microbenchmarks/src/main/java/org/apache/bookkeeper/common/OrderedExecutorBenchmark.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/common/package-info.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/proto/ProtocolBenchmark.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/DigestTypeBenchmark.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/package-info.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/proto/package-info.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/stats/StatsLoggerBenchmark.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/stats/codahale/TimerBenchmark.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/stats/codahale/package-info.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/stats/package-info.java
Currently we are forced to skip `microbenchmarks` checkstyle task because it fails. 
In fact, the "pr-validation" check skips that task.
- fixed checkstyle
- removed the skip in the "pr-validation" check
> Fix checkstyle on "microbenchmarks"

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/ScanAndCompareGarbageCollector.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- conf/bk_server.conf
- site/_data/config/bk_server.yaml
In one day, zookeepers became high cpu usage and disk full.
The cause of this is bookie's gc of overreplicated ledgers.
Gc created/deleted zk nodes under `/ledgers/underreplication/locks` very frequently and some bookies ran gc at same time.
As a result, zookeepers created a lot of snapshots and became disk full.
I want to configure max zk concurrent requests lower than 1000(default) to avoid heavy traffic at a specific time.
* Make max zk concurrent requests for garbage collection of overreplicated ledgers configurable.
> Make maxConcurrentZkRequests for gc configurable

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedScheduler.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
See BP-44 for full motivation. 
This PR focuses on the OrderedExecutor and OrderedScheduler.
- Removed double nesting of TimedCallable/TimedRunnable from OrderedExecutor. These were being added by both the decorators and explicitly in the overridden methods causing double recording of metrics.
- Moved thread ordinal numbers in metric names to a label, in line with modern practices.
- Metrics `task_execution` and `task_queued` changed to be thread-scoped, rather than being an aggregate across all threads. This is configurable, disabled by default. Only enabled in the BookieRequestProcessor. Not in the client or any tests.
Master Issue: #2834
> BP-44: OrderedExecutor metrics

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
Including the port number only complicates things for
admins who rely on OrderedExecutor metrics for alerts
and dashboards. Removing the port number reduces,
the complexity for deployments which use various
non-standard bookie ports.
Removed port number from high priority and long poll thread pool names.
Master Issue: #2834
> BP-44: Removed bookie port number from OrderedExecutor name

- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestBKDistributedLogManager.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestDistributedLogBase.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestNonBlockingReadsMultiReader.java
TestBKDistributedLogManager is flaky. 
Sometimes it passes on the CI because of the retries, sometimes it fails.
It passes all tests locally (or in debugger/IDE) if the cases run one by one.
Full suite often fails, typically with random cases failing. 
AFAICT, frequently tests fail because of 
```
[DL-io-0] ERROR org.apache.bookkeeper.common.allocator.impl.ByteBufAllocatorImpl - Unable to allocate memory
java.lang.OutOfMemoryError: Direct buffer memory
```
As result bookies fail, and then test cases fail with something like "BKTransmitException: Failed to write to bookkeeper" 
I don't see anything from netty's leak detection.
It does NOT fix https://github.com/apache/bookkeeper/issues/2898 but it helped to get https://github.com/apache/bookkeeper/issues/2898 reproed without hitting …
> Reduce flakiness of TestBKDistributedLogManager

- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java8.yml
- bookkeeper-benchmark/build.gradle
- build.gradle
- shaded/distributedlog-core-shaded/build.gradle
- stream/bk-grpc-name-resolver/build.gradle
- tests/integration/cluster/build.gradle
- tests/shaded/distributedlog-core-shaded-test/src/test/java/org/apache/bookkeeper/tests/shaded/DistributedLogCoreShadedJarTest.java
- Fix the compatibility workflows for java11 and java8
- Fixes the dependencies in the tests
Compatibility checks workflow wasn't working because there the github workflow.yaml had syntax issues. Also, since it was enabled 1st time, there were build issues with the tests.
> Fix the compatibility workflows

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookKeeperServerStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDirsManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SyncThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/SyncThreadTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageWriteCacheTest.java
See BP-44 for full motivation
Various enhancements related to DbLedgerStorage:
- All DbLedgerStorage stats now report their ledgerDir.
- Read cache hit/misses now differentiated from write cache.
- Read/write cache hit/misses now counters, not OpStatsLoggers.
The OpStatsLoggers are relatively expensive and the counter
values are most important here.
- Stats where thread info useful are now thread-scoped. In
general the focus is on time based metrics for operations
carried out by the read/write thread pools.
- Time spent counters on sub-operations for reads (entry log,
locations index, readahead).
- Flush time started moved to after lock to avoid 200% time
utilization calculations. Can reach 200% because one thread
is busy flushing and another busy waiting on the lock.
- Time spent …
> BP-44: Ledger storage metrics enhancement

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
Simple code cleanup.
Remove EMPTY_ARRAY_LIST in org.apache.bookkeeper.bookie.Journal. It's not used anymore.
> Cleanup unused Journal#EMPTY_ARRAY_LIST

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBaseV3.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ForceLedgerProcessorV3Test.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorV3Test.java
- docker/scripts/entrypoint.sh
After the readcache has been shutdown, all the buffers will be released in memory. In the meantime, if read and write ops are performed on the read cache, then it results in the segmentation fault on invalid memory. So, this PR will shutdown the request processor that does readops and writeops before the bookie shutdown sequence.
- Stop all the requestProcessor threads before bookie shutdown sequence to avoid read/write ops during bookie shutdown
- Force shutdown the executors so that it is ensured to stop all executor threads before bookie shutdown.
- Apply this diff https://gist.github.com/pradeepbn/a033cae7171f9e6da9a7f92737f843b9 on the master branch to reproduce the issue
- Use this (https://gist.github.com/pradeepbn/65ef387a164953fb3f90057860b1 …
> Reorder the sequence of the bookkeeper server shutdown so that there are no read/ write ops while shutting down the bookie

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
- build.gradle
- circe-checksum/build.gradle
In the `maven-compiler-plugin` configuration there are `lint:deprecation` and `lint:unchecked` options enabled by default (also -`Werror` in order to make the build fails in case of warnings)
The Maven configuration is 
https://github.com/apache/bookkeeper/blob/a522fa33b31e2405830a33cd2120be60d3174cd5/pom.xml#L880-L888
* Enable -Xlint:unchecked -Xlint:deprecation -Werror on all projects
> Gradle compileJava: enable -Xlint options

- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestTxnId.java
On the master branch,  TestTxnId can't find the dependency of `org.apache.bookkeeper.bookie.TestBookieImpl`.
remote the dependency and legacy code since it's not used
remote the dependency and legacy code
> remove legacy code to resole class missing error

- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
- bookkeeper-http/servlet-http-server/src/main/java/org/apache/bookkeeper/http/servlet/BookieServletHttpServer.java
- bookkeeper-http/vertx-http-server/src/main/java/org/apache/bookkeeper/http/vertx/VertxHttpServer.java
- bookkeeper-http/vertx-http-server/src/test/java/org/apache/bookkeeper/http/vertx/TestVertxHttpServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/service/HttpService.java
- conf/bk_server.conf
- site/_data/config/bk_server.yaml
Allow to config bookie http host
For security, make bookie bind addr can config.
For compatibility, make default value is 0.0.0.0
> Allow to configure bookie http host

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- dependencies.gradle
- pom.xml
Bump log4j2 to 2.15.0 to solve https://www.lunasec.io/docs/blog/log4j-zero-day/
> Bump log4j2 to 2.15.0

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/NetUtils.java
Simple code cleanup
1.RackawareEnsemblePlacementPolicyImpl.REPP_DNS_RESOLVER_CLASS has be existed in his parent class,so clean in the child class
2.NetUtils.logger is no use
> Cleanup code in RackawareEnsemblePlacementPolicyImpl

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/UpdateBookieInLedgerCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/RecoverCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperCloseTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/UpdateLedgerOpTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
Ledger replicating puts  heavy loads on cluster.
Now,  ledger replicate only supports split fragments into small pieces.
But, throttling is not supported.
Add a confiuration `replicationRateByBytes `
support throttling  read rate in bytes.
Also bookkeeper shell recover command supports throttle.
> Ledger replicate supports throttle

- .github/workflows/compatibility-check-java8.yml
- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/TestPrometheusFormatter.java
- dependencies.gradle
- metadata-drivers/etcd/build.gradle
- metadata-drivers/etcd/src/test/resources/log4j2.xml
- pom.xml
- stream/bk-grpc-name-resolver/build.gradle
- stream/bk-grpc-name-resolver/src/main/java/org/apache/bookkeeper/grpc/resolver/BKRegistrationNameResolverProvider.java
- stream/bk-grpc-name-resolver/src/test/java/org/apache/bookkeeper/grpc/resolver/BKRegistrationNameResolverTest.java
- stream/clients/java/all/build.gradle
- stream/clients/java/base/build.gradle
- stream/proto/build.gradle
- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestRocksdbKVAsyncStoreWithCheckpoints.java
- stream/tests-common/build.gradle
`BKRegistrationNameResolverProvider` is relying on an interface from older Grpc version that has changed since then. 
This causes conflicts when trying to use BK with a newer version of Ggrpc, which can be the case when other components are requesting a newer Grpc version.
> Upgrade to Grpc 1.42.1

- site/docs/4.10.0/security/tls.md
- site/docs/4.11.0/security/tls.md
- site/docs/4.11.1/security/tls.md
- site/docs/4.12.0/security/tls.md
- site/docs/4.12.1/security/tls.md
- site/docs/4.13.0/security/tls.md
- site/docs/4.14.0/security/tls.md
- site/docs/4.14.1/security/tls.md
- site/docs/4.14.2/security/tls.md
- site/docs/4.14.3/security/tls.md
- site/docs/4.5.0/security/tls.md
- site/docs/4.5.1/security/tls.md
- site/docs/4.6.0/security/tls.md
- site/docs/4.6.1/security/tls.md
- site/docs/4.6.2/security/tls.md
- site/docs/4.7.0/security/tls.md
- site/docs/4.7.1/security/tls.md
- site/docs/4.7.2/security/tls.md
- site/docs/4.7.3/security/tls.md
- site/docs/4.8.0/security/tls.md
- site/docs/4.8.1/security/tls.md
- site/docs/4.8.2/security/tls.md
- site/docs/4.9.0/security/tls.md
- site/docs/4.9.1/security/tls.md
- site/docs/4.9.2/security/tls.md
- site/docs/latest/security/tls.md
The doc of Tls may forget the config `tlsProviderFactoryClass`. Without this config, the tls won't works
> Add tlsProviderFactoryClass in the tls doc

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- dependencies.gradle
- pom.xml
Bump log4j2 to 2.17.0 to solve CVE-2021-45105
details:
https://logging.apache.org/log4j/2.x/security.html
> Bump log4j2 to 2.17.0

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
If `metadataServiceUri` is present (uncommented) in the `bookie.conf`, the bookie will try to use it, even if it is empty, instead of just falling back to `zkServers`, as it happens when the `metadataServiceUri` is not present at all. 
Check for blank, instead of `null`, to make it easier to have both keys and override them as needed.
> Allow to easily override `zkServers` with `metadataServiceUri`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLogMetadataCommand.java
When i use `bookkeeper shell readlogmetadata`  to get an entrylog file's metadata info, i encountered the following exception:
```
19:51:11.282 [main] INFO  org.apache.bookkeeper.bookie.EntryLogger - Failed to get ledgers map index from: 0.log : No file for log 0
19:51:11.284 [main] WARN  org.apache.bookkeeper.bookie.EntryLogger - Failed to get channel to scan entry log: 0.log
Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: No file for log 0
at org.apache.bookkeeper.tools.cli.commands.bookie.ReadLogMetadataCommand.apply(ReadLogMetadataCommand.java:106)
at org.apache.bookkeeper.bookie.BookieShell$ReadLogMetadataCmd.runCmd(BookieShell.java:988)
at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:223)
at …
```
> fix readlogmetadata failed bug and export entrylog file usage to output

- tests/backward-compat/build.gradle
Backward compatibility tests are [flaky](https://github.com/apache/bookkeeper/actions/workflows/backward-compat-tests.yml?query=is%3Afailure++). When they fail, they always fail due to
```
Not enough non-faulty bookies available
```
I spent a lot of time trying to tune connection parameters, split tests and so on, my understanding is that at certain points the machine starts suffering (he restart many times the bookies of different versions - 3 bookies and 1 zk in the same machine) and the bookie is unable to send ZK ping and then it's cut off from the ensemble.
I added the retry options to the tests with max 5 retries per test, it should be enough. (I don't have numbers to demonstrate that, we'll see it )
> Backward compatibility tests: add retries

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/DiskChecker.java
The descriptions of methods getTotalDiskSpace and getTotalFreeSpace are wrong in org.apache.bookkeeper.util.DiskChecker.
> The descriptions of methods getTotalDiskSpace and getTotalFreeSpace are wrong

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/zk/ZKMetadataBookieDriver.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/zk/ZKMetadataClientDriver.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/conf/TestBKConfiguration.java
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/service/RegistrationServiceProvider.java
1. bug fix for error config for BoundExponentialBackoffRetryPolicy in class ZKMetadataClientDriver,if set MaxRetries zero, zk client will throw ConnectionLossException when the zk has some changing,for example: zk leader node changed.
2. In Bookie's ZKClient, different BoundExponentialBackoffRetryPolicy set different MaxRetries,so change zkRetryBackoffMaxRetries to config in Bookie's AbstractConfiguration
1. update a error config for BoundExponentialBackoffRetryPolicy in class ZKMetadataClientDriver
2. change zkRetryBackoffMaxRetries to config
Master Issue: #2760
> zk client config update and bugfix for ZKMetadataClientDriver

- microbenchmarks/build.gradle
Replace gradle deprecated api usage
> Replace gradle deprecated api use runtime to runtimeClasspath

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
bug fix for EntryLocationIndex.getLastEntryInLedger
when the ledger is deleted, then get last entry in this ledger, two case in method(name is EntryLocationIndex.getLastEntryInLedger)
case return -1:
1)  when the ledger is deleted,return -1
2)  then the method(name is SingleDirectoryDbLedgerStorage.getLastEntry) should read entry's location index,  but entryID's value is -1, the code will throw a unexcepted error( error information is "IOException: org.apache.bookkeeper.bookie.EntryLogger$EntryLookupException$MissingLogFileException: Missing entryLog 0 for ledgerId ***, entry -1 at offset 0", if you want to get more details,you can read the Issue: #2927 
case throw NoEntryException:
1)  when the ledger is deleted,throw NoEntryException like the …
> bug fix for EntryLocationIndex.getLastEntryInLedger

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- dependencies.gradle
- pom.xml
modification
Bump log4j2 to 2.17.1 to solve CVE-2021-44832
details:
https://logging.apache.org/log4j/2.x/security.html
> Bump log4j2 to 2.17.1

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/ReadCache.java
If entrySize > segmentSize ,will throw IndexOutOfBoundsException when put entry into ReadCache.
> fix ReadCache bad case : entrySize > segmentSize 

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
the other bookie restart,rereplicate will run failed for BookieIdNotResolvedException when recover the IN_RECOVERY ledger,
then the ReplicationWorker will cost more cpu time  during the other bookie is restarting.
so wait a BackOff Time when rereplicate run failed to reduce CPU Resource
1. check rereplicate status
2. when rereplicate run fail ,call method waitBackOffTime to wait a moment
> wait a BackOff Time when rereplicate failed

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/WeightedRandomSelectionImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
When we meet the following conditions:
1. configured region aware placement policy
2. enable disk weight based placement
3. fallback random selection when selecting ensemble bookies, such as:
- not enough regions
- rack number less than 2 in one region
It will throw the following exception, and create ledger failed.
```
12:15:36.459 [bookkeeper-ml-scheduler-OrderedScheduler-1-0] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/test_v2] Encountered unexpected error when creating ledger
java.lang.NullPointerException: null
at org.apache.bookkeeper.client.WeightedRandomSelectionImpl.getNextRandom(WeightedRandomSelectionImpl.java:150) ~[io.streamnative-bookkeeper-server-4.14.3.1.jar:4.14.3.1]
at …
```
> Fix region aware placement policy use disk weight not work

- .github/workflows/backward-compat-tests.yml
- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/stream-tests.yml
- .github/workflows/tls-tests.yml
Add github actions timeout, default 360m is unreasonable
Give them different timeout according to history run time.
> Add github actions timeout

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
improve the throttle function : old pr: #2778 
1. duplicate definition for replicationRateByBytes
2.make sure this update safety when different callback run averageEntrySize updating
1.clean code for duplicate definition for replicationRateByBytes
2.add a lock to make sure data safety for updateAverageEntrySize
> improve the throttle function

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
The auditor cannot assume to have a Zookeeper based `LedgerManagerFactory`. Instead, the BK client already has a instance of the factory that we can reuse.
Additionally, the code was leaking the factory instance which was supposed to get closed.
> Auditor should get the LegdgerManagerFactory from the client instance

- dependencies.gradle
CVE-2021-22569
Upgraded protobuf dependency
> Upgrading protobuf, CVE-2021-22569

- build.gradle
- gradle.properties
- settings.gradle
- src/owasp-dependency-check-suppressions.xml
Added OWASP dependency-check plugin to gradle build (maven is due for removal so I ignored it)
Run dependency check to detect CVEs/dependencies that need upgrade.
Updated gradle build files.
To run:
```sh
./gradlew clean build -x microbenchmarks:checkstyleMain -x spotbugsTest -x signDistTar -x test dependencyCheckAggregate
```
See `build/reports/dependency-check-report.html` for results.
Current summary:
```
Dependencies Scanned: 360 (359 unique)
Vulnerable Dependencies: 65
Vulnerabilities Found: 174
Vulnerabilities Suppressed: 0
```
> Added OWASP dependency-check

- .github/workflows/pr-validation.yml
- build.gradle
`spotbugsTest` fails on a few submodules.
Run spotbugs against test files is useless and slow down development.
We can just skip it by default without having to specify `-x spotbugsTest`
Skip `spotbugsTest` by default
> [build] do not run spotbugsTest by default

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-server/src/main/java/org/apache/bookkeeper/metastore/Value.java
- build.gradle
- cpu-affinity/src/main/java/org/apache/bookkeeper/common/util/affinity/impl/NativeUtils.java
- cpu-affinity/src/main/java/org/apache/bookkeeper/common/util/affinity/impl/ProcessorsInfo.java
- dependencies.gradle
- stream/common/src/test/java/org/apache/bookkeeper/common/router/HashRouterTest.java
Older versions of guava (w/CVEs) used in some subprojects
Forced the same version of guava; fixed deprecation problems (murmur3_32) and compilation problems (checkArgument).
checkArgument cannot be statically imported because there are now overrides of it; checkstyle was not very cooperative so I had to remove the import altogether. 
Then updated the guava version to match one in Pulsar.
> Forced the same version of guava (plus upgraded it); fixed deprecations etc.

- README.md
- site/community/contributing.md
- site/docs/latest/getting-started/installation.md
Remove Maven from the build guide and remove outdated links and suggestions.
* Removed Coveralls badge (the latest build run in 2020)
* Removed Jira references (all the jira issues have been migrated to GitHub, so there's no need to confuse new contributors)
* Replaced Confluence doc links with official website links
* Replaced Maven instructions with Gradle ones
> [website] Remove Maven references and remove dead links from README

- .github/workflows/owasp-dep-check.yml
- build.gradle
Detect CVEs early and make them visible to the committers
Added GH workflow that will fail if new CVE with level > 7 detected. The plan is to not treat it as blocking merge.
Currently some projects that will not pass the check until other pending PRs are merged.
> CI workflow to check dependencies with OWASP

- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/Main.java
I was trying to start multiple bookies locally and found it's a bit inconvenient to specify different http ports for different bookies.
Add a command-line argument `httpport` to the bookie command to support specifying bookie http port from the command line.
> Support specifying bookie http port as a command argument

- bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/BookieAuthZFactory.java
When we get the right ``authorized`` state, we need to return immediately, do not need to do an unnecessary loop.
- Add ``break``, when get the right ``authorized`` state.
> Fix performance issues to avoid unnecessary loops.

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- dependencies.gradle
Dependency change
I encountered https://github.com/apache/bookkeeper/issues/3024 and noticed that newer version of RocksDB includes multiple fixes for concurrency issues with various side-effects and fixes for a few crashes.
I upgraded, ran `org.apache.bookkeeper.bookie.BookieJournalTest` test in a loop and didn't repro the crash so far.
It is hard to say 100% if it is fixed given it was not happening all the time. 
Upgraded RocksDB
Master Issue: #3024
> Upgrade RocksDB

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
After we support RocksDB backend entryMetaMap, we should avoid updating the entryMetaMap if unnecessary.
In `doGcEntryLogs` method, it iterate through the entryLogMetaMap and update the meta if ledgerNotExists. We should check whether the meta has been modified in `removeIfLedgerNotExists`. If not modified, we can avoid update the  entryLogMetaMap.
1. Add a flag to represent whether the meta has been modified in `removeIfLedgerNotExists` method. If not, skip update the entryLogMetaMap.
> Skip update entryLogMetaMap if not modified

- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/NetworkTopologyImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/net/NetworkTopologyImplTest.java
When we set region or rack placement policy, but the region or rack name set to `/` or empty string, it will throw the following exception on handling bookies join.
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1841) ~[?:?]
at org.apache.bookkeeper.net.NetworkTopologyImpl$InnerNode.getNextAncestorName(NetworkTopologyImpl.java:144) ~[io.streamnative-bookkeeper-server-4.14.3.1.jar:4.14.3.1]
at org.apache.bookkeeper.net.NetworkTopologyImpl$InnerNode.add(NetworkTopologyImpl.java:180) ~[io.streamnative-bookkeeper-server-4.14.3.1.jar:4.14.3.1]
at org.apache.bookkeeper.net.NetworkTopologyImpl.add(NetworkTopologyImpl.java:425) ~[io.streamnative-bookkeeper-server-4.14.3.1.jar:4.14.3.1]
at …
```
> Add rack name invalid check

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/PersistentEntryLogMetadataMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/BookKeeperConstants.java
When we use RocksDB backend entryMetadataMap for multi ledger directories configured, the bookie start up failed, and throw the following exception.
```
12:24:28.530 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.
java.io.IOException: Error open RocksDB database
at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:202) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-SNAPSHOT.jar:4.15.0-SNAPSHOT]
at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:89) ~[org.apache.bookkeeper-bookkeeper-server-4.15.0-SNAPSHOT.jar:4.15.0-SNAPSHOT]
at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.lambda$static$0(KeyValueStorageRocksDB.java:62) …
```
> Support multi ledger directories for rocksdb backend entryMetadataMap

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionTest.java
Flaky  test
AFAICT the test flaked because sometimes provided 15ms timeout for the compaction was not enough.
Possibly related to addition of `baseConf.setGcEntryLogMetadataCacheEnabled(true);` 
I split the test into two:
- one with much higher timeout to make sure compaction can finish
- one with a very short timeout to make sure at least one entry log won't get compacted
Master Issue: #3038
> [ISSUE 3038] Fixed flaky CompactionTest.testMinorCompactionWithMaxTimeMillis

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
When start bookie, it will throws the following error message when dns resolver initialize failed.
```
[main] ERROR org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Failed to initialize DNS Resolver org.apache.bookkeeper.net.ScriptBasedMapping, used default subnet resolver : java.lang.RuntimeException: No network topology script is found when using script based DNS resolver.
```
It is confusing for users.
1. change the log level from error to warn.
> change log level from error to warn when dns resolver initialize failed

- docker/scripts/entrypoint.sh
Current official docker images do not handle the SIGTERM sent by the docker runtime and so get killed after the timeout. No graceful shutdown occurs.
The reason is that the entrypoint does not use `exec` when executing the `bin/bookkeeper` shell script and so the BookKeeper process cannot receive signals from the docker runtime.
Use `exec` when calling the `bin/bookkeeper` shell script.
> Ensure BookKeeper process receives sigterm in docker container

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- conf/bk_server.conf
Fix #2823
RocksDB support several format versions which uses different data structure to implement key-values indexes and have huge different performance. https://rocksdb.org/blog/2019/03/08/format-version-4.html
https://github.com/facebook/rocksdb/blob/d52b520d5168de6be5f1494b2035b61ff0958c11/include/rocksdb/table.h#L368-L394 
```C++
// We currently have five versions:
// 0 -- This version is currently written out by all RocksDB's versions by
// default.  Can be read by really old RocksDB's. Doesn't support changing
// checksum (default is CRC32).
// 1 -- Can be read by RocksDB's versions since 3.0. Supports non-default
// checksum, like xxHash. It is written by RocksDB when
// BlockBasedTableOptions::checksum is something other than kCRC32c. (version
// 0 is silently upconverted)
// 2 …
```
> make rocksdb format version configurable

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/ScanAndCompareGarbageCollector.java
- Even if an exception other than BKNoSuchLedgerExistsOnMetadataServerException occurs of readLedgerMetadata in over-replicated ledger GC, nothing will be output to the log.
(https://github.com/apache/bookkeeper/pull/2844#discussion_r735219876)
- If an exception other than BKNoSuchLedgerExistsOnMetadataServerException occurs in readLedgerMetadata, output information to the log.
> Explicit error message if an exception other than BKNoSuchLedgerExistsOnMetadataServerException occurs in over-replicated ledger GC

- bin/bookkeeper
- site/_data/cli/bookkeeper.yaml
Signed-off-by: Eric Shen <ericshenyuhao@outlook.com>
The description of `bin/bookkeeper autorecovery` is wrong, it won't start in daemon.
* Changed the description in bookkeeper shell
* Update the doc
> ---
>
> ---
>
>
> - [ ] Attach the master issue link in …
> fix(cli): incorrect description for autodiscovery

- bookkeeper-server/build.gradle
- settings.gradle
clean up gradle warnings
- 7c6ef5bef fix gradle implicit dependency
> Implicit dependency

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/ReadCache.java
Original PR: https://github.com/apache/bookkeeper/pull/1755,
It should be that this PR forgot to modify the memory application method.
When the direct memory is insufficient, it does not fall back to the jvm memory, and the bookie hangs directly.
Use `OutOfMemoryPolicy` when the direct memory is insufficient when reading the entry in `ReadCache`.
> Use OutOfMemoryPolicy when the direct memory is insufficient when reading the entry in ReadCache

- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/stream-tests.yml
- .github/workflows/tls-tests.yml
- build.gradle
- dev/ci-tool
Sometimes CI jobs fail due to timeout. It would be useful understand what the latest test was doing before being interrupted. 
* Added a new script for dumping stacktrace.
* Added in all the jobs the step in case of `cancelled()` is true.
> [ci] Dump stacktrace when a job is cancelled

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/PersistentEntryLogMetadataMap.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionByBytesWithMetadataCacheTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionByBytesWithoutMetadataCacheTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionByEntriesWithMetadataCacheTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionByEntriesWithoutMetadataCacheTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionTest.java
RocksDB segfaulted during CompactionTest
RocksDB can segfault if one tries to use it after close.
[Shutdown/compaction sequence](https://github.com/apache/bookkeeper/issues/3040#issuecomment-1036508397) can lead to such situation. The fix prevents segfault.
CompactionTests were updated at some point to use metadata cache and non-cached case is not tested. 
I added the test suites for this case.
Master Issue: #3040
> [ISSUE 3040] RocksDB segfaulted during CompactionTest

- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/testing/executors/MockExecutorController.java
Flaky test on CI
Added extra check & logging to simplify troubleshooting of the flaky test on CI.
Cannot repro the failure locally after running 100+ times in a loop.
Master Issue: #3034
> [Issue 3034] Add extra checks in the mock to help with error troubleshooting on CI

- stream/statelib/src/test/java/org/apache/bookkeeper/statelib/testing/executors/MockExecutorControllerWithSchedulerTest.java
MockExecutorControllerWithSchedulerTest is flaky
testExecute flakes because runnable runs actually asynchronously in this case, modified the test. 
Master Issue: #3034
> ISSUE 3034: Fixed flaky test MockExecutorControllerWithSchedulerTest

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/LedgerDeleteTest.java
when number of ledger's Dir are more than 1,the same of GarbageCollectorThread will do the same thing,
Especially:
1) deleting ledger, then SyncThread will be timed to do rocksDB compact
2) compact: entry, cost cpu.
set a Mod initial Delay time to simply avoid GarbageCollectorThread working at the same time
> set Mod initial Delay time to simply avoid GarbageCollectorThread working at the same time

- build.gradle
- metadata-drivers/etcd/build.gradle
- metadata-drivers/etcd/src/test/java/org/apache/bookkeeper/metadata/etcd/testing/EtcdTestBase.java
ETCD test flake / hang occasionally causing CI job timeout.
Added global timeout - kill test early if hanged
fork tests jvm - I think it helped locally (no repro) but possibly just reduced frequency of hangs 
fixed noop slf4j warning, also to see log in case of hang 
Master Issue: #3044
> ISSUE 3044: ETCD tests hang.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/ReadCache.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/WriteCache.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMap.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMapTest.java
We found that the pulsar broker frequently appeared Full Gc, and found by dumping the heap memory: org.apache.pulsar.broker.service.Consumer#pendingAcks occupies 9.9G of memory. The pendingAcks variable is defined as follows:
The heap memory usage is as follows：
**The old age continues to rise until the FULL GC is triggered, which causes the connection between the broker and the zookeeper to time out, and finally causes the pulsar broker process to exit:**
Full GC:
zookkepeer session timeout:
I found that ConcurrentLongLongPairHashMap only supports expansion, not shrinkage, and most of the memory is not used and wasted.
Of course, this structure is used not only in pulsar, but also in the read and write cache of bookkeeper, which will also lead to a lot of memory waste：
When removing, …
> Optimize memory：Support shrinking in ConcurrentLongLongPairHashMap

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/JournalChannel.java
In current JournalChannel implementation, it create fileChannelProvider instance every time, which is unnecessary.
https://github.com/apache/bookkeeper/blob/4debbbf84db09f80ffeb4154e8e6feed134be0c0/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/JournalChannel.java#L162
Create fileChannelProvider in Journal creation, avoiding call fileChannelProvider init multiple times.
> Avoiding call fileChannelProvider init multiple times

- build.gradle
When run command `./gradlew publishToMavenLocal` to publish jars to local maven repository, it failed with the following exception.
```
Maven publication 'maven' pom metadata warnings (silence with 'suppressPomMetadataWarningsFor(variant)'):
- Variant testFixturesApiElements:
- Declares capability bookkeeper:bookkeeper-common-test-fixtures:unspecified which cannot be mapped to Maven
- Variant testFixturesRuntimeElements:
- Declares capability bookkeeper:bookkeeper-common-test-fixtures:unspecified which cannot be mapped to Maven
These issues indicate information that is lost in the published 'pom' metadata file, which may be an issue if the published library is consumed by an old Gradle version or Apache Maven.
The 'module' metadata file, which is used by Gradle 6+ is not affected.
> Task …
```
> Fix gradle publishToMavenLocal failed

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
When the checkallledgers method is executed periodically, if an exception is thrown, 
time checkAllLedgers statistics status has not been updated. 
So we should update it in finally：
finally {
if (!checkSuccess) {
long checkAllLedgersDuration = stopwatch.stop().elapsed(TimeUnit.MILLISECONDS);
checkAllLedgersTime.registerFailedEvent(checkAllLedgersDuration, TimeUnit.MILLISECONDS);
}
}
> fix checkAllLedgersDuration compute

- stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/store/MVCCStoreFactoryImplTest.java
Test flaked on CI
Fixed test
Master Issue: #3031
> [ISSUE 3031] fixed test; chooseThread() uses orderingKey as a param, not a thread index

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/MathUtils.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/util/TestThreadSelection.java
uneven routing of requests to threads caused by uneven distribution of ledger Ids can leave some threads underutilized
Experimented with a few approaches and picked the simplest/fastest one that produced good results.
Locally tested with keys (ledger ids) up to 100mil across up to 512 threads.
This does not address the fact that generated ledger ids are skewed towards even numbers.
This does not fix routing of the journals/data dirs. 
Master Issue: #2974
> Issue 2974: better thread selection for the Ordered Executor

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/ReadAheadEntryReader.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestBKDistributedLogManager.java
DLM test suite was flaky.
Repro/troubleshooting shows that DLM can skip over a data segment on read.
Test + fix (don't move segment if it moved already).
Master Issue: #2898
> ISSUE 2898: DistributedLogManager can skip over a segment on read.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSet.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSet.java
Cleanup all the buckets that were in Deleted state, so that we can reduce unnecessary expansions.
when removing，Cleanup all the buckets that were in Deleted state.
> reduce unnecessary expansions for  ConcurrentLong map and set

- build.gradle
When use `./gradlew publishToMavenLocal` command to publish jars to local maven repository, it doesn't include test jars.
When publish, including the test jars.
> Fix publish do not include test jar

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSet.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMap.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSetTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMapTest.java
We provide some concurrent maps and sets for specific usage, and provide size() and capacity() interface for user to get the real item number and the max item number. 
However, if user want to monitor how much memory those current maps and set allocated, there is not interface to expose this metric.
Add `sizeInBytes()` interface to expose the memory size has been allocated for those concurrent maps and sets.
> Add sizeInBytes interface for ConcurrentLong map and set

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
When a bookie restart, the garbageCollectorThread will rebuild entryMetadataMap from all the entry log files in ledger directory. For normal case, it will extract the EntryLogMetadata from the index in entry log file. However, if there's no index, then fallback to scanning the entry log file. 
In user's production environment, the log files without index occupied 4%. The total entry log files is 80000, and the log files without index is 3000. The default entry log file size is 2GB, and the garbageCollectorThread will read 3000 * 2GB = 6TB data without speed limit, which will cause ledger disk IO util runs high for dozens of minutes and affect ledger read and write latency.
1. Add read speed rate limiter for scanning entry log file in entryMetadataMap rebuild.
> Add throttle for rebuild entryMetadataMap

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
fix a metric error in bookieStats
getReadEntryStats().registerFailedValue(entrySize) -> getReadBytesStats().registerFailedValue(entrySize)
> fix a metric error in bookieStats

- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/journal/JournalWriter.java
Current bkperf message rate limit use `int` to store the rate value, however, max rate will be limit by `MAX_INTEGER` value to 2GB. We'd better use long to support higher message rate limiter.
Use `long` instead of `int` to store the message rate limit value.
> Fix bkperf message rate limit to 2GB/s

- .github/workflows/website-deploy.yaml
At the moment every night at 00:00 UTC the website job will try to update the `asf-site` branch content.
It is better to run this job whenever a new change is committed to the master branch in order to easy rollback changes and know exactly when the website will be updated.
* the job now runs whenever a commit is pushed to `master` and it change at least a file inside `site/`
> [website] update website every time there is a change

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSet.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSetTest.java
In the ConcurrentOpenHashSet class, when reducing unnecessary expansion logic, lastBucket should be used for comparison.
> fix reduce  unnecessary expansions

- dependencies.gradle
- required for compilation on JDK 17
- see https://projectlombok.org/changelog
> bump lombok from 1.18.20 to 1.18.22 to support java17 compile

- dependencies.gradle
- Bump the testcontainers version to make tests can run on the latest docker on `Mac Intel Chip`
- Bump `docker-java` version to `3.2.13`
> Bump testcontainers version to 1.16.3

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
method:triggerFlushAndAddEntry costing time is a changing,so add a stats metric focus on this method 
1.the previous counter metrics(throttledWriteRequests) are retained
2.add throttledWriteStats to record cost time and count for the method(triggerFlushAndAddEntry)
> add stats for throttled-write

- build.gradle
In Gradle you need to add `mavenLocal()` repository if you want to test local versions of third party libraries built with Maven (like ZooKeeper, Curator...)
Add `mavenLocal()`  repository
> Gradle build: add mavenLocal() repository

- .github/workflows/website-staging-deploy.yaml
- site/scripts/publish-website.sh
- site3/website/scripts/build-website.sh
The website deploy fails in this way: https://github.com/apache/bookkeeper/runs/5588066218?check_suite_focus=true
A workaround is to clone the repo using SSH instead of HTTPS
https://stackoverflow.com/questions/22147574/fatal-could-not-read-username-for-https-github-com-no-such-file-or-directo
* Clone repo using ssh before pushing to asf-site
* Remove javadoc generation for old javadoc in staging site - this could be done in another PR but in this way we should be able to unblock it with less PR overhead - we'll add javadoc manually later on (atm [it fails](https://github.com/apache/bookkeeper/runs/5588079677?check_suite_focus=true) but there is no need to rebuild them everytime
> [website] Fix deploy push to git - use ssh

- .github/workflows/website-deploy.yaml
- .github/workflows/website-staging-deploy.yaml
- site/scripts/publish-website.sh
- site3/website/scripts/publish-website.sh
At the moment the website deployment fail due to lack of write permissions to the repo. we can use the GH_TOKEN for the authentication
* Clone repositories with GH_TOKEN before pushing
> [website] use GH_TOKEN to push to asf-site and asf-staging branches

- .github/workflows/website-deploy.yaml
- .github/workflows/website-staging-deploy.yaml
- site/scripts/publish-website.sh
- site3/website/scripts/publish-website.sh
GH_TOKEN is not set by default. At the moment it fails in this way:
>fatal: could not read Username for 'https://github.com/': No such device or address
* Set GITHUB_TOKEN with the secrets.GITHUB_TOKEN value
* Add fake user while cloning
> [website] fix GITHUB_TOKEN used for deployment

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadLacProcessorV3.java
NoLedgerException does not signify an error in the Bookie that needs
to be fixed. Instead it is a user error that the user is notified about via
the status code `ENOLEDGER`.
Logging this problem at error level introduces an odd difference
between the behaviour of readLac using v2 versus v3 protocol version.
In the former case ReadEntryProcessor logs the same problem at debug
level. As a result changing protocol version appears to be introducing
an error.
> Log NoLedgerException at debug level

- docker/Dockerfile
Make `BOOKIE_HTTP_PORT` optional in `docker run`.
Docker entrypoint will replace `httpServerPort` with `BOOKIE_HTTP_PORT`.
This will cause invalid port if `BOOKIE_HTTP_PORT` is unset in docker
run.
Fixes #3075.
Master Issue: #3075
> Set BOOKIE_HTTP_PORT to make it optional in docker run

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- dependencies.gradle
- pom.xml
Upgrade to newest version of RocksDb which has support for Mac with M1 architecture.
> Upgrade rocksdb to 6.29.4.1

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/BookieAutoRecoveryTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
The test testEmptyLedgerLosesQuorumEventually kills two bookies, and very often it kills the Auditor Bookie.
- BookKeeperClusterTestCase.getAuditor(), ensure that we pick up a Auditor that is running and that is not going to die soon
- ReplicationWorker exits the main loop in case of InterruptedException masked by a UnavailableException (this reduces a lot the spam in the logs, because in any case the thread is deemed to always fail for InterruptedExceptions)
- in testEmptyLedgerLosesQuorumEventually ensure that the Auditor runs and start a new Bookie before the final check (the Auditor does nothing if the is no "bookie to audit", so there are races in which if the cluster does not change the Auditor does not kick in in any case)
> BookieAutoRecoveryTest.testEmptyLedgerLosesQuorumEventually fix flaky test, ensure that the Auditor is alive

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LocalBookieEnsemblePlacementPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestSpeculativeRead.java
When Bookie sanity and autoreovery use the same conf file which has flag `reorderReadSequenceEnabled=true` then bookie-sanity command throws NPE as `LocalBookieEnsemblePlacementPolicy::reorderReadLACSequence` returns null writesets which causes the sanity failure.
```
00:46:46.202 [BookKeeperClientWorker-OrderedExecutor-11-0] ERROR o.a.b.common.util.SafeRunnable       - Unexpected throwable caught 
java.lang.NullPointerException: null
at org.apache.bookkeeper.client.PendingReadOp$SequenceReadRequest.sendNextRead(PendingReadOp.java:399)
at org.apache.bookkeeper.client.PendingReadOp$SequenceReadRequest.read(PendingReadOp.java:385)
at org.apache.bookkeeper.client.PendingReadOp.initiate(PendingReadOp.java:529)
at org.apache.bookkeeper.client.LedgerRecoveryOp.doRecoveryRead(LedgerRecoveryOp.jav …
```
> Fix NPE while reordering read-sequence for local-bookie ensemble policy

- bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java
- bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusTextFormat.java
- bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/PrometheusTextFormatTest.java
- bookkeeper-stats/src/main/java/org/apache/bookkeeper/stats/StatsProvider.java
Fixes #3136 
fix duplicate typeline for prometheus type
remember the prometheus type, record in set, incase print again
Master Issue: #3136
> fix duplicate typeline for prometheus type

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-server/pom.xml
- dependencies.gradle
- pom.xml
- src/owasp-dependency-check-suppressions.xml
- stream/statelib/pom.xml
- stream/storage/impl/pom.xml
We are using an old version of ZooKeeper, 3.6.x (and ZooKeeper 3.5.x was declared EOL a few weeks ago).
We should upgrade to the latest version.
- Upgraded ZooKeeper dependency.
- Exclude LogBack
- Add junit5 jupiter-api required by org.apache.zookeeper.test.ClientBase
In PR #3084 I tried to update ZooKeeper in Gradle files, but without success.
This patch focuses only on Maven
> Upgrade ZooKeeper to 3.8.0

- stream/clients/python/setup.py
Prepare python client for 4.14.5 release as described in the [release guide](https://bookkeeper.apache.org/community/release_guide/#change-python-client-version)
* Bump python client to 4.14.5
> [branch-4.14] Bump Python client version to 4.14.5

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
https://github.com/apache/bookkeeper/pull/2686 introduce RocksDB compaction on checkpoint to fix seeking RocksDB metadata timeout issue. However, trigger RocksDB compaction is a heavy operation and the checkpoint will be triggered in high frequency, which cause db-storage-cleanup thread always into high load, and make the cpu keeps 100%. https://github.com/apache/bookkeeper/pull/2686#issuecomment-1065893543 
Related logs: https://github.com/apache/bookkeeper/pull/2686#issuecomment-1065888832
In order to fix this issue, we divide into two steps.
1. Remove the compactRange logic in during checkpoint
2. Figure out smarter solution for deleted entry compaction in RocksDB
This is the first part.
I have sent a discuss into dev mail list. …
> Revert rocksdb compaction on checkpoint to reduce cpu intensive

- site/_config.yml
- site3/website/docusaurus.config.js
- site3/website/src/components/RecentReleases/index.js
- site3/website/src/pages/releases.md
The current stable version is 4.14.4 but in the website is still 4.11.1
* Edit variables to point to 4.14.4
* Cleanup staging website "download" page
> [website] Update current stable version to 4.14.4

- pom.xml
- src/apple_m1_aol.properties
Support apple m1 `mvn clean package -DskipTests`
- add profile for apple m1 using different `aol.properties` based on https://github.com/maven-nar/nar-maven-plugin/pull/382
- bump lombok to 1.18.22 to support jdk17 package. I think that it was mis-reverted by #3130(the gradle is now 1.18.22) and it doesn't worth open a new pr. Please point out if I am wrong :)
test on my apple m1 mbp
> [build] support apple m1 build

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- dependencies.gradle
- pom.xml
- the bkctl and bk-server has different `http-core` version
- unify the `http-core` version to 4.4.15
> [build] fix master branch broken http-core license check

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/TopologyAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicy.java
It is unnecessary to update  topology, removing and adding the same bookieNode, if the rack of bookie stay unchanged.
> only update topology when bookie rack changed

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- dependencies.gradle
- pom.xml
Upgrades log4j2 version to fix a problem using the log4j bridge.
Upgrade log4j2 version from `2.17.1` to `2.17.2`.
The motivation is that there are multiple issues related to log4j bridge fixed in that minor version: https://logging.apache.org/log4j/2.x/changes-report.html#a2.17.2 
Note that this issue should be cherry-picked to `branch-4.15`.
Master Issue: #3165
The problem was introduced in `2.17.1`. This is the result we obtained running a local Bookie with `2.17.1`:
```
bin/bookkeeper localbookie 1
2022-04-06T18:54:18,075 - WARN  - [main:ServerCnxnFactory@309] - maxCnxns is not configured, using default value 0.
2022-04-06T18:54:18,250 - WARN  - [main-SendThread(127.0.0.1:2181):ClientCnxn$SendThread@1279] - An exception was thrown while closing send thread for session …
```
> Issue 3165: Bookie does not show logs in 4.15.0rc0

- native-io/build.gradle
- native-io/pom.xml
- native-io/src/main/assembly/assembly.xml
- native-io/src/main/java/org/apache/bookkeeper/common/util/nativeio/NativeIO.java
- native-io/src/main/java/org/apache/bookkeeper/common/util/nativeio/NativeIOException.java
- native-io/src/main/java/org/apache/bookkeeper/common/util/nativeio/NativeIOImpl.java
- native-io/src/main/java/org/apache/bookkeeper/common/util/nativeio/NativeIOJni.java
- native-io/src/main/java/org/apache/bookkeeper/common/util/nativeio/NativeUtils.java
- native-io/src/main/java/org/apache/bookkeeper/common/util/nativeio/package-info.java
- native-io/src/main/native-io-jni/build.gradle
- native-io/src/main/native-io-jni/cpp/native_io_jni.c
- pom.xml
This is the first task of BP-47
Provide an interface to the POSIX IO API + extensions for O_DIRECT and Linux's fallocate API in order to support direct IO on supported systems.  Direct IO will allow us to bypass cache layers in the underlying operation system, improving memory usage and reducing unnecessary I/O operations to fill caches that won't be used.
> BP-47 (task1): Add native IO library support

- pom.xml
- stream/distributedlog/common/pom.xml
- stream/distributedlog/core/pom.xml
- stream/distributedlog/pom.xml
- stream/pom.xml
- tests/integration-tests-base-groovy/pom.xml
Allow running units test on jdk17
- add `test.additional.args` to open java modules
- apply the args on `maven-surefire-plugin`
> Allow running units test on jdk17

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadLacProcessorV3.java
When read Lac from ledger, we won't throw NoEntryException, remove this exception catch.
Remove the NoEntryException catch in ReadLac operation.
> remove unnecessary exception catch

- conf/bk_server.conf
https://github.com/apache/bookkeeper/pull/1612 this PR make the Netty io threads number configurable, but doesn't expose to the `bk_server.conf`. This parameter will be usually changed in performance tuning especially deploy this bookie on bare metal which have many cpus. For operation engineer who is unfamiliar with the source code will be hard to do performance tuning.
Expose this parameter configuration into `bk_server.conf` and website. And add more explanation about it.
> Expose Netty threads num config to bk_server.conf

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
The throttler has been checked whether throttle by bytes in `acquire` method, we doesn't need double check.
Remove the double check of whether throttle by bytes.
> Simplify throttle code in metadata scanning

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionTest.java
In `CompactionTest.testCompactionPersistence()`, it specified a directory as rocksdb storage path, but does't clean up it when the test finished.
https://github.com/apache/bookkeeper/blob/e937ae9a6838fd533c3973d6ae6c32d98b6619bd/bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionTest.java#L1011-L1012
Use tmpDir to manage the created directory and clean up the resources when test finished.
> Fix testCompactionPersistence do not cleanup created directory

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/GarbageCollectorThreadTest.java
replace deprecated api use MockitoAnnotations.initMocks
> [minor] [cleanup] replace deprecated api use MockitoAnnotations.initMocks

- bookkeeper-dist/src/assemble/bin-all.xml
add the missing binary to package
> bookeeper-all package missing stream binary
