apache/bookkeeper

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- dependencies.gradle
- pom.xml
Current jetty version is vulnerable to https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-34429
* Upgrade to the latest 9.x one 9.4.46.v20220331
> Bump jetty to 9.4.46.v20220331 to get rid of CVE-2021-34429

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperAdminTest.java
Fix #3222 
The root cause is that BookKeeperAdmin use `asyncReadEntriesInternal` to read entries. However, the `asyncReadEntriesInternal` doesn't check the lastAddConfirm, which will lead to the exception list in issue 3222
Add lastAddConfirm check before call `asyncReadEntriesInternal`
> Fix read empty ledger exception using bookkeeper admin

- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ListUnderReplicatedCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ToggleCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/FormatUtil.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/LastMarkCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListActiveLedgersCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListFilesOnDiscCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListLedgersCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadJournalCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLedgerCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLogCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/EndpointInfoCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/InfoCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/ListBookiesCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/RecoverCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/LedgerMetaDataCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/SimpleTestCommand.java
In PR #2455 , It convert all `System.*.print` statements to `LOG.* statements`. However, in `LOG.*` statements, it uses string concatenation to print messages, which is low performance.
Change the string concatenation format to `LOG.*` standard statements
> Format log statements

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
When run `bin/bookkeeper shell ledgermetadata -h` command, it throw the following exception.
```
23:02:41,236 ERROR Error parsing command line arguments :
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -h
at org.apache.commons.cli.Parser.processOption(Parser.java:363) ~[commons-cli-commons-cli-1.2.jar:1.2]
at org.apache.commons.cli.Parser.parse(Parser.java:199) ~[commons-cli-commons-cli-1.2.jar:1.2]
at org.apache.commons.cli.Parser.parse(Parser.java:85) ~[commons-cli-commons-cli-1.2.jar:1.2]
at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:240) ~[org.apache.bookkeeper-bookkeeper-server-4.16.0-SNAPSHOT.jar:4.16.0-SNAPSHOT]
at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:2372) …
```
> Fix bookie shell help command exception

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookiesListener.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/EnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandleAdv.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/SpeculativeRequestExecutionPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClient.java
Some interfaces have modified the method signature but the annotations have not.
Correct the method signature within annotations and fix typos
> Correct the method signature within annotations

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ListUnderReplicatedCommand.java
- site3/website/docs/reference/cli.md
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ListUnderReplicatedCommandTest.java
Fix #3224 
Add flag for `ListUnderreplicatedCmd` to control only display under replicated ledgers count
> Add get under replicated ledger count

- pom.xml
- add jdk17 required module opens
- bump junit5 version from 5.6.2 to 5.8.2
- bump powermock version from 2.0.2 to 2.0.9
> fix some jdk17 test problem

- bookkeeper-server/pom.xml
Fix #3243 
Allow run LocalBookkeeper directly on IDE. It's typicaly useful for beginners or who want to figure out how bookkeeper works.
- change `snappy-java` and `metrics-core` scope from test to runtime
- mark `snappy-java` and `metrics-core`  dependency optional
we have scope compile dependency in `bookkeeper-dist-server`, so the shell goes well
> Allow run LocalBookkeeper directly in `bookkeeper-server` module or on IDE

- site3/website/docusaurus.config.js
4.15.0 is the latest release but we didn't change it during the release process
* Set 4.15.0 as latest release on the website
> [website] Set 4.15.0 as latest release

- site/docs/4.14.0/overview/overview.md
- site3/website/docs/overview/overview.md
- site3/website/src/pages/releases.md
- site3/website/versioned_docs/version-4.15.0/overview/overview.md
- version.gradle
Some files have version 4.15.0-SNAPSHOT in them (gradle, since it is not used in the release, and some docs that are actually visible on the website)
Changed to correct versions
> cleaning up leftover 4.15-snapshot versions

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- dependencies.gradle
- pom.xml
prometheus client `0.8.1` is release on Jan,2020, Keep update
Bump prometheus client version from 0.8.1 to 0.15.0
Update prometheus client to 0.15.0, compare the metrics txt, the results are same.
> Bump prometheus client version to 0.15.0

- README.md
- site3/website/src/pages/community/issue-report.md
Invalid hyperlink for Apache Pulsar#persistent-storage
Update hyperlinks
[installation guide](https://bookkeeper.apache.org/docs/next/getting-started/installation/)
[documentation](https://bookkeeper.apache.org/docs/next/overview/)
Master Issue: #3275
> ISSUE#3275:fix hyperlink for bookkeeper.apache.org

- site3/README.md
- site3/website/scripts/release-major.sh
- site3/website/scripts/release-minor.sh
- site3/website/src/pages/community/release-guide.md
There's no easy transition in the doc for new releases.
* Added two new scripts `./site3/website/scripts/release-minor.sh` and ./site3/website/scripts/release-major.sh`
* Added instructions [here](https://github.com/apache/bookkeeper/blob/18e9b45568749bbfebe8d8d75d90e5dd4253464d/site3/README.md)
* Updated release guide doc
> [website] Add script for cut new release (release-notes, new docs, sidebar..)

- site3/website/docusaurus.config.js
- site3/website/src/components/RecentReleases/index.js
- site3/website/src/pages/releases.md
Fix #3290
* Fixed the SHA link, we use SHA512
* Fixed source and binary links to use closer.lua instead of archive.apache.org
* Increased the visibility of the checksum validation procedure
Master Issue: #3290
> [website] Make download page fully ASF compliant

- pom.xml
- stream/distributedlog/pom.xml
Keep plugin version update. I am trying to make bookkeeper can run on windows(more developers can join this project). I believe update some maven plugin versions can help a little.
- bump jacoco maven plugin from 0.8.0 to 0.8.8
- bump maven-clean-plugin from 2.5 to 3.2.0
- bump maven-compiler version to 3.10.1
- bump maven-jar-plugin from 2.4 to 3.2.2
- bump nar-maven-plugin from 3.5.2 to 3.10.1
- delete a unnecessary dependency, it's already defined in parent pom
both `google-http-client-gson` and `maven-settings` are not related to this PR
> [build] misc bump serveral maven plugin version

- cpu-affinity/src/main/affinity/cpp/affinity_jni.c
- native-io/src/main/native-io-jni/cpp/native_io_jni.c
master compile is broken by #2549 
Add windows `#ifdef _WIN32` directive on `define`. Test on my m1 mac and windows 10.
> [build] [windows] fix broken master code compile error strerror_s

- pom.xml
Fixes #1514.
1. Configuring maven-javadoc-plugin with `detectOfflineLinks=false` eliminates the Maven invocations (refer to: [https://issues.redhat.com/browse/ISPN-8629](https://issues.redhat.com/browse/ISPN-8629)).
2. Use option `notimestamp` to replace `additionalparam` since the latter is not allowed from version `3.x`.
> ISSUE #1514: Clean up javadoc mojos execution

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/AuthHandler.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/SecurityHandlerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/TLSContextFactory.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
Currently, we initiate hostname verification for the Bookkeeper Client in the `PerChannelBookieClient` class. In order to simplify the code, I propose that we refactor the client so it relies on Netty, its SslHandler/SslEngine, and the JVM, to perform the hostname verification.
When HTTPS is configured as the endpoint verification algorithm, it uses [RFC 2818](https://datatracker.ietf.org/doc/html/rfc2818) to perform hostname verification. This is defined by the Java Security Standard Algorithm Names documentation for JDK versions 8, 11, and 17. Here are the official docs:
* https://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html
* https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html
* …
> [Client] Switch to rely on SslEngine for Hostname Verification

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- dependencies.gradle
- pom.xml
- src/owasp-dependency-check-suppressions.xml
- Bump grpc from 1.45.1 to 1.47.0
- Bump gson from 2.8.9 to 2.9.0
- Bump perfmark-api from 0.23.0 to 0.25.0
- add dependency check suppressions
> Bump grpc from 1.45.1 to 1.47.0, solve dependency check FP

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LegacyCookieValidation.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CookieTest.java
Fixes a bug when validating the Cookie that may fail to consider a custom Bookie ID when configured.
Added custom Bookie ID when executing `possibleBookieIds()` in `LegacyCookieValidation`. Note that this was already fixed few months back, concretely in this PR: https://github.com/apache/bookkeeper/pull/2796
But it seems that the regression bringing back the old behavior was introduced in PR #2901.
This change may need to be cherry-picked to `branch-4.15`.
Master Issue: #3306
Signed-off-by: Raúl Gracia <raul.gracia@emc.com>
> Issue 3306: Bookie can't start after rebooting due the cookie mistmatch

- .github/workflows/macos-build.yml
- .github/workflows/windows-build.yml
Enable maven batch mode to reduce log in mac and windows workflow
> Enable maven batch mode to reduce log in mac and windows workflow

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
---
When adding an entry into a bookie, the entry data lifecycle
is handled by the bookie client. The data buffer will be
released after receiving a corresponding response from the
bookie server. So the user doesn't care about the entry
buffer releasing.
But when the ledgerHandler is closed, the PendingAddOp is not
recycled which leads to the data buffer never being released.
We should release that after the callback is executed.
> Fix the PendingAddOp is not recycled when LedgerHandler closed

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
While testing #3310, I noticed that the `PerChannelBookieClient#exceptionCaught` logic contains redundant logs when the exception is an `SSLException`. This PR removes a redundant log from client.
Based on reading through the rest of the method, this should be a trivial change with no other side effects. My one question is how closing a channel and closing the context differ. Technically, returning early skips the `ctx.close()`, which could change the behavior.
* Return early to prevent a redundant log
> [Client] Deduplicate error log for SSLException

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
---
**Motivation**
If the request is a V2 add request, we retained the data's
reference when creating the AddRequest object. To avoid the
object leak, we need to release the reference if we met
any errors before sending it.
>  Fix the V2 AddRequest object leak issue

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/BookieBackpressureForV2Test.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorTest.java
---
*Motivation*
If one bookie is slow (not down, just slow), the BK client
will the acks to the user that the entries are written after
the first 2 acks. In the meantime, it will keep waiting for
the 3rd bookie to respond. If the bookie responds within the
timeout, the entries can now be dropped from memory, otherwise
the write will timeout internally and it will get replayed
to a new bookie.
In the V3 request, we have [server-side backpressure](https://github.com/apache/bookkeeper/pull/1410)
to impact the client-side behaviors. We should apply the same
changes to the V2 request. That would help this [issue](https://github.com/apache/pulsar/issues/14861)
to be resolved.
*Modification*
- Apply the change https://github.com/apache/bookkeeper/pull/1410 to V2 protocol
Descriptions of the …
> Apply the backpressure changes on the V2 requests

- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTestClient.java
`statsProvider` is actually null, no need assign
> Remove unused value assign in BookKeeperTestClient

- README.md
The code guide link https://bookkeeper.apache.org/community/coding_guide is not found.
Change the link to https://bookkeeper.apache.org/community/coding-guide
> Fix broken link of code guide in README

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerChecker.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieDecommissionTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestLedgerChecker.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/BookieAutoRecoveryTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
Currently decomm malfunctions on an empty ledger:
Autorecovery ends up removing such ledger from the list of underreplicated ledgers but does not update the ensemble leaving the bookie being decommed there and Auditor will add these ledger back on the next run. 
In greater details:
Currently the ReplicationWorker/LedgerChecker end up skipping fragment where ES > WQ and failed bookie is not in the writeset (or a ledger is empty). 
E.g. with ES = 3, WQ = 2
Ensemble: (bk1, bk2, bk3)
bk3 is dead.
if ledger is empty (and e.g. closed) it is added to the list of underreplicated ledgers but autorecovery skips it (no failed fragments, dead bookie remains in the metadata) and simply removes it from UR ledgers (until next Auditor's run adds it back).
This …
> ISSUE 3220: Autorecovery does not process underreplicated empty ledgers

- pom.xml
- tests/pom.xml
There is a CVE in testing, which was introduced by groovy.
```
Error:  Failed to execute goal org.owasp:dependency-check-maven:7.1.0:aggregate (default) on project bookkeeper: 
Error: 
Error:  One or more dependencies were identified with vulnerabilities that have a CVSS score greater than or equal to '7.0': 
Error: 
Error:  testng-6.13.1.jar: CVE-2019-[11](https://github.com/apache/bookkeeper/runs/6953376087?check_suite_focus=true#step:6:12)358(7.5)
Error: 
Error:  See the dependency-check report for more details.
Error:  -> [Help 1]
Error: 
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error: 
Error:  For more information about the errors and possible solutions, please read the …
```
> upgrade groovy from 2.5.17 to 3.0.11 to fix CVE-2019-11358(7.5)

- .github/workflows/bookie-tests.yml
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageTest.java
The `bookie-tests` CI runs the following tests.
```
- name: Run bookie tests
run: mvn -B -nsu -pl bookkeeper-server test -Dtest="org.apache.bookkeeper.bookie.*Test" -DfailIfNoTests=false -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
```
For the `remaining-tests` CI runs the following tests.
```bash
- name: Run remaining tests
run: mvn -B -nsu -am -pl bookkeeper-server clean install test -Dtest="!org.apache.bookkeeper.client.**,!org.apache.bookkeeper.bookie.**,!org.apache.bookkeeper.replication.**,!org.apache.bookkeeper.tls.**" -DfailIfNoTests=false -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
```
The problem is that `bookie-tests` only run tests with the name `org.apache.bookkeeper.bookie.*Test`, however, the `remaining-tests` exclude tests with name `org.apache.bookkeeper.bookie.**`. It …
> Fix bookie CI test not run

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java
https://github.com/apache/bookkeeper/pull/2989
Use estimateMaxDirectMemory instead of maxDirectMemory
> Use estimateMaxDirectMemory instead of maxDirectMemory

- bookkeeper-proto/src/main/proto/DataFormats.proto
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Cookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LegacyCookieValidation.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CookieIndexDirTest.java
stage 2: add and check indexDirs in cookie meta
1. add indexDirs in cookie meta
2. check indexDirs in cookie meta
3. add a testcase for cookie
> add and check indexDirs in Cookie meta

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
AR keeps on logging NPE during rereplication:
```
[ReplicationWorker] WARN  org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Received exception while trying to get network location of bookie: ...
java.lang.NullPointerException: null 
```
The NPE seems to be easily avoidable, no need to throw exception and log it just to ignore.
Added check for bookie being present in the knownBookies map before accessing it.
> Fix: NPE in RackawareEnsemblePlacementPolicyImpl logged by AutoRecovery

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Cookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/cookie/GenerateCookieCommand.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/GenerateCookieCommandIndexTest.java
stage 2: add a funtion in cookie_generate for update indexDirs
1. add a optional param(named --index-dirs) for updating indexDirs
2. add a testcase for GenerateCookieCommand
> Add a param in cookie_generate for updating indexDirs

- site3/website/scripts/javadoc-gen.sh
`javadoc-gen.sh` still uses Gradle for master branch.
- Remove gradle and always use maven
Failure check: https://github.com/apache/bookkeeper/runs/7211295355?check_suite_focus=true
> Remove gradle usage from Javadoc gen script

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageIndexDirTest.java
stage 3~4 : 
1) disk monitor(DiskChecker/LedgerDirsMonitor) have checked indexDir,it's good; 
2) add indexDirs in statsLogger, and add indexDirs's Listener. 
1. add indexDirs in statsLogger, and add indexDirs's Listener. 
2. update index's testcase for SingleDirectoryDbLedgerStorage
> Stage 3~4 : Add indexDirs in statsLogger, add indexDirs's Listener. 

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/FlatLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LegacyHierarchicalLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MSLedgerManagerFactory.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationException.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ListUnderReplicatedCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/QueryAutoRecoveryStatusCommand.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ToggleCommand.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/ForceAuditorChecksCmdTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
- metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManagerFactory.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ListUnderReplicatedCommandTest.java
Shut down Replication Worker and Auditor on non-recoverable ZK error
Some errors require one to re-create Zk client.
Currently BK and underlying components cannot do that transparently.
When running AutoRecovery as a separate service it does not seem to crash in such cases and keeps on running while unable to do anything useful and requires operator restarting the service manually.
One can see such log messages like 
```
ReplicationWorker] ERROR org.apache.bookkeeper.replication.ReplicationWorker - UnavailableException while replicating fragments
org.apache.bookkeeper.replication.ReplicationException$UnavailableException: Error contacting zookeeper
at org.apache.bookkeeper.meta.ZkLedgerUnderreplicationManager.getLedgerToRereplicate(ZkLedgerUnderrepli …
```
> Shut down ReplicationWorker and Auditor on non-recoverable ZK error

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectWriter.java
The work of the `BP-47` has been very meaningful. I am reading and learning it.
As the title, `useFallocate` in `DirectWriter` has no practical meaning, because the judgment of SystemUtils.IS_OS_LINUX always happens.
> Add static declaration for useFallocate in DirectWriter

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieFileChannel.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultFileChannel.java
The `BookieFileChannel` is package public, and can't be implemented out of the `org.apache.bookkeeper.bookie` package.
We should make it public
Make `BookieFileChannel` and `DefaultFileChannel` public
> Make BookieFileChannel interface public

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- pom.xml
Owasp check fails because jetty 9.4.44 is marked as vulnerable due to [CVE-2022-2047](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-2047)
Note that Jetty 9.4.x is EOL after `9.4.48.v20220622` 
* Upgrade to latest 9.4.x (9.4.48.v20220622)
(see https://github.com/eclipse/jetty.project/releases)
> [security] Upgrade Jetty to 9.4.48.v20220622 to get rid of CVE-2022-2047

- bin/common.sh
- deploy/kubernetes/gke/bookkeeper.statefulset.yml
- deploy/kubernetes/gke/bookkeeper.yaml
- stream/conf/streamstorage_cli_env.sh
- stream/conf/streamstorage_env.sh
Fix #3295
Currently, localbookie can't run with jdk17
- remove flag AggressiveOpts
- add flag AutoBoxCacheMax=20000
- add flag BiasedLockingStartupDelay=500
> [ISSUE 3295]Fix JVM exited when running localbookie with jdk17 (#3295)

- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ConvertToInterleavedStorageCommand.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/ConvertToInterleavedStorageCommandTest.java
stage 10 (the last one): 
1)  bugfix indexDirs for ConvertToInterleavedStorageCommand:
init index's LedgerDirsManager use conf.getIndexDirs but old code use conf.getLedgerDirs
the condition that the bug triggers:
1)  when conf.getIndexDirs is different from conf.getLedgerDirs
1.  bugfix indexDirs for ConvertToInterleavedStorageCommand
2. update index's testcase for ConvertToInterleavedStorageCommand( set multi different ledger and index dirs)
> stage 10: bugfix indexDirs for ConvertToInterleavedStorageCommand

- site3/website/src/theme/DocVersionBanner/index.js
For the non latest releases in the website there's alert that says
"This is documentation for Apache BookKeeper 4.14.5, which is no longer actively maintained."
This is not true
* Overridden the DocVersionBanner component to be always null as suggested in the Docusaurus doc https://github.com/facebook/docusaurus/issues/3013
Note that we could add the banner only for the non mantained releases but currently we don't distinct them in the codebase. This would be a useful improvement for the future
> [website] Remove alert for non mantained releases

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieStateManager.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieZKExpireTest.java
Flaky test
AFAICT from [my repro](https://github.com/apache/bookkeeper/issues/3206#issuecomment-1190618336), the test flakes depending whether the ZK client gets the SessionExpired error or not.
Reworked the test to reflect the behavior, added some logging.
Master Issue: #3206
> Issue 3206: Flaky-test: BookieZKExpireTest.testBookieServerZKExpireBehaviour

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
In #3108, we have switched to use GrowableArrayBlockingQueue for the OrderedExecutor.
I've been doing some testing recently, with respect with throughput and latencies when there are many small requests being passed on. This was on newer machines and using Java 17, so my conclusion is that many things have changed since when I did add that class back in the day :). 
I've tested with `LinkedBlockingQueue`, `GrowableArrayBlockingQueue`, JCTools based queue and Cognizant disruptor based queue, in the context of the OrderedExecutor, running in a Pulsar broker and BK bookie.
I've actually lost the document with all the results :/, though the summary was that: 
1. `LinkedBlockingQueue` had the best throughput and latency. Behavior was very stable
2. `GrowableArrayBlockingQueue` had decent …
> Switch back ordered executor to LinkedBlockingQueue

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDirsManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDirsMonitor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerDirsManagerTest.java
- conf/bk_server.conf
- site3/website/docs/reference/config.md
Fix #3141 
If we configure multi ledger disks, the bookie will transition to read-only mode when all disks are reached max usage threshold. However, if just one ledger disk reached max usage threshold, the bookie will continue to receive write requests, which will lead to the ledger disk out of space.
Add a flag to control whether to transition to read-only mode when any disks reaches max usage threshold, and when all disks recovered to less than max usage threshold, the bookie will transition to read-write mode.
> Added flag to control whether to transition to read-only mode when any disks full

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogMetadataMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InMemoryEntryLogMetadataMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/PersistentEntryLogMetadataMap.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/PersistentEntryLogMetadataMapTest.java
Prioritize compaction to free up more space faster.
doCompactEntryLogs() iterates over entry logs in whatever natural order they happen to be, picks the first with usage below thresholds and starts compacting.
Added a Priority Queue of entry logs to pick ones with the most compactable space first; it also helps when the time for compaction is limited (via majorCompactionMaxTimeMillis / minorCompactionMaxTimeMillis), instead of spending time on rewriting files with more data we'll pick the files with the least amount of data first.
Master Issue: #3389
> [Issue 3389] Prioritize compaction of entry logs with the lowest amount of remaining usable data

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ZoneawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestZoneawareEnsemblePlacementPolicy.java
If the ensembleList is empty, should not return PlacementPolicyAdherence.MEETS_STRICT.
Return PlacementPolicyAdherence.FAIL to remind user.
> If ensembleList is empty, return PlacementPolicyAdherence.FAIL.

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/concurrent/FutureUtils.java
Enhance future sync wait. 
The same logicment:
https://github.com/apache/bookkeeper/blob/f887f8d7a507800b71b4143a40b0e45902f5f170/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/SyncCallbackUtils.java#L45-L71
> Enhance future sync wait.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileInfo.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ReadOnlyBookieTest.java
Fixes issue #2665 
When the disk is full, `InterleavedLedgerStorage` creates a new entryLog and index file, copies and moves the old index (newFile) `FileInfo` to the new directory, and finally deletes the old index file.
The old file of `FileInfo` was `deleted`, but it was copied and moved a newFile to the new directory. Therefore, the delete status flag should be restored. If it is not set to false,`checkOpen` will throw `FileInfoDeletedException` when judging the fence status of `ledgerHandle` when adding an entry, causing the writing to fail. When the client changes the `ensemble`, it throws an exception because the test has only two bookie nodes and cannot satisfy the two writeSet: `Not enough non-faulty bookies available`.
```java
public synchronized boolean isFenced() throws …
```
> fix Flaky-test: testBookieContinueWritingIfMultipleLedgersPresent

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
```
LongAdder underReplicatedSize = new LongAdder();
FutureUtils.processList(
Lists.newArrayList(ledgers),
ledgerId ->
ledgerManager.readLedgerMetadata(ledgerId).whenComplete((metadata, exception) -> {
if (exception == null) {
underReplicatedSize.add(metadata.getValue().getLength());
}
}), null);
underReplicatedLedgerTotalSize.registerSuccessfulValue(underReplicatedSize.longValue());
```
`FutureUtils.processList`  is async process, should record `underReplicatedLedgerTotalSize` when it completed.
> Fix underReplicatedLedgerTotalSize calculate problem.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandleAdv.java
Avoid init WriteSet when waitForWriteSetMs < 0.
And LedgerHandleAdv didn't recycle `WriteSet`.
> Avoid init WriteSet when waitForWriteSetMs < 0.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/zookeeper/MockZooKeeperTestCase.java
> Fix autoRecover memory leak.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
When we are writing/reading a lot of small entries, one of the main bottleneck in BK client/server becomes the CPU usage. A big part of it is caused by the syscall overhead when writing to the socket. 
The reason is that we have many independent (and small) operations happening on the connection and each time we call `writeAndFlush()` on each of them, causing many `write()` calls on the socket.
Netty has a mechanism to consolidate the flushes on the channel and it improves the handling of many small entries.
> Consolidate Netty channel flushes to mitigate syscall overhead

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSet.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSet.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSetTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSetTest.java
Optimize concurrent collection's shrink and clear logic
1. Reduce the repeated `Arrays.fill` in the clear process
2. When `capacity` is already equal to `initCapacity`,`rehash` should not be executed
3. Reduce the `rehash` logic in the `clear` process
4. Shrinking must at least ensure `initCapacity`, so as to avoid frequent shrinking and expansion near `initCapacity`, frequent shrinking and expansion, additionally opened `arrays` will consume more memory and affect GC.
If this PR is accepted, I will optimize the same `concurrent collection's shrink and clear logic ` defined in pulsar.
Related to #3061 and #3074
> Optimize concurrent collection's shrink logic

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
The disk usage metric and the number of writable directories about ledger directories is duplicated cause `LedgerDirsManager` was created with same ledgerDir more than once, here it is:
1. with `bookie_ledger` scope
https://github.com/apache/bookkeeper/blob/38dc3281f5f175a7d194d4c0d4b255472886187b/bookkeeper-server/src/main/java/org/apache/bookkeeper/server/Main.java#L365-L366
- `bookie_ledger_dir_<ledger directory>_usage`
- `bookie_ledger_writable_dirs`
2. with `bookie` score
https://github.com/apache/bookkeeper/blob/38dc3281f5f175a7d194d4c0d4b255472886187b/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java#L155
- `bookie_dir_<ledger directory>_usage`
- `bookie_writable_dirs`
The second one wasn't bind with a `DiskChecker`, so it's metric never …
> Remove useless and duplicated ledger directory metrics

- bookkeeper-server/pom.xml
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileChannelProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/JournalChannel.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/datainteg/WriteSetsTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieJournalRollingTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieJournalRollingWithReuseJournalTest.java
- pom.xml
> BP-50: Add reuse journal file feature to support Intel PMem disk

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeper.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookieWatcher.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookieWatcherImpl.java
we need release all quarantined bookies when we use the dynamic config to disable the health check. In some case, we disable the health check when the client has add all bookies to `quarantinedBookies`, then we want to recovery all client's read/write capability immediately.
But now we need wait `BOOKIE_QUARANTINE_TIME_SECONDS` reached or we need restart all client, it's too slowly to recovery the client read/write for us.
Release all `QuarantinedBookies`,  after we dynamic disable the  health check.
> [improve][client] release the bookie from QuarantinedBookies when health check is disabled

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
Set a more reasonable default value to avoid OutOfDirectMemoryError.
The default value of  allocatorPoolingConcurrency is 2 * Runtime.getRuntime().availableProcessors(). It's used to specify the num of Arena in PooledByteBufAllocator. 
Assume:
40 processors
80 arena (processors*2)
2 chunk per arena
16MiB per chunk
JVM's total direct mem should be larger then 80*2*16=2560MiB, otherwise OutOfDirectMemoryError occured.
OutOfDirectMemoryError much more likely to occur in Docker, cause JDK versions earlier than Java SE 8U131 does not support Docker CPU limits.
Use Netty default arena num `PooledByteBufAllocator.defaultNumDirectArena()` as default allocatorPoolingConcurrency.
> update default value of allocatorPoolingConcurrency

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexPersistenceMgr.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/IndexPersistenceMgrTest.java
1. `IndexPersistenceMgr` fails to start after crashing index file movement.
1. Add test to assert index file relocation
2. Fix wrong ledger id parse radix for index relocation file in IndexPersistenceMgr
Master Issue: None
> Fix wrong ledger id parse radix for index relocation file in IndexPersistenceMgr

- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ZooKeeperCluster.java
- pom.xml
Bump puppycrawl checkstyle version to 7.8.2. Fix violation
> Bump puppycrawl checkstyle version from 6.19 to 7.8.2

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
Related to https://github.com/apache/pulsar/pull/12993
> Make sure the LedgerHandle close callback can be completed when encounter exception

- bookkeeper-server/pom.xml
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ReadOnlyBookieTest.java
- pom.xml
Fixes issue #3422 
1.`waitForReadOnlyBookie` adds another `listener` thread to observe the node status of bookie, which may be out of sync with the triggering of node changes(`onClusterChanged`) in `EnsemblePlacementPolicy`.This `sequence` leads to flaky test. 
2.Expose bookie nodes in EnsemblePlacementPolicy to client.
3.Just change from watching zk to thread sleep.
We currently don't have any additional requirements for getting bookie nodes on the client side, so it's better to just use thread sleep here. 
Change from `waitForReadOnlyBookie` and `waitForWritableBookie` to thread `sleep`.
3 seconds is enough for most.
> fix Flaky-test: testBookieShouldTurnWritableFromReadOnly

- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java
- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/TestPrometheusMetricsProvider.java
Fix #2637 #3247
The mertics about `jvm_memory_direct_bytes_used` is acquired by netty's `PlatformDependent#DIRECT_MEMORY_COUNTER`. Which can only acquired the memory used by netty.
- use `java.nio.Bits#RESERVED_MEMORY` for jvm direct memory metrics.
- add tests to ensure `jvm_memory_direct_bytes_max` and `jvm_memory_direct_bytes_used` gets value.
> [ISSUE 2637] Fix jvm_memory_direct_bytes_used metrics when using jdk11+

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/conf/TestServerConfiguration.java
- conf/bk_server.conf
Fix #2115 
Add more instructions to note that `minorCompactionInterval` should be greater than `gcWaitTime`.
> [conf] minorCompactionInterval should be greater than gcWaitTime

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
Upgrade log4j2 from 2.17.2 to 2.18.0
> Upgrade log4j2 to 2.18.0

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/JournalAliveListener.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieMultipleJournalsTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/datainteg/WriteSetsTest.java
- pom.xml
fix #2879 
This pull request let bookie quit when there's journal thread exit
As described in #2879, now if a bookie has multi journal directories means it has multi journal thread. Once a journal thread exits, the bookie will be unhealthy due to the block of all bookie-io threads, and then the bookie will not work but progress is still alive.
This pull request tries to fix this problem.
check the journal thread alive in a fixed interval, let bookie quit once there's a journal thread exit
> issue #2879 : let bookie quit if journal thread exit

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Cookie.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CookieIndexDirTest.java
Fixes https://github.com/apache/bookkeeper/issues/3430, make cookie validation is compatible with old version.
I think we should check indexDirs when configuration‘s indexDirectories is setted  rather than avoiding the check 
1. add compatible check 
2. add testcase to cover the new code
> indexDir compatible fix for issue #3430

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultEntryLogger.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerCacheTest.java
Throwing a NoEntryException from the entry logger
for an entry that the index says should exist is
unsafe. It can cause ledger truncation during ledger
recovery. It only takes a single false NoSuchEntry
response to trigger truncation.
NoEntryException should only be thrown from inside
ledger storage if the entry is not found in the index.
Do not throw NoEntryException from EntryLogger on failing to read entry from log file, throw IOException instead.
Master Issue: #2908
> Issue #2908: Replace unsafe NoEntryException with IOException

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-http/vertx-http-server/src/main/java/org/apache/bookkeeper/http/vertx/VertxAbstractHandler.java
- pom.xml
- site3/website/src/pages/release-notes.md
Vertx has several broken api changes. It raised error when embedded  bookkeeper with vertx application
- Bump vertx version from 3.9.8 to 4.3.2
- Adapt vertx broken API changes
> Bump vertx version from 3.9.8 to 4.3.2

- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/BookieBackpressureForV2Test.java
branch-4.14 fails to compile with this error message:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project bookkeeper-server: Compilation failure
[ERROR] /home/lari/workspace-pulsar/bookkeeper/bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/BookieBackpressureForV2Test.java:[34,9] cannot find symbol
[ERROR]   symbol:   method confByIndex(int)
[ERROR]   location: class org.apache.bookkeeper.proto.BookieBackpressureForV2Test
```
- cherry-picking #3324 requires back porting BookieBackpressureForV2Test to branch-4.14 . Replace `confByIndex(0)` with `bsConfs.get(0)`.
> Backport BookieBackpressureForV2Test to branch-4.14

- bookkeeper-common/src/test/java/org/apache/bookkeeper/test/TestStatsProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndexStats.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndexTest.java
- stats/bookkeeper-stats-api/src/main/java/org/apache/bookkeeper/stats/OpStatsLogger.java
- this metric will help to detect when the bottleneck is in the entry location index lookup operations
and RocksDB tuning is needed
Add new operation latency metrics `lookup-entry-location` which will be provided at the same level of metrics as the existing `entries-count` metric.
> Add latency stats for entry location index lookup so that possible RocksDB bottleneck can be detected

- .asf.yaml
- .github/workflows/README.md
---
*Motivation*
Same as Pulsar, Pulsar is using [.asf.yaml](https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Branchprotection) to configure the project,
like the branch protection.
Add .asf.yaml for configuring the PR required CI.
> Add .asf.yaml for configuring the project

- .asf.yaml
- .github/workflows/README.md
- .github/workflows/backward-compat-tests.yml
- .github/workflows/bookie-tests.yml
- .github/workflows/bot.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java17.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/dead-link-checker.yaml
- .github/workflows/integration-tests.yml
- .github/workflows/macos-build.yml
- .github/workflows/owasp-dep-check.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/stream-tests.yml
- .github/workflows/tls-tests.yml
- .github/workflows/windows-build.yml
using [.asf.yaml](https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Branchprotection) to configure the project,
but there 's some config bugfix for project's .asf.yaml
the name of workflow's jobs is not set, so #3439 causes contexts can't match check's jobs
this picture is the other new add pr's running result: the other pr's workflow run abnormally
this picture is current running result: current pr is running normally because the job name is added in yaml file
1.  add the name for checks
2. change required_approving_review_count to 2 person
3. update README.md for workflows
> bugfix for project's .asf.yaml

- .asf.yaml
Now Bookkeeper is using [.asf.yaml](https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Branchprotection) to configure the project,
.asf.yaml details are determined
1)  Whether checks are enough,
now these checks are required:
```
contexts:
- PR Validation
- Backward compatibility tests
- Bookie Tests
- Build with macos on JDK 11
- Build with windows on JDK 11
- Client Tests
- Compatibility Check Java11
- Compatibility Check Java17
- Compatibility Check Java8
- Integration Tests
- Remaining Tests
- Replication Tests
- StreamStorage Tests
- TLS Tests
```
Do we need to add others, such as: OWASP Dependency Check?
2) required_approving_review_count: 
2.1) is there a need for a limit
2.2) or is the value more reasonable, 1 or 2?
mail talking url: …
> Confirm content and update .asf.yaml

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
Fix group ForceWrite not take effect with forceWriteMarkerSent in while loop of ForceWriteThread
Bookkeeper 4.15 has performance issue. There are too many journal sync.
Then I found in ForceWriteThread, forceWriteMarkerSent is reset to false for every loop, and this can cause shouldForceWrite=true and trigger journal sync. This new logic is bringed by https://github.com/apache/bookkeeper/pull/2962
move forceWriteMarkerSent=false out of while loop.
> Fix group ForceWrite not take effect with forceWriteMarkerSent in while loop of ForceWriteThread

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/EventLoopUtil.java
default value of acceptor threadPool is 2*cpu core, it is unnecessary and not separate configuration。
Make Netty acceptor threads  separate configurable
(Please explain why)
> Make netty acceptor threadPool size configurable

- .github/workflows/backward-compat-tests.yml
- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java17.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/macos-build.yml
- .github/workflows/owasp-dep-check.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/stream-tests.yml
- .github/workflows/tls-tests.yml
- .github/workflows/windows-build.yml
Our current CI doesn't implement a cache solution and it's a waste of resources and time. 
GH offers a builtin action
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows 
* Added a cache for each job that build with maven
> [ci] Cache maven dependencies

- bookkeeper-server/src/test/resources/org/powermock/extensions/configuration.properties
Fix https://github.com/apache/bookkeeper/issues/3115 
When I try to run some test classes, there will occur an error message like the above issue cause `javax/management/MBeanServer` is a system class and javassist's classloader cannot load it. we can add powermock global configuration to ignore this error message.
The powermock's instruction is here: https://github.com/powermock/powermock/wiki/PowerMock-Configuration
Add `org/powermock/extensions/configuration.properties`.
> Add powermock global configuration

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- pom.xml
That's a regular update, `jcommander` 1.78 was released in 2019.
Bump jcommander version from 1.78 to 1.82
> Bump jcommander from 1.78 to 1.82

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
Fixes: https://github.com/apache/bookkeeper/issues/2945
When a read request is rejected due to the limit on the number of reads that can be enqueued, we need to decrement the metric for `bookkeeper_server_READ_ENTRY_IN_PROGRESS` and release the `readsSemaphore`, if it is not null.
* Call `onReadRequestFinish()` for failures in the V2 and V3 request processing logic.
It looks like the V2 responses for this kind of failure are not throttled, even when `throttleReadResponses` is true. We could call `read.sendReadReqResponse(` to enable this throttling. I didn't change it here because there might be a reason we're not throttling these small responses.
> Add missed call to onReadRequestFinish() when read request rejected

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieRecoveryUseIOThreadTest.java
---
*Motivation*
If the user doesn't configure the ReadWorker thread pool, the request will process with io thread. We cannot call await() from an IO thread, if the socket buffer is full, that blocking call would cause a deadlock.
*Modification*
- only wait for the promise when the thread is not io thread
> Fix the deadlock when only using io thread to handle request

- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/SimpleTestCommand.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/client/SimpleTestCommandTest.java
resolves: https://github.com/apache/bookkeeper/issues/3473
Add option to clean up test ledger after simpletest.
Also add metadata for ledger created by simpletest so we have more confidence when clean them up manually.
> Add option to clean up test ledger after simpletest.

- pom.xml
Upgrade the hadoop version to 3.2.4 to fix [CVE-2022-25168](https://www.cve.org/CVERecord?id=CVE-2022-25168)
> upgrade hadoop version to 3.2.4

- docker/Dockerfile
- docker/docker-compose.yml
centos is not maintained anymore, switch to ubuntu
- migrate from centos to ubuntu
- use python3 instead of python2
- Bump bookkeeper version from 4.12.1 to latest 4.15.1
> Migrate Dockerfile from centos to ubuntu

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
AutoRecoveryMain.shutdown() performs blocking operations.
We are calling "shutdown" on the main ZookKeeper client thread.
More context in this Pulsar case https://github.com/apache/pulsar/pull/17638
Run "shutdown" in a separate thread
> AutoRecovery - Do not call shutdown() on the main ZookKeeper client thread

- docker/Dockerfile
- tests/docker-images/statestore-image/Dockerfile
- migrate statestore image from centos7 to ubuntu
- use `--no-install-recommends` to reduce image size
- elminate `gcc`、`gcc-c++` in image
Thanks for @lhotari
> Migrate centos7 to ubuntu 22.10, reduce image size

- pom.xml
Bump snakeyaml from 1.31 to 1.32 to solve CVE-2022-38752
1.32 had this resolved https://www.cvedetails.com/cve/CVE-2022-38752
> Bump snakeyaml from 1.31 to 1.32 to solve CVE-2022-38752

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessorV3.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ForceLedgerProcessorV3Test.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/LongPollReadEntryProcessorV3Test.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ReadEntryProcessorTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorV3Test.java
When a client disconnects from a bookie server, there is a chance that there are pending read requests in the `BookieRequestProcessor`'s queue. Since these are read operations cannot succeed, there is no reason to attempt them.
The primary motivation is to prevent unnecessary reads to the disk as well as decrease the memory utilization associated with unnecessary reads. Additionally, reads are currently performed as blocking calls on the `BookieRequestProcessor` processing thread pool, so failing fast can increase the processing speed of the thread pool. See:
https://github.com/apache/bookkeeper/blob/a65e888b25eb966921ff39032e04f367a553d634/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java#L57-L58
Note: we cannot add this logic for writes because those can be …
> Check if channel closed before processing read request

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LocationsIndexRebuildOp.java
When rebuilding RocksDB index, if we're inserting the entries one by one, we're becoming bottlenecked on the RocksDB insertion. Instead we should add items to the index in batches.
> Speed up the rebuildinding of RocksDB index

- site3/website/docs/admin/decomission.md
The bookkeeper command path is wrong in the demo of [decommission doc](https://bookkeeper.apache.org/docs/admin/decomission/).
Update the command path.
Fix #3498
> Issue #3498  Fix bookkeeper command path in decommission doc

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/stats/BroadCastStatsLogger.java
- bookkeeper-common/src/test/java/org/apache/bookkeeper/test/TestStatsProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryMemTable.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryMemTableWithParallelFlusher.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SyncThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/service/ScrubberService.java
- stats/bookkeeper-stats-api/src/main/java/org/apache/bookkeeper/stats/Counter.java
- stats/bookkeeper-stats-api/src/main/java/org/apache/bookkeeper/stats/NullStatsLogger.java
- stats/bookkeeper-stats-providers/codahale-metrics-provider/src/main/java/org/apache/bookkeeper/stats/codahale/CodahaleStatsLogger.java
- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/LongAdderCounter.java
- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/ThreadScopedLongAdderCounter.java
- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/TestPrometheusMetricsProvider.java
- stream/distributedlog/common/src/main/java/org/apache/distributedlog/common/stats/BroadCastStatsLogger.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/BKAsyncLogWriter.java
The latency of the OpStatsLogger.registerSuccessfulEvent calculation is to convert the time to milliseconds
but Counter.add nothing to do
so when using Counter for latency statistics, the time unit and OpStatsLogger are not unified, which is easy to be misleading.
then we unified latency metric unit 
1.  change name : Counter.add -->  Counter.addCount
2. add new method Counter.addLatency to count the time and convert the time to milliseconds
then how to use counter correctly:
1. when using Counter for latency metric, call Counter.addLatency
2. when using Counter for count metric, call Counter.addCount
> unified latency metric unit

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerChecker.java
When `LedgerChecker` checks Ledger's fragments, it does not keep the order, and the results of the check are not kept in order, which works correctly most of the time.
I'm not sure if we should keep the order of checks and final results, but I observed a flaky-test like this:
https://github.com/apache/bookkeeper/actions/runs/3124965464/jobs/5068848112
I have printed some verbose logs as follows:
testShouldGetTwoFrgamentsIfTwoBookiesFailedInSameEnsemble In the case of success and failure:
2022-09-26T15:00:13,790 - INFO  - [Time-limited test:LedgerChecker@373] - checkLedger nowing.
2022-09-26T15:00:13,792 - INFO  - [Time-limited test:LedgerChecker@398] - LedgerCheck fragments before[Fragment(LedgerID: 0, FirstEntryID: 0[0], LastKnownEntryID: 0[0], Host: [127.0.0.1:50466, 127.0.0.1:50474, …
> ledgerFragment check and results keep order

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerCreateOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieWriteLedgerTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeper.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockLedgerHandle.java
We are currently completing the creation and opening (also with recovery) of the LedgerHandle in the main ZookKeeper (or metadata driver) callback thread.
This leads to unpredictable code to be executed on that thread:
- possible deadlocks (that cannot be prevented fully from BK code)
- execute heavy weight operations, like opening BK connections
This is a good example of a something that tries to open a connection to a bookie because the application executes a "read" after a "openLedger" operation.
```
at org.apache.bookkeeper.proto.PerChannelBookieClient.connect(PerChannelBookieClient.java:532)
at org.apache.bookkeeper.proto.PerChannelBookieClient.connectIfNeededAndDoOp(PerChannelBookieClient.java:658)
at org.apache.bookkeeper.proto.DefaultPerChannelBookieClientPool.initialize(DefaultPer …
```
> LedgerHandle: do not complete metadata operation on the ZookKeeper/Metadata callback thread

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java
https://github.com/apache/bookkeeper/pull/2794 introduced blocking call in the callback.
I can't tell if it contributes to https://github.com/apache/bookkeeper/issues/3466 but it will lead to slow processing main worker pool under the conditions described in the issue (network retries, Zk session reconnects etc) 
Use async close.
> ---
>
> ---
>
>
> …
> LedgerOpenOp: Do not call blocking close() in the callback

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMap.java
After unload all bundles of a heavy pulsar broker, cpu usage is still above 50%, here is a cpu profile and a heapdump
- [28726.html.zip](https://github.com/apache/bookkeeper/files/9683416/28726.html.zip)
It looks like there's a schedule task executing `BookieClientImpl#monitorPendingOperations`.
Most of `completionObjects` in `PerChannelBookieClient` are empty.
IMO, it's worth to check whether a section is empty or not in loop predication.
Add `size > 0` into `Section#removeIf` loop predication.
> Reduce unnecessary loop in removeIf if map is empty

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
Bump jackson version to 2.13.4 to solve CVE-2022-42004
> Bump jackson version to 2.13.4

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
If we don't flush the ReadResponse, the ByteBuf won't be released.
> Fix byteBuf potential memory leak problem.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
The default `dnsResolver` of `RackawareEnsemblePlacementPolicyImpl` is initialized as `ScriptBasedMapping`. Since the script is missing by default, detailed stack information will be printed, but the code will fall back to `DefaultResolver` by default, so only simple exception information needs to be printed.
> Simplified No network topology script is found default log stack output

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDBTest.java
- bookkeeper-server/src/test/resources/test_entry_location_rocksdb.conf
---
In PR #3056, we introduced using rocksDB configuration file to configure it. But it is not compatible with the previous versions of bookkeeper. We used to use the bookie configuration file to configure it. It would make the existing configuration doesn't work. Which causes some performance issues for the user's existing environment.
This PR adds the old configuration back. The new way only works if the rocksDB configuration file is existing.
> Make the rocksDB configuration compatible with previous versions

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
Instead of dequeuing all the `ForceWriteRequest` one by one, use `drainTo()` to reduce contention with the main journal thread.
> Use BlockingQueue.drainTo() in JournalForceWrite thread

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogMetadata.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/DefaultEntryLogTest.java
Fixes #3490
Change `ToString` method, print the content of map.
> Show content of map

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorElector.java
this introduced in #2842, the `ledgerAuditorManager` will be close repeatedly.
```java
private void submitShutdownTask() {
executor.submit(new Runnable() {
@Override
public void run() {
if (!running.compareAndSet(true, false)) {
return;
}
try {
ledgerAuditorManager.close();   <- here has already closed LAM.
} catch (InterruptedException ie) {
Thread.currentThread().interrupt();
LOG.warn("InterruptedException while closing ledger auditor manager", ie);
} catch (Exception ke) {
LOG.error("Exception while closing ledger auditor manager", ke);
}
}
});
}
```
> fix close ledgerAuditorManager repeatedly

- site3/website/docs/reference/cli.md
The [bookkeeper shell queryautorecoverystatus](https://github.com/apache/bookkeeper/blob/b13dd20f0a905c615daef2e1ddcfa0e0979d1a07/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java#L1361) command is not publicly listed on the site
Declare the bookkeeper shell queryautorecoverystatuscommand on the web site
Master Issue: #3536
> <Issue #3537>[website]Declare the bookkeeper shell queryautorecoverystatus command on the web site

- site3/website/docs/admin/upgrade.md
- site3/website/docusaurus.config.js
The community related variables are not replaced
Poor user experience
1、modify Upgrade page template variables
2、add  variables to config
Master Issue: #3534
> <Issue #3534>[website]fix website mailing_lists_url/slack_url

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
Use `BlockingQueue.drainTo()` in the Journal thread to minimize the contention between this thread and the threads passing entries to the journal. 
The drain method in the `ArrayBlockingQueue` method will use the mutex only once and take out all the items in one shot.
The logic in the journal dequeuing is already quite complicated. This change aims at not changing the whole logic, rather doing the minimal intervention.
> Use BlockingQueue.drainTo() in Journal thread

- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/SlowBookieTest.java
`testWriteSetWriteableCheck` always failed. After investigation, it is found that `isWritable=false` is set when the simulated channel is not writable, but the unit test cannot fully perceive the channel establishment, because the channel is completely established asynchronously. The isWritable state of false is changed to true again.
you can see the following logs:
The smallest change is that we can ensure that the channel is established before changing the channel state, such as executing `bkc.getBookieInfo()`, and then `setTargetChannelState`
> Fix flaky-test testWriteSetWriteableCheck

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
When `placementPolicyCheck` is enabled and then `bookkeeper shell autorecovery -disable` is executed, `placementPolicyCheck` will detect ledgers that do not satisfy `placementPolicy` and write to zookeeper, but `ReplicationWorker` no longer obtains ledgers from zookeeper for replication work because autorecovery is disabled, which results in a large number of temporary nodes on zookeeper , when there are more ledgers that do not satisfy placementPolicy, the problem will get worse.
The method of `ReplicationWorker` to get ledger:
```java
private boolean rereplicate() throws InterruptedException, BKException,
UnavailableException {
long ledgerIdToReplicate = underreplicationManager
.getLedgerToRereplicate();
...
```
So we should also disable `placementPolicyCheck`.
> Skipping placementPolicyCheck when ledger replication disabled

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
In BP-44(Ledger storage metrics enhancement), ledger flush start time is moved to after lock to avoid 200% time
  utilization calculations.
However, 200% time utilization still happens in my test. After reading the source code, I found that this part was rolled back by #3160. 
If I understand correctly, this change is not as expected
Flush start time is moved to after lock again.
> Flush time started moved to after lock

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/collections/GrowableMpScArrayConsumerBlockingQueue.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/SingleThreadExecutor.java
- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/collections/GrowableArrayBlockingQueueTest.java
- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/util/TestSingleThreadExecutor.java
The OrderedExecutor queue must be really unbounded or we are subject to deadlocks when a large number of tasks are submitted and may be depending on tasks that are going to be executed on the same executor.
Renamed the `GrowableArrayBlockingQueue` into `GrowableMpScArrayConsumerBlockingQueue` and optimized for single consumer scenario. 
Added test to ensure the `SingleThreadExecutor` is really unbound.
Added simple benchmark test scenario that uses 2 queues and 2 threads passing a bounded number of messages between each others, as fast as possible:
https://github.com/apache/bookkeeper/compare/master...merlimat:bookkeeper:fix-ordered-executor-max-size?expand=1#diff-e8f29aa89f5bf7b81642d51409ab37e220c9a066c009f24b82bafbfb8bc3e4e6R248
```
ArrayBlockingQueue: Throughput 27.433703 Millions …
```
> Single thread executor should not have max capacity by default

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
When disabled replication by the BookKeeper shell, the `replicasCheckTask` doesn't check the `replication disabled` flag and keeps checking the ledger replicas, which will lead to more disk IO.
Check the `replication disabled` flag before running `replicasCheckTask`
> Skip replicasCheck when replication disabled

- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieNetworkAddressChangeTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestDelayEnsembleChange.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
When we config as follow:
```
conf.setDisableServerSocketBind(true);
conf.setEnableLocalTransport(true);
```
The BookieNettyServer will create jvmBootstrap, it binds the address by bookieId.
https://github.com/apache/bookkeeper/blob/255416a8552f34e5fd50231bbeed77e0945b63e3/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java#L374-L428
At line_426, it use bookieId to bind, there is a flag about `BookKeeperClusterTestCase#useUUIDasBookieId`, it set uuid to bookieId.
When the client connects to the server, the remoteAddress `local:a4367111-5740-40dd-a8b2-0fcb2995398b` is strange, the resolve logic  throw java.lang.ArrayIndexOutOfBoundsException.
https://github.com/apache/bookkeeper/blob/255416a8552f34e5fd50231bbeed77e0945b6 …
> [Branch-4.14] Fix TLS test local port case problem

- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SortedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/ResumeCompactionService.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/SuspendCompactionService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/MockLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
- site3/website/docs/admin/http.md
Compaction would bring high disk io util, It would better allowing to control suspending and resuming compaction through api
Add two apis to control resuming and suspending compaction.
`/api/v1/bookie/gc/suspend_compaction`
`/api/v1/bookie/gc/resume_compaction`
> Add new api resumeCompaction and suspendCompaction

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
remove unused variable for `checkEnvironment` in `BookieImpl`
remove unused variable `RegistrationManager registrationManager` for `checkEnvironment` in `BookieImpl`
> [cleanUp]remove unused variable for checkEnvironment

- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
- conf/bk_server.conf
When users configure multiple servers for `metadataServiceUri`, they will be confused about how to separate the server list.
Add an example to explain how to configure multiple servers for `metadataServiceUri`
> Add example for multiple server list in metadataServiceUri configuration

- site3/website/src/pages/community/contributing.md
The property name of `checkstyle suppressions` already changed in the PR https://github.com/apache/bookkeeper/pull/2817/files#diff-f295bca9ef0353572bbaeaeaa17061f524e9236ac46763c836ed779dee99935e, but web site still recommends the old
Since this configuration has a default setting, change the doc-line to "Click Next -> Finish".
> [doc]Fixed incorrect checkstyle configuration prompts

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/api/ReadHandle.java
- site3/website/src/pages/bps/BP-31-durability.md
- site3/website/src/pages/bps/BP-41-bookieid.md
- stream/clients/python/bookkeeper/common/timeout.py
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/ZooKeeperClient.java
> Fix the typo of double the

- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/SlowBookieTest.java
There is a lot of `Thread.sleep()` in Bookie tests, which may lead to flaky tests.
Replace sleep with await to avoid flaky test in SlowBookieTest
> Replace sleep with await to avoid flaky test in SlowBookieTest

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
[CVE-2022-3171](https://ubuntu.com/security/CVE-2022-3171)
[CVE-2022-42003](https://github.com/FasterXML/jackson-databind/commit/d78d00ee7b5245b93103fef3187f70543d67ca33)
- upgrade `jackson.version` from `2.13.4 -> 2.14.0-rc1` 
- upgrade `protobuf.version` from `2.19.2 -> 3.19.6`
> Upgrade dependencies for CVE-2022-3171 and CVE-2022-42003

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/LogMetadata.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestMetadata.java
Write meta to log header before fsync in DirectIO mode
Fix READ_METADATA_FALLBACK issue, details can be seen in https://github.com/apache/bookkeeper/issues/3588
Write meta to log header before fsync in DirectIO mode
- Why the last close call fsync to ensure metadata is flushed to the log file: the close triggers fsync only when nativebuffer is not null, however native buffer is not used when flush metadata into header 
- Does the metadata write overwrite the ledger content: No. The metadata is written in reserved locations for header, which from offset 0 to offset 1024.
Master Issue: #3588
> ---
> checks for pull requests. A pull request …
> Issue 3588: write meta to log header before fsync in DirectIO mode

- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieRecoveryUseIOThreadTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/api/BookKeeperBuildersOpenLedgerTest.java
When running the check style, it fails with the following exception.
```
Error:  /home/runner/work/bookkeeper/bookkeeper/bookkeeper-server/src/test/java/org/apache/bookkeeper/client/api/BookKeeperBuildersOpenLedgerTest.java:45: Missing a Javadoc comment. [JavadocType]
Audit done.
[INFO] There is 1 error reported by Checkstyle 6.19 with buildtools/src/main/resources/bookkeeper/checkstyle.xml ruleset.
Error:  src/test/java/org/apache/bookkeeper/client/api/BookKeeperBuildersOpenLedgerTest.java:[45] (javadoc) JavadocType: Missing a Javadoc comment.
```
Add javadoc comments for test classes.
> Add javadoc comments for test classes

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerManager.java
Correct @link class name error.
`BKException` to  `org.apache.bookkeeper.client.BKException.`
> Correct link class name

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/stats/EntryMemTableStats.java
The `getEntryStats` in `EntryMemTableStats` has wrong parent
Change the parent from `BOOKIE_ADD_ENTRY` to `BOOKIE_READ_ENTRY`
> Fix memtable getEntryStats typo

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieImplTest.java
org.apache.bookkeeper.bookie.BookieImpl#setExplicitLac did not release the reference to the entry at the end.
> Fix ByteBuf memory leak problem when setExplicitLac

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieImplTest.java
1. Add ByteBuf refCnt test for `addEntry` and `recoveryAddEntry`
2. use pooled ByteBuf reduce heap usage
> Add ByteBuf refCnt test for AddEntry and use pooled ByteBuf reduce heap usage

- bookkeeper-common/pom.xml
- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/EventLoopUtil.java
- pom.xml
Allow users to enable IO_uring for BK network transport.
Since the Netty implementation is still considered experimental, it will not be enabled by default, rather only when the `-Denable.io_uring=true` is passed.
> Allow to use IO uring instead of epoll

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
Main issue: #3559
When reading small entries, consolidate the response into a single buffer instead of using ByteBufList
> Optimize ReadResponse for small entry sizes

- conf/bk_server.conf
Updated description about flushInterval configuration：
`This config is used when entryLogPerLedgerEnabled=true or ledgerStorageClass=org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage.
`
https://github.com/apache/bookkeeper/blob/5724bc8434a4d6903487221d39713f39a4bcb6b4/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java#L459-L477
>  update doc about flushInterval config

- docker/Dockerfile
- docker/scripts/apply-config-from-env.py
Fix #3549
migrate apply-config-from-env.py from python2 to python3
fix docker/Dockerfile
Issue 3549: migrate apply-config-from-env.py from python2 to python3
add newline character, and reformat for docker/Dockerfile
change print to print()
Master Issue: 3549
> Issue 3549: migrate apply-config-from-env.py from python2 to python3

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieTest.java
> [branch-4.14] Fix ByteBuf memory leak problem when setExplicitLac

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
Right now, if bookie fails to replay the journal then it logs journal-txn-id but it doesn't log journal dir path. It will be useful if bookie prints journal path along with journal-dir in case if user is using multi-journal directories so, user can troubleshoot the issue and fix it correctly.
```
2022-11-07T18:29:07,205+0000 [main] ERROR org.apache.bookkeeper.bookie.Bookie - Exception while replaying journals, shutting down
java.io.IOException: Recovery log 1667603421612 is missing
at org.apache.bookkeeper.bookie.Bookie.replay(Bookie.java:932) ~[org.apache.bookkeeper-bookkeeper-server-4.12.jar:4.12]
at org.apache.bookkeeper.bookie.Bookie.readJournal(Bookie.java:911) ~[org.apache.bookkeeper-bookkeeper-server-4.12.jar]
```
Add journal dir file path in journal replay failure.
> [log] Add journal file path that caused failure in multi-journal config

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/GetBookieInfoProcessorV3.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/GetBookieInfoProcessorV3Test.java
In `GetBookieInfoProcessorV3`, even if throw `IOException` and get DiskSpace failed, it will still `registerSuccessfulEvent`, which is wrong, we should `registerFailedEvent`.
1. registerFailedEvent when get DiskSpace failed.
2. add unit test.
> Fix GetBookieInfo failed event stats

- dev/docker/Dockerfile
- dev/release/Dockerfile
---
*Motivation*
When using the lower maven version to build bookkeeper, we will meet the license problem in the binary package.
```
ch.qos.logback-logback-classic-1.2.10.jar unaccounted for in LICENSE
ch.qos.logback-logback-core-1.2.10.jar unaccounted for in LICENSE
io.netty-netty-tcnative-2.0.48.Final.jar unaccounted for in LICENSE
io.netty-netty-transport-native-epoll-4.1.75.Final.jar unaccounted for in LICENSE
```
> Upgrade maven version in release docker image

- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/EmbeddedServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/Main.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/TestEmbeddedServer.java
Is enough common for project to start an embedded version of BK using such classes. Instead of rewrite every time boilerplate code the full server instantiation can be extracted from Main class creating a public API to create BookieService from configurations and/or provided component instances.
I've took code from Main class and refactored into a builder as EmbeddedServer class.
Just providing the configuration to the builder produces the same server that Main class was generating.
Added multiple builder properties to permit to inject custom implementations for various components. "Injected" component lifecycle is responsability of the implementor (ie.: if you provide specific instances you need to remember to start and/or stop such instances …
> Issue #3488 Create an EmbeddedSever extracting code from Main class and adding a builder pattern

- bookkeeper-dist/all/pom.xml
- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
The `bkperf` dependency doesn't include in the bookkeeper-all package, and when we run `bin/bkperf` command, it will throw the following exceptions.
```
$ bin/bkperf journal append -j data -n 100000000 --sync true
Couldn't find module '(org.apache.bookkeeper-)?bookkeeper-perf' jar.
Do you want me to run `mvn package -DskipTests` for you ? (y|n)
```
Include the `bookkeeper-perf` dependency into `bookkeeper-all` package.
> Include bkperf into bk all package

- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTest.java
AuditorReplicasCheckTest has the following tests that are flaky, detected using the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool.
testReplicasCheckForLedgersFoundHavingLessThanAQReplicasOfAnEntry()
testReplicasCheckForLedgersFoundHavingLessThanWQReplicasOfAnEntry()
testReplicasCheckForLedgersFoundHavingNoReplica()
testReplicasCheckForLedgersWithEmptySegments()
The tests fail due to non-deterministic ordering in the HashMap `segmentEnsembles`
The following check fails in the `newEnsembleEntry()` method since it assumes the ordering of `segmentEnsembles` to be deterministic:
```
checkArgument(ensembles.isEmpty() || firstEntry > ensembles.lastKey(),
"New entry must have a first entry greater than any existing ensemble key");
```
Fixes #3550 
Command to reproduce:
```
mvn …
```
> Issue 3550: Fix flaky tests in AuditorReplicasCheckTest

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandleAdv.java
Apply recycle logic during add entry creation but ledger close to LedgerHandleAdv
This pr is a supplement to #3321
If I understand correctly. these recycled logic should be applied to LedgerHandleAdv
> ---
>
> ---
>
>
> - [ ] Attach the master issue link in …
> Apply recycle logic during add entry creation but ledger close to LedgerHandleAdv

- dev/docker/Dockerfile
- dev/release/Dockerfile
There are a lot of critical CVEs in the `maven:3.8.6-jdk-11` docker image
https://snyk.io/test/docker/maven%3A3.8.6-jdk-11
Use `maven:3.8.3-eclipse-temurin-11` instead of `maven:3.8.6-jdk-11` to fix it.
> Upgrade docker image version to fix CVEs

- site3/website/docusaurus.config.js
- site3/website/src/pages/release-notes.md
- site3/website/src/pages/releases.md
Releases page is malformed
Also update latest version to 4.15.3 since the doc is already online
> [website] Fix releases page header and move latest release to 4.15.3

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- conf/bk_server.conf
When there are a lot of ledgers to be deleted, the EntyLocationIndex in RocksDB will delete a large number of entries at one time. 
```
Nov 11, 2022 @ 05:49:39.336     05:49:39.336 [db-storage-cleanup-10-1] INFO  org.apache.bookkeeper.bookie.storage.ldb.EntryLocationIndex - Deleted indexes for 0 entries from 16074 ledgers in 625.242 seconds
Nov 11, 2022 @ 10:18:08.281     10:18:08.281 [db-storage-cleanup-10-1] INFO  org.apache.bookkeeper.bookie.storage.ldb.EntryLocationIndex - Deleted indexes for 0 entries from 13376 ledgers in 248.66 seconds
Nov 11, 2022 @ 14:27:06.949     14:27:06.949 [db-storage-cleanup-10-1] INFO  org.apache.bookkeeper.bookie.storage.ldb.EntryLocationIndex - Deleted indexes for 0 entries from 11798 ledgers in 265.118 seconds
Nov 11, 2022 @ 19:45:40.593 …
```
> Make RocksDB delete entries batch size configurable

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
The master branch has added RocksDB read latency and read from storage latency in https://github.com/apache/bookkeeper/pull/2862. This Pr can not be cherry-picked to branch-4.14. However, the above two metrics will be helpful for investigating entry read latency spike issues. 
Bring the RocksDB read latency and read from storage latency for entry reading to branch-4.14.
> [Branch-4.14] Add rocksDB read latency and read from storage latency for entry reading

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
Currently, We cannot disable minorCompaction and majorCompaction by setting interval to -1, with `gcWaitTime` is  enabled.
Don't validate CompactionInterval if compaction is disabled
> Dont validate CompactionInterval when compaction is disabled

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java
Follow the same rules to complete the callback to avoid Bookkeeper client operations being allowed even after its closure.
- Use `bk.getReturnRc(rc)` check the client state.
> Check client if closed when complete callback.

- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieSanityService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
- site3/website/docs/admin/http.md
Right now, if Bookie startup or process fails due to various reasons then bookie getState() rest API still gives a successful response even though bookie writes are not going through. Therefore. Bookie should have a REST API to check bookie sanity test and that can be used to check bookie liveliness in k8/helm-chart or to plot bookie health graph.
Add Bookie REST API to check bookie health to validate bookie liveliness
> Add Http-service to check bookie sanity state

- .github/changes-filter.yaml
- .github/workflows/backward-compat-tests.yml
- .github/workflows/bookie-tests.yml
- .github/workflows/client-tests.yml
- .github/workflows/compatibility-check-java11.yml
- .github/workflows/compatibility-check-java17.yml
- .github/workflows/compatibility-check-java8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/macos-build.yml
- .github/workflows/owasp-dep-check.yml
- .github/workflows/pr-validation.yml
- .github/workflows/remaining-tests.yml
- .github/workflows/replication-tests.yml
- .github/workflows/stream-tests.yml
- .github/workflows/tls-tests.yml
- .github/workflows/windows-build.yml
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieSanityService.java
Master build fails due to checsktyle
```
Error:  /home/runner/work/bookkeeper/bookkeeper/bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieSanityService.java:26:1: Extra separation in import group before 'org.apache.bookkeeper.common.util.JsonUtil' [ImportOrder]
Error:  /home/runner/work/bookkeeper/bookkeeper/bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieSanityService.java:36:1: Extra separation in import group before 'lombok.Data' [ImportOrder]
Error:  /home/runner/work/bookkeeper/bookkeeper/bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieSanityService.java:36:1: Import lombok.Data appears after other imports that it should precede [ImportOrder]
```
The problem is that if a pull contains doc …
> Run CI when a pull request contains doc changes

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/HierarchicalLedgerManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListLedgersCommand.java
When I run `bookkeeper shell listledgers` command and get exception like the below, the shell process doesn't exit forever. I expect shell processes will exit soon.
```
...
06:00:02.801 [main-EventThread] ERROR o.a.b.t.c.c.b.ListLedgersCommand     - Unable to read the ledger: 15256124 information
06:00:02.805 [main-EventThread] ERROR o.a.b.p.BookkeeperInternalCallbacks  - Error in multi callback : -25
06:00:02.807 [main] ERROR o.a.b.t.c.c.b.ListLedgersCommand     - Received error return value while processing ledgers: -1
06:00:02.810 [main] ERROR o.a.b.t.c.c.b.ListLedgersCommand     - Received Exception while processing ledgers
org.apache.bookkeeper.client.BKException$BKReadException: Error while reading ledger
at org.apache.bookkeeper.client.BKException.create(BKException.java:62)
at …
```
> Exit bookkeeper shell correctly even if fails to run for some reason

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/CleanupLedgerManager.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/CleanupLedgerManagerTest.java
There is a memory leak point in Bookkeeper client, see the following heap report:
It happens when opening a non-existent or expired ledger data. The following screen shot is memeory leak point by [Eclipse Memory Analyzer](https://www.eclipse.org/mat/).
Handle exception and clean up when promise complete exceptionally.
Master Issue: [#1](https://github.com/HQebupt/bookkeeper/pull/1)
> [fix][server]fix memory leak when operating ledger metadata

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
1) Use ReferenceCountUtil.safeRelease() instead of ByteBuf.release() in InterleavedLedgerStorage
> [refactor] [server] Refactor ByteBuf release method in InterleavedLedgerStorage

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultEntryLogger.java
Master Issue: [#2](https://github.com/HQebupt/bookkeeper/pull/2)
> [refactor][bookkeeper] Refactor ByteBuf release method in DefaultEntryLogger

- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/SimpleTestCommand.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/client/SimpleTestCommandTest.java
> Enhance simple test

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/datainteg/EntryCopierImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectEntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectReader.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/LogMetadata.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/LogReaderScan.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/ReadCache.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CheckpointOnNewLedgersTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestDirectEntryLogger.java
1) Use ReferenceCountUtil.safeRelease() instead of ByteBuf.release() in module bookkeeper-server
> [refactor] [server] Refactor ByteBuf release method in module bookkeeper-server

- bookkeeper-common-allocator/src/test/java/org/apache/bookkeeper/common/allocator/impl/ByteBufAllocatorBuilderTest.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/journal/AbstractStateStoreWithJournal.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/KVUtils.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVAsyncStore.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCRecord.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCRecordCoder.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCStoreImpl.java
Master Issue: [#7](https://github.com/HQebupt/bookkeeper/pull/7)
> [refactor][bookkeeper] Refactor ByteBuf release method in stream/statelib

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectReader.java
remove unused variable attempts:
https://github.com/apache/bookkeeper/blob/01232c94c91759a175345e8c055951e5cc6091dd/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectReader.java#L209-L215
> [clean] remove unused variable attempts

- conf/bk_server.conf
- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java
---
###Motivation
Expose the default JVM Metrics or not. If you are using the BookKeeper as an embedded service and you want to expose metrics in your application, you might need to disable this to avoid the JVM metrics register duplicated.
- Add a configuration variable to decide whether or not to expose the JVM metrics
> Add an argument to decide expose the default JVM metrics

- stream/distributedlog/core/src/main/java/org/apache/bookkeeper/client/LedgerReader.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/EnvelopedEntry.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/EnvelopedEntryReader.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/EnvelopedEntryWriter.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/tools/DistributedLogTool.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestEntry.java
1) Use ReferenceCountUtil.safeRelease() instead of ByteBuf.release() in module distributedlog-core
> [refactor] [server] Refactor ByteBuf release method in module distributedlog-core

- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/journal/JournalWriter.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/IncrementTask.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/WriteTask.java
Master Issue: [#3](https://github.com/HQebupt/bookkeeper/pull/3)
> [refactor][bookkeeper] Refactor ByteBuf release method in  tools

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieStickyReadsTest.java
I found the following flaky-test: org.apache.bookkeeper.bookie.BookieStickyReadsTest.stickyReadsWithFailures:
https://github.com/apache/bookkeeper/actions/runs/3367374609/jobs/5584792353
```
Error:  Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.925 s <<< FAILURE! - in org.apache.bookkeeper.bookie.BookieStickyReadsTest
Error:  org.apache.bookkeeper.bookie.BookieStickyReadsTest.stickyReadsWithFailures  Time elapsed: 1.752 s  <<< ERROR!
java.lang.IndexOutOfBoundsException: Index: -1, Size: 3
at java.base/java.util.LinkedList.checkElementIndex(LinkedList.java:559)
at java.base/java.util.LinkedList.get(LinkedList.java:480)
at org.apache.bookkeeper.test.BookKeeperClusterTestCase.serverByIndex(BookKeeperClusterTestCase.java:369)
at …
```
> Use READ_ENTRY_SCHEDULING_DELAY to stable stickyReadsWithFailures

- stats/bookkeeper-stats-providers/prometheus-metrics-provider/pom.xml
- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java
- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/TestPrometheusMetricsProvider.java
In #3252, it only uses poolMxBeanOp to get direct memory usage. It only works in jdk11.
But if the user still uses the old version, netty still uses `NoCleanerConstructor` ByteBuffer to allocate direct memory, the poolMxBeanOp didn't cover it.
We should check the netty `PlatformDependent.useDirectBufferNoCleaner()`, then choose the corresponding way to get direct memory usage.
> Make `jvm_memory_direct_bytes_used` metrics compatible with jdk8.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ReadOnlyLedgerHandle.java
change Future.thenRun to Future.whenComplete in the bookie project there are places that must be released.
1) the first place is updated in  #3662 
2) the second place is this pr: #3672 
the condition that the bug triggers:
1) when future handle exception, thenRun will be ignored to run
1) handle exception and clean up when promise complete exceptionally.
2) org.apache.bookkeeper.client.LedgerRecovery2Test#testFirstWriterCannotCommitWriteAfter2ndWriterCloses has cover this pr, so no need to add a new testcase
> [fix][server]fix memory leak when closeRecovered,failed on clearing newEnsemblesFromRecovery

- stream/distributedlog/common/src/test/java/org/apache/distributedlog/io/TestCompressionCodec.java
- stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/EnvelopedRecordSetReader.java
- stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/EnvelopedRecordSetWriter.java
- stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/LogRecord.java
1) Use ReferenceCountUtil.safeRelease() instead of ByteBuf.release() in module distributedlog-core/distributedlog-protocol
> [refactor] [server] Refactor ByteBuf release method in module distributedlog-core/distributedlog-protocol

- stream/clients/java/kv/src/main/java/org/apache/bookkeeper/clients/impl/kv/PByteBufSimpleTableImpl.java
- stream/clients/java/kv/src/main/java/org/apache/bookkeeper/clients/impl/kv/PByteBufTableRangeImpl.java
- stream/common/src/main/java/org/apache/bookkeeper/common/router/AbstractHashRouter.java
- tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/table/DelCommand.java
1) Use ReferenceCountUtil.safeRelease() instead of ByteBuf.release() in module stream-storage-common/stream-storage-java-kv-client/stream-storage-cli
> [refactor] [server] Refactor ByteBuf release method in module stream-storage-common/stream-storage-java-kv-client/stream-storage-cli

- bookkeeper-common-allocator/src/test/java/org/apache/bookkeeper/common/allocator/impl/ByteBufAllocatorBuilderTest.java
Master Issue: [#7](https://github.com/HQebupt/bookkeeper/pull/7)
> [refactor][bookkeeper] Refactor ByteBuf release method in bookkeeper-common-allocator

- bookkeeper-slogger/api/src/test/java/org/apache/bookkeeper/slogger/SloggerTest.java
The test in org.apache.bookkeeper.slogger.SloggerTest#testMap express non-deterministic behaviour and change the order of the attributes. The fix is changing HashMap to LinkedHashMap to ensure determinism.
Fixing non-deterministic flaky tests.
Changed the HashMap to LinkedHashMap in test code.
Master Issue: #3701 
> ---
>
> ---
>
>
> - [x] Make sure the PR title is formatted like:
>     `<BP-#>: …
> Fix Flaky Tests

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/TestEntryLogIds.java
When building the EntryLogIdsImpl object, the ledgerDirsManager variable is used. When the EntryLogIdsImpl object is used to generate an id, all ledger directories will be scanned in the findLargestGap method. for example:
We configured three ledger directories:
/data1/bk-data1
/data1/bk-data2
/data1/bk-data3
The findLargestGap method scans these three data directories to generate ids, but actually only needs to scan one data directory corresponding to the EntryLogIdsImpl object:
https://github.com/apache/bookkeeper/blob/01232c94c91759a175345e8c055951e5cc6091dd/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java#L225-L236
When building the EntryLogIdsImpl object, use the variable ldm instead of the variable ledgerDirsManager:
```
lDirs[0] = …
```
> [fix][server] When dbStorage_directIOEntryLogger=true, EntryLogIdsImpl only takes effect for a single ledger directory

- bookkeeper-common-allocator/src/test/java/org/apache/bookkeeper/common/allocator/impl/ByteBufAllocatorBuilderTest.java
- stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/routing/RoutingHeaderProxyInterceptor.java
Master Issue: [#5](https://github.com/HQebupt/bookkeeper/pull/5)
> [refactor][bookkeeper] Refactor ByteBuf release method in stream/storage

- bookkeeper-common-allocator/src/test/java/org/apache/bookkeeper/common/allocator/impl/ByteBufAllocatorBuilderTest.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClientImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManager.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/WriteCacheTest.java
Master Issue: [#4](https://github.com/HQebupt/bookkeeper/pull/4)
> [refactor][bookkeeper] Refactor ByteBuf release method in bookkeeper-server

- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/journal/JournalWriter.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/IncrementTask.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/WriteTask.java
Master Issue: [#3](https://github.com/HQebupt/bookkeeper/pull/3)
> [refactor][bookkeeper] Refactor ByteBuf release method in tools 

- README.md
- site3/website/src/pages/community/slack.md
The Slack auto-invite app on Heroku has stopped working. Adding a different Slack app to allow users to auto-invite.
> Added new way to self-invite to BK Slack

- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/ClusterInfoService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
- site3/website/docs/admin/http.md
- stream/server/src/main/java/org/apache/bookkeeper/stream/server/StorageServer.java
Information provided by current REST API is not enough (and cumbersome to combine) to answer such question as "is any data in danger if I shut down one more bookie".
E.g. getting list of underreplicated ledgers can get some info but it is either fast (no ledgers) or can be super slow on large cluster with some bookies lost (it retrieves full list of ledgers).
Even if there are no UR ledgers it still possible that the problem is that Auditor is down etc.
Added api/v1/bookie/cluster_info REST API
```
curl -s 127.0.0.1:8080/api/v1/bookie/cluster_info
{
"auditorElected" : false,
"auditorId" : "",
"clusterUnderReplicated" : false,
"ledgerReplicationEnabled" : true,
"totalBookiesCount" : 1,
"writableBookiesCount" : 1,
"readonlyBookiesCount" : 0, …
```
> [feature] Added api/v1/bookie/cluster_info REST API

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultBookieAddressResolver.java
In some cases, we need  RegistrationClient to do some work, so expose the registration client.
See comment https://github.com/apache/pulsar/pull/18672#discussion_r1059624499.
> Expose registrationClient in DefaultBookieAddressResolver.

- site3/website/docs/deployment/manual.md
configuration 'zkServers' is deprecated, user only config this parameter may cause failure. So update manual deployment page.
> [docs] update parameter in manual deployment page

- pom.xml
Bump hadoop-common from 3.2.4 to 3.3.4 to avoid indirect dependent security vulnerabilities, such as **commons-text**
Bump hadoop-common from 3.2.4 to 3.3.4
> Bump hadoop-common from 3.2.4 to 3.3.4

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
Remove the unnecessary `ledgerData.hasExplicitLac()` check,  because we have check it at Line985
Remove the unnecessary `ledgerData.hasExplicitLac()` check
> Remove unnecessary hasExplicitLac check

- pom.xml
This update doesn't solve CVE problems. regular update.
> Bump snakeyaml from 1.32 to 1.33

- .github/workflows/bk-ci.yml
1. Make code coverage have a base branch to diff.
2. Every PR may not sync and merge the latest master code, so we need to run CI for the target branch after a PR merged.
> Add push trigger condition for CI

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
In the QueueEntry recycle, it only recycles itself to the object pool, but didn't reset some properties.
Like entry, cb, etc. We should reset the filed before recycles itself.
> Fix QueueEntry recycle problem.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- conf/bk_server.conf
This PR is to resolve the issue https://github.com/apache/bookkeeper/issues/3734 in branch-4.14 by following this suggestion. https://github.com/apache/bookkeeper/issues/3734#issuecomment-1407338171
1. Revert https://github.com/apache/bookkeeper/pull/3653
2. Bring https://github.com/apache/bookkeeper/pull/3646 to branch-4.14 to make delete entries batch size configurable.
> [Branch-4.14] Revert PR#3653 and make delete entries batch size configurable

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java
> [bookie] Fix memory leak when the Bookie is in read only mode

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
Some time ago, I fixed a bug where check of all ledgers periodically run by the auditor got stuck (cf. https://github.com/apache/bookkeeper/pull/3214). That PR was merged so we cherry-picked it and released it, but `checkAllLedgers` still got stuck when the `inFlightReadEntryNumInLedgerChecker` value was very small.
The cause is that multiple `BookKeeperClientWorker-OrderedExecutor` threads are blocked waiting for the semaphore to be released. This semaphore is released by the `BookKeeperClientWorker-OrderedExecutor` threads, so they should not run the `LedgerChecker#checkLedger` method.
```
"BookKeeperClientWorker-OrderedExecutor-1-0" #60 prio=5 os_prio=0 tid=0x00007f680401d800 nid=0x75e8 waiting on condition [0x00007f684a6e9000]
java.lang.Thread.State: WAITING (parking)
at …
```
> Issue 3070: Fix issue where checkAllLedgers could get stuck when read throttling is enabled

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ReadOnlyBookieTest.java
PR #2887 introduced the feature of shutdown the bookie service after any Journal thread exits, so we don't need to wait in BookieImpl for all Journal threads to exit before shutdown the Bookie service, because this cannot happen.
> BookieImpl remove wait until journal quits

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
It seems that  L1131-1132 is duplicated of L1146-1147, so we need remove the first one.
https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java#L1126-L1148
Remove the duplicated JournalQueueStats
> Fix the duplicated JournalQueueStats

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectWriter.java
small fix: when ByteBuf size is zero. the acquired buffer is not released.
> DirectWriter only acquire buffer when need write.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- conf/bk_server.conf
We have the following configurations from the DirectIO entry logger.
```
dbStorage_directIOEntryLoggerTotalWriteBufferSizeMb
dbStorage_directIOEntryLoggerTotalReadBufferSizeMb
dbStorage_directIOEntryLoggerReadBufferSizeMb
```
In fact, the units are bytes instead of bits. But from the first sight of the configuration name, users may be confused by the units, because we use `Mb` instead of `MB`.
I suggest changing the configuration name suffix from `Mb` to `MB` to avoid confusing.
- Change `dbStorage_directIOEntryLoggerTotalWriteBufferSizeMb` to `dbStorage_directIOEntryLoggerTotalWriteBufferSizeMB`
- Change `dbStorage_directIOEntryLoggerTotalReadBufferSizeMb` to `dbStorage_directIOEntryLoggerTotalReadBufferSizeMB`
- Change `dbStorage_directIOEntryLoggerReadBufferSizeMb` to …
> Change directIO configuration names to avoid confusing

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandleAdv.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClientImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/PendingAddOpTest.java
`PendingAddOp` is not thread-safe and the BK client instead follows a pattern of "jumping" to a particular thread for both the requests and the callback path. 
This is in practice much more expensive than acquiring a mutex since in most cases the caller will have already serialized the calls to `ledger.append()`. 
With this change, we can avoid 2 context switches and the very big contention on the executor queues used between the threads.
> Made PendingAddOp thread safe

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
We have 3 bookies in the same rack, and configured `E = 2, W = 2, A = 2`. When one bookie restarted, we found the ledger select bookie from the same rack failed in the ensemble change replacing the failed bookie step.
Due to there being no log information in `selectRandomFromRack`, it's hard to debug the root cause.
https://github.com/apache/bookkeeper/blob/02e64a4b97e03afc9993ab227f82a5956965c03f/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java#L630-L679
Add one warn log in `selectRandomFromRack` when selecting a new bookie node failed.
> Add logs for ensemble select failed

- pom.xml
Our ci tests use `code-coverage` profile to run, using `-Dio.netty.leakDetection.level=paranoid` will cover more cases.
> Make profile `code-coverage` and `dev-debug` tests using `-Dio.netty.leakDetection.level=paranoid`

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
Related to https://github.com/apache/bookkeeper/issues/3734
Upgrade RocksDB version to 7.9.2
> Upgrade RocksDB version to 7.9.2

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
Fix #3805
The test was failing because the updates to the object, done in the `initiate()` method, were not immediately visible to other threads. We must use synchronized consistently in all the accesses.
> Fixed locking of PendingAddOp

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
We registered `ReadEntrySchedulingDelayStats` of `ReadEntryProcessor` as `WriteThreadQueuedLatency` mistakenly, so we need fix it.
Register `ReadEntrySchedulingDelayStats`  if `ReadEntryProcessor`
> Fix ReadEntryProcessor v2 SchedulingDelayStats

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/ArrayGroupSort.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/WriteCache.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/ArraySortGroupTest.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/bookie/GroupSortBenchmark.java
(This is stacked on top of #3800 & #3806 -- I'll rebase once these are merged)
Few improvements in the `ArrayGroupSort`:
1. Use insertion sort once the quick-sort partitions are small enough
2. Use static methods and fix group/key size (since we only care for key=2 and group=4)
3. Unroll the loop for comparison and swap of elements
Benchmarks:
```
Benchmark                                    Mode  Cnt       Score       Error  Units
GroupSortBenchmark.preSortedGroupSort       thrpt    3       6.278 ±     0.149  ops/s
GroupSortBenchmark.randomGroupSort          thrpt    3    1465.937 ±    80.175  ops/s
GroupSortBenchmark.reverseSortedGroupSort   thrpt    3       6.301 ±     1.130  ops/s
```
```
Benchmark                                   Mode  Cnt       Score      Error  Units …
```
> Improvements in ArrayGroupSort

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/CRC32CDigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/CRC32DigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DirectMemoryCRC32Digest.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DummyDigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/MacDigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/StandardCRC32Digest.java
- circe-checksum/src/main/java/com/scurrilous/circe/checksum/Crc32cIntChecksum.java
- circe-checksum/src/main/java/com/scurrilous/circe/checksum/IntHash.java
- circe-checksum/src/main/java/com/scurrilous/circe/checksum/Java8IntHash.java
- circe-checksum/src/main/java/com/scurrilous/circe/checksum/Java9IntHash.java
- circe-checksum/src/main/java/com/scurrilous/circe/checksum/JniIntHash.java
- circe-checksum/src/test/java/com/scurrilous/circe/checksum/ChecksumTest.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManagerBenchmark.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/DigestTypeBenchmark.java
In `DigestManager.verifyDigestAndReturnData()` there are a couple of simple improvements: 
1. For the temp buffer where to store the digest, do not acquire a buffer from the pool each time. Instead, use a thread-local buffer.
2. Instead of taking slices() at each time, extend the interface to take a "offset, length" pair and save the allocations.
```
Benchmark                            (entrySize)   Mode  Cnt   Score   Error   Units
DigestManagerBenchmark.verifyDigest           64  thrpt    3  13.450 ± 3.634  ops/us
DigestManagerBenchmark.verifyDigest         1024  thrpt    3   7.908 ± 2.637  ops/us
DigestManagerBenchmark.verifyDigest         4086  thrpt    3   3.233 ± 0.882  ops/us
DigestManagerBenchmark.verifyDigest         8192  thrpt    3   1.846 ± 0.047  ops/us
```
Allocations: 230 …
> Improved efficiency in DigestManager.verify()

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/CRC32CDigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/CRC32DigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DummyDigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/MacDigestManager.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/DigestTypeBenchmark.java
In `DigestManager` there are several accesses to ThreadLocal variable per each entry processed.
The reason is the mainly due to `DigestManager` API which exposes a stateful `update()` method which can be invoked multiple times and keeps the current checksum as a thread-local variable.
If we exclude MAC digest which is 20 bytes, for other digests we can instead keep the current checksum in a local variable and pass it each time, avoiding all the thread-locals and also the need for writing the checksum result into a buffer.
```
Benchmark                            (entrySize)   Mode  Cnt   Score   Error   Units
DigestManagerBenchmark.verifyDigest           64  thrpt    3  13.450 ± 3.634  ops/us
DigestManagerBenchmark.verifyDigest         1024  thrpt    3   7.908 ± 2.637  ops/us …
```
> Avoid thread-local state when computing CRCs

- pom.xml
Building BK with Java 19 fails because there is a deprecation warning and it's being treated as an error.
In a few places, we are using `Thread.getId()` which has been deprecated since Java 19. There is now a new replacement: `Thread.getThreadId()`. 
The problem is that we cannot use the new method (which is only in Java 19+) and the build fails with the deprecated method.
I believe the best solution is to not use `-Werrror` flag in the build.
> Remove compiling with `-Werror` to support Java 19

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/LedgerMetaDataCommand.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/client/LedgerMetaDataCommandTest.java
Bk-CLI api supports creating ledger metadata from the metadata binary payload-file but it doesn't support updating metadata for existing ledger which will require some time during updating metadata in some operational update usecases. Therefore, support update metadata if ledger already exists by adding a flag.
`bookkeeper shell ledgermetadata -restorefromfile` command can update ledger-metadata by passing additional `--update flag`.
> Support update ledger metadata option bk-cli

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
`./bin/bookkeeper shell ledgermetadata` usage is showing incorrect params `dump-to-file` , `restore-from` to user while executing the command.
Fix usage with correct param `dumptofile` and `restorefromfile`
> Fix: bookie-shell ledger-metadata usage with correct param

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/LedgerMetaDataCommand.java
https://github.com/apache/bookkeeper/pull/2019 has introduced a typo in ledgerMetadata bk-shell command which checks invalid input param `restorefromefile` instead of `restorefromfile`. so, this PR fixes that typo which will not cause any compatibility issue for this functionality as such.
> Fix: typo for ledger-metadata param: restorefromfile

- site3/website/src/pages/community/mailing-lists.md
- site3/website/src/pages/community/meeting.md
Fix the mailing-lists.md dead links which cause Dead link checker failed.
There are some links looks like not stable, we can use new link to replace it.
CI filed link:https://github.com/apache/bookkeeper/actions/runs/4260370313/jobs/7413461899
```
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-user/
ERROR: 4 dead links found!
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-dev/
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-issues/
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-commits/
20 links checked.
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-user/ → Status: 0
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-dev/ → Status: 0
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-issues/ → Status: 0
[✖] …
```
> fix mailing-lists dead links

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-server/pom.xml
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/JournalChannel.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/PageCacheUtil.java
- native-io/src/main/java/org/apache/bookkeeper/common/util/nativeio/NativeIO.java
- native-io/src/main/java/org/apache/bookkeeper/common/util/nativeio/NativeIOImpl.java
- native-io/src/main/java/org/apache/bookkeeper/common/util/nativeio/NativeIOJni.java
- native-io/src/main/native-io-jni/cpp/native_io_jni.c
- pom.xml
- shaded/distributedlog-core-shaded/pom.xml
For calling `posix_fadvise`, we are using JNA which is a wrapper on top of JNI. While JNA is convenient because it's dynamically creating a stub for accessing native methods, it's also very inefficient compared to direct JNI access.
Since we already have JNI modules, we should add `posix_fadvise` there and remove the dependency on JNA.
> Use JNI directly for posix_fadvise

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufList.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/ByteBufListTest.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/logsegment/BKLogSegmentEntryReader.java
Related to https://github.com/apache/bookkeeper/issues/3792
> [Branch-4.15] Use ReferenceCountUtil.release() instead of ReferenceCountUtil.safeRelease()

- circe-checksum/src/main/java/com/scurrilous/circe/checksum/Crc32cIntChecksum.java
In #3810 the signature of `Crc32cIntChecksum.resumeChecksum()` was changed to accept `offset` & `len` in the buffer.
Since this method is also used externally (in Pulsar), we should leave also the old method signature to avoid breaking the API when upgrading BK.
> Fixed back API of Crc32cIntChecksum

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- conf/bk_server.conf
The option of triggering journal callbacks from a thread-pool instead of from the JournalForceWrite thread is not really helpful under any condition.
The only thing this option does is to introduce an extra context switch to jump on this thread-pool and from there it will trigger the response, though basically no work is done in this thread-pool. It will just jump on the Netty IO-thread for the specific connection and from there the serialization and the socket write will be done.
When using the thread-pool, one can see the effect of the extra-context switch and the contention on the execution.
Additionally, when 0 threads are configured, we are using the Guava DirectExecutor which has non-zero overhead in the form of a mutex that is contended between multiple journal threads.
> Remove callback threadpool for sending add responses

- pom.xml
- src/aarch64_aol.properties
---
When releasing the bookkeeper on aarch64 Mac OS, it will build aarch64 linux image to release operations. Add aol properties for the aarch64 linux.
the properties come from https://github.com/maven-nar/nar-maven-plugin/blob/master/src/main/resources/com/github/maven_nar/aol.properties#L583
> Support build in the aarch64 linux platform

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DistributionSchedule.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerChecker.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingWriteLacOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RoundRobinDistributionSchedule.java
For computing WriteSet we use a `Recycler` to avoid instantiating a new object each time. While that avoid allocations, it's based on thread-locals and has non-zero cost.
In most cases the usage of WriteSet that we are doing is very basic: 
* Get a `WriteSet` from the recycler
* check the bookie indices
* recycle the write-set
Instead, we can just expose a method in the `DistributionSchedule` interface and avoid any recycler or object allocations.
> Avoid using thread-local WriteSet when possible

- .github/workflows/bk-ci.yml
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/PageCacheUtil.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerCacheTest.java
- buildtools/src/main/resources/bookkeeper/findbugsExclude.xml
- microbenchmarks/src/main/java/org/apache/bookkeeper/bookie/GroupSortBenchmark.java
- pom.xml
The Spotbugs check failed, which blocked the PRs' CI
- https://github.com/apache/bookkeeper/actions/runs/4315781701/jobs/7530640684
- https://github.com/apache/bookkeeper/actions/runs/4319029437/jobs/7538019260
- When generating javadoc, it throws NPE:
```
[ERROR] NullPointerException
java.lang.NullPointerException
at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions (MojoExecutor.java:439)
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:325)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
at …
```
> Fix Spotbugs check failed

- bookkeeper-server/src/main/java/org/apache/bookkeeper/processor/RequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestHandler.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ForceLedgerProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/GetBookieInfoProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/GetListOfEntriesOfLedgerProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/LongPollReadEntryProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBaseV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadLacProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessorV3.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteLacProcessorV3.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ForceLedgerProcessorV3Test.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/GetBookieInfoProcessorV3Test.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/LongPollReadEntryProcessorV3Test.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ReadEntryProcessorTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/TestBookieRequestProcessor.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorV3Test.java
This is just a preparatory refactoring change. The final goal is to streamline the send-response path from Journal to the client connections.
We're now passing the Netty Channel object as context for the requests, though that prevents us from adding more state and logic when tracking back to the original connection.
Instead, we can pass `BookieRequestHandler` where we can potentially add new fields.
> Pass BookieRequestHandler instead of Channel to the request processors

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDBTest.java
- bookkeeper-server/src/test/resources/test_entry_location_rocksdb.conf
- conf/default_rocksdb.conf.default
- conf/ledger_metadata_rocksdb.conf.default
Fix https://github.com/apache/bookkeeper/issues/3734#issuecomment-1407626941
We have two rocksDB tables, one for the ledger index, and another for the entry log location.
- ledger index RocksDB table: Use the default table option, and the checksum is `kCRC32c`
- entry log location RocksDb table: Use configured table option, and the checksum is `kxxHash` 
When we upgrade the RocksDB version from 6.10.2 to 7.9.2, the new RocksDB version's default table checksum has changed from `kCRC32c` to `kXXH3`, and `kXXH3` only supported since RocksDB 6.27. The RocksDB version rollback to 6.10.2 will be failed due to RocksDB 6.10.2 doesn't support the `kXXH3` checksum type.
In this PR, I make the RocksDB checksum type configurable. But there is one change that will change the ledger index RocksDB …
> Make RrocksDB checksum type configurable

- .github/workflows/website-deploy.yaml
Website deployment build failed
https://github.com/apache/bookkeeper/actions/runs/4340797094/jobs/7579680220
It may be caused by the maven 3.9.0 bug
https://issues.apache.org/jira/browse/MNG-7679
Set the maven version to 3.8.7 instead of the default 3.9.0 to fix the issue.
> Fix website deploy build failed

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/collections/BatchedArrayBlockingQueue.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/collections/BatchedBlockingQueue.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/collections/BlockingMpscQueue.java
- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/collections/BatchedArrayBlockingQueueTest.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/common/MpScQueueBenchmark.java
One of the main contention points in bookies is the Journal queue. There are multiple threads posting entries to be added on the journal on the queue. 
In order to reduce contention and increase overall throughput (when there are many small entries), we can adopt a strategy of "bulk" inserting to the queue.
`BatchedArrayBlockingQueue` is a fixed size blocking queue, very similar to Java `ArrayBlockingQueue` with 2 additional methods: 
1. `putAll(T[] array, int offset, int len)` --> Add all the items from the array in one shot, block if full
2. `takeAll(T[] dest)` --> Take all the available items in the queue that fit into the destination array, block if empty
We use arrays here instead of List/Collection because it enables to do `System.arrayCopy()` which is way faster than a for loop and …
> Added BatchedArrayBlockingQueue

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/processor/RequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestHandler.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/TestBookieRequestProcessor.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorTest.java
Note: this is stacked on top of #3830 & #3835
This change improves the way the AddRequests responses are send to client. 
The current flow is: 
* The journal-force-thread issues the fsync on the journal file
* We iterate over all the entries that were just synced and for each of them:
1. Trigger channel.writeAndFlus()
2. This will jump on the connection IO thread (Netty will use a `write()` to `eventfd` to post the task and wake the epoll)
3. Write the object in the connection and trigger the serialization logic
4. Grab a `ByteBuf` from the pool and write ~20 bytes with the response
5. Write and flush the buffer on the channel
6. With the flush consolidator we try to group multiple buffer into a single `writev()` syscall, though each call will have a long list of buffer, making the memcpy …
> Group and flush add-responses after journal sync

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessor.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ReadEntryProcessorTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/TestBackwardCompatCMS42.java
Make the read entry request object recyclable like the add request to reduce the object creation when doing catchup read from Pulsar.
Add recycler to the read request.
> Make read entry request recyclable

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
The batch requests logFile is the same one, and the last request happens to be rolloverFileRequest, it may force write logFile twice.
The first force write: https://github.com/apache/bookkeeper/blob/57031323166bd55004aaf50e3f46611dbb7eacf7/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java#L535
The second force write:
https://github.com/apache/bookkeeper/blob/57031323166bd55004aaf50e3f46611dbb7eacf7/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java#L390
> Avoid unnecessary force write.

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/FileInfoBackingCacheTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/HandleFailuresTest.java
`HandleFailuresTest` and `FileInfoBackingCacheTest` sometimes blocked the CI for 30 minutes and timed out by the configured 1800s `<forkedProcessTimeoutInSeconds>1800</forkedProcessTimeoutInSeconds>`
https://github.com/apache/bookkeeper/actions/runs/4382682699/jobs/7673671554
```
2023-03-10T10:08:25.6989894Z [INFO] Running org.apache.bookkeeper.client.HandleFailuresTest
2023-03-10T10:38:27.0756444Z [INFO] Running org.apache.bookkeeper.client.api.WriteHandleTest
```
https://github.com/apache/bookkeeper/actions/runs/4374329604/jobs/7653852875
```
2023-03-09T12:31:17.1298580Z [INFO] Running org.apache.bookkeeper.client.HandleFailuresTest
2023-03-09T13:01:18.4961335Z [INFO] Running org.apache.bookkeeper.client.api.WriteHandleTest
``` …
> [Flaky Test] Add timeout for two flaky timeout tests

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileSystemUpgrade.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/UpgradeTest.java
Now we have written indexDir into Cookie in #3372 .
When we configure an independent indexDir, the `FileSystemUpgrade` tool will fail when the cookie is an old version or a new cookie version will be added in the future, because it does not consider indexDirs when upgrading, so we should add indexDirs to the upgrade step.
You can use the following two implementations of getAllDirectories in FileSystemUpgrade, and then run some tests added by this PR in UpgradeTest, and you will find that the first implementation will fail the test, while the second implementation will succeed.
1:
```java
private static List<File> getAllDirectories(ServerConfiguration conf) {
List<File> dirs = new ArrayList<>();
dirs.addAll(Lists.newArrayList(conf.getJournalDirs()));
Collections.addAll(dirs, …
```
> [improve] Fix indexDirs upgrade failed

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/FileInfoBackingCacheTest.java
The unit test `testRaceGuavaEvictAndReleaseBeforeRetain` sometimes runs timeout https://github.com/apache/bookkeeper/actions/runs/4382055343/jobs/7670828738
The root cause is that two threads sleep same time to run the logic, which leads to them interacting with each other and can't exit the while loop.
https://github.com/apache/bookkeeper/blob/cd43c91addb252f139cc207fe10adbb9344f9590/bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/FileInfoBackingCacheTest.java#L255-L260
Due to the guavaCache size being one, when a new item putting into the cache, it will evict the previous one. The while loop can't exit with the following steps.
```
- Thread 1 put item A into the cache
- Thread 1 runs into sleep 100ms
- Thread 2 trigger evict item A from the cache
- Thread 2 put item B into …
```
> [Flaky] Fix flaky test in testRaceGuavaEvictAndReleaseBeforeRetain

- bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchThroughputLatency.java
When I start up a standalone bookie and use the following command the test the bookie server performance `bin/benchmark writes`, it throws the following exception and the benchmark process is blocked.
```
2023-03-12T11:22:37,685 - INFO  - [main:BenchThroughputLatency@376] - Calculating percentiles
2023-03-12T11:22:37,797 - INFO  - [main:BenchThroughputLatency@397] - 0 completions in 60003 milliseconds: 0 ops/sec
2023-03-12T11:22:38,185 - INFO  - [main:BenchThroughputLatency@416] - 99th percentile latency: NaN
2023-03-12T11:22:38,185 - INFO  - [main:BenchThroughputLatency@417] - 95th percentile latency: NaN
Exception in thread "main" java.lang.NullPointerException
at org.apache.bookkeeper.benchmark.BenchThroughputLatency.close(BenchThroughputLatency.java:114)
at …
```
> Fix NPE in BenchThroughputLatency

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDBTest.java
- bookkeeper-server/src/test/resources/conf/entry_location_rocksdb.conf
- bookkeeper-server/src/test/resources/test_entry_location_rocksdb.conf
- conf/entry_location_rocksdb.conf.default
After PR #3056 , Bookkeeper set `level_compaction_dynamic_level_bytes=true` as `TableOptions` in `entry_location_rocksdb.conf.default` , which will cause `level_compaction_dynamic_level_bytes` lose efficacy and will cause rocksDB .sst file compact sort chaos when update bookie release.
As RocksDB  conf, `level_compaction_dynamic_level_bytes` need set as `CFOptions` https://github.com/facebook/rocksdb/blob/master/examples/rocksdb_option_file_example.ini
1. Change `level_compaction_dynamic_level_bytes=true` from `TableOptions` to `CFOptions`  in `entry_location_rocksdb.conf.default` ;
> Modify incorrect rocksDB config level_compaction_dynamic_level_bytes to CFOptions

- .github/workflows/bk-ci.yml
Correct the running job flag for the test group.
The running tests job flag doesn't match the tests. Correct the job flag. Introduced by https://github.com/apache/bookkeeper/pull/3851.
> Correct the running job flag for the test group.

- site3/website/src/pages/release-notes.md
> Release note for 4.15.4

- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
- bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/TriggerLocationCompactService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
- site3/website/docs/admin/http.md
After the bookie instance running long time, the bookie entry location index rocksDB `.sst` file size maybe expand to 20-30GB as one ledger data dir's location index in some case, which will cause the rocksDB scan operator cost more time and cause the bookie client request timeout.
Add trigger entry location index rocksDB compact REST API which can trigger  entry location rocksDB compaction and get the compaction status. 
The full range entry location index rocksDB compact will cause the entry location index dir express higher IOUtils. So we'd better trigger the entry location rocksDB compact by the api in low data flow period.
**Some case before rocksDB compact:**
**After rocksDB compact:**
1. Add  REST API  to trigger entry location index rocksDB compact.
> Add trigger entry location index rocksDB compact REST API 

- .github/workflows/bk-ci.yml
There're two reasons that we want to disable the code coverage.
1. The current report result is not accurate.
2. We can't get the PR's unit test's code coverage because of the apache Codecov permission.
> Disable code coverage and Codecov report

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/GarbageCollectorThreadTest.java
- conf/bk_server.conf
When we use `TransactionalEntryLogCompactor` to compact the entry log files, it will generate a lot of small entry log files, and for those files, the file usage is usually greater than 90%, which can not be compacted unless the file usage decreased.
We introduce the entry log file size check during compaction, and the checker is controlled by `gcEntryLogSizeRatio`. 
If the total entry log file size is less than `gcEntryLogSizeRatio * logSizeLimit`, the entry log file will be compacted even though the file usage is greater than 90%. This feature is disabled by default and the `gcEntryLogSizeRatio` default value is `0.0`
> Add small files check in garbage collection

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorBookieCheckTask.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorCheckAllLedgersTask.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTask.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTask.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorTask.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorCheckAllLedgersTaskTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTaskTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTaskTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
Fixes #3817 
For details, see: #3817 
When there is an `auditTask` during the `lostBookieRecoveryDelay` delay, other detection tasks should be skipped.
> [improvement] Delay all audit task when have a already delayed bookie check task

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
Garbage collector does
```
extractMetaFromEntryLogs();
doGcLedgers();
```
where extractMetaFromEntryLogs checks if ledger exists in the storage and doGcLedgers removes deleted ledgers from the storage.
Logically, these should be reordered.
Currently it means that deleted ledgers will be either re-verified during compaction and skipped (if verifyMetadataOnGC is true) or picked up on the next GC run.  
In prod it means data released later.
The tests pass as they tend to do
```
getGCThread().enableForceGC();
getGCThread().triggerGC().get();
```
where both of these calls trigger gc.
reordered operations
> [fix][gc] Change order of doGcLedgers and extractMetaFromEntryLogs

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
> Fix compaction threshold default value precision problem.

- bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchReadThroughputLatency.java
- bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchThroughputLatency.java
The `BenchReadThroughputLatency` only supports the V3 protocol to read ledgers from the bookie server. Add the V2 protocol support.
Add V2 protocol support for BenchReadThroughputLatency
> Add V2 protocol support for BenchReadThroughputLatency

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufList.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/ByteBufListTest.java
- stream/distributedlog/common/src/test/java/org/apache/distributedlog/io/TestCompressionCodec.java
- stream/distributedlog/core/src/main/java/org/apache/bookkeeper/client/LedgerReader.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/EnvelopedEntry.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/EnvelopedEntryReader.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/EnvelopedEntryWriter.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/logsegment/BKLogSegmentEntryReader.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/tools/DistributedLogTool.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestEntry.java
- stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/EnvelopedRecordSetReader.java
- stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/EnvelopedRecordSetWriter.java
- stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/LogRecord.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/journal/AbstractStateStoreWithJournal.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/KVUtils.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVAsyncStore.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCRecord.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCRecordCoder.java
- stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCStoreImpl.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/journal/JournalWriter.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/IncrementTask.java
- tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/WriteTask.java
> [Branch-4.14] Use ReferenceCountUtil.release() instead of ReferenceCountUtil.safeRelease()

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieWriteLedgerTest.java
https://github.com/apache/bookkeeper/pull/3837 introduced group flush add responses triggered by journal sync. However, if we skip writing journals, the add responses won't be flushed to the netty channel and the client will receive write entries timeout.
- Flush the add responses when skipping writing journals
- Add tests to cover V2 protocol and skip writing journal cases.
> Fix write entry failed in without writing journal case

- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieWriteLedgerTest.java
https://github.com/apache/bookkeeper/pull/3884 introduced a parameterized test for BookieWriteLedgerTest, but those parameters don't work due to they are set in the constructor method, which doesn't run for each test. We need to set them in the `setUp()` method to ensure they are configured for each test.
Move the parameters from the constructor method to the `setUp()` method to make sure they are configured for each test.
> Fix BookieWriteLedgerTest parameterized failed

- bookkeeper-server/pom.xml
- pom.xml
- testtools/pom.xml
The current parent pom in Bookkeeper includes log4j-core and slf4j-log4j-impl dependencies, which are being transitively passed down to many modules. This has resulted in an unnecessary increase in the number of dependencies for these modules.
- move the log4j-impl and log4j-core to testtools
- declare log4j-impl and log4j-core dependency in bookkeeper server module.
Fix #3891 
Also see
- https://github.com/apache/pulsar/issues/19484
- https://github.com/apache/pulsar/pull/19937
> [ISSUE 3891] Optimize log4j dependency in Bookkeeper

- pom.xml
There is a critical CVE-2019-10202 in `org.codehaus.jackson:jackson-mapper-asl`
Detailed paths
Introduced through: org.apache.distributedlog:dlfs@4.16.0-SNAPSHOT › org.apache.hadoop:hadoop-common@3.3.4 › org.apache.avro:avro@1.7.7 › org.codehaus.jackson:jackson-mapper-asl@1.9.2
Fix: No remediation path available.
Introduced through: org.apache.distributedlog:dlfs@4.16.0-SNAPSHOT › org.apache.hadoop:hadoop-common@3.3.4 › com.sun.jersey:jersey-json@1.19 › org.codehaus.jackson:jackson-mapper-asl@1.9.2
Fix: No remediation path available.
Introduced through: org.apache.distributedlog:dlfs@4.16.0-SNAPSHOT › org.apache.hadoop:hadoop-common@3.3.4 › com.sun.jersey:jersey-json@1.19 › org.codehaus.jackson:jackson-jaxrs@1.9.2 › org.codehaus.jackson:jackson-mapper-asl@1.9.2
Fix: No remediation path …
> Upgrade hadoop version to 3.3.5 to resolve CVE-2019-10202

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
Fixes  #3771
Move cleanupExecutor to finally block to make sure it can be executed every checkpoint process.
> Execute clean indexes in finally

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
fix: #3908 
1.  finally unlock SingleDirectoryDbLedgerStorage#flushMutex
> [Bug] SingleDirectoryDbLedgerStorage#flushMutex does not release lock on all exception paths

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
In EntryLocationIndex#removeOffsetFromDeletedLedgers, if there are no ledgers to delete, the key pair will leak.
Check the ledgers to deletion Set first, and if the set is not empty, then generate the keys.
> Fix keys leak in EntryLocationIndex when ledgersToDelete is empty

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/TestBookieImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageReadCacheTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageWriteCacheTest.java
- conf/bk_server.conf
read ahead only limits the number of entries, which is not precise enough. so we need to add the bytes limit to make the prefetch to be more controllable
1.  add dbStorage_readAheadCacheBatchBytesSize properties 
2. when dbStorage_readAheadCacheBatchBytesSize is setted, use it to limit the bytes for read ahead entries.
1. Regression test case:  DbLedgerStorageReadCacheTest#chargeReadAheadCacheRegressionTest
2. Unit test case:   DbLedgerStorageReadCacheTest#chargeReadAheadCacheUnitTest
3. Perf test case:   DbLedgerStorageReadCacheTest#compareDiffReadAheadPerfTest
perf test results demonstrating improvements with this option:
case(read ahead cache by limit bytes size) get less cachemiss,it is suitable for large messages, reduce the pollution of …
> [feature] [server] add dbStorage_readAheadCacheBatchBytesSize properties when read ahead entries

- dev/docker/Dockerfile
- dev/release/Dockerfile
Detailed paths
Introduced through: maven@3.8.6-eclipse-temurin-11 › openssl/libssl3@3.0.2-0ubuntu1.7
Fix: No remediation path available.
Introduced through: maven@3.8.6-eclipse-temurin-11 › openssl@3.0.2-0ubuntu1.7
Fix: Upgrade to openssl@3.0.2-0ubuntu1.8 
  | BASE IMAGE | VULNERABILITIES | SEVERITY |  
-- | -- | -- | -- | --
Current image | maven:3.8.6-eclipse-temurin-11 | 48 | 0C1H22M25L |  
Minor upgrades | maven:3.9.0-eclipse-temurin-11 | 19 | 0C0H2M17L
Upgrade the docker base image to `maven:3.9.0-eclipse-temurin-11` to resolve the CVE
> Upgrade docker base image to resolve CVE-2023-0286

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManager.java
#3783 introduced a change in the behavior of `LedgerHandle#asyncAddEntry`. This PR re-introduces the original behavior.
Apache Pulsar just upgraded to Bookkeeper client version 4.16.0. In doing so, we observed new errors related to unexpected reader positions in the passed in byte buffer. Here is a thread discussing some of the observations: https://lists.apache.org/thread/n4dpmbo5t9bvq5t1fp8fn4m6c6d9d9so.
Based on my analysis, it seems that the core issue is with the type of `ByteBuf` being passed to the BK client. Previously, the `readerIndex` for the `ByteBuf` that was passed did not change. Now, it seems to move forward. I am assuming this is because of specific conditions related to `CompositeByteBuf`, but I haven't yet been able to create a …
> [fix] DigestManager should not advance readerIndex

- stream/distributedlog/io/dlfs/pom.xml
After upgrading the Hadoop version to 3.3.5, the CVE-2019-10202 still exists.
Detailed paths
Introduced through: org.apache.distributedlog:dlfs@4.16.0-SNAPSHOT › org.apache.hadoop:hadoop-common@3.3.5 › org.apache.avro:avro@1.7.7 › org.codehaus.jackson:jackson-mapper-asl@1.9.13
Detailed paths
Introduced through: org.apache.distributedlog:dlfs@4.16.0-SNAPSHOT › org.apache.hadoop:hadoop-common@3.3.5 › org.apache.hadoop:hadoop-auth@3.3.5 › net.minidev:json-smart@2.4.7
Fix: No remediation path available.
Detailed paths
Introduced through: org.apache.distributedlog:dlfs@4.16.0-SNAPSHOT › org.apache.hadoop:hadoop-common@3.3.5 › com.github.pjfanning:jersey-json@1.20 › org.codehaus.jettison:jettison@1.1
Fix: No remediation path available.
After checking the code of package …
> Remove avro, hadoop-auth and jersey-json dependencies from hadoop-common to resolve CVE-2019-10202, CVE-2023-1370 and CVE-2022-45685

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookKeeperServerStats.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieStateManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/SanityTestCommand.java
- conf/bk_server.conf
- site3/website/docs/admin/metrics.md
- site3/website/docs/reference/config.md
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/SanityTestCommandTest.java
It solves #3923 
Right now, Bookie metrics (Prometheus) don't show if Bookie's sanity is passing or not. and with container-based Prometheus bookie metrics which are used for monitoring, it will be really useful if metrics also show the bookie sanity state so, Prometheus can automatically scrape the bookie sanity state and one can set up monitoring on it. 
Therefore, add support to include the bookie sanity state in the bookie metrics.
For example:
```
URL: http://localhost:8000/metrics
:
bookie_SERVER_SANITY 1
```
- Add periodic task which performs sanity command on bookie and captures bookie sanity test periodically
- Reuse the `SanityTestCommnad` for this purpose but SanityTestCommand has lot of blocking IO which can cause thread blocking for metrics collection.
- Therefore, implement …
> [stats][bookie] Add bookie sanity test metrics

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
PerChannelBookieClient completionObjects occupy a lot of heap space and cannot be recycled.
The figure below shows that the internal table array of ConcurrentOpenHashMap has used space size=0, but the array length is still 16384, and the memory overhead is 65552bytes.
ConcurrentOpenHashMap default DefaultConcurrencyLevel=16. We have hundreds of bookie nodes. Due to the feature of bookie polling and writing, the client and server have long connection characteristics, which will as a result, the memory usage of about 65552 * 16 * 1776 = 1.74GB cannot be recycled, and the space take up by these tables is all size=0 (The broker's owner topic has drifted to other brokers due to Full GC).
When the throughput of the pulsar cluster increases and the bookie cluster expands, these memory usage will …
> Enable PCBC completionObjects autoShrink to reduce memory usage and gc

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
https://github.com/apache/bookkeeper/blob/a6387d191f28a59af72f6613b633d6898980a0b0/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java#L487-L517
At line 501, increases getReclaimedSpaceViaDeletes stats.
https://github.com/apache/bookkeeper/blob/a6387d191f28a59af72f6613b633d6898980a0b0/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java#L734-L767
But at line 755, it didn't increases getReclaimedSpaceViaDeletes stats.
> Fix ReclaimedSpaceViaDeletes stats incorrect problem.

- site3/website/scripts/release-major.sh
The release-major script execute `cd site3/website` twice, which will lead to `No such directory` error
> Fix release-major script bug

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorCheckAllLedgersTask.java
When ledgerReplication disabled, we don't need to register `checkAllLedgersTime` failedEvent because we already skipped the check and didn't encounter any exception.
```java
Stopwatch stopwatch = Stopwatch.createStarted();
boolean checkSuccess = false;
try {
if (!isLedgerReplicationEnabled()) {
LOG.info("Ledger replication disabled, skipping checkAllLedgers");
checkSuccess = true;    <= here
return;
}
LOG.info("Starting checkAllLedgers");
checkAllLedgers();
......
checkSuccess = true;
} catch (InterruptedException ie) {
......
} finally {
if (!checkSuccess) {
long checkAllLedgersDuration = stopwatch.stop().elapsed(TimeUnit.MILLISECONDS);
auditorStats.getCheckAllLedgersTime()
.registerFailedEvent(checkAllLedgersDuration, TimeUnit.MILLISECONDS);
}
}
```
> fix wrong update checkAllLedgersTime when ledgerReplication disabled

- .github/workflows/website-deploy.yaml
- .github/workflows/website-pr-validation.yml
- site3/website/package.json
- site3/website/yarn.lock
There are many CVEs in docusaurus 2.0.0-beta.17 version. 
Detailed paths
Introduced through: site-3@0.0.0 › @docusaurus/core@2.0.0-beta.17 › cssnano@5.1.0 › yaml@1.10.2
Fix: No remediation path available.
Introduced through: site-3@0.0.0 › @docusaurus/core@2.0.0-beta.17 › postcss-loader@6.2.1 › cosmiconfig@7.0.1 › yaml@1.10.2
Fix: [Upgrade](https://app.snyk.io/org/streamnative-org/fix/b453ecf3-1fc1-4ac1-a9e6-7c4cc6a8b4a1?vuln=SNYK-JS-YAML-5458867) to @docusaurus/core@2.0.0 
Introduced through: site-3@0.0.0 › @docusaurus/core@2.0.0-beta.17 › css-minimizer-webpack-plugin@3.4.1 › cssnano@5.1.0 › yaml@1.10.2
Fix: No remediation path available.
Detailed paths and remediation
Introduced through: site-3@0.0.0 › @docusaurus/core@2.0.0-beta.17 › eta@1.12.3
Fix: …
> Upgrade docusaurus to 2.4.0

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
Upgrade the RocksDB version to 6.29.4.1 to make sure BookKeeper 4.16.0 can roll back 4.14.x
Refer to: https://github.com/apache/bookkeeper/issues/3734#issuecomment-1407626941
> ---
>
> ---
>
>
>     `e.g. BP-1: 64 bits ledger is …
> Upgrade rocksDB version to 6.29.4.1

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
We should return, when an exception is encountered, the executor should not be scheduled tasks after it has been shutdown.
> When the executor has been shut down, do not schedule task

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragment.java
LedgerFragment adds the state of replicateType, but it has not been added to the toString method. I think the replicateType should be added to the toString method to track the state of LF and troubleshoot problems.
LedgerFragment is generally in `DATA_LOSS` or `DATA_NOT_ADHERING_PLACEMENT` state.
But it shouldn't have status when it's in detection progress or used elsewhere, so I added `NULL` status.
The following log shows the result:
replicating `DATA_LOSS` LedgerFragment
replicating `DATA_NOT_ADHERING_PLACEMENT` LedgerFragment
checking LedgerFragment in `NULL` type
> [improve] Enhance LedgerFragment toString method

- bin/bookkeeper
- conf/bkenv.sh
- site3/website/docs/reference/cli.md
- tests/docker-images/statestore-image/bin/bookkeeper
According to the configuration of ENTRY_FORMATTER_CLASS in the bookkeeper shell command, it will never take effect, we should remove it,
We can use -entryformat or configure in bookie config to take effect.
> drop invalid entryFormat arg from shell command

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
When one ledger file is broken, `getEntryLogMetadata` will throw an IllegalArgumentException, which is a RuntimeException and won't be caught in the whole garbage collector execution path. The exception will be caught by the thread SafeRunnable and interrupt the garbage collector, leading to those deleted ledgers can't be recycled and the ledger disk usage up.
```
2023-04-01T00:55:29,497+0000 [GarbageCollectorThread-11-1] INFO  org.apache.bookkeeper.bookie.GarbageCollectorThread - Garbage collector thread forced to perform GC before expiry of wait time.
2023-04-01T00:55:29,498+0000 [GarbageCollectorThread-11-1] INFO  org.apache.bookkeeper.bookie.GarbageCollectorThread - Extracting entry log meta from entryLogId: 17
2023-04-01T00:55:29,498+0000 [GarbageCollectorThread-11-1] INFO …
```
> Fix garbage collection blocked by runtime exception

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
> Fix npe when iterate pendingLedgersUpdates and pendingDeletedLedgers.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageTest.java
This PR solves the problem described #3940. 
Because compaction is triggering a flush after each entry log file is compacted, the flush on the DbLedgerStorage causes the write cache to be underutilized and ultimately it will slow down the writes.
The call to `flush()` in `updateEntriesLocations()` was there to ensure that every entry log file we might be compacting has the indexes already flushed into RocksDB. If that's not the case, the compaction might first write the new location and the regular flush will override it with the old location, to a file that is already deleted.
In practice, we don't actually need to trigger a new flush for that to be valid, we just need to ensure that if there is a pending `flush()`, we wait until it's done. If there are no pending flushes, we're also …
> Avoid compaction to trigger extra flushes DbLedgerStorage

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
I deployed the pulsar-3.0.0 version, and I observed the log of bookkeeper-4.16.1 as follows, I did not config special indexDirectories, but the printed log told me that indexDirectories was specified, which is wrong.
```
2023-05-23T19:52:45,192+0800 [main] INFO  org.apache.bookkeeper.bookie.storage.ldb.SingleDirectoryDbLedgerStorage - indexDir is specified, creating single directory db ledger storage on /data0/pulsar/data/ledgers/current
2023-05-23T19:52:45,322+0800 [main] INFO  org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB - Searching for a RocksDB configuration file in /usr/local/pulsar/apache-pulsar-3.0.0/conf/ledger_metadata_rocksdb.conf
2023-05-23T19:52:45,322+0800 [main] INFO  org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB - Found a RocksDB …
```
> check indexBaseDir specified with ledgerBaseDir

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
I am stopping a pulsar broker, and I observed a lot of the following logs in the broker log:
```
17:48:35.894 [shutdown-thread-43-1] INFO  org.apache.bookkeeper.proto.PerChannelBookieClient - Closing the per channel bookie client for 10.184.xx.xx:3181
17:48:35.894 [shutdown-thread-43-1] ERROR io.netty.util.concurrent.DefaultPromise.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:923) ~[io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:350) …
```
> [fix] Clear channel when channelInactive

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
In the given code snippet, a ForceWriteRequest object is created with the flushed flag always set to true when calling the createForceWriteRequest method, reused from a recycle pool. Consequently, when the flushFileToDisk method is invoked, it checks the flushed flag and only performs the file flush if it is false. However, since the flushed flag is always true due to the recycling process, the file flush is skipped.
```
private ForceWriteRequest createForceWriteRequest(JournalChannel logFile,
long logId,
long lastFlushedPosition,
RecyclableArrayList<QueueEntry> forceWriteWaiters,
boolean shouldClose) {
ForceWriteRequest req = forceWriteRequestsRecycler.get();
req.forceWriteWaiters = forceWriteWaiters;
req.logFile = logFile;
req.logId = logId;
req.lastFlushedPosition = …
```
> Fix Journal without flush

- pom.xml
- stats/bookkeeper-stats-providers/otel-metrics-provider/pom.xml
- stats/bookkeeper-stats-providers/pom.xml
Refer to https://github.com/apache/bookkeeper/pull/3968#discussion_r1205098805
- Move the otel module from root pom.xml to the sub-module of `Apache BookKeeper :: Stats :: Parent`
> Format otel module dependencies

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectReader.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectWriter.java
When open a non-exist file for DirectReader, it will throw an exception. The ByteBuf won't release.
When close DirectWriter, if the close failed, the ByteBuf also won't release.
> Fix memory leak of direct memory in direct memory entry logger.

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/bk/SimpleLedgerAllocator.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestBKLogWriteHandler.java
- stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestRollLogSegments.java
Issue #3812
Fix bug and one UT for verification
Fix the bug
To avoid the ledger being created twice, add a state check before setting a new state
> [Bug] Always one orphan ledger is created

- bookkeeper-http/vertx-http-server/src/main/java/org/apache/bookkeeper/http/vertx/VertxHttpServer.java
- bookkeeper-http/vertx-http-server/src/test/java/org/apache/bookkeeper/http/vertx/TestVertxHttpServer.java
There is a potential arbitrary file upload vulnerability with `httpServerEnabled=true`, it's caused by `BodyHandler.create()` which returns a BodyHandler that automatically processes file upload requests.
https://github.com/apache/bookkeeper/blob/7f64246ad38981126cc8dd929ff448805a738b8f/bookkeeper-http/vertx-http-server/src/main/java/org/apache/bookkeeper/http/vertx/VertxHttpServer.java#L82
This simple command will upload a file into the `file-uploads` directory under the bookkeeper server process `CWD`.
```shell
$ curl -i --request POST \
--url http://localhost:8000/api/v1/bookie/info \
--header 'Content-Type: multipart/form-data' \
--form file=@<a-path-of-the-file>
$ ls
LICENSE  NOTICE  README.md  bin  conf  deps  file-uploads  lib  logs  scripts
$ ls file-uploads …
```
> Fix arbitrary file upload vulnerability with httpServerEnabled

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/Buffer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/BufferPool.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectCompactionEntryLog.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectEntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectReader.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/LogReaderScan.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestBuffer.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestDirectReader.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestDirectWriter.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestMetadata.java
Some classes in the DirectIO component use `PooledByteBufAllocator` to create ByteBuf instead of using the BookKeeper-initiated allocator. When we configured the BookKeeper allocator OOM policy to shut down, the OOM policy can't apply to those classes which use `PooledByteBufAllocator` to create ByteBuf. 
- Unify ByteBufAllocator for the DirectIO component.
> Unify ByteBufAllocator for the DirectIO component

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
Improve remove performance  of `LedgerMetadataIndex#pendingDeletedLedgers`.
Currently the `pendingDeletedLedgers` is a `ConcurrentLinkedQueue`,  and we just call `remove` and `add` and `poll` method of this queue.  And it seems that we need not keep the order when poll items from it. 
Removing items from  `ConcurrentLinkedQueue` need traversal the queue. Changing the `LedgerMetadataIndex#pendingDeletedLedgers` as a `ConcurrentHashSet` will improve the remove performance.
Changing the `LedgerMetadataIndex#pendingDeletedLedgers` as a `ConcurrentHashSet`
> Change pendingDeletedLedgers as ConcurrentHashSet

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgersIndexRebuildOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadJournalCommand.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
This PR is generated from https://github.com/apache/bookkeeper/pull/3437
Fix https://github.com/apache/bookkeeper/issues/2220
When we use `kill -9` command to stop one bookie pod, the journal file may be broken. If we try to start up the bookie pod again, the pod will startup to fail with the following exception.
```
10:15:55.026 [main] ERROR org.apache.bookkeeper.bookie.Bookie - Exception while replaying journals, shutting down
java.io.IOException: Invalid record found with negative length -448299468
at org.apache.bookkeeper.bookie.Journal.scanJournal(Journal.java:821) ~[org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
at org.apache.bookkeeper.bookie.Bookie.replay(Bookie.java:945) ~[org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
at …
```
> Support skip invalid journal record in replying journal stage

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
Address multiple CVEs:
CVE-2023-34453
CVE-2023-34454
CVE-2023-34455
See https://github.com/xerial/snappy-java/releases/tag/v1.1.10.1
> Upgrade snappy-java to address multiple CVEs

- stream/common/src/main/java/org/apache/bookkeeper/common/resolver/ServiceNameResolverProvider.java
- grpc version was upgraded to 1.56.0 in #3992
- that breaks binary compatibility for DnsNameResolverProvider class
- see https://github.com/grpc/grpc-java/commit/fcb5c54e4b82d354f42ced0121928fabce9ef53f#diff-b04e884de51ed12ff79482f600a2d4ec18e405ee189a4952ae35f4d2742b7160L50
- make the field type NameResolverProvider instead of DnsNameResolverProvider
- this prevents possible NoSuchMethodError errors about DnsNameResolverProvider.newNameResolver method
> Fix issue with binary compatibility with older grpc versions at runtime in the client

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageTest.java
We found one place where the bookie may lose data even though we turn on fsync for the journal.
Condition:
- One journal disk, and turn on fsync for the journal
- Configure two ledger disks, ledger1, and ledger2
Assume we write 100MB data into one bookie, 70MB data written into ledger1's write cache, and 30 MB data written into ledger2's write cache. Ledger1's write cache is full and triggers flush. In flushing the write cache, it will trigger a checkpoint to mark the journal’s lastMark position (100MB’s offset) and write the lastMark position into both ledger1 and ledger2's lastMark file.
At this time, this bookie shutdown without flush write cache, such as shutdown by `kill -9` command, and ledger2's write cache (30MB) doesn’t flush into ledger disk. But ledger2's lastMark position …
> Fix data lost when configured multiple ledger directories

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- pom.xml
---
We upgrade grpc and protobuf to address CVE-2023-32732. But it requires the protobuf 3.22+. In protobuf 3.22.0, it introduces a breaking change. It requires all the sub-project, which depend on the bookkeeper to upgrade protobuf to 3.22.0+. It should not be acceptable in a minor release.
So we use a lower version of grpc and protobuf to address the CVE issue.
See more context: https://github.com/apache/bookkeeper/pull/3997
> [Branch-4.16] Downgrade grpc and protobuf to avoid introducing breaking change

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SortedLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/TriggerGCService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/MockLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/service/TriggerGCServiceTest.java
When I use `curl -XPUT http://<ip>:<port>/api/v1/bookie/gc` command to trigger garbage compaction, the bookie server returns `Internal Server Error`. Then I checked the bookie server's log, and nothing was found.
After a deep debugging of the server, I found the following exception.
```
org.apache.bookkeeper.common.util.JsonUtil$ParseJsonException: Failed to deserialize Object from Json string
at org.apache.bookkeeper.common.util.JsonUtil.fromJson(JsonUtil.java:41)
at org.apache.bookkeeper.server.http.service.TriggerGCService.handle(TriggerGCService.java:71)
at org.apache.bookkeeper.http.vertx.VertxAbstractHandler.processRequest(VertxAbstractHandler.java:55)
at org.apache.bookkeeper.http.vertx.VertxHttpHandlerFactory$1.handle(VertxHttpHandlerFactory.java:47)
at …
```
> Fix trigger GC not work

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
Bump guava version from 31.0.1-jre to 32.0.1-jre, Fix CVE-2023-2976
> Bump guava version from 31.0.1-jre to 32.0.1-jre

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
We should recycle `LongWrapper` in  `finally` block to avoid memory leak. Beacuase `flush()` and `removeDeletedLedgers()` could throw Exception.
Recycle `LongWrapper` in  `finally` block
> Recycle LongWrapper finally to avoid memory leak

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
Optimize `Iterable<Long>  getActiveLedgersInRange(0, Long.MAX_VALUE)` by  avoid applying the filter predicate when traverse the `Iterable<Long>`.
There are many places call `getActiveLedgersInRange(0, Long.MAX_VALUE)`  to get the `Iterable` of all the `ledgerId`,  for example:
1. https://github.com/apache/bookkeeper/blob/147b5bf846189584d6a9b4e20ac9a73e6e617255/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/ScanAndCompareGarbageCollector.java#L124-L125
2. https://github.com/apache/bookkeeper/blob/147b5bf846189584d6a9b4e20ac9a73e6e617255/bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ConvertToDBStorageCommand.java#L88
3. https://github.com/apache/bookkeeper/blob/147b5bf846189584d6a9b4e20ac9a73e6e617255/bo …
> Optimize getActiveLedgersInRange

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/ClusterInfoCommand.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieShellTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/ClusterInfoCommandTest.java
PR #3710 introduced a future for get ClusterInfo about bookies cluster.
This is convenient for us to obtain the basic information of the cluster through the rest api, which is very useful.
When we disable the http port, it will be very troublesome to obtain these cluster information through the command tool, because most of the command tools print the output through the log4j info log, and it will be very troublesome for us to aggregate these results. So I hope to introduce a shell command for this feature.
> [improve] Add ClusterInfo shell Command

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeper.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockLedgerHandle.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockReadHandle.java
Pin the order executor in `LedgerHandle`  to save the choose thread overhead. For details reason:
We could call `executeOrdered()` frequently, e.g., when in `asyncReadEntries`. And we would compute the thread index from ledgerId every time when call `executeOrdered()`. So pin the order executor will save the thread index compution time.
- Choose the order executor in `LedgerHandle`  constructor method and save it as a final field
- Override `getMainWorkerPool()` in `MockBookKeeper` to fix UT NPE exception when call `this.executor = clientCtx.getMainWorkerPool().chooseThread(ledgerId);`
> Pin order executor in LedgerHandle

- site3/website/docusaurus.config.js
The PR #4002 generated the website doc of 4.16.2, but missed updating the `latest_release` variable, and the official document still shows 4.16.1
https://bookkeeper.apache.org/releases
> fix latest_release to 4.16.2

- tests/backward-compat/bc-non-fips/pom.xml
bouncycastle jdk15 on is deprecated in https://github.com/bcgit/bc-java/issues/1139
we can switch to bouncycastle jdk18on
Use Bouncycastle jdk18on instead of jdk15on
> Use Bouncycastle jdk18on instead of jdk15on

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
Fix deletedLedgers count.  We should increase the `deletedLedgers` in the loop, otherwise it's value will always be zero
Increase the `deletedLedgers` in the loop
> Fix deletedLedgers count

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageTest.java
---
In rocksdb, memory usage is related to batch size. The more operations in a single batch, the more memory is consumed. Expose the configuration to allow control the batch size.
> Allow to set max operation numbers in a single rocksdb batch

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieStateManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/SanityTestCommand.java
- tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/SanityTestCommandTest.java
Start the bookie at branch `master`,  notice that there are some logs as followings:
```
2023-08-08T11:28:58,754 - INFO  - [BookieHighPriorityThread-OrderedExecutor-0-0:ReadEntryProcessorV3@205] - Ledger fence request received for ledger: 11360 from address: /192.168.31.216:58247
2023-08-08T11:28:58,784 - INFO  - [BookieHighPriorityThread-OrderedExecutor-0-0:ReadEntryProcessorV3@205] - Ledger fence request received for ledger: 11360 from address: /192.168.31.216:58247
2023-08-08T11:28:58,789 - INFO  - [BookieHighPriorityThread-OrderedExecutor-0-0:ReadEntryProcessorV3@205] - Ledger fence request received for ledger: 11360 from address: /192.168.31.216:58247
2023-08-08T11:28:58,792 - INFO  - [BookieHighPriorityThread-OrderedExecutor-0-0:ReadEntryProcessorV3@205] - Ledger fence request …
```
> Improve sanity test command.

- site3/website/docs/getting-started/installation.md
fix the stats/bookkeeper-stats-providers hype-link
https://bookkeeper.apache.org/docs/getting-started/installation/#package-directory
[bookkeeper-stats](https://github.com/apache/bookkeeper/tree/master/bookkeeper-stats)
[bookkeeper-stats-providers](https://github.com/apache/bookkeeper/tree/master/bookkeeper-stats-providers)
- File Not Found
fix
> fix the stats/bookkeeper-stats-providers hype-link

- dev/release/000-run-docker.sh
- dev/release/Dockerfile
---
Because we have a Native IO that needs to be built from cpp code. The build platform will impact the target library. People are using different laptop to execute the release process with docker, we need to force the image to use linux/amd64 platform to ensure the .so lib build out the correct platform lib.
Since most of time we are using amd64 to run the bookie, making the dev docker image build from amd64.
Update the dev Dockerfile to use the specified platform.
> [release] Force to use linux/amd64 to build release

- conf/log4j2.xml
We introduced DirectIO since BookKeeper 4.16.0, and the DirectIO classes use KV-based Slf4jSlogger. https://github.com/apache/bookkeeper/blob/master/bookkeeper-slogger/slf4j/src/main/java/org/apache/bookkeeper/slogger/slf4j/Slf4jSlogger.java 
In order to print the KV out, we need to add `%X` flag in log4j2.yaml, otherwise the log will miss the detailed key and values.
In order to reduce the impact on current logger appenders, I add MDC-based appenders for `CONSOLE`, `TRACEFILE`, and `ROLLINGFILE` by adding `%X` for log4j2.yaml Appender PatternLayout. 
Only classes under `org.apache.bookkeeper.bookie.storage.directentrylogger` will enable MDC-based appender logger.
If the key value has items, the log will look like:
```
2023-06-19T16:01:56,685+0800 [main] INFO …
```
> Enable kv logs in log4j configuration

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/component/AbstractLifecycleComponent.java
- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/component/AutoCloseableLifecycleComponent.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/EmbeddedServer.java
If closed with exception, the log will always be `failed to close AutoCloseableLifecycleComponent`.  It will be better to print the `componentName` instead of the class name.
Print the `componentName` instead of `AutoCloseableLifecycleComponent` class name if closed with exception
> fix AutoCloseableLifecycleComponent close exception log

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultEntryLogger.java
In the `getEntryLogMetadata` method, the `FileNotFoundException` exception is caught before the more general Exception. This modification ensures that if the log file is not found, there is no need to proceed with the `extractEntryLogMetadataByScanning(entryLogId, throttler)` method call.
This enhancement improves the code's error handling by distinguishing between different exceptions that may occur during the retrieval of entry log metadata. It ensures that unnecessary operations, scanning the log, are skipped when the log file is not found.
> Optimize getEntryLogMetadata

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultEntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLoggerAllocator.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectEntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/EntryLogIdsImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LedgerDirUtil.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CreateNewLogTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestEntryLogIds.java
Fixes #4040 
Upgrade guide:
If the user already uses the DirectEntryLogger in production, can not disable DirectEntryLogger directly. 
There are two ways:
1. Upgrade to the version with this PR, and disable DirectEntryLogger. Then restart, and the data won't be lost.
2. If you don't want to upgrade to the bookie version, you should stop the bookie first, then find the entry log which has the biggest log id.  Modify the `lastLogId` file content using the biggest log id. (Not recommend)
> Make compatible between DefaultEntryLogger and DirectEntryLogger

- stream/server/src/main/java/org/apache/bookkeeper/stream/cluster/StreamCluster.java
Fix comment typo in `StreamCluster`
`// stop servers` -> `// start servers`
> Fix comment typo in StreamCluster

- stream/clients/java/base/src/test/java/org/apache/bookkeeper/clients/impl/container/TestStorageContainerInfo.java
I am working on research that investigates test smell refactoring in which we identify alternative implementations of test cases, study how commonly used these refactorings are, and assess how acceptable they are in practice. This smell is known as _Assertion Roulette_, where a test method has multiple asserts without explanatory messages, which can sometimes make it difficult to identify which assert has failed. We would like to get your feedback on this particular test refactoring. Thanks in advance for your input.
> Add explanatory messages to the asserts

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
When triggering one bookie decommission, the bookie check max interval is 10 minutes. 
```
2023-08-10T13:56:08,911-0400 [main] INFO  org.apache.bookkeeper.client.BookKeeperAdmin - Resetting LostBookieRecoveryDelay value: 0, to kickstart audit task
2023-08-10T13:56:50,793-0400 [main] INFO  org.apache.bookkeeper.client.BookKeeperAdmin - Count of Ledgers which need to be rereplicated: 23140
2023-08-10T14:08:47,350-0400 [main] INFO  org.apache.bookkeeper.client.BookKeeperAdmin - Count of Ledgers which need to be rereplicated: 2984
2023-08-10T14:19:02,330-0400 [main] INFO  org.apache.bookkeeper.client.BookKeeperAdmin - Count of Ledgers which need to be rereplicated: 2984
2023-08-10T14:29:17,332-0400 [main] INFO  org.apache.bookkeeper.client.BookKeeperAdmin - Count of Ledgers which need to be …
```
> Optimize bookie decommission check wait interval

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
When the garbage collection is triggered, we don't know the actual compaction progress, for example, the total entrylog files waiting to be compacted and how many entrylog files have been compacted. Without the information, we don't know when will the garbage collection will finish.
Print the garbage collection progress every one minutes, and the progress contains how many EntryLog files have been compaction and the total EntryLog files waiting to be compacted.
> Print compaction progress

- pom.xml
To make all UTs can run under JDK17
add `--add-opens java.base/java.util.concurrent.locks=ALL-UNNAMED`
> Some UTs fail when running under JDK17

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RegionAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicy.java
Rack-aware placement policies enable preference for bookies that reside in the same rack as the bookie client.
- Initiate local node by resolving the rack information
https://github.com/apache/bookkeeper/blob/5b5c05331757e7356579076970e61f119f5d34ae/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java#L207-L215
- When generating new ensembles for a ledger, the selecting algorithm will set the localNode's rack to `curRack` and select one bookie from `curRack` first 
https://github.com/apache/bookkeeper/blob/5b5c05331757e7356579076970e61f119f5d34ae/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java#L420-L426
However, when resolving the local node's rack information, we use IP to resolve the …
> Rackaware placement policy support local node awareness by hostname

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestLedgerFragmentReplication.java
Master issue: #4036 
Set the `numberOfEntriesToReplicate` to 0 when ledger is empty
> Fix NoSuchElementException when rereplicate empty ledgers

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RegionAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
If the `perRegionPlacement` available bookies are empty, do not pick a bookie from it.
> Ignore the empty `perRegionPlacement` when RegionAwareEnsemblePlacementPolicy#newEnsemble

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
OWASP dependency check reports CVE-2023-44981 for Zookeeper.
Upgrade Zookeeper to 3.8.3.
Release notes: https://zookeeper.apache.org/doc/r3.8.3/releasenotes.html
Also upgrade snappy-java to 1.1.10.5 since Zookeeper depends on that library.
> Upgrade Zookeeper to 3.8.3 to address CVE-2023-44981

- conf/bk_server.conf
In `conf/bk_server.conf`, the document and default value of `diskUsageWarnThreshold` and `diskUsageLwmThreshold` is not synced with the code.
- Update the document and default value of `diskUsageWarnThreshold` and `diskUsageLwmThreshold`
> Update the document of diskUsageWarnThreshold

- site3/website/src/pages/release-notes.md
BookKeeper 4.16.2 is complied for M1 and can not run on x86_64 Linux if you enabled direct IO. We need to update the release note to let users know the risks of this version
Update release note for 4.16.2
> Update release note for 4.16.2

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
While shouldRolloverJournal is true，the QueueEntry qe is not added to the toFlush queue but we decrease the JournalQueueSize incorrectly.
Decrease the JournalQueueSize after correct NonNull check of qe.
> Fix bug of negative JournalQueueSize

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
Detailed paths
Introduced through: org.apache.distributedlog:dlfs@4.16.0-SNAPSHOT › org.apache.distributedlog:distributedlog-core@4.16.0-SNAPSHOT › org.apache.bookkeeper:bookkeeper-server@4.16.0-SNAPSHOT › org.bouncycastle:bc-fips@1.0.2.3
Fixed in org.bouncycastle:bc-fips@1.0.2.4
Upgrade the org.bouncycastle:bc-fips dependency from 1.0.2.3 to 1.0.2.4
> Upgrade bc-fips to 1.0.2.4 to fix CVE-2022-45146

- bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/CleanupLedgerManager.java
---
In the cleanup ledger manager, we just record every future and remove them when the future complete. Seems we don't need to print the logs
> Remove the unused logs in the CleanupLedgerManager.recordPromise

- conf/bk_server.conf
The AutoRecovery would move the data to another alive bookie to ensure the data replicas. So it will read data from the alive bookie at the ensemble, then write the data to the new bookie.
When reading data, it will choose the bookie in the ensemble randomly, so it may choose the bookie that may be already shut down, and then print many warm logs.
If we make stickyReadSEnabled=true, it will read the data from the alive bookie continually, and won't print any warm log, and the stickyReadS can improve hit rate of the bookie server read cache, speed the read operation.
> Make AutoRecovery enable stickyReadS as default.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/net/NetworkTopologyImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/net/NetworkTopologyImplTest.java
- `NetworkTopologyImpl` does not allow multi Bks register with different `depthOfAllLeaves.`
- Regarding `NetworkTopologyImpl,` once a node is added, the `depthOfAllLeaves` will be initiated. 
- When a new BK is registering:
-  `EnsemblePlacementPolicy.networkTopology.add( newBkNode )`
- `EnsemblePlacementPolicy.knownBookies.add( newBkNode )`
- Once `network topology.add(newBkNode)` fail, it will not call `knownBookies.add( newBkNode )`
---
- Register `[BK1,BK2]` with rack `/r_1`
- `depthOfAllLeaves` is `2` now.
- Restart `[BK1,BK2]` with rack `/region_1/r_1`
- the depth of  `/region_1/r_1` is `3`, different with `2`
- Since `depthOfAllLeaves` of `NetworkTopologyImpl` is still `2`, `[BK1, BK2]` could not be added, and get an error `can't add leaf node BK1 at depth 3 to the topology.`
You …
> Fix no known bookies after reset racks for all BKs

- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/HandleFailuresTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockBookieClient.java
Master Issue: https://github.com/apache/bookkeeper/issues/4109
Fix Flaky-test: HandleFailuresTest.testHandleFailureBookieNotInWriteSet
When we call `b1Delay.completeExceptionally(new BKException.BKWriteException())` at line480(code1),  the `preWriteHook` will complete with exception  and then do some actions in the choosen thread(code2), e.g., put the failure bookie to `delayedWriteFailedBookies`(code3).  So the `delayedWriteFailedBookies` update is async.
However, `lh.appendAsync("entry2".getBytes()))`(Line483 in Code4) is invoked in main thread. So when `appendAsync` execute,  the `delayedWriteFailedBookies` could be not updated yet, and `changeInProgress.complete(null)`(code5) will never be invoked.
We can reproduce this flasy-test if we put …
> issue 4109: Fix Flaky-test: HandleFailuresTest.testHandleFailureBookieNotInWriteSet

- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieZKExpireTest.java
The `BookieZKExpireTest.testBookieServerZKSessionExpireBehaviour` is a flaky test and the root cause is described in https://github.com/apache/bookkeeper/pull/3418. 
There is a race condition in the zookeeper reconnection and listener and it is an expected behavior in Bookie.
We created one issue to track this https://github.com/apache/bookkeeper/issues/4142. 
We can skip this flaky test to unblock the pending PRs.
Skip this flaky test.
> ---
>
> ---
> Be sure to do all …
> Use Flaky flag to skip testBookieServerZKSessionExpireBehaviour test

- circe-checksum/src/main/java/com/scurrilous/circe/checksum/Java9IntHash.java
- circe-checksum/src/test/java/com/scurrilous/circe/checksum/Java9IntHashTest.java
In the method `Java9IntHash.resume(int current, ByteBuf buffer, int offset, int len)`, It tries to read all the data batch an batch, and finally to calculate `checksum`. But it forgets to forward the `offset` of the `ByteBuf`.
https://github.com/apache/bookkeeper/blob/master/circe-checksum/src/main/java/com/scurrilous/circe/checksum/Java9IntHash.java#L110-L117
```java
byte[] b = TL_BUFFER.get();
int toRead = len;
while (toRead > 0) {
int length = Math.min(toRead, b.length);
buffer.slice(offset, len).readBytes(b, 0, length); // Here, the variable `offset` never change.
negCrc = resume(negCrc, b, 0, length);
toRead -= length;
}
```
The log of issue:
```
2023-12-01T08:16:58,235+0000 [pulsar-io-8-5] ERROR org.apache.pulsar.broker.service.Producer - [PersistentTopic{topic=persistent://x/x/x}] …
```
> fix calculate checkSum when using Java9IntHash

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
The **ledgersCount.incrementAndGet** should be called in **setExplicitLac** , just like in **setFenced** and **setLimbo**.
> Add ledgersCount.incrementAndGet in setExplicitLac function

- stats/bookkeeper-stats-providers/codahale-metrics-provider/src/main/java/org/apache/bookkeeper/stats/codahale/FastTimer.java
- stats/bookkeeper-stats-providers/codahale-metrics-provider/src/test/java/org/apache/bookkeeper/stats/codahale/FastTimerTest.java
FastTimer returns zero rate if rate call happens immediately after the first timer update. E.g. this test would fail:
```java
FastTimer t = new FastTimer();
t.update(10, TimeUnit.NANOSECONDS);
assertTrue("should calculate mean before advancing time", t.getMeanRate() > 0);
```
Fixed + added a test
> FastTimer to return rates if queried at the same second as update

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- pom.xml
Keep Netty and Netty's io_uring libraries up-to-date. 
Release notes since last upgrades:
Netty:
- https://netty.io/news/2023/12/15/4-1-104-Final.html
- https://netty.io/news/2023/12/13/4-1-103-Final.html
- https://netty.io/news/2023/11/09/4-1-101-Final.html
- https://netty.io/news/2023/10/10/4-1-100-Final.html
- https://netty.io/news/2023/09/21/4-1-99-Final.html
- https://netty.io/news/2023/09/21/4-1-98-Final.html
- https://netty.io/news/2023/08/23/4-1-97-Final.html
- https://netty.io/news/2023/07/27/4-1-96-Final.html
- https://netty.io/news/2023/07/20/4-1-95-Final.html
io_uring: 
- https://netty.io/news/2023/11/17/io_uring_0-0-24-Final.html
- https://netty.io/news/2023/10/02/multiple_releases_incubator.html
- Upgrade Netty to 4.1.103.Final (from 4.1.94.Final)
- Upgrade Netty io_uring to …
> Upgrade Netty to 4.1.104.Final and io_uring to 0.0.24.Final

- conf/bk_server.conf
https://bookkeeper.apache.org/docs/reference/config/#statistics
The default configuration declared on the bookkeeper.apache.org website has been annotated and is invalid
Master Issue: #4154
> [fix][conf-stats] Fix default configuration 'statsProviderClass'

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
The auditor didn't close the ledger manager and ledger under replication manager the thread will leak.
Run the test `AuditorPeriodicBookieCheckTest` and get the stack.
```
Full thread dump Java HotSpot(TM) 64-Bit Server VM (11.0.15+8-LTS-149 mixed mode):
Threads class SMR info:
_java_thread_list=0x0000600003e44460, length=16, elements={
0x00007fad34009000, 0x00007fad45032800, 0x00007fad14813800, 0x00007fad44010800,
0x00007fad44011800, 0x00007fad45037800, 0x00007fad3400a000, 0x00007fad45812800,
0x00007fad34944000, 0x00007fad4585f800, 0x00007fad45456000, 0x00007fad4444c000,
0x00007fad3431b800, 0x00007face5825800, 0x00007face5860800, 0x00007face4009800
}
"main" #1 prio=5 os_prio=31 cpu=1801.68ms elapsed=20.85s tid=0x00007fad34009000 nid=0x2a03 waiting on condition  [0x000000030a10d000] …
```
> Fix auditor thread leak problem.

- docker/scripts/apply-config-from-env.py
- docker/scripts/common.sh
- docker/scripts/init_zookeeper.sh
Fix #4136 
Modify `apply-config-from-env.py` to accept individual files as parameters instead of a configuration folder. This change will enable the script to selectively apply the configuration override mechanism only to the necessary files.
> Issue 4136: Fix logging configurations are broken in docker image

- docker/README.md
> [doc] fix bookkeeper binary path

- site3/website/docs/admin/bookies.md
After the issue on disabled sticky reads, I'm adding this to improve documentation about performance on reading.
Master Issue: #4130
> Issue #4130: [doc][site] split performance in two parts and add sticky reads part.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RegionAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
The entry write supports the local node Rack-Aware placement policy but does not support the local node Region-Aware placement policy
The entry read supports the local node Region-Aware placement policy but does not support the local node Rack-Aware placement policy
In order to match the local node region/rack awareness both on entry write and read, we need to support the following feature
Entry write supports local node region awareness placement policy
Entry read supports local node rack awareness placement policy
- The PR aims to support the entry write local node region awareness placement policy. 
- It will select one bookie that is located in the same region and rack with the local node to form the ledger ensemble.
> Entry write support local node region aware placement policy

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
When deploying Bookie on K8s with limited CPU resources, once the CPU is throttled, the journal write latency will increase.
One case of causing CPU throttle is garbage collection triggered.
The journal write latency is sensitive with the journal CPU, especially when the CPU is throttled.
Increase the JournalThread and ForceWriteThread priority to reduce the latency impaction when the CPU is being throttled.
> Increase journal thread priority

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestLedgerFragmentReplicationWithMock.java
---
#3783 changed the recovery add request flags. It causes when replication happening, if the ledger was fenced, the ledger can not be recovered. Because the recovery add flag is not added then the normal add is not allowed to a fenced ledger.
> Fix the autorecovery failed replicate by add entry fenced error

- docker/README.md
> Fix Docker README.md

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectEntryLogger.java
When we use DirectIO and a catch up read occurs, a memory leak occurs because the ByteBuf is not released. 
Because although in the `internalReadEntry` method in `DirectEntryLogger`, even if the upper layer `fillReadAheadCache` uses the `ReferenceCountUtil.release(entry)` method in the finally block to release ByteBuf, it will still cause an exception thrown by `internalReadEntry`, and the `entryLogger.readEntry` method happens to be in try. ..catch unexpected, causing ByteBuf to not be released correctly
Master Issue: #4134
> Issue 4134: Fixing memory leak error when using DirectEntryLogger

- conf/log4j2.shell.xml
Optimize shell log print.
When we execute the bookkeeper shell , e.g., `bin/bookkeeper shell listbookies -a`, it will print a lot of redundant logs. And the key infomation is hard to find:
Changing the `log4j2.shell.xml` to only print the key infomation, other logs will be printed to the `bookkeeper-shell.log` file
After changing:
> Optimize shell log print

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RegionAwareEnsemblePlacementPolicy.java
fix a config error in RegionAware#initialize.
There is double config ignoreLocalNodeInPlacementPolicy in RegionAware#initialize. Actually one of 
the config is useHostnameResolveLocalNodePlacementPolicy.
use correct config name
> fix a config error in RegionAware#initialize

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultEntryLogger.java
Cleanup `logfileHeader`  in `DefaultEntryLogger`.   There is no place to invoke `DefaultEntryLogger#logfileHeader` to write,  and the `logfileHeader` has moved to `EntryLoggerAllocator`:
https://github.com/apache/bookkeeper/blob/a842f3e92cbe7c9a99f72567af19b8f7c4ce7e82/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLoggerAllocator.java#L66
https://github.com/apache/bookkeeper/blob/a842f3e92cbe7c9a99f72567af19b8f7c4ce7e82/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLoggerAllocator.java#L79-L87
https://github.com/apache/bookkeeper/blob/a842f3e92cbe7c9a99f72567af19b8f7c4ce7e82/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLoggerAllocator.java#L170-L171
Cleanup `logfileHeader`  in …
> Cleanup logfileHeader  in DefaultEntryLogger

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/TopologyAwareEnsemblePlacementPolicy.java
When some bookie is down, the resolver will resolve failed, it will print many logs. 
1. In RackawareEnsemblePlacementPolicyImpl#replaceBookie, reduce the repeat resolve operation.
2. In TopologyAwareEnsemblePlacementPolicy#resolveNetworkLocation, avoid to print the stack info.
> Improve auto-recovery noise log when some bookie down.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorElector.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorLedgerCheckerTest.java
Now, when we shut down the auditor elector. The shutdown behavior via submitting a shutdown task to do it. 
In some cases, the follower auditor elector executor is always blocked due to waiting leader election, so the shutdown task will lie in the task queue forever, get no chance to execute.
In the pulsar, the case happen. See https://github.com/apache/pulsar/pull/21797#discussion_r1436278822
So in the auditor elector shutdown, if the remain task can't done in time, we should invoke shutdownNow to interrupt the blocked thread.
> Fix auditor elector executor block problem.

- bookkeeper-proto/src/main/proto/BookkeeperProtocol.proto
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClientImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookkeeperInternalCallbacks.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ResponseBuilder.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufList.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockBookieClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockBookies.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieClientTest.java
This is the third PR for the batch read(https://github.com/apache/bookkeeper/pull/4051) feature.
Bookkeeper client introduces batch read request API.
> [BP-62] Bookkeeper client introduce batch read request api.

- site3/website/src/pages/release-notes.md
Generate BookKeeper 4.16.4 release note
> Generate 4.16.4 release note

- deploy/kubernetes/gke/bookkeeper.statefulset.yml
- tests/docker-images/statestore-image/Dockerfile
1. There are multiple spec.ports fields in sts yaml
2. The RUN command specified in dockerfile is not standardized
Master Issue: #4185
> [improve][docker] fix yaml and dockerfile

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeperTestCase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ReadLastConfirmedAndEntryOpTest.java
- conf/bk_server.conf
If one ledger's ensemble is [bk0, bk1] and bk0 is down, the bookie client may send a read request to bk0 first then fail with the following errors, and resend the read request to bk1 in the end. 
```
2023-10-19T18:33:52,042 - ERROR - [BookKeeperClientWorker-OrderedExecutor-3-0:PerChannelBookieClient@563] - Cannot connect to 192.168.31.216:3181 as endpoint resolution failed (probably bookie is down) err org.apache.bookkeeper.proto.BookieAddressResolver$BookieIdNotResolvedException: Cannot resolve bookieId 192.168.31.216:3181, bookie does not exist or it is not running
2023-10-19T18:33:52,042 - INFO  - [BookKeeperClientWorker-OrderedExecutor-3-0:DefaultBookieAddressResolver@77] - Cannot resolve 192.168.31.216:3181, bookie is unknown …
```
> Enable reorder read sequence for bk client by default

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BatchedReadOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ListenerBasedPendingReadOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ReadOpBase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestParallelRead.java
This is the fourth PR for the batch read(https://github.com/apache/bookkeeper/pull/4051) feature.
Refactor read op, extract ReadOpBase. Introduce batchedReadOp.
> [BP-62] Refactor read op, and introduce batchReadOp.

- .github/workflows/codeql.yml
> Enable CodeQL static code scanner

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- bookkeeper-server/pom.xml
- pom.xml
Netty's epoll support for Linux on ARM64 (aarch_64) is missing. 
- add netty-transport-native-epoll for linux-aarch_64
- use netty-bom to align versions
> Use netty-bom for aligning netty library versions, add epoll for linux-aarch_64

- .github/workflows/bk-ci.yml
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/CRC32CDigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/CRC32DigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DirectMemoryCRC32Digest.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DummyDigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/MacDigestManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/StandardCRC32Digest.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufList.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufVisitor.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/checksum/CompositeByteBufUnwrapBugReproduceTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/ByteBufListTest.java
- circe-checksum/src/main/java/com/scurrilous/circe/checksum/Crc32cIntChecksum.java
- circe-checksum/src/main/java/com/scurrilous/circe/checksum/IntHash.java
- circe-checksum/src/main/java/com/scurrilous/circe/checksum/Java8IntHash.java
- circe-checksum/src/main/java/com/scurrilous/circe/checksum/Java9IntHash.java
- circe-checksum/src/main/java/com/scurrilous/circe/checksum/JniIntHash.java
Cherry pick #4196 to branch-4.16
> [branch-4.16] Fix checksum calculation bug when the payload is a CompositeByteBuf with readerIndex > 0 (#4196)

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
- stats/bookkeeper-stats-providers/codahale-metrics-provider/src/main/java/org/apache/bookkeeper/stats/codahale/FastTimer.java
Fix implicit cast from long to int
> ---
>
> ---
>
>
> - [ ] Attach the master issue link in the …
> Fix implicit cast from long to int

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
We support batch reading in [BP-62](https://github.com/apache/bookkeeper/pull/4051) and auto-recovery is the best case to support this feature. This PR supports batch reading for auto-recovery and introduces a flag `recoveryBatchReadEnabled` to enable batch reading for auto-recovery
We introduce a flag `recoveryBatchReadEnabled` to enable batch reading for auto-recovery.
> AutoRecovery supports batch read

- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
The method `InetAddress.getLocalHost().getHostName()` result may be different from `InetAddress.getLocalHost().getCanonicalHostName()`.
In the laptop, the method `InetAddress.getLocalHost().getHostName()` return `horizondeMBP`, the method `InetAddress.getLocalHost().getCanonicalHostName()` return `horizondembp`.
We should also update the rack for `InetAddress.getLocalHost().getCanonicalHostName()`.
> Add `InetAddress.getLocalHost().getCanonicalHostName()` for TestRackawareEnsemblePlacementPolicy#updateMyRack.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListFilesOnDiscCommand.java
- docker/README.md
- site3/website/docs/admin/bookies.md
- site3/website/docs/reference/cli.md
- site3/website/src/pages/community/coding-guide.md
| Parameter | Description | Default
| --------- | ----------- | ------- | 
| journalDirectories | The directories to which Bookkeeper outputs its write-ahead log (WAL). Could define multi directories to store write head logs, separated by ','.<br />For example:<br /> journalDirectories=/tmp/bk-journal1,/tmp/bk-journal2<br />If journalDirectories is set, bookies will skip journalDirectory and use this setting directory.<br /> | /tmp/bk-journal | 
| journalDirectory | @Deprecated since 4.5.0, in favor of using `journalDirectories`.<br /><br />The directory to which Bookkeeper outputs its write-ahead log (WAL).<br /> | /tmp/bk-txn | 
update doc about conf#JournalDirectory 2 conf#JournalDirectories& fix listfilesondisc cmd description
Master Issue: …
> [improve] fix doc & fix listfilesondisc cmd description

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
`setBatchReadEnabled` is duplicated, which breaks the compilation:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project bookkeeper-server: Compilation failure: Compilation failure: 
Error:  /home/runner/work/bookkeeper/bookkeeper/bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java:[2110,32] method setBatchReadEnabled(boolean) is already defined in class org.apache.bookkeeper.conf.ClientConfiguration
```
Remove the duplicated method.
> Remove duplicate setBatchReadEnabled

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieMultipleJournalsTest.java
- pom.xml
Upgrade the mockito for better compatibility with the latest JDK.
Because mockito@5 requires the JDK 11, we can only upgrade to mockito@4.11.0.
- Upgrade mockito from 3.12.4 to 4.11.0.
- Using wrapper instead of extend the `BookieCriticalThread` in the `Journal` and `BookieImpl`, because the mocktio doesn't support spying the `Thread` class: https://github.com/mockito/mockito/issues/2906#issuecomment-1426688993
> Upgrade mockito from 3.12.4 to 4.11.0

- bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchReadThroughputLatency.java
In BenchReadThroughputLatency, it generates the ledger zk node path using 
`String.format("/ledgers/L%010d", ledger.get());`
But if the user uses `HierarchicalLedgerManager`, `LegacyHierarchicalLedgerManager`, or `LongHierarchicalLedgerManager`, the ledger zk node path is not the same as the way in the BenchReadThroughputLatency.
So we need support config the `genLedgerWay` to match the custom LedgerManager.
> BenchReadThroughputLatency support config the way of gen ledger path.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
We must add the filename check before doing any operations to reduce the attack risk.
Add filename check.
> ---
>
> ---
>
> …
> Fix uncontrolled data used in path expression

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- pom.xml
Keep Netty and Netty's io_uring libraries up-to-date.
Release notes since last upgrades:
Netty:
- https://netty.io/news/2024/02/13/4-1-107-Final.html
- https://netty.io/news/2024/01/19/4-1-106-Final.html
- https://netty.io/news/2024/01/16/4-1-105-Final.html
io_uring:
- https://netty.io/news/2024/02/19/io_uring_0-0-25-Final.html
updated dependencies in pom.xml
> Upgrade Netty to 4.1.107.Final and io_uring to 0.0.25.Final

- bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchReadThroughputLatency.java
Fix BenchReadThroughputLatency batch read can't stop problems.
> Fix BenchReadThroughputLatency batch read can't stop problems.

- dev/release/000-run-docker.sh
The 000-run-docker.sh script didn't work for me with my configs.
Use an alternative way to get project.version
> Simplify getting project version in release script

- bookkeeper-common/pom.xml
- bookkeeper-dist/all/pom.xml
- bookkeeper-dist/bkctl/pom.xml
- bookkeeper-dist/pom.xml
- bookkeeper-dist/server/pom.xml
- bookkeeper-server/pom.xml
- circe-checksum/pom.xml
- cpu-affinity/pom.xml
- microbenchmarks/pom.xml
- native-io/pom.xml
- pom.xml
- shaded/bookkeeper-server-shaded/pom.xml
- shaded/bookkeeper-server-tests-shaded/pom.xml
- shaded/distributedlog-core-shaded/pom.xml
- stream/clients/java/all/pom.xml
- stream/clients/java/base/pom.xml
- stream/distributedlog/common/pom.xml
- stream/distributedlog/core/pom.xml
- stream/distributedlog/protocol/pom.xml
- stream/proto/pom.xml
- stream/server/pom.xml
- stream/storage/api/pom.xml
- stream/storage/impl/pom.xml
- stream/tests-common/pom.xml
- tests/docker-images/all-versions-image/pom.xml
- tests/docker-images/current-version-image/pom.xml
- tests/pom.xml
dev/release/003-release-perform.sh fails with errors
```
[INFO] [INFO] --- source:3.3.0:jar (attach-sources) @ buildtools ---
[INFO] [INFO] Building jar: /Users/lari/workspace-pulsar/bookkeeper/target/checkout/buildtools/target/buildtools-4.17.0-sources.jar
[INFO] [INFO]
[INFO] [INFO] --- source:3.3.0:jar-no-fork (attach-sources) @ buildtools ---
[INFO] [ERROR] We have duplicated artifacts attached.
...
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.3.0:jar-no-fork (attach-sources) on project buildtools: Presumably you have configured maven-source-plugn to execute twice times in your build. You have to configure a classifier for at least on of them. -> [Help 1]
[INFO] [ERROR]
```
After resolving that, there was another set of errors in installing …
> Fix duplicate artifacts issue with maven-source-plugin in release build

- dev/release/000-run-docker.sh
- dev/release/Dockerfile
While testing the dev/release/000-run-docker.sh I ran into several problems. 
- My ~/.gitconfig settings collided with the configuration used in 000-run-docker.sh
- I'm using GitHub CLI `gh auth login` to manage git credentials for GitHub
- The git commit failed because of some unsafe directory warning
- gpg-agent failed to run and gpg signing failed
- add more instructions when the script starts
- add workaround for gpg-agent and gpg issue
> Improve release script instructions

- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeperTestCase.java
fix #4200 
`DeferredSyncTest.testForceWillAdvanceLacOnlyUpToLastAcknoledgedWrite` is flaky. The build times out since the test MAY never finishes.  This PR fix it.
Use `synchronized` block to operate `suspendedBookiesForForceLedgerAcks` and `deferredBookieForceLedgerResponses`
Master Issue: #4200
> Issue 4200: fix flaky test DeferredSyncTest.testForceWillAdvanceLacOnlyUpToLastAcknoledgedWrite

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
I tried to use command `bin/bookkeeper shell listbookies -a` to get all bookies from localbookie, it raised error
```
ERROR Fail to process command 'list'
org.apache.bookkeeper.client.BKException$ZKException: Error while using ZooKeeper
at org.apache.bookkeeper.discover.ZKRegistrationClient.lambda$getChildren$4(ZKRegistrationClient.java:352) ~[bookkeeper-server-4.17.0-SNAPSHOT.jar:4.17.0-SNAPSHOT]
at org.apache.bookkeeper.zookeeper.ZooKeeperClient$25$1.processResult(ZooKeeperClient.java:1177) ~[bookkeeper-server-4.17.0-SNAPSHOT.jar:4.17.0-SNAPSHOT]
at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:668) ~[zookeeper-3.8.1.jar:3.8.1]
at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:553) ~[zookeeper-3.8.1.jar:3.8.1]
Caused by: …
```
> Add Cookie to LocalBookie

- circe-checksum/src/main/java/com/scurrilous/circe/utils/NativeUtils.java
- cpu-affinity/src/main/java/org/apache/bookkeeper/common/util/affinity/impl/NativeUtils.java
Creating the temp directory for unpacking the native library is failing for the affinity library.
Use `Files.createTempDirectory()` instead.
> ---
>
> ---
>
>
> …
> Fixed creation of temporary dir in NativeUtils

- pom.xml
Java 22 has been released. Lombok 1.18.32 comes with Java 22 support.
Lombok changelog: https://projectlombok.org/changelog
Upgrade Lombok to 1.18.32
> Upgrade Lombok to 1.18.32 for Java 22 support

- bookkeeper-http/vertx-http-server/src/main/java/org/apache/bookkeeper/http/vertx/VertxHttpServer.java
- The http handler implementations in Bookkeeper aren't necessarily non-blocking. That's why they should be executed on the blocking thread pool in vertx.
Executing on blocking thread pool in vertx can be achieved by registering the handlers using the `blockingHandler` method instead of the `handler` method.
> Use vertx blockingHandlers to run Bookkeeper http handlers which could be blocking

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-server/pom.xml
- pom.xml
Adding lmax disruptor in dependency allow user to config AsyncLogger in log4j2.xml like this
```xml
<Loggers>
<AsyncLogger name="async" level="info">
<AppenderRef ref="AsyncConsole"/>
</AsyncLogger>
</Loggers>
```
See also https://logging.apache.org/log4j/2.x/manual/async.html
> feat: allow user config AsyncLogger in log4j2

- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/conf/ConfigDefTest.java
fix windows test failure in ConfigDefTest.  difference is lineSeparator
change readfile to read line and insert `lineSeparator`
> fix: windows test failure in ConfigDefTest

- stats/bookkeeper-stats-providers/prometheus-metrics-provider/pom.xml
fix test log in prometheus-metrics-provider module
```
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
```
add `testtools` dependency in prometheus-metrics-provider module, it contains `log4j-slf4j2-impl`
> fix: miss test log in prometheus-metrics-provider module

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieClientTest.java
This root cause was found by @codelipenghui  and I just tried to reproduce and write this PR.
`PerChannelBookieClient.addEntry` duplicates the binary data (`@param toSend`) and sends the binary data new to the IO out. Manually release the binary data new if can not be sent out due to the channel switching. See the explanation below.
**Issue:** it released the original data (`@param toSend`), it is wrong. Leading a memory leak and the bellow error log
```
"Apr 10, 2024 @ 16:06:49.893","2024-04-10T16:06:49,892+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.common.util.SingleThreadExecutor - Error while running task: refCnt: 0, increment: 1"
"Apr 10, 2024 @ 16:06:49.893","io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1"
"Apr 10, 2024 @ …
```
> [fix] Fix ByteBuf release/retain in PerChannelBookClient

- circe-checksum/pom.xml
- cpu-affinity/pom.xml
Fix #2261 
fix tests running when skipTests provided
config skipTests flag for `nar-maven-plugin`
> fix tests running when skipTests provided

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
Fix #3639 
Fix mistake typo, compatible code can be removed in next major version
> compatible fix wrong key for getHttpServerTrustStorePassword

- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/TestPrometheusMetricsProvider.java
Fixed the JVM Direct Memory Metrics test failure on Windows due to differences in line separators across operating systems.
- Moved the ByteBuf allocation after metrics server started.
- Changed the line separator in assertions from System.lineSeparator() to \n.
> test: fix testJvmDirectMemoryMetrics windows test failure

- .github/workflows/codeql.yml
- .github/workflows/java21-daily-build.yml
- .github/workflows/windows-daily-build.yml
Add `java21` and `windows` daily build to prepare future support. We already do some works in java21 and windows. See alos #4189 
Add daily github actions to trigger `mvn clean install` on java21 and windows
> build: add java21 and windows daily build

- bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchThroughputLatency.java
According to `https://stackoverflow.com/questions/12808934/what-is-p99-latency`, the implementation for `percentile` in bookkeeper-benchmark is wrong.
When I did benchmark tests using bookeeper-benchmark, I found that the percentile output seemed wrong. After checking the source code I think the current implementation is wrong.
Fix function `percentile` in bookkeeper-benchmark to make it corrent.
> fix wrong implementation for `percentile` in bookkeeper-benchmark

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/Buffer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectEntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
Fix some typos in package org.apache.bookkeeper.bookie.storage.
`satify` => `satisfy`
`Interruped` => `Interrupted`
`LedgerLoggger` => `LedgerLogger`
`orginalLedgerId` => `originalLedgerId`
`IOExecption` => `IOException`
> chore: fix some typos in package org.apache.bookkeeper.bookie.storage

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/datainteg/DataIntegrityCookieValidation.java
Fix typos in class DataIntegrityCookieValidation
fix typos: `authoritive` => `authoritative`
> chore: fix typos in class DataIntegrityCookieValidation

- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieZKExpireTest.java
As of JDK 21, the methods `suspend` and `resume` on the `Thread` class throw `UnsupportedOperationException`.
1. Added junit5 annotation `@EnabledForJreRange(max = JRE.JAVA_17)`(It's modern and better than junit4) to tests that use `suspend` and `resume`, effectively disabling these tests on JDK versions higher than 17 where these methods are not supported.
2. Migrate this test file to junit5
> build: disable BookieZKExpireTest beyond jdk17

- shaded/distributedlog-core-shaded/pom.xml
Fix #2700 
- shade jar should include com.google.guava:failureaccess.
- remove unused exclude dependency now.
> fix guava shade error in distributedlog

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSet.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMap.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSet.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSetTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMapTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSetTest.java
This is the bug fix simillar to Pulsar. refer to: https://github.com/apache/pulsar/pull/18390.
Fix bugs in:
```
ConcurrentLongHashMap
ConcurrentLongHashSet
ConcurrentLongLongHashMap
ConcurrentLongLongPairHashMap
ConcurrentOpenHashMap
ConcurrentOpenHashSet
```
> [fix] Fix ArrayIndexOut0fBoundsException caused by optimistic lock

- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestBuffer.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestDirectEntryLogger.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestDirectEntryLoggerCompat.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestDirectReader.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestDirectWriter.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestEntryLogIds.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestMetadata.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestTransactionalEntryLogCompactor.java
1. Added junit5 annotation `@DisabledOnOs(OS.WINDOWS)`(It's modern and better than junit4) to tests that use `suspend` and `resume`, effectively disabling these tests on windows.
2. Migrate these test files to junit5
See also https://lists.apache.org/thread/hlyc722gy45s3y61q7n79hdcr6cgrx7v
> build: disable DirectIO Tests in windows

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieStateManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/StateManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieStateReadOnlyService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
When bookie disabled readOnlyMode, once the user initiates a readOnly conversion through the rest api, the bookie process will be shut down directly.
```java
public void doTransitionToReadOnlyMode() {
......
if (!conf.isReadOnlyModeEnabled()) {
LOG.warn("ReadOnly mode is not enabled. "
+ "Can be enabled by configuring "
+ "'readOnlyModeEnabled=true' in configuration."
+ " Shutting down bookie");
shutdownHandler.shutdown(ExitCode.BOOKIE_EXCEPTION);
return;
}
......
}
```
I have the following reasons for this PR:
1. If the user wants to shut down the bookie, there is no need to operate it through the rest api, and can directly use the shell shutdown script.
2. The user switches the readOnly state through the rest api, the first purpose is not to shut down the bookie process;
3. Exposing the …
> Prevent bookie shutdown due to rest api when bookie prohibits readOnlyMode

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
remove duplicate forceGarbageCollection setValue, it is redundant and error-prone. It's already seted in
https://github.com/apache/bookkeeper/blob/945cfa138f2b64f258d5b53a98505264085500f0/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java#L473-L478
> improve: remove duplicate forceGarbageCollection setValue in run method

- bin/bookkeeper-daemon.sh
Master Issue: #3112
Fix the failed pid occupied check. we'll fail when use bookkeeper-daemon.sh start or stop bookie, after the last time we exit the bookie direct kill or the bookie occurred non-normal exit, then the bin/bookkeeper-bookie.pid are retained, and the pid in the file is occupied by the thread in other progress.
Change the pid occupied check from 'kill -0 $pid' to 'ps -p $pid'. The both will return true when the pid is occupied by one progress, but 'kill -0 $pid' will return true and the 'ps -p $pid' will return false when the pid is occupied by one progress's sub thread.
StackOverflow discussion:
https://stackoverflow.com/questions/30958964/why-do-kill-0-pid-echo-and-ps-ppid-echo-sometimes-differ
> Fix the pid occupied check when use bookkeeper-daemon.sh start or stop

- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/service/HttpService.java
If you set `httpServerHost`, the bookie http info endpoint doesn't expose the host correctly but it always return 0.0.0.0 
Use `httpServerHost` configuration
> fix: bookie http endpoint info always return 0.0.0.0

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java
Fix #4326 
Currently, when a `LedgerFencedException` occurs during the write operation, it is logged at the ERROR level in `WriteEntryProcessor`. This is misleading and unnecessarily alarming for system administrators, as a fenced ledger during recovery is an expected scenario, not an actual error condition. This change aims to reduce the severity level of such log entries to make the logs more informative and less cluttered with non-critical errors.
- Adjusted the log level for `LedgerFencedException` in `WriteEntryProcessor` from ERROR to WARN.
- Added ledger ID and client IP information to the log message for better context and tracking.
- Corrected a typo in the comment within the same file to improve code readability.
This change makes the log output more consistent with how fenced …
> Adjust Log Level for LedgerFencedException in WriteEntryProcessor

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
Fix #4107 
This PR addresses a misconfiguration in `BookieNettyServer` where the `WRITE_BUFFER_WATER_MARK` was incorrectly applied to the server channel (`option()`) instead of the child channels (`childOption()`).
> Apply WRITE_BUFFER_WATER_MARK setting to child channels in BookieNetty Server

- bookkeeper-server/src/test/java/org/apache/bookkeeper/conf/TestBKConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
The tests under `bookkeeper-server` were failing on Windows due to path handling and other compatibility issues. The aim of this PR is to ensure that all tests pass on Windows as well as other operating systems by making the necessary adjustments in the test code.
- **TestBKConfiguration**: Updated the comment style from a block comment to a single-line comment for `setZkRetryBackoffMaxRetries`.
- **TestTLS**:
- Modified `getResourcePath` to use `Paths.get()` which handles file paths in a cross-platform manner.
- Replaced `assertTrue` with `assertFalse` followed by `isEmpty()` to check if ensembles are present, improving the readability.
> Fix test TestTLS for Windows compatibility in BookKeeper

- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieZKExpireTest.java
In JDK21, it's is no way to change private static final variable currently, before figure out how to replace, disable it first
```
Field logField = repp.getClass().getDeclaredField("LOG");
Logger mockLogger = mock(Logger.class);
Field modifiers = Field.class.getDeclaredField("modifiers");
modifiers.setAccessible(true);
modifiers.setInt(logField, logField.getModifiers() & ~Modifier.FINAL);
```
See also https://issues.apache.org/jira/browse/CASSANDRA-18181
1. Added junit5 annotation `@EnabledForJreRange(max = JRE.JAVA_17)`(It's modern and better than junit4) to tests that use `suspend` and `resume`, effectively disabling these tests on JDK versions higher than 17 where these methods are not supported.
2. BookieZKExpireTest should be annotated as junit5 test.
3. Make …
> build: disable testNewEnsembleBookieWithOneEmptyRegion method in TestRegionAwareEnsemblePlacementPolicy beyond jdk11

- circe-checksum/pom.xml
- cpu-affinity/pom.xml
- native-io/pom.xml
Fix build warnings, and `librt` is not used.
```
[INFO] --- nar-maven-plugin:3.5.2:nar-compile (default-nar-compile) @ circe-checksum ---
[INFO] Compiling 2 native files
[WARNING] No file matching patterns ("librt.a, librt.so) for library name "rt" was found.
[INFO] 2 total files to be compiled.
```
> build: remove unused cpp library rt

- pom.xml
When using SLF4J 2.0.x, it's useful to use slf4j-bom to align slf4j library versions. This is necessary to ensure that logging doesn't break due to mixed slf4j library versions.
Similarly, it's useful to use log4j-bom to align log4j library versions.
SLF4J 2.0.x upgrade was made in PR #4248 .
- use slf4j-bom and log4j-bom in dependencyManagement
> Use slf4j-bom and log4j-bom in dependencyManagement

- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSetTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMapTest.java
Fix #2077 
By the way, I have been tested, negative number will fail.
In the existing tests for `ConcurrentLongHashSet` and `ConcurrentLongLongHashMap`, the method `Math.abs(random.nextLong())` is used to generate keys. However, `Math.abs` can return a negative number if `Long.MIN_VALUE` is generated, which is problematic for tests that assume non-negative keys. Additionally, the assertions in the tests are using the older JUnit 4 style, which is less readable and not as flexible as JUnit 5.
1. **Key Generation Fix**: Replaced `Math.abs(random.nextLong())` with `ThreadLocalRandom.current().nextLong(Long.MAX_VALUE)` to ensure that all generated keys are non-negative.
2. **Assertion Updates**: Updated all assertions in the `ConcurrentLongHashSetTest` and `ConcurrentLongLongHashMapTest` to …
> Fix improper negative key generation and update assertions in tests

- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
JDK 17 and later throw `UnsupportedOperationException` for the `suspend` and `resume` methods, causing the `testConstructionZkDelay` and `testConstructionNotConnectedExplicitZk` tests to fail.
See jdk21 daily build error: https://github.com/apache/bookkeeper/actions/runs/8962118072
- Disabled the two affected test methods for JDK 17 and above using the `@EnabledForJreRange` annotation.
- Transitioned to JUnit 5 annotations and assertions.
Q: why there are so many line changes? like format change
A: In junit5, the msg should be put in the latest param, related to some changes.
> Disable two tests in BookKeeperTest on JDK 17+ due to UnsupportedOperationException

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
- CVE-2023-5072(7.5), CVE-2022-45688(7.5)
- Also bump apache from 29 to 32, it will update some maven plugins(like maven-shade-plugin), to support jdk21
> Bump jackson from 2.13.4.20221013 to 2.17.1 to address CVE list

- .github/workflows/bk-ci.yml
- .github/workflows/java21-daily-build.yml
- .github/workflows/owasp-daily-build.yml
- pom.xml
This PR aims to enhance the security posture of our project by automating the OWASP dependency checks. With increasing dependency updates and potential vulnerabilities, having a daily automated check ensures timely detection and mitigation of security risks.
- Added a new GitHub Actions workflow (`owasp-daily-build.yml`) that triggers an OWASP dependency check every day at 00:00 UTC.
- Updated the OWASP dependency check Maven plugin version in `pom.xml` from `8.0.2` to `9.1.0` to utilize the latest features and improvements for our security checks.
- Made a minor grammatical correction in the existing workflow file (`bk-ci.yml`) for better readability.
> build: add owasp daily build

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/JournalChannel.java
There is a resource leak in the `JournalChannel` implementation of Apache Bookkeeper when the channel is closed before it is fully initialized (specifically, before the writing of headers begins). In such cases, the buffer channel (`bc`) is not yet instantiated, but the file channel (`fc`) might already be open.
Updated the `close()` method in `JournalChannel` to include a conditional check that closes the file channel (`fc`) if the buffer channel (`bc`) is null. This ensures that all resources are properly released, even if the `JournalChannel` is prematurely closed before full initialization.
wrie header method
https://github.com/apache/bookkeeper/blob/ba7f988f7a27b80f8d607b44b155978763678713/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/JournalChannel.java#L250-L265
> fix: resource leak when JournalChannel is not fully initialized

- bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
Main Issue: may related to #1614 
The `bkHttpServiceProvider` was not being closed after the completion of the test cases in `TestHttpService`.
1. **JUnit Imports Update**: Switched imports to `junit.jupiter.api`.
2. **Service Closure Enhancement**: Added an `@AfterEach` method to close `bkHttpServiceProvider` after each test run.
3. **Assertion Refactor**: Refactored assertions for improved readability and consistency using appropriate `assertTrue`, `assertFalse`, `assertNull`, and `assertEquals` methods.
> test: fix bkHttpServiceProvider not closed in TestHttpService

- site3/website/docs/reference/config.md
- site3/website/versioned_docs/version-4.10.0/reference/config.md
- site3/website/versioned_docs/version-4.11.1/reference/config.md
- site3/website/versioned_docs/version-4.12.1/reference/config.md
- site3/website/versioned_docs/version-4.13.0/reference/config.md
- site3/website/versioned_docs/version-4.14.8/reference/config.md
- site3/website/versioned_docs/version-4.15.5/reference/config.md
- site3/website/versioned_docs/version-4.16.5/reference/config.md
- site3/website/versioned_docs/version-4.17.0/reference/config.md
- site3/website/versioned_docs/version-4.5.1/reference/config.md
- site3/website/versioned_docs/version-4.6.2/reference/config.md
- site3/website/versioned_docs/version-4.7.3/reference/config.md
- site3/website/versioned_docs/version-4.8.2/reference/config.md
- site3/website/versioned_docs/version-4.9.2/reference/config.md
The current configuration documentation for BookKeeper lacks some important parameters. Additionally, existing parameters are not optimally organized. This update:
- Introduces missing parameters like `isThrottleByBytes`, `compactionRateByEntries`, and `compactionRateByBytes`.
- Reorganizes the configuration parameters for better clarity.
- **Added:** New parameters that were missing in the configuration:
- `compactionRateByEntries`: Set the rate at which compaction will read entries, measured in entries per second.
- `compactionRateByBytes`: Set the rate at which compaction will read entries, measured in bytes per second.
- **Reorganized:** Adjusted the placement of existing parameters for better logical grouping and readability:
- `minorCompactionThreshold`: Adjusted position for …
> doc: add missing parameters and reorganize existing parameters in compact settings

- .github/workflows/bk-ci.yml
- .github/workflows/codeql.yml
- .github/workflows/owasp-daily-build.yml
- Removed Maven setup steps from `.github/workflows/bk-ci.yml`, `setup-java` will set maven ready.
- Changed the name of the daily build in `.github/workflows/owasp-daily-build.yml` from "JDK 21 Daily Build" to "OWASP Daily Build"
- Added needed params distribution to 'temurin'.
test on fork repo, it works well.
https://github.com/shoothzj/bookkeeper/actions/runs/9032270409/job/24820129535
```
Error:  Failed to execute goal org.owasp:dependency-check-maven:9.1.0:aggregate (default) on project bookkeeper: 
Error:  
Error:  One or more dependencies were identified with vulnerabilities that have a CVSS score greater than or equal to '7.0': 
Error:  
Error:  amqp-client-5.5.3.jar: CVE-2023-46120(7.5)
Error:  bc-fips-1.0.2.4.jar: CVE-2024-29[8](https://github.com/shoothzj/bookkeeper/actions/run …
```
> build: fix OWASP GitHub daily workflow

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicy.java
In the RackawareEnsemblePlacementPolicyImpl#selectRandomInternal method, if bookieNode in the ensemble list is not added to the excludeBookies set and the diskWeight feature is enabled, this method will fall into an infinite loop. 
https://github.com/apache/bookkeeper/blob/3ed93a0342ccff8c30ea472d731a7b593b4d32b0/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java#L773-L777
The root cause is the newly selected bookies already exist in the ensemble list, leading the `ensemble.addNode(bookie)` method to return `false` and the while loop continues.
https://github.com/apache/bookkeeper/blob/3ed93a0342ccff8c30ea472d731a7b593b4d32b0/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java#L841
In …
> Fix disk weight ensemble infinite loop bug

- site3/website/docs/admin/upgrade.md
4.14.0 introduce new conf `minorCompactionMaxTimeMillis` and `majorCompactionMaxTimeMillis`, but not recorded in the `upgrade.md`.
Record the conf change in 4.14.0.
> Add Compaction Duration Settings to 4.14.0 Upgrade Docs

- site3/website/docusaurus.config.js
- site3/website/versioned_docs/version-4.15.5/overview/overview.md
- site3/website/versioned_docs/version-4.17.0/api/ledger-api.md
- site3/website/versioned_docs/version-4.17.0/overview/overview.md
- site3/website/versioned_docs/version-4.17.0/reference/config.md
- Fix some versions wrong in the version docs. 
- Cherry-Pick the removal of twitter metrics library to 4.17.0 doc
- Update the `latest_release` and `stable_release `
> doc: update documentation for releases and APIs to reflect correct versions

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- pom.xml
CVE-2023-44487(7.5), CVE-2023-4785(7.5), CVE-2023-33953(7.5)
> Bump grpc from 1.56.0 to 1.64.0 to address CVE list

- bin/bookkeeper-daemon.sh
- dev/publish-docker-images.sh
- stream/clients/python/bookkeeper/common/datetime_helpers.py
- stream/clients/python/bookkeeper/common/protobuf_helpers.py
- stream/clients/python/bookkeeper/common/retry.py
- stream/clients/python/bookkeeper/common/router/router.py
- stream/clients/python/bookkeeper/common/timeout.py
- stream/clients/python/bookkeeper/common/util.py
- stream/clients/python/bookkeeper/kv/futures.py
- stream/clients/python/tests/unit/bookkeeper/common/future/test__helpers.py
- stream/clients/python/tests/unit/bookkeeper/common/test_grpc_helpers.py
- tests/scripts/src/test/bash/bk_test.sh
Introduce typos ci to avoid typos. This is a part of https://lists.apache.org/thread/04hqqcnkfc5189zsxj0s5wm37t2x7bky
> fix typos in sh and py files

- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/testing/executors/MockExecutorController.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SyncThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerStorageCheckpointTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
- stats/bookkeeper-stats-api/src/main/java/org/apache/bookkeeper/stats/ThreadRegistry.java
- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/DataSketchesOpStatsLogger.java
- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/ThreadScopedDataSketchesStatsLogger.java
There is an issue in the `ThreadRegistry` that causes incomplete Prometheus metrics reporting. It is trivial to reproduce:
1. Start bookies with multiple journal directories.
2. Start multiple clients writing to the bookies.
3. Observe that the `bookkeeper_server_ADD_ENTRY_count` does not increment at a similar rate to the journal's add entry rate.
The bug can be understood abstractly by considering the following:
1. The `threadPoolMap` in `ThreadRegistry` goes from thread id to `ThreadPoolThread`.
2. The `ThreadPoolThread` is defined by the thread pool and the configured id.
3. Every time we set the id for step 2, we use `0`.
4. When we have multiple journals, we call the same `ThreadRegistry.register(journalThreadName, 0);` method multiple times. …
>  Fix ThreadRegistry#register behavior to ensure correct Prom metrics 

- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufVisitor.java
ByteBufVisitor added in #4196 contains some code that isn't used and covered by unit tests. 
It's better to remove such code since it makes it harder to reason about the solution. The ByteBufVisitor solution will unwrap all direct buffers that can be unwrapped without the code that is to be removed. I believe that I forgot this code from some earlier phase of the solution where it was necessary to include this.
I ran some local tests and didn't see that the code was used for the original purpose that it was added for (supporting read-only buffers).
Remove the unused code.
> Remove unused code from ByteBufVisitor

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/util/TestOrderedExecutor.java
Fix [#4373](https://github.com/apache/bookkeeper/issues/4373)
As shown in the issue.
This is the first pr to fix the lost metric problem. And the other pr improve the metric in SingleThreadExecutor.
If we only fix the problem but do not change the metric , the metric is as follow, the metric become visible, though the format is not same.
> fix lost prometheus metric in OrderedExecutor  

- .github/workflows/bk-ci.yml
- .github/workflows/owasp-daily-build.yml
- src/owasp-dependency-check-suppressions.xml
`integrate-tests` module depends on `arquillian-cube`, which are updates infrequently. Lastly release was in 2018, and it depends on a lot of dependency with CVEs, like `bcprov-jdk15on-1.64.jar` etc. But it still merging code frequently, my team will trying to ask for new release, I think we can remove tests module from owasp check for now.
I run the check locally, fix 7 error, and no new errors generated compared to daily build result.
```
[ERROR] amqp-client-5.5.3.jar: CVE-2023-46120(7.5)
[ERROR] jetcd-core-0.7.7.jar: CVE-2020-15113(7.1)
[ERROR] jetcd-grpc-0.7.7.jar: CVE-2023-44487(7.5), CVE-2017-8359(9.8), CVE-2023-33953(7.5), CVE-2020-15113(7.1), CVE-2020-7768(9.8), CVE-2017-7861(9.8), CVE-2017-9431(9.8), CVE-2017-7860(9.8)
[ERROR] okio-3.2.0.jar: CVE-2023-3635(7.5)
```
After refresh …
> build: remove tests module from owasp check

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/AuthHandler.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClientImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ByteStringUtil.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufList.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/util/ByteBufListTest.java
Cherry-pick #4293 to branch-4.16
> [branch-4.16] fix: reference counting (retain/release) in PerChannelBookieClient (#4293)

- bookkeeper-common/src/test/java/org/apache/bookkeeper/common/testing/executors/MockExecutorController.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SyncThread.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerStorageCheckpointTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
- stats/bookkeeper-stats-api/src/main/java/org/apache/bookkeeper/stats/ThreadRegistry.java
- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/DataSketchesOpStatsLogger.java
- stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/ThreadScopedDataSketchesStatsLogger.java
* Make tests fail
* Fix ThreadRegistry#register to ensure correct Prom metrics
* Change style to match BK standards
* Fix tests
---------
Co-authored-by: Nicolò Boschi <boschi1997@gmail.com>
---------
(cherry picked from commit 1d82b9278cc8916ca4410bd38f8fea50bfc41aaa) Conflicts:
bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SyncThread.java
Fix #xyz
Main Issue: #xyz
BP: #xyz
> ---
> checks for pull requests. A pull request …
>  Fix ThreadRegistry#register behavior to ensure correct Prom metrics #4300

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- bookkeeper-server/pom.xml
- pom.xml
- Upgrade vertx-core to 4.5.7 to address CVE-2024-1300
- Depends on merging #4264 before this PR (since Netty 4.1.108.Final is required for vertx-core 4.5.7)
Fix #xyz
Main Issue: #xyz
BP: #xyz
> ---
>
> ---
> Be sure to do all the following to help us incorporate your contribution
>
>
>     `<BP-#>: …
> [branch-4.16] cherry-pick #4157 #4204 #4224 #4265 update netty and vertx

- circe-checksum/src/main/java/com/scurrilous/circe/checksum/Java8IntHash.java
- circe-checksum/src/main/java/com/scurrilous/circe/utils/NativeUtils.java
- microbenchmarks/pom.xml
- microbenchmarks/src/main/java/org/apache/bookkeeper/bookie/package-info.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/proto/ProtocolBenchmark.java
- microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManagerBenchmark.java
- **circe-checksum module:**
- Removed unused imports such as `java.nio.ByteBuffer` and `java.util.zip.Checksum` in `Java8IntHash.java`.
- Removed `java.io.IOException` import in `NativeUtils.java`.
- **microbenchmarks module:**
- Modified the `pom.xml` to enforce Checkstyle by removing the `<skip>true</skip>` configuration.
- Removed unused `ByteBufList` imports from `ProtocolBenchmark.java` and `DigestManagerBenchmark.java`.
> Adapt Checkstyle in microbenchmarks module

- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
In Pulsar, there are multiple reports (for example apache/pulsar#22601, apache/pulsar#21421) about data corruption when TLS is enabled between Pulsar Brokers and Bookkeeper Bookies and when V2 protocol is enabled in broker.conf with the default configuration setting `bookkeeperUseV2WireProtocol=true`.
The reason to change the order of FlushConsolidationHandler compared to SslHandler is due to the fact that Netty [SslHandler's](https://netty.io/4.1/api/io/netty/handler/ssl/SslHandler.html) STARTTLS support uses the flush event. My assumption is that having [FlushConsolidationHandler](https://netty.io/4.1/api/io/netty/handler/flush/FlushConsolidationHandler.html) in "front" of the flushes could cause problems.
- See the Netty SslHandler code in: …
> Fix TLS stability issues with V2 protocol that caused data corruption

- pom.xml
The purpose of this update is to correct a configuration error in our OWASP Dependency Check Maven plugin setup. 
I appreciate @xiezhx9 for opening the issue on [jeremylong/DependencyCheck #6697](https://github.com/jeremylong/DependencyCheck/issues/6697). Also, a special thanks to @jeremylong for his guidance and response.
From dependency-check-plugin maintainer jeremylong
> With the setup specified ODC would run too many times - once with the specified configuration and once without. You can either put the plugin into the build/plugins or in the reporting - don't do both.
> Regarding it re-running on each child module - you likely want to specify <inherited>false</inherited>.
And I believe that cause error I meet before
```
Error: Failed to execute goal …
```
> Correct Configuration Error in OWASP Dependency Check Plugin Setup

- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieDecommissionTest.java
This method is annotated with `@Test`, and it's actually runs well. Like in https://github.com/apache/bookkeeper/actions/runs/9295092940/job/25581685669
```
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 219.1 s -- in org.apache.bookkeeper.client.BookieDecommissionTest
```
The `@FlakyTest` annotation was removed from the `testDecommissionBookie` method in the `BookieDecommissionTest` class.
> Remove @FlakyTest annotation from testDecommissionBookie method

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/BKLogSegmentWriter.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/metadata/BKDLConfig.java
- stream/distributedlog/core/src/main/java/org/apache/distributedlog/zk/ZKVersionedSetOp.java
Main Issue #995
In the current implementation, several components use `assert` statements to verify conditions. However, assert statements are not typically enabled in production environments, which means these checks can be bypassed, potentially leading to unclear errors later in the execution. Replacing these with explicit checks ensures that our error handling is active and clear during production runs.
- **BKLogSegmentWriter.java**: Added a check to verify the context type before casting to `BKTransmitPacket`.
- **BKDLConfig.java**: Introduced a check for the type of `dlConfig` before casting to `BKDLConfig`.
- **ZKVersionedSetOp.java**: Added a check to ensure the operation result is of type `OpResult.ErrorResult`.
> Replace assert statements with explicit checks

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/ZKLogSegmentMetadataStore.java
Fix duplicated call `zkGetLogSegmentNames` in `getLogSegmentNames`.
We have called `zkGetLogSegmentNames` at line425 and got the result, so there is no need call `zkGetLogSegmentNames` again at line430.
Remove duplicated `zkGetLogSegmentNames` at line430.
> Fix duplicated call zkGetLogSegmentNames in getLogSegmentNames

- stream/distributedlog/core/src/main/java/org/apache/distributedlog/ReadAheadEntryReader.java
I saw some logs print repeatedly.
```
2023-08-12T03:52:59,027+0000 [main-EventThread] INFO  org.apache.distributedlog.ReadAheadEntryReader - segments is updated with []
2023-08-12T03:52:59,065+0000 [main-EventThread] INFO  org.apache.distributedlog.ReadAheadEntryReader - segments is updated with []
2023-08-12T03:52:59,129+0000 [main-EventThread] INFO  org.apache.distributedlog.ReadAheadEntryReader - segments is updated with []
2023-08-12T03:52:59,175+0000 [main-EventThread] INFO  org.apache.distributedlog.ReadAheadEntryReader - segments is updated with []
2023-08-12T03:52:59,208+0000 [main-EventThread] INFO  org.apache.distributedlog.ReadAheadEntryReader - segments is updated with []
2023-08-12T03:52:59,225+0000 [main-EventThread] INFO  org.apache.distributedlog.ReadAheadEntryReader - …
```
> Disable annoying logs when segments is empty

- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTest.java
Some RegistrationManager implements(PulsarRegistrationManager) will delete the bookie's node in the close method, which will lead to the test failure.
> Close the RegistrationManager in the finally block in AuditorPlacementPolicyCheckTest.

- site3/website/docs/api/ledger-api.md
- site3/website/versioned_docs/version-4.10.0/api/ledger-api.md
- site3/website/versioned_docs/version-4.11.1/api/ledger-api.md
- site3/website/versioned_docs/version-4.12.1/api/ledger-api.md
- site3/website/versioned_docs/version-4.13.0/api/ledger-api.md
- site3/website/versioned_docs/version-4.14.8/api/ledger-api.md
- site3/website/versioned_docs/version-4.15.5/api/ledger-api.md
- site3/website/versioned_docs/version-4.16.5/api/ledger-api.md
- site3/website/versioned_docs/version-4.17.0/api/ledger-api.md
- site3/website/versioned_docs/version-4.6.2/api/ledger-api.md
- site3/website/versioned_docs/version-4.7.3/api/ledger-api.md
- site3/website/versioned_docs/version-4.8.2/api/ledger-api.md
- site3/website/versioned_docs/version-4.9.2/api/ledger-api.md
1. fix the bookkeeper-server-shaded version by  `site.latest_release`
2. fix the overview title version.
> Fix the bookkeeper-server-shaded version in ledger-api doc

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
This PR addresses the issue where RocksDB configurations fail to correctly resolve paths on Windows systems in the `ServerConfiguration` class. See windows daily build failed in https://github.com/apache/bookkeeper/actions/runs/9294883674
> Note: Currently, windows is limited to some development jobs, there are still problems to be solved
- Updated `ServerConfiguration.java` to utilize `java.nio.file.Paths` for path normalization and resolution.
- Refactored the `getDefaultRocksDBConf`, `getEntryLocationRocksdbConf`, and `getLedgerMetadataRocksdbConf` methods to use a new method `getFilePath`.
> Fix RocksDB configuration path handling on Windows

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestSpeculativeBatchRead.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestSpeculativeRead.java
Fix #3514
This configuration may have initially intended to add a switch in `slowBookies`, but it was overlooked. I reset the history to when the code was merged into the master branch; it is still only referenced in the test files. Furthermore, even if the test call is removed, the test cases still pass. Therefore, I think it is reasonable to remove it.
> chore: remove dead config ensemblePlacementPolicyOrderSlowBookies

- .github/workflows/bk-ci.yml
- tests/backward-compat/upgrade/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatUpgrade.groovy
- tests/docker-images/all-released-versions-image/Dockerfile
- tests/integration-tests-utils/src/main/java/org/apache/bookkeeper/tests/integration/utils/BookKeeperClusterUtils.java
Expanded backwards-compat tests
On pulsar slack @rdhabalia reported BK-related errors during upgrade.
Backwards compat tests: 
* added new BK versions
* pulsar upgrade cases
* read check from old server (new client reads from old server)
* upgrade tests with CRC32C (for select cases)
> [improve][tests] Backwards compat tests: added new versions, pulsar upgrade cases, read check from old server

- .github/workflows/codeql.yml
The codeql workflow needs read pull-requests permission when use action `apache/pulsar-test-infra/paths-filter@master`
> [ci] Fix apache/pulsar-test-infra/paths-filter action permission in CodeQL workflow

- bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
When the `ReadEntryProcessor` runs slow, the `TimedRunnable` will print the warn log like below:
```
Runnable xx:xx took too long xx micros to execute.
```
https://github.com/apache/bookkeeper/blob/fd2c7c6f632deb0130b9c8fc506a6b66ac02b341/bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java#L197-L208
However we found that NPE happened in this log:
```
WARN  [BookieReadThreadPool-OrderedExecutor-1-0:OrderedExecutor$TimedRunnable@206] - Runnable [!!!org.apache.bookkeeper.proto.ReadEntryProcessor@1dd094f3=>java.lang.NullPointerException:Cannot invoke "org.apache.bookkeeper.proto.BookieProtocol$ReadRequest.getLedgerId()" because "this.request" is null!!!]:class org.apache.bookkeeper.proto.ReadEntryProcessor took too …
```
> Fix TimedRunnable log NPE

- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
As described from #4288 , we will remove deprecated method `setAllocatorPoolingConcurrenncy`(because of typos) and release in 4.18.
Remove deprecated method `setAllocatorPoolingConcurrenncy`
> Remove deprecated method `setAllocatorPoolingConcurrenncy`

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDirsManager.java
fix the descriptions of `getTotalFreeSpace` and `getTotalDiskSpace` which confused before.
> fix: correct the description of LedgerDirManager's methods

- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockLedgerHandle.java
Fix #1413
change ledger state to close when close metadata
> Fix incorrect metadata state in MockLedgerHandle close method

- site3/website/src/pages/community/release-guide.md
- stream/clients/python/scripts/publish.sh
This PR updates the release scripts to ensure more robust and consistent release processes. The changes include modifying the git tagging instructions to prevent potential mis-tags and updating the Python scripts to use Python 3 explicitly, which aligns with best practices for Python development.
1. **Release Guide Modification**: Using ^{} ensures that the tag is created for the commit itself, not rc tag to be deleted. 
2. **Python Publishing Script**: Changed all instances of `python` to `python3`, modern operation systems default has `python3`, but not all has `python`
> Update Release Script Instructions and Python Publishing Scripts

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/TestBookieImpl.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageReadCacheTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageWriteCacheTest.java
- conf/bk_server.conf
Cherry-pick https://github.com/apache/bookkeeper/pull/3895
* [feature] [server] add dbStorage_readAheadCacheBatchBytesSize properties when read ahead entries
Discussion: https://lists.apache.org/thread/sgtfow2hjg4zp3z0mhk3xttb972pjrjw
---------
Co-authored-by: lushiji <lushiji@didiglobal.com>
(cherry picked from commit f5455f01584b1b0a592f020eed49d3cb774da0a9)
Fix #xyz
Main Issue: #xyz
BP: #xyz
> ---
>
> ---
> Be sure to …
> [Branch-4.16] [cherry-pick] add dbStorage_readAheadCacheBatchBytesSize properties when read ahead entries 

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/TopologyAwareEnsemblePlacementPolicy.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicy.java
When the bookie is not available, the RackawareEnsemblePlacementPolicyImpl default rack will be `/default-region/default-rack`, it should be `/default-rack` for RackawareEnsemblePlacementPolicyImpl.
There are some logs.
```
2024-06-17T05:22:46,591+0000 [ReplicationWorker] ERROR org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy - Cannot resolve bookieId `test-bk-3:3181` to a network address, resolving as /default-region/default-rack
org.apache.bookkeeper.proto.BookieAddressResolver$BookieIdNotResolvedException: Cannot resolve bookieId test-bk-3:3181, bookie does not exist or it is not running
at org.apache.bookkeeper.client.DefaultBookieAddressResolver.resolve(DefaultBookieAddressResolver.java:66) ~[io.streamnative-bookkeeper-server-4.16.5.2.jar:4.16.5.2]
at …
```
> Correct RackawareEnsemblePlacementPolicyImpl defaultRack when the bookie is not available.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/zookeeper/ZooKeeperClient.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/zookeeper/ZooKeeperWatcherBase.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperClientZKSessionExpiry.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ZooKeeperCluster.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ZooKeeperClusterUtil.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/zookeeper/TestZooKeeperClient.java
If the system property `readonlymode.enabled` is set to true on a ZooKeeper server, read-only mode is enabled. Data can be read from the server in read-only mode even if that server is split from the quorum.
https://zookeeper.apache.org/doc/current/zookeeperAdmin.html#Experimental+Options%2FFeatures
To connect to the server in read-only mode, the client must also allow read-only mode. The `ZooKeeperClient` class in the bookkeeper repository also has an option called `allowReadOnlyMode`.
https://github.com/apache/bookkeeper/blob/15171e1904f7196d8e9f4116ab2aecdf582e0032/bookkeeper-server/src/main/java/org/apache/bookkeeper/zookeeper/ZooKeeperClient.java#L219-L222
However, even if this option is set to true, the connection to the server in read-only mode will actually fail. The cause is in …
> Enable ZooKeeper client to establish connection in read-only mode

- bookkeeper-server/src/test/resources/conf/default_rocksdb.conf
- bookkeeper-server/src/test/resources/conf/entry_location_rocksdb.conf
- bookkeeper-server/src/test/resources/conf/ledger_metadata_rocksdb.conf
- bookkeeper-server/src/test/resources/test_entry_location_rocksdb.conf
- conf/default_rocksdb.conf.default
- conf/entry_location_rocksdb.conf.default
- conf/ledger_metadata_rocksdb.conf.default
Fix erros of rocksdb default config
The default rocksdb config has some errors and need fix.
1. Fix error rocksdb default config for CFOptions.
2. Update rocksdb config for unit test
> fix[rocksdb]: fix error rocksdb default config for CFOptions

- .github/workflows/bk-ci.yml
- .github/workflows/owasp-daily-build.yml
- pom.xml
See more in https://github.com/apache/pulsar/pull/22999. Thanks for @lhotari 
INFRA-TICKET https://issues.apache.org/jira/projects/INFRA/issues/INFRA-26000
> [fix][ci] Fix OWASP Dependency Check download by using NVD API key

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- bookkeeper-server/src/test/resources/conf/default_rocksdb.conf
- bookkeeper-server/src/test/resources/conf/entry_location_rocksdb.conf
- bookkeeper-server/src/test/resources/conf/ledger_metadata_rocksdb.conf
- bookkeeper-server/src/test/resources/test_entry_location_rocksdb.conf
- conf/bk_server.conf
- conf/default_rocksdb.conf.default
- conf/entry_location_rocksdb.conf.default
- conf/ledger_metadata_rocksdb.conf.default
Fix #4479
RocksDB format_version 5 has been supported since RocksDB 6.6 . It's required for certain performance optimizations.
Currently the default is format_version 2 which is really old. It's better to default to a more modern version.
- upgrade default format_version from 2 to 5
- specify format_version=5 in various configuration files
> Set default format_version to 5 for RocksDB databases

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeper.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
Before understanding the problem solved by this PR, you can try to use this Test method to execute it in the existing master branch, and the unit test will fail.
```java
@Test
public void testBookieWatcher() throws Exception {
ClientConfiguration conf = new ClientConfiguration();
conf.setMetadataServiceUri(zkUtil.getMetadataServiceUri());
StaticDNSResolver tested = new StaticDNSResolver();
try (BookKeeper bkc = BookKeeper
.forConfig(conf)
.dnsResolver(tested)
.build()) {
final Map<BookieId, BookieInfoReader.BookieInfo> bookieInfo = bkc.getBookieInfo();
// 1. check all bookies in client cache successfully.
bookieInfo.forEach((bookieId, info) -> {
final CompletableFuture<Versioned<BookieServiceInfo>> bookieServiceInfo = bkc.getMetadataClientDriver() …
```
> [client][fix] Bookie WatchTask may be stuck

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
In file RackawareEnsemblePlacementPolicyImpl.java 
In the log.warn below, we should print out the list of ensemble, instead of the object. The “ensemble” in line-619 should be changed into “ensemble.toList()”.
https://github.com/apache/bookkeeper/blob/999cd0f2ab14404be4d6c24e388456dbe56bb1a8/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java#L600C3-L619C47
The “ensemble” in line-619 changed into “ensemble.toList()”.
> [improve] when rackaware failed to choose a bookie, print out the list of ensemble.

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeper.java
Followed #4481 comment:
https://github.com/apache/bookkeeper/pull/4481#discussion_r1721182862
1. rename client highPriorityTaskExecutor 
2. shutdownNow when not shutdown cleanly
> Rename the client high priority thread pool

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
CVE-2024-7254
Upgrade protobuf to 3.25.5
> Upgrade protobuf to 3.25.5 to address CVE-2024-7254

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- pom.xml
Upgrade to Netty 4.1.115.Final to address CVE-2024-47535. This DoS vulnerability doesn't practically apply to BookKeeper since the vulnerability requires write access to the filesystem where the application using Netty is running. However, it's always useful to address CVEs by upgrading to a version that doesn't contain known vulnerabilities.
- Upgrade Netty to 4.1.115.Final
- netty-bom in 4.1.115.Final upgrades Netty tcnative to 2.0.69.Final
- Release notes:
- [4.1.115.Final](https://netty.io/news/2024/11/12/4-1-115-Final.html)
- [4.1.114.Final](https://netty.io/news/2024/10/01/4-1-114-Final.html)
- Netty tcnative [changes in 2.0.69.Final since 2.0.66.Final](https://github.com/netty/netty-tcnative/compare/netty-tcnative-parent-2.0.66.Final...netty-tcnative-parent-2.0.69.Final)
> Upgrade to Netty 4.1.115.Final to address CVE-2024-47535

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
corrupt entry log file causes OODMEs and stuck GC.
Log (from bk 4.15.x):
```
2025-01-03T00:24:55,037+0000 [GarbageCollectorThread-7-1] INFO  org.apache.bookkeeper.bookie.GarbageCollectorThread - Extracting entry log meta from entryLogId: 45795
2025-01-03T00:24:55,038+0000 [GarbageCollectorThread-7-1] INFO  org.apache.bookkeeper.bookie.EntryLogger - Failed to get ledgers map index from: 45795.log : Negative position
2025-01-03T00:24:55,039+0000 [GarbageCollectorThread-7-1] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 1936946533 byte(s) of direct memory (used: 1140850688, max: 2147483648)
at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:845) …
```
> Fix: Garbage collection stuck on corrupt entry log file

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieShellTest.java
Running `recover` command with rate limit like
```
bin/bookkeeper shell recover -rate 10000 <the rest of the params>
```
produces error
```
The provided bookie dest 10000 will be ignored!
ERROR: invalid value for option replicationRate : null
```
Fixed the bug, added tests.
> [cli] Fix: recover command doesn't accept rate limit parameter

- conf/bk_server.conf
RocksDB config for the file based configuration alternative has been missing from bk_server.conf
- Add comments and missing keys to bk_server.conf
This depends on #4559 so that `dbStorage_rocksDB_format_version` would apply to all RocksDB databases.
> Add documentation to bk_server.conf about RocksDB config

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
Related to upgrading RocksDB to 9.x, #4422. Downgrading isn't possible if databases aren't created with a specified formatVersion that previous versions support.
Set formatVersion to 5 for all RocksDB databases configured with Java code in BookKeeper.
> Ensure that formatVersion is specified for all RocksDB databases

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
The solution to locate RocksDB config files has been broken since  #4407 in master branch.
- fix issue in locating the RocksDB config files. 
- Add proper comments to explain the reason why the method exists
- Fixes also the issue on Windows as attempted in #4407
> Fix and improve locating RocksDB config files

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndexTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageTest.java
The rest of the places where Batch is used have been changed: use KeyValueStorage.Batch, close it in finally.
This modification is not caused by a fault. I just found that the code is not written rigorously enough and is prone to bugs when I was combing through it.
1.  The rest of the places where Batch is used have been changed: use KeyValueStorage.Batch, close it in finally.
> fix: Every time use KeyValueStorage.Batch, close it in finally

- bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
Fix #4517
we can move changeEnsembleLoop out side the metadataLock because the changing ensemble field can be a guard for do the action and the callback will trigger next.
> ---
>
> ---
> Be sure to do all the following to help us incorporate your contribution
>
>
> - [ ] Attach the master issue …
> Reduce metadataLock contention in LedgerHandle

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- pom.xml
While working on #4580, I noticed that the Commons Compress version and the Commons Codec library version aren't compatible. It causes a ClassDefNotFoundError in running tests which were using some specific methods of docker-java.
While exploring this, I noticed that Apache Commons library versions haven't been kept up-to-date for a long time and it's better to handle that for 4.18.0 release.
- upgrade commons-cli from 1.2 to 1.9.0
- upgrade commons-codec from 1.6 to 1.18.0
- upgrade commons-io from 2.17.0 to 2.19.0
- upgrade commons-lang3 from 3.6 to 3.17.0
- upgrade commons-compress from 1.26.0 to 1.27.0
> Upgrade Apache Commons libraries to compatible versions

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- pom.xml
- Keeping Netty version up-to-date.
- Address CVE-2025-24970
- Upgrade Netty to 4.1.119.Final
- Comes with tcnative 2.0.70.Final
- Upgrade netty-transport-native-io_uring to 0.0.26.Final
> Upgrade Netty to 4.1.119, tcnative to 2.0.70 and io_uring to 0.0.26

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDBTest.java
Fix https://github.com/apache/bookkeeper/issues/4238
Add a boolean status check before KeyValueStorageRocksDB.count()
> Fix the coredump that occurs when calling KeyValueStorageRocksDB.count after rocksdb has been closed

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- pom.xml
Before next 4.18.x and 4.17.x releases, it would be useful to have grpc upgraded to latest version.
- [1.72.0 release notes](https://github.com/grpc/grpc-java/releases/tag/v1.72.0)
- [1.71.0 release notes](https://github.com/grpc/grpc-java/releases/tag/v1.71.0)
- Upgrade grpc from 1.70.0 to 1.72.0
> Upgrade to grpc 1.72.0

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
- pom.xml
- tests/README.md
- tests/backward-compat/upgrade-direct/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatUpgradeDirect.groovy
- tests/backward-compat/upgrade-direct/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatUpgradeDowngrade.groovy
- tests/backward-compat/upgrade-direct/src/test/resources/TestCompatUpgradeDowngrade/conf/default_rocksdb.conf
- tests/backward-compat/upgrade-direct/src/test/resources/TestCompatUpgradeDowngrade/conf/entry_location_rocksdb.conf
- tests/backward-compat/upgrade-direct/src/test/resources/TestCompatUpgradeDowngrade/conf/ledger_metadata_rocksdb.conf
- tests/backward-compat/upgrade/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatUpgrade.groovy
- tests/docker-images/all-released-versions-image/Dockerfile
- tests/integration-tests-topologies/src/main/resources/cube-definitions/3-node-all-version-unstarted.yaml
- tests/integration-tests-utils/pom.xml
- tests/integration-tests-utils/src/main/java/org/apache/bookkeeper/tests/integration/utils/BookKeeperClusterUtils.java
Fix #4409
Upgrade RocksDB to v.9.9.3 to pick up latest performance and stability improvements and fixes in deleteRanges.
Hopefully deleteRanges() is stable enough for us to try again perf improvements https://github.com/apache/bookkeeper/pull/3653 that were reverted previously.
The upgrade/downgrade tests pass now. The problem was that `format_version` wasn't set in all cases and that resulted in using the default `format_version=6` of RocksDB 9.x. There were multiple bugs in setting the `format_version`. The related fixes to address this are #4466, #4480, #4559 and #4560.
The [RocksDB 9.0.0 release notes](https://github.com/facebook/rocksdb/releases/tag/v9.0.0) mention the default format_version change:
> format_version=6 is the new default setting in BlockBasedTableOptions, for more …
> Upgrade to RocksDB 9.9.3

- .github/workflows/bk-ci.yml
- pom.xml
- stream/distributedlog/common/pom.xml
- stream/distributedlog/core/pom.xml
- stream/distributedlog/pom.xml
- stream/pom.xml
- tests/integration-tests-base-groovy/pom.xml
Some tests fail due to DNS timeouts as explained in #4585.
Some of these failures might be caused by the default negative DNS cache that is 10 seconds by default or by the default positive DNS cache that is 30 seconds by default. It's better to set reduce dns cache settings to 1 second for tests.
- pass `-Dsun.net.inetaddr.ttl=1 -Dsun.net.inetaddr.negative.ttl=1` in test JVM arguments to configure the DNS cache settings
- For OpenJDK, it's not possible to override settings in `$JAVA_HOME/conf/security/java.security` with System properties, see https://github.com/openjdk/jdk11u/blob/master/src/java.base/share/classes/sun/net/InetAddressCachePolicy.java . By default there's a negative TTL setting set to 10 seconds.
- apply respective settings to `$JAVA_HOME/conf/security/java.security` in …
> Adjust DNS cache expiration in tests to reduce test timeout failures

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
- bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
- pom.xml
Keeping Netty up-to-date and getting minor bug fixes into BookKeeper.
- [Netty 4.1.120.Final release notes](https://netty.io/news/2025/04/23/4-1-120-Final.html)
- [Netty 4.1.121.Final release notes](https://netty.io/news/2025/04/24/4-1-121-Final.html)
Upgrade Netty to 4.1.121.Final
> Upgrade Netty to 4.1.121.Final

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultEntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLoggerAllocator.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/DefaultEntryLogTest.java
---
We observed numerous errors in the broker that failed to read the ledger from the bookkeeper; although the ledger metadata still exists, it was unable to read from the bookkeeper. After checking the data, we found the ledger located entry log was deleted by the bookkeeper. We have a data loss issue with the bookkeeper.
The entry log file was deleted by the Garbage collector because the entry log file wrote a wrong file header.
And there is an example that the shows the header is wrong:
```
Failed to get ledgers map index from: 82.log : Not all ledgers were found in ledgers map index. expected: -1932430239 -- found: 0 -- entryLogId: 82
```
> Fix the data loss issue that caused by the wrong entry log header

- bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
- bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
When cherry-picking #4600, a bug was introduced. Now fix it.
> fix cherry-pick: Upgrade Jetty to 9.4.57.v20241219 to address CVE-2024-6763

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultEntryLogger.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
We met the GarbageCollectionThread was stopped by some runtime error, but we didn't catch it then, causing the GC to stop. 
Such as: 
https://github.com/apache/bookkeeper/pull/3901
https://github.com/apache/bookkeeper/pull/4544
In our case, the GC stopped because of the OutOfDirectMemoryException then the process stopped and the files can not be deleted. But we didn't see any error logs. This PR enhance the log info when an unhandled error happens.
We already have the [PR](https://github.com/apache/bookkeeper/pull/4544) fixed that. 
And another fix in this PR is to change the Exception to the Throwable in the getEntryLogMetadata.
Here is the error stack:
```
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 213909504 byte(s) of direct memory (used: 645922847, max: …
```
> Log all the error in the GarbageCollectorThread

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieStorageThresholdTest.java
Main Issue: https://github.com/apache/bookkeeper/issues/4655
When a single ledger disk becomes full, `suspendMajorGC()`/`suspendMinorGC()` pauses garbage collection (GC) for **all disks**. However, a single disk failure should not affect GC operations on other disks.  
**Two scenarios:**  
- **Even Data Distribution**: Data is evenly distributed across ledger disks. When all disks are nearly full and one disk fills first.  
- **Uneven Data Distribution**: Individual disk usage spikes due to write skew or data cleanup anomalies.  
For the even Data Distribution:  
Disabling GC only on the full ledger disk first, then waiting for the next check (default `diskCheckInterval=10000` ms) to disable GC on other disks causes no harm.  
For uneven storage distribution:  
Disabling GC on all ledger …
> Only stop Gc for the fill disk for DbLedgerStorage

- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieStateManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieStatus.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDirsMonitor.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/StateManager.java
- bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieStateReadOnlyService.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieInitializationTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerCacheTest.java
- bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorLedgerCheckerTest.java
Issue: BK stays at `readOnly` state even if the disk is empty
Reproduce steps
- Configurations
- `diskUsageLwmThreshold`: `0.85`
- `diskUsageWarnThreshold`: `0.85`
- `diskUsageThreshold`: `0.90`
- `persistBookieStatusEnabled`: `true`
- The state of BK switches to `read-only` because the disk usage increased to `0.92`.
- The disk usage came down to `0.851`.
- Restart the BK.
- The state is set to `read-only`, because the payload of the state file is `1, {timestamp}, Read_only`
- **(Highlight)**  The attributes of `LedgerDirsManager` is as follows
-  `filledDirs`: `[]`
- `writableLedgerDirectories`: `["ledger-0"]`
- **Issue:** the state stays at `read_only` and never recovers, because there is no ledger dir that will switch state from `filled` to `writable` since the `filledDirs` is empty. …
> [fix]BK stays at read_only state even if the disk is empty
